### ISSUE TITLE
Create Listing using API Endpoint fulfill Listing

### ISSUE THREAD

**Issue by mohsinkc** [ProjectOpenSea/opensea-js#1006]
Hey everyone,
I am relatively new to Opensea API and web3. I have a question I have created a react app that connects my wallet, then there are 2 input fields one for contract address and one for token id. There is a button to buy the specific nft that matches the contract address and token id. I use the API endpoint to retrieve listings and the filter for the lowest listing. The I use the API endpoint to fulfill the listing it returns a response object.
My Question:
How can I then use that object to buy the nft and register the event on chain?
Any help would be greatly appreciated.
Thanks.

**Comment by ryanio** [comment]
The opensea API fulfillment endpoints return a "transaction" object you can submit to the chain to fulfill the order.

https://docs.opensea.io/reference/fulfill-a-listing
https://docs.opensea.io/reference/fulfill-an-offer

**Comment by mohsinkc** [comment]
> The opensea API fulfillment endpoints return a "transaction" object you can submit to the chain to fulfill the order.
> 
> https://docs.opensea.io/reference/fulfill-a-listing
> https://docs.opensea.io/reference/fulfill-an-offer

My question is how would I do that?  Just give me an idea on how I can do it.
Thanks alot for reply

**Comment by JoshuaSchmidt-OpenSea** [comment]
@mohsinkc If you still have issues, feel free to reopen this ticket.
