### ISSUE TITLE
url_1.URLSearchParams is not a constructor

### ISSUE THREAD

**Issue by MaximusDecimus** [ProjectOpenSea/opensea-js#1011]
Looks like a bad import in api.ts in version 5.0.3

```
import { URLSearchParams } from "url";
```

**Comment by JoshuaSchmidt-OpenSea** [comment]
@MaximusDecimus What version of node are you using?

**Comment by wizardlabsxyz** [comment]
Same problem here...

node version: v16.19.0

**Comment by MaximusDecimus** [comment]
Yes, thats what I use as well. Thanks

**Comment by JoshuaSchmidt-OpenSea** [comment]
This should be fixed in v6.0.2
