### ISSUE TITLE
Latest v6 release can't npm install `husky install` fails

### ISSUE THREAD

**Issue by wizardlabsxyz** [ProjectOpenSea/opensea-js#1014]
Simply trying to npm install. I'm using windows subsystem for linux with node v14.21.2 (also tried v16.19.0)

```
npm WARN old lockfile   code: 'EINTEGRITY'
npm WARN old lockfile }
npm ERR! code 127
npm ERR! path /home/wizard/workspace/clientwork/sunnyswapmain/sunnyswap/node_modules/opensea-js
npm ERR! command failed
npm ERR! command sh -c -- husky install
npm ERR! sh: 1: husky: Permission denied
```

**Comment by JoshuaSchmidt-OpenSea** [comment]
Can you try running
```
rm -rf node_modules
npm install
```

**Comment by wizardlabsxyz** [comment]
Yeah i tried this a number of times. No change. I also tried this 
https://stackoverflow.com/questions/51811564/sh-1-node-permission-denied

And i tried intalling husky in project but that did not help.

**Comment by Ailein** [comment]
face the same problem.

**Comment by Ailein** [comment]
getting the same error

**Comment by ryanio** [comment]
For now if you clear the `postinstall` script in package.json that should help unblock the install while we investigate further how to help fix the husky issue

**Comment by Ailein** [comment]
I tried pulling the code from Github and building it without any issues. I didn't clear postinstall, but only encountered errors with Husky when installing through npm.

**Comment by ryanio** [comment]
this should help https://github.com/ProjectOpenSea/opensea-js/pull/1015

**Comment by Ailein** [comment]
Yes, this fixed my issue. Can you release a new version? Thank you！

**Comment by Ailein** [comment]
using 'husky install || true' , I released a test package,

`npm i opensea-js-test`

It worked for me and there were no issues with husky.

**Comment by JoshuaSchmidt-OpenSea** [comment]
This should no longer be an issue in v6.0.1
Feel free to reopen if you have issues.

**Comment by taylangzc** [comment]
having the same issue even with 

`yarn add opensea-js-test`

`error \node_modules\@opensea\seaport-js: Command failed.
Exit code: 1
Command: husky install || true
Arguments:
Directory: \node_modules\@opensea\seaport-js
Output:
'husky' is not recognized as an internal or external command,
operable program or batch file.`
