### ISSUE TITLE
How can I get the testnets api key?

### ISSUE THREAD

**Issue by bin0316** [ProjectOpenSea/opensea-js#1028]
How can I get the testnets api key?

_Originally posted by @bin0316 in https://github.com/ProjectOpenSea/opensea-js/issues/78#issuecomment-1577925799_

**Comment by ryanio** [comment]
you should be able to create a testnets api key here https://testnets.opensea.io/account/settings?tab=developer

**Comment by cterech** [comment]
@bin0316 fyi - testnets endpoints do not require API keys!
