### ISSUE TITLE
Execution reverted while accepting bid on GOERLI : 'cannot estimate gas; transaction may fail or may require manual gas limit'

### ISSUE THREAD

**Issue by thismad** [ProjectOpenSea/opensea-js#1039]
I am trying to accept a bid on my own item : 
token_id : 649
collection_contract :'0x65b618Cb70B31C6CDaFd7B98F42082EeAe1e4445'

Transfer timer is gone, I can accept bids on the UI, but when I try to do it via API, I get execution reverted error.
I successfully fetch the corresponding bid order with api.getOrder and give it to OpenseaSDK.fulfillOrder.

Thanks for looking into it!

**Comment by thismad** [comment]
It looks like its because SDK uses seaport 1.5 meanwhile testnet only supports 1.4? From the https://docs.opensea.io/reference/fulfill-an-offer-testnets?

**Comment by ryanio** [comment]
please share a code snippet to reproduce the error to see how to help. also, make sure you update to the latest v6

**Comment by thismad** [comment]
Here is my code :
```
// No API key needed when using Goerli or test networks
// private keys here
const chainId = (clientNetwork == 'mainnet') ? Chain.Mainnet : Chain.Goerli;

let provider = new providers.InfuraProvider(chainId, apiKeyInfura);
let signer = new ethers.Wallet(privateKey, provider);
let os: OpenSeaSDK;
os = new OpenSeaSDK(provider, 
            {chain: chainId},
            undefined,
            signer);
 try {
        const order = await os.api.getOrder({
            side: "bid",
            tokenId: data.token_id,
            assetContractAddress: data.collection_contract,
            orderBy:"eth_price",
            orderDirection:"desc"
        });
        console.log(order)     // order is correctly fetched here, error when trying to fulfill it
        try {
            const txHash = await os.fulfillOrder({order, accountAddress: process.env[`${walletName}_PUBLIC_KEY`]!});
            pythonRes = {
                status: true,
                responseJson: {txHash},
                message: 'success',
            }
        } catch (e) {
            let typedError: Error = e as Error;
            pythonRes = {
                status: false,
                responseJson: {},
                errorCode: -2,
                message: typedError.message,
            }
        }
    } catch (e) {
        let typedError: Error = e as Error;
        pythonRes = {
            status: false,
            responseJson: {},
            errorCode: -5,
            message: typedError.message,
        }
    }
```
 
 
I am running the latest version of seaport-js (6.0.5)
When I try to fulfill through API on the opensea api testnet on the website it does work.
But not through code.



Here is the result of the order from api.getOrder(): 
```
{
  createdDate: '2023-06-13T07:03:27.987079',
  closingDate: '2023-06-16T07:03:17',
  listingTime: 1686639802,
  expirationTime: 1686898997,
  orderHash: '0xd6b3956e75436711f98788e0d06c4b3ceccdf9360a5c9bb7c6ec399be60293c9',
  maker: {
    address: '0x5aab90d910b3dd9c172d4a62bb27128e12540ecd',
    config: '',
    profileImgUrl: 'https://storage.googleapis.com/opensea-static/opensea-profile/3.png',
    user: { username: undefined }
  },
  taker: null,
  protocolData: {
    parameters: {
      offerer: '0x5aab90d910b3dd9c172d4a62bb27128e12540ecd',
      offer: [Array],
      consideration: [Array],
      startTime: '1686639802',
      endTime: '1686898997',
      orderType: 2,
      zone: '0x000000e7Ec00e7B300774b00001314B8610022b8',
      zoneHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
      salt: '0x360c6ebe00000000000000000000000000000000000000003ebcf379a672b438',
      conduitKey: '0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000',
      totalOriginalConsiderationItems: 2,
      counter: 0
    },
    signature: null
  },
  protocolAddress: '0x00000000000000adc04c56bf30ac9d3c0aaf14dc',
  currentPrice: BigNumber { _hex: '0x2386f26fc10000', _isBigNumber: true },
  makerFees: [],
  takerFees: [ { account: [Object], basisPoints: '250' } ],
  side: 'bid',
  orderType: 'basic',
  cancelled: false,
  finalized: false,
  markedInvalid: false,
  clientSignature: undefined,
  makerAssetBundle: {
    maker: null,
    assets: [ [Object] ],
    assetContract: undefined,
    name: null,
    slug: null,
    description: null,
    externalLink: null,
    permalink: null
  },
  takerAssetBundle: {
    maker: null,
    assets: [ [Object] ],
    assetContract: undefined,
    name: null,
    slug: null,
    description: null,
    externalLink: null,
    permalink: null
  }
}
```

Thanks for looking into it.

**Comment by ryanio** [comment]
@thismad what stands out to me first is this line ```accountAddress: process.env[`${walletName}_PUBLIC_KEY`]!``` your ethereum address is different than the public key, see: https://ethereum.stackexchange.com/a/33178
> The address is the last 20 bytes of the hash of the public key.

**Comment by thismad** [comment]
Actually, it is wrongly labelled as it is my address, not my public key. I just copied the address from Etherscan and named it public key which is wrong. (I originally thought public key = address).

I don't think this is the problem as the rest of the code such as :
```
try {
        // Throws error if order is not found
        // Get the first order (sorted by default in ascending order by price, bc on OS a nft can be listed at multiple prices)

        const order = await os.api.getOrder({
            side: "ask",
            tokenId: data.token_id,
            assetContractAddress: data.collection_contract
        });
        console.log('DEBUG - Order from API when calling /opensea/buy_listing : ', order)
        await new Promise(resolve => setTimeout(resolve, 1000));  // Sleep for 1000 milliseconds, or 1 second
        console.log(process.env[`${walletName}_PUBLIC_KEY`])
        try {
            const txHash = await os.fulfillOrder({
                order,
                accountAddress: process.env[`${walletName}_PUBLIC_KEY`]!
            });
            pythonRes = {
                status: true,
                responseJson: {
                    txHash
                },
                message: 'success',
            }
        } catch (error) {
            let typedError: Error = error as Error;
            pythonRes = {
                status: false,
                responseJson: {},
                errorCode: -2,
                message: typedError.message,
            }
        }
    } catch (error) {
        let typedError: Error = error as Error;
        pythonRes = {
            status: false,
            responseJson: {},
            errorCode: -5,
            message: typedError.message,
        }
    }
```
Does indeed work.

**Comment by ryanio** [comment]
If you have an example tx hash of the revert we can put it in Tenderly to see what the error occurring on chain is.

**Comment by thismad** [comment]
Unfortunately I cant seem to find a tx hash for it, it just gives me this error : 
{'status': False, 'responseJson': {}, 'errorCode': -2, 'message': 'cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"execution reverted","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0x0B5C8913F7EB1fFADFB6F2cBbED7E71A5A10ae2d","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x59682f18"},"to":"0x00000000000000ADc04C56Bf30aC9d3c0aAF14dC","data":"0xfb0f3ee1000000000000000000000000000000000000000000000000000000000000002000000000000000000000000065b618cb70b31c6cdafd7b98f42082eeae1e444500000000000000000000000000000000000000000000000000000000000019ab00000000000000000000000000000000000000000000000000000000000000010000000000000000000000005aab90d910b3dd9c172d4a62bb27128e12540ecd000000000000000000000000000000e7ec00e7b300774b00001314b8610022b8000000000000000000000000b4fbf271143f4fbf7b91a5ded31805e42b2208d60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002386f26fc10000000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000648c617a00000000000000000000000000000000000000000000000000000000649055f00000000000000000000000000000000000000000000000000000000000000000360c6ebe00000000000000000000000000000000000000005f6a37236f3c6d610000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000e35fa931a0000000000000000000000000000000a26b00c1f0df003000390027140000faa7190000000000000000000000000000000000000000000000000000000000000040b8043bba4bc26588a1b4933268d7e11a64298230aa69a0911656711998f13a03f2f4b5344ef6a35e3010588470b7452abe3baf9c3cb9dcc3a0f3f8a0909b2774","type":2,"accessList":null},"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\\"jsonrpc\\":\\"2.0\\",\\"id\\":47,\\"error\\":{\\"code\\":3,\\"data\\":\\"0xd232fd2cafd3f7242062b2e6f8d70151b182e669981da566bb111131388a5b66d956b19e\\",\\"message\\":\\"execution reverted\\"}}","error":{"code":3,"data":"0xd232fd2cafd3f7242062b2e6f8d70151b182e669981da566bb111131388a5b66d956b19e"},"requestBody":"{\\"method\\":\\"eth_estimateGas\\",\\"params\\":[{\\"type\\":\\"0x2\\",\\"maxFeePerGas\\":\\"0x59682f18\\",\\"maxPriorityFeePerGas\\":\\"0x59682f00\\",\\"from\\":\\"0x0b5c8913f7eb1ffadfb6f2cbbed7e71a5a10ae2d\\",\\"to\\":\\"0x00000000000000adc04c56bf30ac9d3c0aaf14dc\\",\\"data\\":\\"0xfb0f3ee1000000000000000000000000000000000000000000000000000000000000002000000000000000000000000065b618cb70b31c6cdafd7b98f42082eeae1e444500000000000000000000000000000000000000000000000000000000000019ab00000000000000000000000000000000000000000000000000000000000000010000000000000000000000005aab90d910b3dd9c172d4a62bb27128e12540ecd000000000000000000000000000000e7ec00e7b300774b00001314b8610022b8000000000000000000000000b4fbf271143f4fbf7b91a5ded31805e42b2208d60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002386f26fc10000000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000648c617a00000000000000000000000000000000000000000000000000000000649055f00000000000000000000000000000000000000000000000000000000000000000360c6ebe00000000000000000000000000000000000000005f6a37236f3c6d610000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000e35fa931a0000000000000000000000000000000a26b00c1f0df003000390027140000faa7190000000000000000000000000000000000000000000000000000000000000040b8043bba4bc26588a1b4933268d7e11a64298230aa69a0911656711998f13a03f2f4b5344ef6a35e3010588470b7452abe3baf9c3cb9dcc3a0f3f8a0909b2774\\"}],\\"id\\":47,\\"jsonrpc\\":\\"2.0\\"}","requestMethod":"POST","url":"https://goerli.infura.io/v3/ee986c0691af4ae3a6b2c60c62af1e22"}}, tx={"data":"0xfb0f3ee1000000000000000000000000000000000000000000000000000000000000002000000000000000000000000065b618cb70b31c6cdafd7b98f42082eeae1e444500000000000000000000000000000000000000000000000000000000000019ab00000000000000000000000000000000000000000000000000000000000000010000000000000000000000005aab90d910b3dd9c172d4a62bb27128e12540ecd000000000000000000000000000000e7ec00e7b300774b00001314b8610022b8000000000000000000000000b4fbf271143f4fbf7b91a5ded31805e42b2208d60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002386f26fc10000000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000648c617a00000000000000000000000000000000000000000000000000000000649055f00000000000000000000000000000000000000000000000000000000000000000360c6ebe00000000000000000000000000000000000000005f6a37236f3c6d610000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000e35fa931a0000000000000000000000000000000a26b00c1f0df003000390027140000faa7190000000000000000000000000000000000000000000000000000000000000040b8043bba4bc26588a1b4933268d7e11a64298230aa69a0911656711998f13a03f2f4b5344ef6a35e3010588470b7452abe3baf9c3cb9dcc3a0f3f8a0909b2774","to":{},"from":"0x0B5C8913F7EB1fFADFB6F2cBbED7E71A5A10ae2d","type":2,"maxFeePerGas":{"type":"BigNumber","hex":"0x59682f18"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.7.0)'}

**Comment by ryanio** [comment]
See my reply here on why "cannot estimate gas" is a general catchall error and how to narrow in on the actual error: https://github.com/ProjectOpenSea/opensea-js/issues/1047#issuecomment-1610196719
