### ISSUE TITLE
ethers v6

### ISSUE THREAD

**Issue by ekhishigee** [ProjectOpenSea/opensea-js#1042]
I am trying to use this library with ethers v6. But I see it is not supported. Any chance we get some basic support?

**Comment by ryanio** [comment]
We plan to but we will likely wait another 1-2 months for developer tools and the community to upgrade to v6 before we do to avoid upgrading too early and breaking compatibility across our user base. Until then please use ethers v5. Keep an eye on our releases for when this happens.

**Comment by nftchance** [comment]
Hey just here to ping that this is the only developer tool I need that has not updated :)

**Comment by rigwild** [comment]
Keep open

**Comment by Slers** [comment]
Please add compatibility for ethers.js v6

**Comment by nftchance** [comment]
Thanks @ryanio <3
