### ISSUE TITLE
Sorry you can't access the Developer Hub at this time.

### ISSUE THREAD

**Issue by mohsinkc** [ProjectOpenSea/opensea-js#1044]
Hey everyone @jtaaa @JoshuaSchmidt-OpenSea ,
I have been trying to access the Opensea website to generate API Keys, I login verify my email, and then when I click on get access then after human verification, I see this message
Sorry you can't access the Developer Hub at this time.
I have tried different wifis, even tried vpn but it doesn't work, it used to work a couple of weeks ago.
Can you guys check if this is my internet issue or this option is unavailable at the moment due to some maintenance.
Thanks,
Cheers

**Comment by thenerdassassin** [comment]
Can you open a support ticket: https://support.opensea.io/hc/en-us/requests/new so someone can look into your individual case and get you access.

**Comment by mohsinkc** [comment]
I have already opened a ticket #967603, this issue is not coming on my
machine but also on one of my coworkers machine who is in a different time
zone. He says it was working fine a few days ago. But now it gives this
error. I have tried different networks even used vpn. Same issue.
Can you please check if there are others who are facing this issue.
Thanks alot for the reply and your help.
