### ISSUE TITLE
Buy listed nft on opensea using sdk

### ISSUE THREAD

**Issue by tungleanh92** [ProjectOpenSea/opensea-js#1045]
I'm following this doc (https://github.com/ProjectOpenSea/opensea-js) to buy nft listed on opensea. But I can't find a way to create provider with private key to call fulfillOrder method. Can someone help me. Tks

**Comment by ryanio** [comment]
See: https://docs.ethers.org/v5/api/signer/#Wallet

**Comment by ryanio** [comment]
Please let us know if you are still having trouble initializing a provider with private key, the ethers docs should help in this regard, but I can give you an example if needed (probably a nice thing to add to the README to help others if you want to contribute with a PR!)
