### ISSUE TITLE
Can I use OpenSea to mint newly created NFTs?

### ISSUE THREAD

**Issue by qiaokeli111** [ProjectOpenSea/opensea-js#1050]
i I want to use JS to automatically mint newly created NFTs. Is there any way to achieve this?

**Comment by ryanio** [comment]
You can mint NFTs using tutorials online, you don't need opensea-js for this. Just use a network we support (eg polygon Mumbai) for it to show up on OpenSea.

Here is a tutorial, there are many online like this if you search for them: https://docs.alchemy.com/docs/how-to-create-an-nft
