### ISSUE TITLE
Issue creating a listing

### ISSUE THREAD

**Issue by FiveNine** [ProjectOpenSea/opensea-js#1054]
Hi I've been trying to create a listing using `createSellOrder` but cant seem to get working. Initially i was using ethers v5.7.2 but was getting the error `The method eth_signTypedData_v4 does not exist/is not available`. 

I was told I should try upgrading my ethers library version and I did to 6.2.2. I had to modify the JSONRPCProvider a little bit since its different in this version but now i get this error `Either signer or a JsonRpcProvider must be provided` and i dont understand why it says that when im providing both. Here's the code:
```js
const { ethers, JsonRpcProvider } = require('ethers');
const { OpenSeaSDK, Chain } = require('opensea-js');


const provider = new JsonRpcProvider(
    "https://goerli.infura.io/v3/API_KEY"
);

const wallet = new ethers.Wallet("PRIVATE_KEY", provider)

const openseaSDK = new OpenSeaSDK(
    provider, 
    {
        chain: Chain.Goerli
    }, 
    wallet
);

const main = async () => {
    let startTime = Date.now();
    startAmount = 0.0002;

    const expirationTime = Math.round(Date.now() / 1000 + 60*60); // seconds
    const listing = await openseaSDK.createSellOrder({
        asset: {
            tokenId: "25", 
            tokenAddress: "0xd08d514c3a6f4625a3546a9dff43c8e27a5cd00a"
        },
        accountAddress: "0x71931FB99CEAD5f1cF647BCf815b46ec55439964",
        startAmount: startAmount,
        expirationTime: expirationTime
    })
};

main();
```
I have also looked into older issues created on this github and they seemed to have similar code. I'm genuinely confused what is the issue here.

**Comment by FiveNine** [comment]
Update: I was informed on discord to revert back to ethers 5 as ethers 6 isnt compatible. So current error I have is: `The method eth_signTypedData_v4 does not exist/is not available`

**Comment by ryanio** [comment]
you have to create a wallet and pass that as a provider, infura alone cannot do anything on behalf of your accounts because it doesn't have access to them https://docs.ethers.org/v5/api/signer/#Wallet

**Comment by FiveNine** [comment]
i am creating a wallet arent i?
`const wallet = new ethers.Wallet("PRIVATE_KEY", provider)`

**Comment by ryanio** [comment]
ah sorry, hmmm

**Comment by ryanio** [comment]
what version of opensea-js are you on

**Comment by FiveNine** [comment]
6.0.5

**Comment by FiveNine** [comment]
package.json
```json
{
  "name": ".",
  "version": "1.0.0",
  "description": "",
  "main": "app-opensea.js",
  "bin": {
    "positionbot": "./app.js"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@opensea/seaport-js": "^2.0.3",
    "axios": "^1.4.0",
    "ethers": "^5.7.2",
    "nexe": "^4.0.0-rc.2",
    "node-fetch": "^3.3.1",
    "opensea-js": "^6.0.5",
    "prompt-sync": "^4.2.0",
    "prompt-sync-history": "^1.0.1",
    "web3": "^4.0.1"
  }
}
```

**Comment by FiveNine** [comment]
Oh also i used the same provider for when i was trying to create a listing using seaport-js as well. [seaport-js issue](https://github.com/ProjectOpenSea/seaport-js/issues/288#issue-1757702028)

**Comment by ryanio** [comment]
ohh you are passing the wallet as the logger, it's the next param. we should really reorder that

**Comment by ryanio** [comment]
so change to 
 ```
const openseaSDK = new OpenSeaSDK(
    provider, 
    {
        chain: Chain.Goerli
    }, 
    undefined // <-- here
    wallet
);
```

**Comment by FiveNine** [comment]
hmm still getting the same error

**Comment by FiveNine** [comment]
let me know and i can send you the wallet address and api keys on discord or something if you would like to test on your own end.

**Comment by ryanio** [comment]
never send anyone your api keys or wallet addresses.

are you sure? 

what happens if you log `console.log((openseaSDK as any)._signerOrProvider)`

**Comment by FiveNine** [comment]
> never send anyone your api keys or wallet addresses.
its just a test wallet with nothing on it at all so no biggie and the api key is a free tier too :) so yea do send me a friend request if that makes it easier for you to help! cuz i cant friend req u on discord haha.

heres the results for `console.log((openseaSDK)._signerOrProvider)`
```JsonRpcProvider {
  _isProvider: true,
  _events: [],
  _emitted: { block: -2 },
  disableCcipRead: false,
  formatter: Formatter {
    formats: {
      transaction: [Object],
      transactionRequest: [Object],
      receiptLog: [Object],
      receipt: [Object],
      block: [Object],
      blockWithTransactions: [Object],
      filter: [Object],
      filterLog: [Object]
    }
  },
  anyNetwork: false,
  _networkPromise: Promise { <pending> },
  _maxInternalBlockNumber: -1024,
  _lastBlockNumber: -2,
  _maxFilterBlockRange: 10,
  _pollingInterval: 4000,
  _fastQueryDate: 0,
  connection: {
    url: 'https://goerli.infura.io/v3/0c21bddaab0542ce96daa501cafec4a3'
  },
  _nextId: 42
}
```

**Comment by FiveNine** [comment]
im sorry for the confusion, here's the actual result ```
Wallet {
  _isSigner: true,
  _signingKey: [Function (anonymous)],
  _mnemonic: [Function (anonymous)],
  address: '0x71931FB99CEAD5f1cF647BCf815b46ec55439964',
  provider: JsonRpcProvider {
    _isProvider: true,
    _events: [],
    _emitted: { block: -2 },
    disableCcipRead: false,
    formatter: Formatter { formats: [Object] },
    anyNetwork: false,
    _networkPromise: Promise { <pending> },
    _maxInternalBlockNumber: -1024,
    _lastBlockNumber: -2,
    _maxFilterBlockRange: 10,
    _pollingInterval: 4000,
    _fastQueryDate: 0,
    connection: {
      url: 'https://goerli.infura.io/v3/API_KEY'
    },
    _nextId: 42
  }
}
```

**Comment by FiveNine** [comment]
ok it seems to work thank you so much for the help once again @ryanio !

**Comment by FiveNine** [comment]
huh this is strange... it says "The offerer does not have the amount needed to create or fulfill."
but if i do `console.log(ethers.utils.formatEther(await wallet.getBalance()))` it prints out `0.489033197357834406`
