### ISSUE TITLE
Can't show the nft image but click  "view original media" can show

### ISSUE THREAD

**Issue by glenzk** [ProjectOpenSea/opensea-js#1057]
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" height="350px" width="350px" viewBox="0 0 350 350">

<image width="350" height="350" x="0" y="0" href="https://ipfs.io/ipfs/{cidA}" />

<image width="350" height="350" x="0" y="0" href="https://ipfs.io/ipfs/{cidB}" />

</svg>
```

I'm trying to encode the above code as tokenURI to draw an nft image.    
But the image can't be shown on opensea, while if I click the "view original media"  button the image can be rendered fine.

**Comment by ryanio** [comment]
This issue is related: https://github.com/ProjectOpenSea/opensea-js/issues/932

We don't show images within svgs for security reasons. You can use an iframe instead if you would like to do this.
