### ISSUE TITLE
Use OpenSea JS to build our own NFT marketplace using EVM blockchain (not supported by OpenSea.com)?

### ISSUE THREAD

**Issue by AnhDOS** [ProjectOpenSea/opensea-js#1059]
Hi,

Can I use OpenSea JS to build our own NFT marketplace using EVM blockchain (not supported by OpenSea.com)?
Or I have to follow what OpenSea has? Or is there copyright?

**Comment by ryanio** [comment]
opensea-js is designed to talk to the OpenSea backend, so it won't be useful for using a chain not supported by OpenSea itself

Seaport, the marketplace protocol, is open source though and you are free to deploy and use on your own chains. https://github.com/ProjectOpenSea/seaport

**Comment by AnhDOS** [comment]
Hi @ryanio. Thank you, we can test the Seaport now.
I'd like to ask whether you open source your OpenSea UI as well so we can use it?

**Comment by ryanio** [comment]
No the opensea UI is not open source
