### ISSUE TITLE
Error when listing assets from certain collections

### ISSUE THREAD

**Issue by kocken** [ProjectOpenSea/opensea-js#1065]
Hello! I have an issue using the OpenSea API & JavaScript SDK to create a listing for certain collections. Might have to do with collections that enforce creator fees (is_creator_fees_enforced: true). Using the OpenSea JS SDK "createSellOrder" function, I'm able to create listings for many of my collection assets, but I get an error when trying to sell assets from the following collections: 888geisha, guttermelo, 6sixty6. Good to know - All of those appear to enforce collections fees, so perhaps the issue could be connected to this.

The error I get is "You have not provided all required creator fees.". Here's the full error message: 
`bad response (status=400, headers={"date":"Thu, 06 Jul 2023 21:15:38 GMT","content-type":"application/json","content-length":"63","connection":"close","x-trace-id":"4706527872227492387","vary":"Accept, Origin","allow":"GET, POST, HEAD, OPTIONS","x-frame-options":"DENY","x-content-type-options":"nosniff","referrer-policy":"same-origin","cross-origin-opener-policy":"same-origin","cache-control":"no-store","cf-cache-status":"DYNAMIC","set-cookie":"__cf_bm=HPYkHQ8Smc59rVtxG1eOCUHX3umlco7kPjdekF_6Qls-1688678138-0-AcVNrCmoHEckwbIgqpaQKYtCXbcw22MJQHO6AoFLnhrwnrgXqo8tGVk5ABTMBtXKbNQ8xaXAs2z9Ehs2nvuGIys=; path=/; expires=Thu, 
06-Jul-23 21:45:38 GMT; domain=.opensea.io; HttpOnly; Secure, _cfuvid=zBQBovRIKLz3QoaUC9Kt_sYlDH7v..NlzQIu.M3HRLE-1688678138230-0-604800000; path=/; domain=.opensea.io; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=15552000; includeSubDomains; preload","server":"cloudflare","cf-ray":"7e2add39a97d1d16-CPH"}, body="{\"errors\":[\"You have not provided all required creator fees.\"]}", requestBody="{\"parameters\":{\"offerer\":\"0xB2BA75d8F3649862eAb2B4f15D7Ad96AE0f7b379\",\"zone\":\"0x0000000000000000000000000000000000000000\",\"zoneHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"startTime\":\"1688678137\",\"endTime\":\"1691270137\",\"orderType\":1,\"offer\":[{\"itemType\":2,\"token\":\"0x64364c4705b19fac018ee65c1a14038d3db7e2d9\",\"identifierOrCriteria\":\"620\",\"startAmount\":\"1\",\"endAmount\":\"1\"}],\"consideration\":[{\"itemType\":0,\"token\":\"0x0000000000000000000000000000000000000000\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"7246499999999033\",\"endAmount\":\"7246499999999033\",\"recipient\":\"0xB2BA75d8F3649862eAb2B4f15D7Ad96AE0f7b379\"},{\"itemType\":0,\"token\":\"0x0000000000000000000000000000000000000000\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"187499999999975\",\"endAmount\":\"187499999999975\",\"recipient\":\"0x0000a26b00c1f0df003000390027140000faa719\"},{\"itemType\":0,\"token\":\"0x0000000000000000000000000000000000000000\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"65999999999991\",\"endAmount\":\"65999999999991\",\"recipient\":\"0xca24c12b5c57de1dcefdd911cbcef03c53fc4a97\"}],\"totalOriginalConsiderationItems\":3,\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"conduitKey\":\"0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000\",\"counter\":\"0\"},\"signature\":\"0x4f391fce5d6b5ed2c2818c952d3a0f1e7b66cde91e618cad3181efcc7cd341ccccf44620dc0ed879e58ea0dcc35a9399b3ff14c92101ec2cc0301c5a06dfe090\",\"protocol_address\":\"0x00000000000000ADc04C56Bf30aC9d3c0aAF14dC\"}", requestMethod="POST", url="https://api.opensea.io/v2/orders/ethereum/seaport/listings", code=SERVER_ERROR, version=web/5.7.1)`

It appears that the payload has the correct fees though, creator fee is included in the consideration, and so are Opensea fees:
`"consideration":[{"itemType":0,"token":"0x0000000000000000000000000000000000000000","identifierOrCriteria":"0","startAmount":"7246499999999033","endAmount":"7246499999999033","recipient":"0xB2BA75d8F3649862eAb2B4f15D7Ad96AE0f7b379"},{"itemType":0,"token":"0x0000000000000000000000000000000000000000","identifierOrCriteria":"0","startAmount":"187499999999975","endAmount":"187499999999975","recipient":"0x0000a26b00c1f0df003000390027140000faa719"},{"itemType":0,"token":"0x0000000000000000000000000000000000000000","identifierOrCriteria":"0","startAmount":"65999999999991","endAmount":"65999999999991","recipient":"0xca24c12b5c57de1dcefdd911cbcef03c53fc4a97"}]`

I've also attempted to map the payload myself, and then sent a POST request to https://api.opensea.io/v2/orders/ethereum/seaport/listings, but this gives me the same response: 
`{"errors":["You have not provided all required creator fees."]}`.

So it appears that the API might be faulty for these type of collections, or am I doing something wrong?

**Comment by ryanio** [comment]
thanks for reporting, there is likely a math precision issue between this SDK and the opensea backend, since the collections you listed as examples all have non-standard creator fee basis points amounts:

- 888geisha: 88 bps
- guttermelo: 187 and 563 bps
- 6sixty6: 333 and 333 bps

we will look into fixing this

**Comment by ryanio** [comment]
could you share your `createSellOrder` parameters, what price are you trying to list at? i tried listing an item at .0075 with a collection that has 88 basis points to replicate the above and it seems to be working okay

**Comment by mayavolt** [comment]
I have same error with this createSellOrder parameters:

```ts
await openseaSDK.createSellOrder({
      asset: {
        tokenId: item.id,
        tokenAddress: NFT_CONTRACT_ADDRESS,
      },
      startAmount: 1.5,
      endAmount: 1.3,
      expirationTime: EXPIRATION_TIME, 
      accountAddress: OWNER_ADDRESS,
    });
   ```

**Comment by kocken** [comment]
Here are my parameters, mostly dynamic and generated in run-time:
`          const sellResponse = await openSeaSdk.createSellOrder({
            asset: asset,
            accountAddress: accountAddress,
            startAmount: sellPriceEth,
            endAmount: sellPriceEth,
            expirationTime: expirationTime,
            quantity: 1,
            paymentTokenAddress: '0x0000000000000000000000000000000000000000',
            listingTime: currentTime
          });`

For this specific case, I tried to sell a 888geisha asset for 0.007499999999999 ETH using SDK.
Logs for this instance:
`Error: bad response (status=400, headers={"date":"Sun, 09 Jul 2023 09:17:53 GMT","content-type":"application/json","content-length":"63","connection":"close","x-trace-id":"15751573330045688875","vary":"Accept, Origin","allow":"GET, POST, HEAD, OPTIONS","x-frame-options":"DENY","x-content-type-options":"nosniff","referrer-policy":"same-origin","cross-origin-opener-policy":"same-origin","cache-control":"no-store","cf-cache-status":"DYNAMIC","set-cookie":"__cf_bm=UzTsVlpxs1UrVUZS2bkh1IfQKcc6tMMukinLHHRKcps-1688894273-0-AdXzcqlmr7jkv6kCLZnvkFn90zX9qLdBs15w+ieJahTZflLAhe0XCGhZSWCRh8Y/MTBCkvE1bDznk8O/LcnvwA0=; path=/; expires=Sun, 09-Jul-23 09:47:53 GMT; domain=.opensea.io; HttpOnly; Secure, _cfuvid=budmaLJmSRrcJrSErIMJmJT0NKfrNfxRWBv0P1L3rHo-1688894273082-0-604800000; path=/; domain=.opensea.io; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=15552000; includeSubDomains; preload","server":"cloudflare","cf-ray":"7e3f79f4bf6fabdb-CPH"}, body="{\"errors\":[\"You have not provided all required creator fees.\"]}", requestBody="{\"parameters\":{\"offerer\":\"0xB2BA75d8F3649862eAb2B4f15D7Ad96AE0f7b379\",\"zone\":\"0x0000000000000000000000000000000000000000\",\"zoneHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"startTime\":\"1688894273\",\"endTime\":\"1691486273\",\"orderType\":1,\"offer\":[{\"itemType\":2,\"token\":\"0x64364c4705b19fac018ee65c1a14038d3db7e2d9\",\"identifierOrCriteria\":\"620\",\"startAmount\":\"1\",\"endAmount\":\"1\"}],\"consideration\":[{\"itemType\":0,\"token\":\"0x0000000000000000000000000000000000000000\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"7246499999999033\",\"endAmount\":\"7246499999999033\",\"recipient\":\"0xB2BA75d8F3649862eAb2B4f15D7Ad96AE0f7b379\"},{\"itemType\":0,\"token\":\"0x0000000000000000000000000000000000000000\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"187499999999975\",\"endAmount\":\"187499999999975\",\"recipient\":\"0x0000a26b00c1f0df003000390027140000faa719\"},{\"itemType\":0,\"token\":\"0x0000000000000000000000000000000000000000\",\"identifierOrCriteria\":\"0\",\"startAmount\":\"65999999999991\",\"endAmount\":\"65999999999991\",\"recipient\":\"0xca24c12b5c57de1dcefdd911cbcef03c53fc4a97\"}],\"totalOriginalConsiderationItems\":3,\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"conduitKey\":\"0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000\",\"counter\":\"0\"},\"signature\":\"0xcad6511daccc54221dbf22d1f88577963155aa0ee3bc17e6bdacdebf66623e4356d3d12030cd5c8d942531183995518b95877665dde25b9cc321ba30211c09c8\",\"protocol_address\":\"0x00000000000000ADc04C56Bf30aC9d3c0aAF14dC\"}", requestMethod="POST", url="https://api.opensea.io/v2/orders/ethereum/seaport/listings", code=SERVER_ERROR, version=web/5.7.1)`
