### ISSUE TITLE
Retrieve Offer returning an empty order object list

### ISSUE THREAD

**Issue by Vinicius-Fiorio** [ProjectOpenSea/opensea-js#1073]
### I would like to receive the list of offers for any token ID, 
_but when executing the code below, for some IDs the list is returned correctly and for others an empty list is returned (even though there are offers in that token ID)_

My code:
```js
require('dotenv').config();
const ethers = require('ethers');
const { OpenSeaSDK, Chain } = require("opensea-js");

//Just read
const provider = new ethers.providers.JsonRpcProvider(
  "https://mainnet.infura.io"
);

const openseaSDK = new OpenSeaSDK(provider, {
  chain: Chain.Mainnet,
  apiKey: process.env.API_KEY,
});

async function getOrders(id){
  const { orders } = await openseaSDK.api.getOrders({
    assetContractAddress: "0xeb2dfc54ebafca8f50efcc1e21a9d100b5aeb349",
    tokenId: id,
    side: "bid",
    orderBy: "eth_price"
  });

  return orders
}

getOrders(8797);
```

At the moment this token ID **#8797** has +10 offers
![image](https://github.com/ProjectOpenSea/opensea-js/assets/44504672/b0292096-663c-4508-9699-d022041b8d20)

but returns:
```js
[]
```

When I run the function again but now changing the tokenId property to another ID (for example **#7**) is returned the expected
![image](https://github.com/ProjectOpenSea/opensea-js/assets/44504672/968e8ea7-6c3d-4b5c-88a5-738566513790)

```js
{
  ...
  "orders": [
    {
      "created_date": "2023-07-07T23:58:30.459700",
      "closing_date": "2023-07-08T00:17:51",
      "listing_time": 1688774271,
      "expiration_time": 1688775471,
      "order_hash": "0x3147d3124c9c50c45675a10ae8b953abe02899a1620225df67af2244138246d0",
      "protocol_data": {
        "parameters": {
          "offerer": "0x80c9a4104f594029f3f7f9e4fde5ac25e9e64cdf",
          "offer": [
            {
              "itemType": 1,
              "token": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
              "identifierOrCriteria": "0",
              "startAmount": "2002700000000000000", //same ETH as the highest offer
              "endAmount": "2002700000000000000"

              ...{more data}
            }
          ]
        }
      }
    }
  ]     
}

```

**Comment by ryanio** [comment]
Those are collection offers, ideally we'd additionally query to include them in the sdk on getOffers https://docs.opensea.io/reference/retrieve-collection-offers

**Comment by Vinicius-Fiorio** [comment]
I believe I should use this method if I chose to view the collection offer as you mentioned, which in fact is working perfectly:
![image](https://github.com/ProjectOpenSea/opensea-js/assets/44504672/517f1b9e-979b-4326-b28e-7c171b58cfb0)
_(filter: eth_price, desc)_
![image](https://github.com/ProjectOpenSea/opensea-js/assets/44504672/bbdcc2be-9cda-4c04-a6e3-e058cc197304)

By checking the offers of the first nft listed we can see that there is a higher offer than the collection offer(which I believe is an exclusive offer for that specific tokenId)
![image](https://github.com/ProjectOpenSea/opensea-js/assets/44504672/1914967b-3df6-4808-b29a-1bb864d50588)

Searching for offers for a specific tokenId returns no offers
![image](https://github.com/ProjectOpenSea/opensea-js/assets/44504672/e26e070a-655e-4ac7-a0cc-72e45d0d2adb)

I then think about searching by trait(The nft in question has the trait Type: Kubz), and then returns the offer
![image](https://github.com/ProjectOpenSea/opensea-js/assets/44504672/5774f201-02b8-4423-911d-fc1a9830ee3e)

Now I understand better how it works, I would like to suggest an endpoint to return the set of offers mixing (collection + trait + tokenId), it would make the API consumption easier and it would not be necessary to make many requests to get all the offer information of a certain tokenId
_I mean that when we open the page of a token in OpenSea we can see this mixture in the offers section_

Thanks for the correction
