### ISSUE TITLE
Creating orders on sepolia not yet supported by the SDK.

### ISSUE THREAD

**Issue by tienvv1234** [ProjectOpenSea/opensea-js#1085]
I can not create order with Sepolia, and the Goerli required minimun 0.001 ETH, how can pass to this one and test all function in testnet

**Comment by ryanio** [comment]
Why can't you create with Sepolia? It is supported now in the latest version of opensea-js

**Comment by tienvv1234** [comment]
I am using Opensa version 6.1.2, when I call the function createBuyOrder it will return this error
Creating orders on Sepolia not yet supported by the SDK(https://testnets.opensea.io/assets/goerli/0xf4910c763ed4e47a585e2d34baa9a4b611ae448c/41523119144019418335847972109562421607287855164231022950688170492050305712129
)
![image](https://github.com/ProjectOpenSea/opensea-js/assets/34591094/81813dd7-a627-4f18-b2fa-3b67caab26f3)

**Comment by ryanio** [comment]
getAssets is not supported multichain, use getNFTsByCollection or getNFTsByContract instead. the next release (v6.1.4) will throw an error to let you know about this
