### ISSUE TITLE
Calculating NFT unit price 2.0

### ISSUE THREAD

**Issue by UTkzhang** [ProjectOpenSea/opensea-js#1088]
Hello, we just closed https://github.com/ProjectOpenSea/opensea-js/issues/1064 and the update worked in the sense that the remainingQuantity field is now returned correctly. However, my issue has not been resolved. I realized that the currentPrice field on the Orders api actually returns the price based on the original quantity i.e (10 eth if 10 items were listed at first, even if 8 are remaining). As such, we still do not have a reliable way of calculating the current unit price of an item.

On Opensea, this is quite clearly shown, so I am sure there is an easy way to get this value
<img width="978" alt="image" src="https://github.com/ProjectOpenSea/opensea-js/assets/34317307/48fd8c14-3b7f-4a84-a211-dd1ff14f7c81">

I am just looking for a quote of the lowest listing of a given asset. The currentPrice is not that helpful of a field because it is not current and not a unit price :/

My work around has been to use the seaport protocolData.parameters.offer[0].startAmount, but this is not that reliable as the endAmount could differ from the startAmount in certain rare cases. How does Opensea calculate the current unit price? Looking for some more advice here, thanks!

**Comment by ryanio** [comment]
For 1155 you are correct to divide by startAmount, I don't believe we support orders with different start/endAmounts for non-currency items, so there should be no worry about cases where startAmount != endAmount for the 1155 token

**Comment by UTkzhang** [comment]
thanks!
