### ISSUE TITLE
Errors: Duplicate order, SERVER_ERROR (createSellOrder)

### ISSUE THREAD

**Issue by mayavolt** [ProjectOpenSea/opensea-js#1089]
Using the `createSellOrder` method, I am trying to list my items.

```ts
try {
  await openseaSDK.createSellOrder({
        asset: {
          tokenId: asset.id,
          tokenAddress: NFT_CONTRACT_ADDRESS,
        },
        accountAddress: ACCOUNT_ADDRESS,
        startAmount: startPrice, // 3.5
        endAmount: endPrice, // 1.5
        expirationTime: EXPIRATION_TIME
      });
} catch (e) {
    console.error(e);
    throw error;
}
```

Sometimes (once or twice), it works fine, but in most cases, I catch errors like:
```json  reason: 'bad response',
  code: 'SERVER_ERROR',
  status: 400,
  headers: {
    [...]
    server: 'cloudflare',
    'cf-ray': '7e6182a1b93c7768-LHR'
  },
  body: '{"errors":["Duplicate order 0xa4ee11149e68d238d8c315f8ea74fcd88fb29df3deb1d.................."]}',
  requestMethod: 'POST',
  url: 'https://api.opensea.io/v2/orders/ethereum/seaport/listings'
  ```

My package.json
```json
 "dependencies": {
    "@0x/subproviders": "^8.0.1",
    "ethers": "^5.7.2",
    "opensea-js": "6.1.3",
    "web3": "^4.0.3",
  },
  "engines": {
    "node": "18.16.1"
  },
```

Any ideas about what's wrong and how to solve this problem?

**Comment by ryanio** [comment]
Duplicate order would mean the API already has the order, it won't accept the same order twice

**Comment by mayavolt** [comment]
> Duplicate order would mean the API already has the order, it won't accept the same order twice

But, I don't call the listing method twice for the same nft. I have five nft in my collection, which are in the same conditions, such as price and expiration date (6 months). I want to set a price for them that will fall during the month. From 3.5 to 1.5 in one month. That's works for two nft successfully, and the rest give this error. Can you elaborate on what my mistake is, please?

**Comment by ryanio** [comment]
Without seeing more of your code it's hard to tell. If you change the salt it should let you continue to submit with the same parameters.

**Comment by mayavolt** [comment]
Looks like I got this error (Duplicate order) when I called createSellOrder in the setTimeout() function.

```ts

const sellAsset = async (asset: Asset) => {
  try {
    await openseaSDK.createSellOrder({
          asset: {
            tokenId: asset.id,
            tokenAddress: NFT_CONTRACT_ADDRESS,
          },
          accountAddress: ACCOUNT_ADDRESS,
          startAmount: startPrice, // 3.5
          endAmount: endPrice, // 1.5
          expirationTime: EXPIRATION_TIME
        });
  } catch (e) {
      console.error(e);
      throw error;
  }
}

// Works fine
sellAsset(asset); 

// Doesn't work and throws an error
setTimeout(() => {
   sellAsset(asset);
}, 3000);
```

I use setTimeout() because I need time to read all nfts from JSON files and add them into an array. Do you know how to "fix" it?

**Comment by ryanio** [comment]
using setTimeout for that case is an anti pattern, instead you should use an async process and wait until you have everything ready. you also didn't `await` sellAsset. also you cant call sellAsset then call it again in setTimeout, otherwise then you have duplicate orders.

**Comment by ryanio** [comment]
This seems like user error so I am closing for now, but please open a new issue with your problematic code to recreate if you are still experiencing issues. Ensure you are only calling to create the order ONCE and awaiting it properly. Duplicate order seems like a valid error response that explains the problem.
