### ISSUE TITLE
SVGs not showing on opensea page

### ISSUE THREAD

**Issue by zuuring** [ProjectOpenSea/opensea-js#109]
Seems to be an issue where SVGs are not previewing correctly on main pages. However works when opening image directly from link

https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/63072010777396919798111357654285112804114173870330065563187205085082163347457

**Comment by eth0izzle** [comment]
It's because OpenSea renders SVGs as images, i.e. using the HTML `<img />` tag. Browsers will ignore any JavavScript inside SVGs when rendered like this. OpenSea might not want to support this for security reasons.

OS team, if you want to support this then you could render all types as

    <object data="image.svg" type="image/svg+xml">
        <img src="image.svg">
    </object>

**Comment by ariesjia** [comment]
```html
<embed src="./image.svg" />
```
`<embed/>`  tag can also achieve a similar effect

**Comment by esteban-OpenSea** [comment]
Hello, just wanted to follow up on this. I have seen SVG's working. Are you still having this issue?

**Comment by aberrier** [comment]
Hello @esteban-OpenSea 
Can you provide examples of SVG working with <image /> tag inside ?

**Comment by esteban-OpenSea** [comment]
Check this out for the latest update on SVG: https://github.com/ProjectOpenSea/opensea-js/issues/410 also this video does a good job of explaining working SVG: https://www.youtube.com/watch?v=QVWs9e4RFSA

**Comment by ITzWick** [comment]
> Hello, just wanted to follow up on this. I have seen SVG's working. Are you still having this issue?

No sir it's not working on me... I can see my art in opensea website but not in opensea application... It's showing my profile pic instead of my art!!. Please help..

https://opensea.io/assets/ethereum/0x495f947276749ce646f68ac8c248420045cb7b5e/35210098598941525044272801741479103848255072606645292746636009289008052961281

**Comment by ITzWick** [comment]
Help me... Or contact opensea to solve this problem!😢

**Comment by charlesashby** [comment]
Any updates on this? It seems that on-chain SVGs work, but if you have an `<image>` tag in your SVG file it doesn't work.

I know that this collection was able to get it to work after getting in touch with the team: https://opensea.io/collection/neotokyo-outer-citizens

But I can't get it to work on a test net (e.g. https://testnets.opensea.io/collection/my-tokens-name) is it just a test net issue, would it work on mainnet?

**Comment by charlesashby** [comment]
Following up on this, it seems like the NFTs on this page are displayed as iframes https://opensea.io/collection/neotokyo-outer-citizens, would be great to have a way to toggle that as a creator

**Comment by ariesjia** [comment]
opensea provide `animation_url` config in metadata, this is a better way to create an interaction NFT

link [https://docs.opensea.io/docs/metadata-standards](https://docs.opensea.io/docs/metadata-standards)

**Comment by OodavidsinoO** [comment]
> Check this out for the latest update on SVG: #410 also this video does a good job of explaining working SVG: https://www.youtube.com/watch?v=QVWs9e4RFSA

The problem exists when trying to create a lazy-mint NFT directly through OpenSea. We know the on-chain NFTs and animation_url support SVG and HTML which lazy-mint NFTs don't. It needs to be fixed.

**Comment by zuuring** [comment]
@sunwrobert This is still not fixed despite being close
<img width="771" alt="Screenshot 2022-08-22 at 16 49 53" src="https://user-images.githubusercontent.com/7145746/185937520-c110b933-f1a9-497d-8413-fff439000615.png">
d

**Comment by zuuring** [comment]
Would be easiest fix to render all SVGs as object type, should resolve it :)

```
<object data="image.svg" type="image/svg+xml">
    <img src="image.svg">
</object>
```

**Comment by alexvobo** [comment]
Any updates on this?

**Comment by tavurth** [comment]
<img width="384" alt="Screenshot 2023-10-18 at 20 24 00" src="https://github.com/ProjectOpenSea/opensea-js/assets/100964/a9636ae8-4fae-4f01-af75-134425d3eadb">

So... OpenSea does not support SVG?

**Comment by piecesnbits** [comment]
yeah why? reopen please

**Comment by sullof** [comment]
It looks like still this has not been solved. 
For example
https://opensea.io/item/ethereum/0x3b6aad76254a79a9e256c8aed9187dea505aad52/1
does not show the composite svg, which is visible directly linked, like
https://arweave.net/XyrKASYUNop9CXyjdPo6OKW-ttIb2Fkv06IHRtmv2XQ/1.svg
Solving it without security issue is quite simple. Are you guys going to solve it?
