### ISSUE TITLE
Can't get order info

### ISSUE THREAD

**Issue by flingjie** [ProjectOpenSea/opensea-js#11]
sometimes, seaport.api.getOrders return { orders: [], count: 1 }, but  I can find the order on opensea website
![image](https://user-images.githubusercontent.com/6680819/50957306-dfc22b80-14f8-11e9-9817-6baf1dd3bb39.png)
![image](https://user-images.githubusercontent.com/6680819/50957372-0aac7f80-14f9-11e9-994a-f02029e72e3c.png)

**Comment by alexanderatallah** [comment]
Hello! You’re querying for Buy orders, which are offers. The listing in the screenshot is a sell order. The count shouldn’t have been 1 though, it should have been 0; deploying a fix for that now

**Comment by n4ru** [comment]
Was this fix ever deployed? Looking like a no on my end when I query anything - still returns count of 1 with an empty orders array.
