### ISSUE TITLE
Does buying/selling with this SDK still give royalties through OpenSea?

### ISSUE THREAD

**Issue by alexwasner** [ProjectOpenSea/opensea-js#110]
See title. I have asked around on Discord to no avail.

**Comment by alexwasner** [comment]
![Screen Shot 2021-05-25 at 3 32 18 PM](https://user-images.githubusercontent.com/4612947/119564480-757b5000-bd6e-11eb-812b-04ab8acdcee2.png)
Closing, but leaving this here for future devs looking for the same answer

**Comment by esteban-OpenSea** [comment]
Check [this](https://docs.opensea.io/docs/10-setting-fees-on-secondary-sales) out! This is not an issue related to the opensea-js, so I will close out this ticket. Thanks!
