### ISSUE TITLE
Why is "trait_count" always zero in the traits array?

### ISSUE THREAD

**Issue by jenshandersson** [ProjectOpenSea/opensea-js#1101]
When getting a single NFT we are receiving the traits array and the rarity, but the `trait_count` is always 0 (for all our mainnet collections). Why is that? And is there anything we can do to get them? Looking at opensea.io the trait counts are in the UI, and we would love to get the same data in the public API. Thanks!

Example collection: 0x1db727c12fb0558fd57d472964a9e136e306b958 (ethereum)

**Comment by ryanio** [comment]
where are you seeing `trait_count`?  there is a property `traits` you can check the length of?

**Comment by jenshandersson** [comment]
> where are you seeing `trait_count`? there is a property `traits` you can check the length of?

I assumed the trait_count would represent how many tokens have this exact trait value, ie what percentage have the same trait. See image below:

<img width="492" alt="image" src="https://github.com/ProjectOpenSea/opensea-js/assets/1150467/3666b6fe-ea7a-4b69-a619-aedc040b32dd">

In this api https://docs.opensea.io/reference/get-an-nft

But maybe I misunderstand the api then? Is it possible to see that how many tokens have eg “Collapsed”: “False”?

Thanks!

**Comment by ryanio** [comment]
ah hmm not too sure, will try to ask and get back to you here

**Comment by jenshandersson** [comment]
Great thanks! Yea I expected it to represent these percentages here: 

<img width="600" alt="image" src="https://github.com/ProjectOpenSea/opensea-js/assets/1150467/1499c2c3-9182-4387-8d99-3b865fa63f96">

**Comment by ryanio** [comment]
it seems to work for other collections but not yours so I'm not quite sure, I'll open a ticket internally to investigate further

**Comment by ryanio** [comment]
thanks for your patience, we have made some progress debugging this issue specifically, haven't implemented a fix yet but will let you know here when we do

**Comment by thenerdassassin** [comment]
@jenshandersson We are currently working on a fix in the API for this issue. Most likely, the solution will be a new endpoint to get all the traits, along with the count, for the collection. Make sure to follow along to the API [changelog](https://docs.opensea.io/changelog) for a release announcement.

**Comment by ryanio** [comment]
just wanted to share an update, we will likely be releasing a new v2 api endpoint for trait stats/counts, so i will give an update here when that is out!
