### ISSUE TITLE
500 Server Error when using V2 endpoints to "Get an NFT" on Goerli

### ISSUE THREAD

**Issue by SMLaursen** [ProjectOpenSea/opensea-js#1102]
Most NFTs on Goerli, doesn't work with the new V2 endpoints, e.g.;
https://testnets-api.opensea.io/v2/chain/goerli/contract/0x09e8617f391c54530cc2d3762ceb1da9f840c5a3/nfts/1416 leads to a **500**

I found a few that are working though, e.g.;
https://testnets-api.opensea.io/v2/chain/goerli/contract/0xf4910c763ed4e47a585e2d34baa9a4b611ae448c/nfts/99929431184251114397491372700882567496026176329676333277480802736469828435970

Also, "get-an-nft-testnets" is missing here; 
https://docs.opensea.io/reference/get-an-nft

**Comment by SMLaursen** [comment]
@cterech

**Comment by ryanio** [comment]
get-an-nft along with the other new endpoints are now available in the testnets section.

i am filing a ticket internally to investigate the 500 error, thanks for reporting.

**Comment by ryanio** [comment]
if you have more examples of returning 500 that would be great if you can reply with them here, so we have more examples to investigate and confirm when fixed

**Comment by rigwild** [comment]
Examples from #1120


```sh
curl --request GET \
     --url https://testnets-api.opensea.io/v2/chain/goerli/contract/0xe2de2249cf1c9d76eaf24257b85bbe83bd218a0b/nfts \
     --header 'accept: application/json'

curl --request GET \
     --url https://testnets-api.opensea.io/v2/chain/goerli/contract/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/nfts/1 \
     --header 'accept: application/json'
```

both return HTTP 500

```html
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
<script>(function(){var js = "window['__CF$cv$params']={r:'7ec82794484e0406'};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/invisible.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v2cb3a2ab87c5498db5ce7e6608cf55231689030342039" integrity="sha512-DI3rPuZDcpH/mSGyN22erN5QFnhl760f50/te7FTIYxodEF8jJnSFnfnmG/c+osmIQemvUrnBtxnMpNdzvx1/g==" data-cf-beacon='{"rayId":"7ec82794484e0406","version":"2023.4.0","b":1,"token":"96047490de144c8b91be74ba7605ab69","si":100}' crossorigin="anonymous"></script>
</body>
</html>
```

**Comment by SMLaursen** [comment]
**Examples giving 500 :** 
https://testnets-api.opensea.io/v2/chain/goerli/contract/0x10b8b56d53bfa5e374f38e6c0830bad4ebee33e6/nfts/212
https://testnets-api.opensea.io/v2/chain/goerli/contract/0x09e8617f391c54530cc2d3762ceb1da9f840c5a3/nfts/1074
https://testnets-api.opensea.io/v2/chain/goerli/contract/0x317a8fe0f1c7102e7674ab231441e485c64c178a/nfts/12121

I have a vague theory, that it somehow relates to the age of the mint as most older stuff (See examples above) doesn't seem to work, whereas newer stuff that seems to work, e.g.;
https://testnets-api.opensea.io/v2/chain/goerli/contract/0x4d836a9f8e3a2f5d31bfb7ac961d30d5480a75b3/nfts/4897

Also it seems to be on a per collection basis - and not individual NFT-basis

**Comment by ryanio** [comment]
This is being worked on and should be resolved over the next couple of days, we are backfilling data on testnets to resolve the issue. Will leave a reply here when fully resolved and we can check all the above examples are working. Thanks everyone.

**Comment by montasaurus** [comment]
@SMLaursen the backfill is completed and it should be working now. I checked the links you provided and they're all returning as expected. Thanks for letting us know about this!
