### ISSUE TITLE
Metadata Refresh API fails

### ISSUE THREAD

**Issue by ppals** [ProjectOpenSea/opensea-js#1107]
Does not support mumbai

Error 400

{
  "errors": [
    "Chain mumbai not supported"
  ]
}

**Comment by ryanio** [comment]
are you using the testnets endpoint

**Comment by ppals** [comment]
no... I'm using https://testnet.api.opensea.io/v2/chain/${chain}/contract/${contractAddress}/nfts/${tokenId}/refresh

where $chain is mumbau

**Comment by ppals** [comment]
Reference:

https://docs.opensea.io/reference/refresh-nft-metadata

**Comment by ryanio** [comment]
the domain is `testnets-api.opensea.io`, just use the sdk `refreshNFTMetadata()`?

this is working for me:

```bash
curl --request POST \
     --url https://testnets-api.opensea.io/v2/chain/mumbai/contract/0xac59e473d8d445576beb0f22fa176c6196a1fdf1/nfts/32/refresh \
     --header 'accept: application/json'

> "Successfully queued metadata refresh for contract 0xac59e473d8d445576beb0f22fa176c6196a1fdf1 and token_id 32"%
```

**Comment by ryanio** [comment]
Closing as I cannot recreate the issue, please open a new issue with how to recreate with the problematic code if you are still experiencing issues. Thanks!
