### ISSUE TITLE
npm install --save opensea-js error code: 128

### ISSUE THREAD

**Issue by ming0109** [ProjectOpenSea/opensea-js#112]
PS C:\Users\wmy\Desktop\3dptrust V2.0> npm install --save opensea-js
npm ERR! Error while executing:
npm ERR! E:\Git\cmd\git.EXE ls-remote -h -t https://github.com/ProjectOpenSea/wyvern-js.git
npm ERR!
npm ERR! fatal: unable to access 'https://github.com/ProjectOpenSea/wyvern-js.git/': OpenSSL SSL_read: Connection was reset, errno 10054
npm ERR!
npm ERR! exited with error code: 128.
npm ERR! A complete log of this run can be found in:   
npm ERR!     C:\Users\wmy\AppData\Roaming\npm-cache\_logs\2021-05-28T08_19_39_784Z-debug.log

**Comment by ming0109** [comment]
I tried to switch the node version, but the problem was not resolved.

**Comment by esteban-OpenSea** [comment]
We are aware of this issue. Please refer to [this](https://github.com/ProjectOpenSea/opensea-js/issues/69) issue. I am closing this one out since it is a duplicate issue.
