### ISSUE TITLE
Compile error while import from "src/orders/types";

### ISSUE THREAD

**Issue by mkideal** [ProjectOpenSea/opensea-js#1121]
### Component

API

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

6.1.4

### Operating System

macOS (Apple Silicon)

### Describe the bug

node_modules/opensea-js/lib/api/types.d.ts:2:30 - error TS2307: Cannot find module 'src/orders/types' or its corresponding type declarations.

`import { ProtocolData } from "src/orders/types";`

If I change `src/orders/types` to `../orders/types`, the error disappeared.

**Comment by ryanio** [comment]
you should import from the package, like `import { ProtocolData } from "opensea-js/orders/types";`

**Comment by mkideal** [comment]
It's imported by `node_modules/opensea-js/lib/api/types.d.ts:2:30`, not my source code

**Comment by ryanio** [comment]
ooh got it, thank you, will open a PR to fix

**Comment by ryanio** [comment]
this should be fixed in [v6.1.5](https://github.com/ProjectOpenSea/opensea-js/releases/tag/v6.1.5) now! thanks again for reporting
