### ISSUE TITLE
Can we getNFTsByCollection/getNFTsByContract order by price?

### ISSUE THREAD

**Issue by mkideal** [ProjectOpenSea/opensea-js#1128]
### Component

API

### Describe the feature you would like

I want to show items order by price(fixed) using `getNFTsByCollection()`.

**Comment by ryanio** [comment]
Sorry no this is not currently supported on the API level for that endpoint, you'll want to use `getOrders` with `orderBy: "eth_price"`

**Comment by mkideal** [comment]
But, how can I getOrders by collection?
