### ISSUE TITLE
Cannot config OpenSeaPort for mumbai testnet

### ISSUE THREAD

**Issue by nhoclove9x** [ProjectOpenSea/opensea-js#113]
Hello everyone,

I have problem with opensea-js. 
I wanna using opensea-js on my project but cannot config with mumbai testnet.

At this time opensea not support alright?

**Comment by miloops** [comment]
any update on this? I'm having the same issue

**Comment by cre-mer** [comment]
Same issue here...

When trying this:
```
const seaport = new OpenSeaPort(provider, {
  networkName: "mumbai",
  apiKey: API_KEY
});
```

I get the following error:
`Type '"mumbai"' is not assignable to type 'Network | undefined'.`

**Comment by esteban-OpenSea** [comment]
Hello, are you still having issues with this?

**Comment by esteban-OpenSea** [comment]
Checking in again, are you still having this issue?
