### ISSUE TITLE
No way of knowing original creator of NFT

### ISSUE THREAD

**Issue by nawangwe** [ProjectOpenSea/opensea-js#114]
I noticed that you can only get the maker and owner, which both present the current owner of the NFT, is there any way of determining the original creator of the NFT?

**Comment by esteban-OpenSea** [comment]
If you review the documentation. You can access creator username. Closing this ticket since it's not an issue/bug on opensea-js.

<img width="178" alt="Screen Shot 2022-03-30 at 5 57 02 PM" src="https://user-images.githubusercontent.com/99999009/160937785-e0ffb538-bd44-4476-a329-e3b11c74e12c.png">
