### ISSUE TITLE
Can multi openseaSDK.createSellOrder() by using promise all?

### ISSUE THREAD

**Issue by Nganguyenth** [ProjectOpenSea/opensea-js#1157]
### Component

API

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [ ] Node (minimum v16)

### What version of opensea-js are you on?

1.2.1

### What function is the bug in?

createSellOrder

### Operating System

None

### Describe the bug

I want to create multi openseaSDK.createSellOrder() by using Promise.all() but get an error: "Duplicate order". Is anyone used to it? Help me, please...

I just awaited one by one but sometimes still get an error: "Duplicate order". i don't now how to control this :(((

**Comment by ryanio** [comment]
you want to create multiple of the same listing? why? is it 1155? you should be able to increase quantity instead

**Comment by Nganguyenth** [comment]
No. I have an array of NFTs that need to be listed. I used map() and used promise.all(). NFTs have different tokenId and also different prices. But when running the code, it still gives an error NFT
`await Promise.all(
        recordsExprired.map(async (record) => {
          await this.sumsubService.sellNFT({
            tokenAddress: record.contract + '',
            tokenId: record.tokenId + '',
            startAmount: record.price + '',
            expirationTime: this.expirationTime,
          });
        }),
      );`

**Comment by mayavolt** [comment]
Same problem, still haven't found a solution here #1089

**Comment by ryanio** [comment]
@Nganguyenth does it work without Promise.all? If you just submit the orders one at a time? Sounds like you are probably running the script multiple times. Duplicate order means we already have it in our database.

@mayavolt your code showed that you were submitting the order multiple times in the same fn:

```js
// Works fine
sellAsset(asset); 

/* But when I call the function in the timer instead, 
*  it doesn't work and throws an error
**/
setTimeout(() => {
   sellAsset(asset);
}, 3000);
```

the code above would submit the order, then submit it again 3s later

**Comment by mayavolt** [comment]
Dear @ryanio, you have misunderstood me. Of course, I don't call sellAsset(asset) in that sequence. I just gave two examples showing that everything works in one case (upper), but when I try to sell multiple nfts (lower), I get an error like the issues's author. I called these functions separately.

**Comment by Nganguyenth** [comment]
This seems like user error so I am closing for now
