### ISSUE TITLE
Unhandled Rejection Opensea error while making Buying Items

### ISSUE THREAD

**Issue by monetree** [ProjectOpenSea/opensea-js#117]
I’m trying to mark asset on OpenSea sold programmatically.  While I was able to successfully to get assets and check balance, I was unable to mark the asset sold using this function: https://projectopensea.github.io/opensea-js/#buying-items

Please see error screenshot here: https://i.stack.imgur.com/HG7bf.png

Below is the code snippet:

`    
     import * as Web3 from "web3";
     import { OpenSeaPort, Network } from "opensea-js";
    import { OrderSide } from "opensea-js/lib/types";

    // This example provider won't let you make transactions, only read-only calls:
    const provider = new Web3.providers.HttpProvider("https://mainnet.infura.io");
    const seaport = new OpenSeaPort(provider, {
    networkName: Network.Main,
    });
    export const OpenSeaAsset = async () =>
    await seaport.api.getAsset({
        tokenAddress: "0x...", // CryptoKitties
        tokenId: "30830", // Token ID
    });

    const asset = {
    tokenAddress: "0x...", // CryptoKitties
    tokenId: "30830", // Token ID
    };

    export const OpenSeaBalance = async () =>
    await seaport.getAssetBalance({
        accountAddress: "0x...", // string
        asset: asset, // Asset
    });

    export const offer = async () =>
    await seaport.createBuyOrder({
        asset: {
        tokenId: "30830",
        tokenAddress: "0x...",
        schemaName: "ERD721", // WyvernSchemaName. If omitted, defaults to 'ERC721'. Other options include 'ERC20' and 'ERC1155'
        },
        accountAddress: "0x...",
        // Value of the offer, in units of the payment token (or wrapped ETH if none is specified):
        startAmount: 1,
    });

    //   https://opensea.io/assets/0x2a46f2ffd99e19a89476e2f62270e0a35bbf0756/30830

    const order = async () => await seaport.api.getOrder({ side: OrderSide.Sell });
    const accountAddress = "0x1105c90c745339675EE8535e06663e5537C25798"; // The buyer's wallet address, also the taker
    export const transaction = async () =>
    await seaport.fulfillOrder({ order: order, accountAddress: accountAddress });`

**Comment by aliuchuang** [comment]
> did you find a fix?

I also met 😖

**Comment by wolfian** [comment]
Anyone found a solution to this issue? .-.

**Comment by emorling** [comment]
Anyone?

**Comment by esteban-OpenSea** [comment]
Hello, just wanted to check with everyone on this. Is this still an issue?

**Comment by esteban-OpenSea** [comment]
Checking in again, is this still an issue?

**Comment by bilalkhann16** [comment]
nope, no longer an issue.

**Comment by esteban-OpenSea** [comment]
Thanks for confirming, I will go ahead and close.
