### ISSUE TITLE
How well is this SDK maintained?

### ISSUE THREAD

**Issue by tre-dev** [ProjectOpenSea/opensea-js#118]
I'm grateful for the SDK, though I'm having the feeling that it's a bit too unmaintained.

There are several packages (i.e. wyvern-js, wyvern-schemas) that are outdated or bloated due to bad module practice (typescript & webpack as dependencies) https://github.com/ProjectOpenSea/wyvern-schemas/blob/master/package.json#L44

On top of that, I've noticed a few smaller bugs within opensea-js itself (i.e. there are some fields missing when converting from api-json to converted-json)

As a developer, who already integrated OpenSea within my project and is thinking about going even deeper, I need a well-maintained SDK, because when seeing open issues without comments about critical use-cases, it makes me wonder: will it even work when I spend time integrating it?

I hope this makes sense.

**Comment by 0xfoobar** [comment]
The lack of response is an answer in itself

**Comment by brandsimon** [comment]
Yes, sadly I have the same impression.

**Comment by ameshkin** [comment]
Yeah having the same issues myself.

**Comment by omnigolp** [comment]
Since they released a new version, they probably just ignore the issues?

**Comment by tre-dev** [comment]
There are still quite a lot of issues un-answered. Would be good if they could shift some of their $100M funding into making sure community developers are happy. Starts with transparent communication...

**Comment by eth0izzle** [comment]
Whilst I agree with you @tre-dev and I'm sure the team are on it but in the meantime you can help the fellow community out by fixing some of the bugs you mentioned and submitting PRs.

**Comment by Harrison97** [comment]
Not at all it seems. The readme is completely dead..

**Comment by tre-dev** [comment]
fyi, I'm moving away from using opensea-js in my frontend code. The size is just too much.

https://bundlephobia.com/package/opensea-js@1.2.1

I wish the OpenSea Team would spend some time & money into it. Maybe they're already working on it, but then the communication isn't really well done.

**Comment by esteban-OpenSea** [comment]
Hello everyone, we are working diligently to improve the SDK. Regarding the dependencies, I see they are updated. Any other bugs everyone else is encountering? 

For future reference, please provide specific details of any bugs/issues you might encounter. We appreciate the general feedback but in order to take actionable steps to fix these, details on the issues would be much appreciated!

**Comment by esteban-OpenSea** [comment]
Checkin in again, please make sure you are using the most recent version of Node and the SDK.

**Comment by JoshuaSchmidt-OpenSea** [comment]
Version 6 will remove all of the old dependencies. It will only have 3 total dependencies.
