### ISSUE TITLE
`refreshNftMetadata` does not appear to be a valid operation on this API.

### ISSUE THREAD

**Issue by dcsan** [ProjectOpenSea/opensea-js#1194]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

v2.0#9eqy6x159l3n6xcgf

### What function is the bug in?

refreshNftMetadata

### Operating System

macOS (Intel)

### Describe the bug

`refreshNftMetadata` does not appear to be a valid operation on this API.

does this SDK have anything to do with the SDK examples on OS website? 
eg trying to call this API:
https://docs.opensea.io/reference/refresh-nft-metadata

```
const openseaSdk = require("api")("@opensea/v2.0#9eqy6x159l3n6xcgf");
    const result = await openseaSdk.refreshNftMetadata(params);

>  Error: Sorry, `refreshNftMetadata` does not appear to be a valid operation on this API.
```

when i look in docs here https://projectopensea.github.io/opensea-js/
this API is indeed not listed.
so are there TWO OS SDKs?
seems that `require("api")("@opensea/v2.0#9eqy6x159l3n6xcgf");` just a way to (build and) [install an API](https://www.npmjs.com/package/api) given the openAPI definitions

and yet the endpoint doesn't function.

it seems it would be better to just make my own SDK to raw call if the rest endpoints are available. 
maybe someone can recommend an opensource project that is doing this?

**Comment by ryanio** [comment]
you aren't using the library correctly. please see the [quick start guide](https://github.com/ProjectOpenSea/opensea-js/blob/main/developerDocs/quick-start.md). you need to import and initialize the library properly (with an API key if using mainnets) and use [this function](https://github.com/ProjectOpenSea/opensea-js/blob/39da0468b40a7d751507affdeab442376765ea56/src/api/api.ts#L620):

```
  public async refreshNFTMetadata(
    chain: Chain,
    address: string,
    identifier: string,
  )
```
