### ISSUE TITLE
npm install --save opensea-js error

### ISSUE THREAD

**Issue by 233loser** [ProjectOpenSea/opensea-js#12]
code:
npm ERR! code 128
npm ERR! Command failed: E:\Git\Git\cmd\git.EXE clone -q git://github.com/ProjectOpenSea/wyvern-js.git D:\学习资料\编译 相关\_cacache\tmp\git-clone-a87fe90a --config core.longpaths=true
npm ERR! warning: templates not found in C:\Users\233loser\AppData\Local\Temp\pacote-git-template-tmp\git-clone-227d30e5
npm ERR! error: unable to create file src/wyvern-ethereum/test/aux.js: No such file or directory
npm ERR! Encountered 1 file(s) that should have been pointers, but weren't:
npm ERR!        src/wyvern-ethereum/utxo-merkle-proof/package.json
npm ERR! fatal: unable to checkout working tree
npm ERR! warning: Clone succeeded, but checkout failed.
npm ERR! You can inspect what was checked out with 'git status'
npm ERR! and retry the checkout with 'git checkout -f HEAD'
npm ERR!
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\学习资料\编译相关\_logs\2019-01-17T03_00_17_843Z-debug.log

**Comment by yasiriqbal776** [comment]
@233loser  does you solve this issue?

**Comment by alexanderatallah** [comment]
@yasiriqbal776 the aux.js file has been removed. Try installing the latest version
