### ISSUE TITLE
Error when maker != token owner: Transfer calldata doesn't match

### ISSUE THREAD

**Issue by aramalipoor** [ProjectOpenSea/opensea-js#120]
As I posted in https://github.com/wyvernprotocol/wyvern-v3/issues/55#issuecomment-869012087 when the order "maker" is different than token's "owner", I get this error from OpenSea APIs:
```json
{
    "success": false,
    "errors": [
        "[\"Transfer calldata doesn't match.\"]"
    ]
}
```
To avoid repeating I have put all details in the issue on wyvern-v3 repo. Would you be able to help me understand if that's something I'm doing wrong or it's a limitation on OpenSea backend APIs?

**Comment by aramalipoor** [comment]
@alexanderatallah can you point me to the right direction?

**Comment by jrm0695** [comment]
> @alexanderatallah can you point me to the right direction?

Did you find the solution ? I get the same error when using HDWalletProvider with new version of Opensea-js API

**Comment by esteban-OpenSea** [comment]
Just wanted to follow up on this. Are you still running in to this issue?
