### ISSUE TITLE
"getOrder" does not filter by hash

### ISSUE THREAD

**Issue by aecdanjundex** [ProjectOpenSea/opensea-js#123]
openSeaPort.api.getOrder({hash: ...}); does not filter by hash

**Comment by esteban-OpenSea** [comment]
Hey, just wanted to follow up on this. Are you still running into issues?

**Comment by pastet89** [comment]
I am having similar problem. I try:  `seaport.api.getOrder({ hash: orderHash })` and I get `Error: API Error 400: Invalid request: {"hash":["extra fields not permitted"]}`
@esteban-OpenSea How to get an order exactly by its hash?
