### ISSUE TITLE
EndAmount from english auction not working 

### ISSUE THREAD

**Issue by lehongvo** [ProjectOpenSea/opensea-js#1237]
### Component

API

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

6.1.11

### What function is the bug in?

createSellOrder

### Operating System

macOS (Apple Silicon)

### Describe the bug

"When setting up an English auction for NFTs with the parameters startAmount: 0.03, endPrice: 0.01, englishAuction: true, and an expirationTime of 10 minutes from the startTime, there's an issue. When the current time exceeds the expirationTime, the system immediately cancels the auction. However, our desired behavior is that when the current time is greater than the expirationTime, the NFT price should be set to the endAmount. How can we achieve this?"

Is this the correct interpretation of your question? If so, I can provide guidance on how to address this issue in your English auction system.

```order = await openseaSDK.createSellOrder({
                asset: {
                    tokenAddress: tokenAddress,
                    tokenId: tokenId,
                    tokenStandard: 'ERC721'
                },
                accountAddress,
                startAmount: "0.03",
                endPrice: "0.01",
                paymentTokenAddress: "0xa6fa4fb5f76172d178d61b04b0ecd319c5d1c0aa",
                englishAuction:true,
                expirationTime: Math.round(Date.now() / 1000 + 60 * 10) // Six munites
            })```

**Comment by ryanio** [comment]
That's not how English auctions work on OpenSea, there is no use of the end price. If you would like to achieve your goal you should programmatically list the NFT for a fixed price after the auction is over if there is no qualifying bid.

**Comment by lehongvo** [comment]
@ryanio thank you so much
