### ISSUE TITLE
when i use cancelOrder that have happend an  Cancel NFT Listing On OpenSea

### ISSUE THREAD

**Issue by jokereven** [ProjectOpenSea/opensea-js#1257]
### Component

API

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

    "opensea-js": "6.1.9",

### What function is the bug in?

cancelOrder

### Operating System

None

### Describe the bug

i have use cancel offers on my account, but when the code run 
![image](https://github.com/ProjectOpenSea/opensea-js/assets/73232691/a28df7c9-923d-4b73-8a63-10a9b4be4a36)
https://etherscan.io/tx/0x19cb49c3a0630c4f6d2be95db5d417a7ce24050c4d80ae5ace4d20b7ec1b7122 but i have no the nft, if my wallet have much eth it will all out, i think it's a big problem, the team should to resolve it, peace.

**Comment by ryanio** [comment]
what's the issue/problem? i don't understand

**Comment by jokereven** [comment]
> what's the issue/problem? i don't understand
when i use cancelOrder to cancel a offer order but  that cancel as a list order, you know i am saw.

**Comment by ryanio** [comment]
I still don't understand this issue, closing for now.
