### ISSUE TITLE
additional market for TON blockchains on the Opensea platform

### ISSUE THREAD

**Issue by axlywb** [ProjectOpenSea/opensea-js#1263]
### Component

Other (please describe)

### Describe the feature you would like

Can the Opensea team?
providing market space for TON Chain

we want artists to store their work on the TON blockchain. and can be marketed on opensea.

### Additional context

provides for the TON blockchain

**Comment by ryanio** [comment]
we don't take requests for new chains in this repository, sorry. you can reach out to opensea support with your request if you'd like.
