### ISSUE TITLE
createListing - serverError: Error: Client network socket disconnected before a secure TLS connection was established

### ISSUE THREAD

**Issue by MuhammadMinhaj** [ProjectOpenSea/opensea-js#1268]
### Component

API

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

6.1.12

### What function is the bug in?

createListing

### Operating System

Windows

### Describe the bug

Hello,

I've been working on integrating the OpenSea API with our internal server. Unfortunately, I have encountered an issue while attempting to list an asset on OpenSea via the API.

Sample of source code:

![Source](https://github.com/ProjectOpenSea/opensea-js/assets/64159776/7a6dbd6b-4843-4e4d-bff5-aed0aab605e1)

I have attached the error message and a snippet of my source code for your reference. It's worth noting that while this integration has sometimes worked, most of the time, it throws the following error:

![server-error](https://github.com/ProjectOpenSea/opensea-js/assets/64159776/0de7870b-70f3-4140-a344-a0e7910d0a0f)

I would greatly appreciate your assistance with resolving this issue. 

Thank you.

**Comment by ryanio** [comment]
this seems like a network error on your side if you only get it intermittently

**Comment by ryanio** [comment]
closing for now, if you can provide any steps to recreate the issue please let us know

**Comment by MuhammadMinhaj** [comment]
OK, I'll look into this further on our internal server and will get back to you once I have more information. Thank you.
