### ISSUE TITLE
Doing a api.get call on a deployed site give me ERROR:Cross-Origin Request Blocked: ... (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

### ISSUE THREAD

**Issue by M-Tech212** [ProjectOpenSea/opensea-js#129]
the full error 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.opensea.io/account/0x19de410480ff953852ed9171683b956febea25f2?. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Im deploying through firebase. It works fine on a local environment, but when deployed, I get this error. Ive tried setting the Access-Control-Allow-Origin header on both firebase and through web3 options, but I'm still getting the same error. after re-reading the documentation again today, it sounds like maybe it might be on your end, because I think the header allows for sites to do api calls on your data? Any other git issues relating to CORS seems to be on your side. Any help would be more than appreciated as I don't know much networking and I've been stuck for a few days now.

**Comment by M-Tech212** [comment]
api.getAssets works so I'm starting to assume that it is intentionally done this way. Would love to know the answer eventually

**Comment by HaoCherHong** [comment]
not really, those which doesn't have method also got CORS error.

**Comment by HaoCherHong** [comment]
@M-Tech212 hey I just figured out. Adding `/api/v1` in front of you path should fix the problem:
```
https://api.opensea.io/api/v1/account/0x19de410480ff953852ed9171683b956febea25f2?
```

**Comment by esteban-OpenSea** [comment]
@HaoCherHong is correct. Please refer to the api documentations. https://docs.opensea.io/reference/api-overview
