### ISSUE TITLE
How to we using openseaSDK to cancel all lising

### ISSUE THREAD

**Issue by lehongvo** [ProjectOpenSea/opensea-js#1291]
### Component

API

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

6.1.13

### What function is the bug in?

cancelOrder

### Operating System

macOS (Apple Silicon)

### Describe the bug

# We cancel only one lising is ok, working very good
```
//------------------------------------------------------------
const orders= await openseaSDK.api.getOrder({
            assetContractAddress: tokenAddress,
            tokenId,
            side: "ask",
        });
const transactionHash = await openseaSDK.cancelOrder({ orders , accountAddress});       
//------------------------------------------------------------
```
#-- But we cancel all  listing we see error, 
**Error canceling listing: TypeError: Cannot read properties of undefined (reading 'protocolAddress')**
Source code error:
```
//------------------------------------------------------------
const orders = await openseaSDK.api.getOrders({
            assetContractAddress: tokenAddress,
            tokenId,
            side: "ask",
        });
        const transactionHash = await openseaSDK.cancelOrder({ orders , accountAddress});
        console.log("Transaction hash cancel", transactionHash);
//------------------------------------------------------------   
```
@ryanio Can you help me, we feel very happy and appreciate you helping us, because it is very urgent with the project.

**Comment by ryanio** [comment]
You can't just pass `orders` to cancelOrder you have to follow the provided API. If you use Typescript you will get more helpful errors from the compiler instead of asking us every time (you've opened 10+ issues in our repositories in the last month with basic troubleshooting questions and not bugs). Also please read the source and docs above each method. You have to iterate over each order and call cancelOrder with the order. 

You can also use incrementCounter in seaport if you want to cancel all your orders cheaply with one transaction.

**Comment by lehongvo** [comment]
Hello @ryanio. Thank you very much!
**_"You can also use incrementCounter in seaport if you want to cancel all your orders cheaply with one transaction."_**
I don't understand very well. Can you clearly state what you mean?

**Comment by ryanio** [comment]
@lehongvo for more about incrementCounter:

https://github.com/ProjectOpenSea/seaport-js/blob/3e6b69c9fe1787c06d3b23349bb0b7ec66911ae2/src/seaport.ts#L585-L592

https://docs.opensea.io/reference/seaport-interface#incrementcounter

**Comment by lehongvo** [comment]
@ryanio thankyou so much

**Comment by lehongvo** [comment]
Hi @ryanio 
Is there any way to cancel all listings of an NFT?
Thanks

**Comment by ryanio** [comment]
No only by order or by whole account (counter)
