### ISSUE TITLE
Error On Building  Branch

### ISSUE THREAD

**Issue by yasiriqbal776** [ProjectOpenSea/opensea-js#13]
I am trying to build code from master branch with tag **0.5.0-rc5** But it is giving me error , I have attached image. 
![Screen Shot 2019-05-08 at 8 13 53 PM](https://user-images.githubusercontent.com/8578370/57386492-e5413100-71cd-11e9-876f-33e8a3c6ecc2.png)

**Comment by yasiriqbal776** [comment]
Typings was not install
i do run ```npm install typings -g
npm install --save-dev types/web3
```

**Comment by alexanderatallah** [comment]
I believe the `@types/web3` package is meant to be used with the web3-1.0 betas, which aren't stable yet. We're using 0.20.6, which works with `web3-typescript-typings`
