### ISSUE TITLE
Include asset 'animation_url' & 'animation_original_url' in assetFromJSON() function

### ISSUE THREAD

**Issue by MagRelo** [ProjectOpenSea/opensea-js#130]
Via the API, there are two fields that contain the asset's .mp4 content: 

{
   "animation_url": "https://storage.opensea.io/files/71ad3686a865f11a4734cd199744cb91.mp4",
   "animation_original_url": "https://storage.opensea.io/files/71ad3686a865f11a4734cd199744cb91.mp4",
} 

Eg, https://rinkeby-api.opensea.io/api/v1/assets?token_ids=73386105297704686597876021099790691394724770035420894709349741439120324952065

These fields are not being passed through `assetFromJSON()` function @ https://github.com/ProjectOpenSea/opensea-js/blob/84a4e811e020e98945749157075514047079bc72/lib/utils.js#L229

**Comment by esteban-OpenSea** [comment]
We are looking into this! Thanks.

**Comment by ryanio** [comment]
this is now in master branch, should be released in the next version
