### ISSUE TITLE
[bug] getAllListings parameter next cannot be set

### ISSUE THREAD

**Issue by iaping** [ProjectOpenSea/opensea-js#1301]
### Component

API

### Have you ensured that all of these are up to date?

- [ ] opensea-js
- [ ] Node (minimum v16)

### What version of opensea-js are you on?

6.1.14

### What function is the bug in?

getAllListings

### Operating System

None

### Describe the bug

Parameter next, the setting does not take effect, see getAllListings

**Comment by iaping** [comment]
![Uploading bug-opensea.png…]()

**Comment by iaping** [comment]
`
public async getAllListings(
    collectionSlug: string,
    limit?: number,
    next?: string,
  ): Promise<GetListingsResponse> {
    const response = await this.get<GetListingsResponse>(
      getAllListingsAPIPath(collectionSlug),
      serializeOrdersQueryOptions({
        limit,
        next,
      }),
    );
    return response;
  }
`

**Comment by iaping** [comment]
<img width="754" alt="bug-opensea" src="https://github.com/ProjectOpenSea/opensea-js/assets/15192203/7e3e04c9-4397-4d3a-90bf-17a9bb4d0af2">

serializeOrdersQueryOptions no next parameters

@ryanio

**Comment by ryanio** [comment]
thanks for the issue, fixing this now

**Comment by ryanio** [comment]
Released [v6.1.15](https://github.com/ProjectOpenSea/opensea-js/releases/tag/v6.1.15) with this fix, please let me know if it works for you, thanks again!

**Comment by iaping** [comment]
It works, thanks
