### ISSUE TITLE
createListing error: "An incorrect OpenSea fee has been provided. Expecting 250 basis points, but received 249."

### ISSUE THREAD

**Issue by Ghijo1** [ProjectOpenSea/opensea-js#1318]
### Component

API

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

6.1.14

### What function is the bug in?

createListing

### Operating System

Windows

### Describe the bug

Hello, i get the following error when i try to list an NFT whit createListing:

'{"errors":["An incorrect OpenSea fee has been provided. Expecting 250 basis points, but received 249."]}'

How can i solve it?
Thank you!

**Comment by ryanio** [comment]
you are probably using a listing amount that is not rounding properly, what price are you trying to list for? would recommend using a more round number with less decimals (e.g. .15 eth instead of .14999999 eth)

**Comment by Ghijo1** [comment]
> you are probably using a listing amount that is not rounding properly, what price are you trying to list for? would recommend using a more round number with less decimals (e.g. .15 eth instead of .14999999 eth)

Yep, I solved typing price.toFixed(4) 
Thank you!! :)
