### ISSUE TITLE
Orders not going through: MaxListeners exceeded warning

### ISSUE THREAD

**Issue by msieg** [ProjectOpenSea/opensea-js#132]
Here is the warning I get. My code used to work when looping and placing orders with async + await. Now no orders go through and this happens:

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unlock listeners added. Use emitter.setMaxListeners() to increase limit

Can anyone help? Thanks.

**Comment by esteban-OpenSea** [comment]
Hello, just wanted to follow up on this. Are you still running into this issue?
