### ISSUE TITLE
fulFillOrder without own node

### ISSUE THREAD

**Issue by maraboo-afk** [ProjectOpenSea/opensea-js#133]
Hey mates. Is there any way to send a **fulFillOrder** transaction without having own node? Infura doesn't work because it can't store private key for signing a transaction.

**Comment by cj-l** [comment]
Also facing this. It looks like [you can have local private private keys when dealing with hosted nodes](https://web3py.readthedocs.io/en/stable/web3.eth.account.html#sign-a-transaction), however I'm not sure how this integrates with opensea-js

**Comment by maraboo-afk** [comment]
@cj-l eventually I deployed a node

**Comment by maraboo-afk** [comment]
@cj-l eventually I deployed a node
