### ISSUE TITLE
createListing error: "TypeError: signer.signTypedData is not a function at Seaport.signOrder"

### ISSUE THREAD

**Issue by hungnm92** [ProjectOpenSea/opensea-js#1347]
### Component

API

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

^7.0.6

### What function is the bug in?

createListing

### Operating System

Linux

### Describe the bug

Hello there,
i get the following error when i try to list an NFT using createListing. i use nodejs version 16.20.2, ethers  ver ^5.7.2
Here is my code:

> const { ethers } = require('ethers');
  const { OpenSeaSDK, Chain, TokenStandard }  = require("opensea-js")
  const provider = new ethers.providers.JsonRpcProvider('https://polygon-mainnet.g.alchemy.com/v2/${API_KEY_POLYGON}');
  const privateKey = PRIVATE_KEY
  const wallet = new ethers.Wallet(privateKey, provider);
  const openseaSDK = new OpenSeaSDK(wallet, {
      chain: Chain.Polygon,
      apiKey: OPENSEA_API_KEY,
  });
const accountAddress = wallet.address;
const paymentTokenAddress = "0x0000000000000000000000000000000000000000"
const checkBalance = async function (NFTId) {
    const asset = {
        tokenAddress: TOKEN_CONTRACT,
        tokenId: NFTId.toString(),
        tokenStandard: TokenStandard.ERC721,
    };
    return await openseaSDK.getBalance({
        accountAddress,
        asset,
    });
}
const createListing = async function (NFTId) {
    // Expire this auction three days from now.
    // Note that we convert from the JavaScript timestamp (milliseconds) to seconds:
    const expirationTime = Math.round(Date.now() / 1000 + 180 * 60 * 24);
    return await openseaSDK.createListing({
        asset: {
            tokenId: NFTId.toString(),
            tokenAddress: TOKEN_CONTRACT,
            tokenStandard: TokenStandard.ERC721
        },
        accountAddress: accountAddress,
        startAmount: 1,
        expirationTime: expirationTime,
        paymentTokenAddress: paymentTokenAddress
    });
}
async function run() {
    const NFTIds = [1,2]
    for (const NFTId of NFTIds) {
        let balance = await checkBalance(catId)
        balance = ethers.BigNumber.from(balance).toNumber()
        if (balance > 0) {
            try {
                const listing = await createListing(NFTId)
            } catch (error) {
                console.log('listing error', error)
            }
        }
        break
    }
}
run()

After run file, i got issue

> listing error TypeError: signer.signTypedData is not a function
    at Seaport.signOrder (/node_modules/@opensea/seaport-js/lib/seaport.js:372:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.createOrder (/node_modules/@opensea/seaport-js/lib/seaport.js:170:35)
    at async OpenSeaSDK.createListing (/node_modules/opensea-js/lib/sdk.js:276:23)
    at async createListing (/opensea.js:65:12)
    at async run (/opensea.js:61:33)

How can i solve it? @ryanio Can you help me?
Thank you!

**Comment by ryanio** [comment]
You have to use ethers v6

**Comment by hungnm92** [comment]
wow, i forget to check that, it works perfectly! Thank you so much.
