### ISSUE TITLE
Support limit and next parameters in GetBestListings

### ISSUE THREAD

**Issue by as-iotex** [ProjectOpenSea/opensea-js#1379]
### Component

API

### Describe the feature you would like

Currently the GetBestListings method does not support the limit and next parameters https://docs.opensea.io/reference/get_best_listings_on_collection_v2

I think this would be pretty easy to add. I am happy to try, but I am not a JS developer. If someone can point me to a guide on what needs to change in the library and how I can test my changes I would be happy to do it.

Otherwise, would someone be able to kindly add support for this?

```js
/**
     * Gets the best listing for a given token.
     * @param collectionSlug The slug of the collection.
     * @param tokenId The token identifier.
     * @returns The {@link GetBestListingResponse} returned by the API.
     */
    async getBestListing(collectionSlug, tokenId) {
        const response = await this.get((0, apiPaths_1.getBestListingAPIPath)(collectionSlug, tokenId));
        return response;
    }
```

Thanks very much

**Comment by ryanio** [comment]
Hey @as-iotex, thanks that would be great if you want to open a PR to add! You just have to follow similar to:

https://github.com/ProjectOpenSea/opensea-js/blob/fa026db57faa2ce4c9d49f8fa8fd1c9e0703aeaa/src/api/api.ts#L208-L228

**Comment by as-iotex** [comment]
@ryanio sure, I will try. But please bear with me, I am not an expert in JS 
I just found this issue https://github.com/ProjectOpenSea/opensea-js/issues/1381 while following the contributing guide

**Comment by as-iotex** [comment]
Unfortunately I tried the endpoint and it does not return the "next" field as indicated in the response body documentation. Even if there actually are more listings
![image](https://github.com/ProjectOpenSea/opensea-js/assets/82106612/b7bcd585-fc36-4c0f-80d0-d76612825e1e)

The actual response is just the listings array. Eg:
![image](https://github.com/ProjectOpenSea/opensea-js/assets/82106612/83f8486a-f6a5-460f-abce-5c4c4a474c79)

Is there a support channel for the actual API?

**Comment by ryanio** [comment]
thanks for flagging, this is something i can fix, will let you know once fixed

**Comment by ryanio** [comment]
@as-iotex thanks for your patience, ok this should be fixed now! just checked and the api response properly includes the "next" cursor now

**Comment by ryanio** [comment]
This is now added in [v7.0.9](https://github.com/ProjectOpenSea/opensea-js/releases/tag/v7.0.9), thank you!
