### ISSUE TITLE
npm build error TS2742: The inferred type of 'getPostCollectionOfferPayload' cannot be named without a reference to 'opensea-js/node_modules/@opensea/seaport-js/lib/types'

### ISSUE THREAD

**Issue by as-iotex** [ProjectOpenSea/opensea-js#1381]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

master

### Operating System

Linux

### Describe the bug

Followed the steps on https://github.com/ProjectOpenSea/opensea-js/blob/main/developerDocs/contributing.md but I am getting an error

```bash
npm install
npm install -g typescript

tsc --version
Version 5.3.3

node --version
v18.18.0

npm run build
```

Produces the following error:

```bash
npm install

> opensea-js@7.0.8 postinstall
> husky install || exit 0

husky - Git hooks installed

> opensea-js@7.0.8 prepare
> npm run build


> opensea-js@7.0.8 build
> npm run abi-type-gen && tsc -p tsconfig.build.json


> opensea-js@7.0.8 abi-type-gen
> typechain --target=ethers-v6 src/abi/*.json --out-dir=src/typechain/contracts

Successfully generated 9 typings!
src/orders/utils.ts:14:14 - error TS2742: The inferred type of 'getPostCollectionOfferPayload' cannot be named without a reference to 'opensea-js/node_modules/@opensea/seaport-js/lib/types'. This is likely not portable. A type annotation is necessary.

14 export const getPostCollectionOfferPayload = (
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/orders/utils.ts:14

npm ERR! code 1
npm ERR! path .../node_modules/opensea-js
npm ERR! command failed
npm ERR! command sh -c npm run build

```

**Comment by ryanio** [comment]
What happens if you set `"declaration": false` in tsconfig

**Comment by as-iotex** [comment]
> Does it help if you set `"declaration": false` in tsconfig.json

That fixed it. Do you want me to PR the change to the json?

**Comment by ryanio** [comment]
no let's keep it as-is, if other devs have issues I'll think about changing it but it's not happening on my local and don't want to change the downstream behavior of the lib
