### ISSUE TITLE
Recent Changes to API Rate Limit?

### ISSUE THREAD

**Issue by moleary45git** [ProjectOpenSea/opensea-js#139]
I've noticed that over the last day or so that I'm being throttled when using the SDK to call OpenSea API, even when increasing the time between API calls to 3 seconds. Even when waiting 3 seconds between API calls, roughly half of my API calls are throttled. I hadn't previously ever had an issue with API throttling and wonder if recent changes have been made that allow fewer requests per second. I do not have an API key, but have never had one.

This is the error that I've receiving from the API:
API Error 429: Message: {"detail":"Request was throttled."}

Any help would be appreciated! Thanks!

**Comment by esteban-OpenSea** [comment]
Please follow https://github.com/ProjectOpenSea/opensea-js/issues/86 issue for the latest update on the 429 issues. Closing this out so since it's a duplicate case.

Also, the rate limit is 4/sec
