### ISSUE TITLE
Transfer method doesn't return a transaction hash

### ISSUE THREAD

**Issue by oggy95** [ProjectOpenSea/opensea-js#1396]
Hello. I'm trying to implement opensea-js to my project and notice that method transfer, which I want to use to transfer NFT's between addresses, return nothing, but in sdk there is a transaction hash which is watched for success/error blockchain status.

https://github.com/ProjectOpenSea/opensea-js/blob/cc43e084046f65b9d2970eef888525996b361340/src/sdk.ts#L1037

Is there a possibility to change this method to return transaction hash?
Or I should use another method for transfering NFT between addresses?

**Comment by ryanio** [comment]
In _confirmTransaction the sdk will emit transaction created and confirmed events which you can listen to, which includes the tx hash

**Comment by oggy95** [comment]
Yeah, I rewrite application to listen events from the SDK.
Sorry for bothering :)
