### ISSUE TITLE
How would I use the seaport object on the backend?

### ISSUE THREAD

**Issue by nickjuntilla** [ProjectOpenSea/opensea-js#14]
This SDK appears to be for in in-browser app. What could I do to translate these methods to the backend?

**Comment by nickjuntilla** [comment]
I found this: https://github.com/ProjectOpenSea/opensea-creatures/blob/master/scripts/sell.js but does that mean I would have to re-initialize the provider each time I wanted to call methods using a different mnemonic or private key?

**Comment by alexanderatallah** [comment]
You can use the seaport on the backend - it works with Node.js! Version 8.11.x works best, as specified in the README. And yes you would have to re-initialize the provider when you're using new private keys

**Comment by nickjuntilla** [comment]
Thank you!
