### ISSUE TITLE
Silent failure on createSellOrder?

### ISSUE THREAD

**Issue by Dobermensch** [ProjectOpenSea/opensea-js#140]
Cross posted here:

https://stackoverflow.com/questions/68817488/opensea-js-sdk-createsellorder-method-doesnt-seem-to-work-or-silent-failure

**Comment by baguettex** [comment]
same issue

**Comment by ccostel** [comment]
I'm getting the same issue.

**Comment by dhavalsoni2001** [comment]
I am facing the same issue.

**Comment by dwarsz** [comment]
I am also facing this issue, when calling any OpenSea method while I can successfully make opensea API calls.

**Comment by hugotkk** [comment]
same. I am testing on rinkeby testnet. I can see the proxy register transaction in proxy address.

**Comment by hugotkk** [comment]
Actually I started with [opensea-creatures](https://github.com/ProjectOpenSea/opensea-creatures.git) demo for my work. 
It works if I use the demo code.
I am checking if it is related to the node / jdk version.
node 12, jdk version 1.2.0 <- not work
node 14, jdk version 1.1.5 <- ok

**Comment by chahakshah111** [comment]
@hugotkk I'm still getting the same error with the version you have specified.

**Comment by fammobiletech** [comment]
having the same issue

**Comment by alexanderatallah** [comment]
This type of issue tends to be fixed by removing all your `node_modules` and reinstalling using `yarn` instead of `npm`

**Comment by kevinjanada** [comment]
Having the same issue as well

**Comment by cre-mer** [comment]
Same issue here

**Comment by Toeplitz** [comment]
After the upgrade to version 2.0.0 createSellOrder stopped working here as well. Just hangs silently. Not sure how to extract more information on this.

**Comment by nachoverdon** [comment]
Having the same issue.

I'm using opeansea-js version 3.0.2
Node 16.14.2
npm 8.5.0
TypeScript 3.5.2

I'm using it in as a node script like this:

```ts
private getSeaport(): OpenSeaPort {
    const walletSubprovider = config.wallet.mnemonic ? 
      new MnemonicWalletSubprovider({
        mnemonic: config.wallet.mnemonic,
        baseDerivationPath: `44'/60'/0'/0`,
      })
      : new PrivateKeyWalletSubprovider(config.wallet.privateKey!);

    const rpcSubprovider = new RPCSubprovider(
      `https://eth-mainnet.alchemyapi.io/v2/${process.env.ALCHEMY_API_KEY}`
    );

    const providerEngine = new Web3ProviderEngine();

    providerEngine.addProvider(walletSubprovider);
    providerEngine.addProvider(rpcSubprovider);
    providerEngine.start();

    return new OpenSeaPort(providerEngine, {
      networkName: Network.Main,
      apiKey: process.env.OPENSEA_API_KEY,
    }, (arg => console.log("arg is", arg)));
  }
```

I tried using yarn (1.22.4) instead, as sugested above, and got the same problem.

I tried to catch some unhandled exception using the following:

```
process.on('uncaughtException', function (err) {
    console.error(err);
});

process.on('unhandledRejection', (reason, promise) => {
    console.log(`Unhandled Rejection at: ${promise}, reason: ${reason}\n`);
});

process.on('exit', function (code) {
    console.log("Node exiting with code " + code);
});
```

The `exit` command is getting called with code `0` for some unknown reason.

**Comment by esteban-OpenSea** [comment]
Are you still running into this issue? Even after doing this:

_This type of issue tends to be fixed by removing all your node_modules and reinstalling using yarn instead of npm_

**Comment by felipeasf** [comment]
I've been facing the same issue, I also tried a lot of different workarounds and nothing so far...
