### ISSUE TITLE
Relax testnet API throttling thresholds

### ISSUE THREAD

**Issue by rigwild** [ProjectOpenSea/opensea-js#1408]
### Component

API

### Have you ensured that all of these are up to date?

- [x] opensea-js
- [x] Node (minimum v16)

### What version of opensea-js are you on?

-

### What function is the bug in?

-

### Operating System

None

### Describe the bug

Hi,

Since a fews weeks, I noticed that my app in testnet keeps breaking due to HTTP 429 rate limit errors.
Could you relax a bit the throttling thresholds? It seems I am not alone having this issue, see https://github.com/ProjectOpenSea/opensea-js/discussions/1402 https://github.com/ProjectOpenSea/opensea-js/discussions/1377

I don't know if you changed the rate limit policy, but it seems too aggressive, considering that to only render a very simple page we might fetch the content of an NFT + its OpenSea offers, leading to a 429.

Thanks!

**Comment by UPavankumar** [comment]
You might be encountering HTTP 429 errors due to rate limits imposed by OpenSea API. This could be caused by aggressive throttling or outdated opensea-js. To address this, check the opensea-js version and implement your own rate limiting logic in your application.

**Comment by rigwild** [comment]
> You might be encountering HTTP 429 errors due to rate limits imposed by OpenSea API. This could be caused by aggressive throttling or outdated opensea-js. To address this, check the opensea-js version and implement your own rate limiting logic in your application.

Ok chatgpt


Waiting for a real answer from OpenSea team

**Comment by ryanio** [comment]
At what rate are you sending requests?

**Comment by rigwild** [comment]
Very slow rate on our app, the issue is that the rate limit is on instant TPS

Example: I do 2 requests to load the page, then 0 requests until the user performs some action -> I am rate limited because I sent 2 reqs/s, even though it's super low traffic

I would suggest that you change the throttling strategy to be like 60 reqs/min instead of 1 reqs/s, so that you can still project your API but allow bursts of requests

**Comment by iesrbt** [comment]
Hi,
just to confirm, my app is doing 4 or 5 SDK calls a day tops, (several hours in between) and still get:

minter  |   info: {
minter  |     requestUrl: 'https://testnets-api.opensea.io/api/v2/collections/xxxxxxxxx?',
minter  |     responseBody: '{"detail":"Request was throttled.","id":"1KQIYV"}',
minter  |     responseStatus: '599 CLIENT ESCALATED SERVER ERROR (429 Too Many Requests; exceeded maximum retry limit)'
minter  |   },
minter  |   shortMessage: 'exceeded maximum retry limit'

SDK version: 7.0.9

Thanks for your support.

**Comment by ryanio** [comment]
Thanks for reporting, I was able to recreate. It looks like we can configure throttle limits in ethers, so I will work on adding that to fix this issue.

**Comment by ryanio** [comment]
have released this in [v7.1.0](https://github.com/ProjectOpenSea/opensea-js/releases/tag/v7.1.0), please give it a try and let me know if it fixes the issue.

**Comment by rigwild** [comment]
Thanks! Shouldn't the fix be made on the API side instead of inside the client?

The rate limiting is done by the server. Consumers of the OpenSea API doing direct HTTP API calls will trigger this limit anyway.

You can reproduce easily:

1. Go to https://testnets.opensea.io/collection/coolcatssepolia
2. Open devtools and paste the following script to load the details of an NFT and its pending offers
3. Notice the 429 rate limit

```ts
const nftModelDetailed = await fetch(`https://testnets-api.opensea.io/api/v2/chain/sepolia/contract/0x5E28ab57D09C589ff5C7a2970d911178E97Eab81/nfts/50/`)
const nftBestListing = await fetch(`https://testnets-api.opensea.io/api/v2//listings/collection/coolcatssepolia/nfts/50/best`)

// Or even more realistic, in parallel
const [nftModelDetailed, nftBestListing] = await Promise.all([
	fetch(`https://testnets-api.opensea.io/api/v2/chain/sepolia/contract/0x5E28ab57D09C589ff5C7a2970d911178E97Eab81/nfts/50/`),
	fetch(`https://testnets-api.opensea.io/api/v2//listings/collection/coolcatssepolia/nfts/50/best`),
])
```

**Comment by ryanio** [comment]
Sure I see what you mean, I'll look into fixing it, thanks

**Comment by ryanio** [comment]
@rigwild thanks again for the report. we made some infra changes on the API side so your above code example should work now, let me know?

**Comment by rigwild** [comment]
Still the same issue

```sh
curl https://testnets-api.opensea.io/api/v2/chain/sepolia/contract/0x5E28ab57D09C589ff5C7a2970d911178E97Eab81/nfts/50/
curl https://testnets-api.opensea.io/api/v2//listings/collection/coolcatssepolia/nfts/50/best
```

**Comment by ryanio** [comment]
@rigwild sorry about that, missed your message, looks like we applied it to mainnets only and not testnets, it should be fixed for testnets now.

**Comment by rigwild** [comment]
I can confirm it works properly now, thanks!
