### ISSUE TITLE
How can I get the current price using Opensea.js

### ISSUE THREAD

**Issue by QibingLee** [ProjectOpenSea/opensea-js#141]
Hi, everyone. I am wondering how can I get the current price for a given asset, e.g., the price provided by its owner or the latest order price. It is much helpful to us.

**Comment by esteban-OpenSea** [comment]
I recommend looking over the documentation: https://github.com/ProjectOpenSea/opensea-js#fetching-orders

The API docs also show an endpoint for stats: https://docs.opensea.io/reference/retrieving-collection-stats

I hope this helps, feel free to reopen if you have any other questions
