### ISSUE TITLE
Support acquiring the link for MoonPay payments.

### ISSUE THREAD

**Issue by tra4less** [ProjectOpenSea/opensea-js#1431]
### Component

API

### Describe the feature you would like

I want to get payment link(moonpay)

<img width="355" alt="image" src="https://github.com/ProjectOpenSea/opensea-js/assets/18096911/63da697e-6b0d-4f72-98d0-af0b45f2d39a">

**Comment by ryanio** [comment]
thanks for the request, we have never surfaced moonpay pay links via the API but it is an interesting idea. we would have to reach out to moonpay to see if this is something they would support.
