### ISSUE TITLE
How can I buy the nft listings directly without making offers.

### ISSUE THREAD

**Issue by bilalkhann16** [ProjectOpenSea/opensea-js#145]
I'm trying to write a script that can purchase the specific nft listings. The documentation only covers the making offer functionality but I want to buy the listings instantly without making offers. How can I achieve this using the SDK? Thank you.

**Comment by jonathanjm** [comment]
Hi @bilalkhann16, where you able to solve this? I'm trying to figure out the same.

**Comment by bilalkhann16** [comment]
@jonathanjm Yes, you can buy the specific nft listings. learn more about buying the nft listings [https://github.com/ProjectOpenSea/opensea-js#buying-items](here)

**Comment by jonathanjm** [comment]
thanks!
