### ISSUE TITLE
Error: You have provided fees that we cannot attribute to OpenSea or the collection, in klaytn chain

### ISSUE THREAD

**Issue by suropark** [ProjectOpenSea/opensea-js#1454]
### Discussed in https://github.com/ProjectOpenSea/opensea-js/discussions/1409

<div type='discussions-op-text'>

<sup>Originally posted by **suropark** March 10, 2024</sup>
hi, is there anyone knows how to handle this error in klaytn chain

```
"You have provided fees that we cannot attribute to OpenSea or the collection"
```

chain  : klaytn 

```
      const offer = await this.sdk.createOffer({
        asset: {
          tokenId,
          tokenAddress,
        },
        accountAddress: accountAddress,
        startAmount: price,
        expirationTime: (Math.round(Date.now() / 1000) + duration).toString(),
      });

```

all parameters are filled correctly

</div>

**Comment by ryanio** [comment]
what tokenId and tokenAddress are you using? will try to recreate
