### ISSUE TITLE
Item in collection, but in private folder/ hidden. How to unhide the item ?

### ISSUE THREAD

**Issue by kissapig** [ProjectOpenSea/opensea-js#148]
I see no way to unhide an item that I previously made hidden (private folder).

**Comment by esteban-OpenSea** [comment]
Check this out:

https://support.opensea.io/hc/en-us/articles/4402034895635-How-do-I-hide-items-from-my-OpenSea-profile-#:~:text=How%20to%20unhide%20items%20on%20OpenSea
