### ISSUE TITLE
Can the first item in the array returned by eth_accounts be used for the currently selected address?

### ISSUE THREAD

**Issue by circle-hotaru** [ProjectOpenSea/opensea-js#149]
I'm using imToken to connect OpenSea. There are 4 accounts in it and will return all of them in an array by `eth_accounts`. The first account is imToken currently account. But it looks like OpenSea always uses the last account. This makes it impossible for us to switch to the account we want.

**Comment by esteban-OpenSea** [comment]
Are you still having issues with this? Please use the updated SDK and Node version

**Comment by circle-hotaru** [comment]
Thank you very much, there are no such problems anymore.
