### ISSUE TITLE
Polygon/matic support in this library

### ISSUE THREAD

**Issue by n00b21337** [ProjectOpenSea/opensea-js#150]
I am trying to use this library with Polygon and Matic but I see it is not really supported. Would at least like to be able to use 
**createSellOrder** method as adding big projects now is pretty hard manually.  Any chance we get some basic support?

**Comment by shawwwwwwww** [comment]
+1

We are deciding whether to use opensea-js and an embedded marketplace over trying to roll our own code, but since it's a game with a high drop rate, we need Polygon mainnet support.

If this is a near-term thing, can we get an ETA? Would be helpful to plan around. Is there any way we could contribute to the open source to add Polygon support to Opensea-js, would that PR be accepted?

**Comment by andychan1998** [comment]
I also need this library to support Polygon too. I would really appreciate it if someone from OpenSea can give us some guidance on the plan on this issue.

**Comment by adriadrop** [comment]
They said they will do it but no ETA, so probably we cant hold our breath for it and do it manually for now :(

**Comment by bx67212** [comment]
+1

**Comment by lly835** [comment]
> +1
> 
> We are deciding whether to use opensea-js and an embedded marketplace over trying to roll our own code, but since it's a game with a high drop rate, we need Polygon mainnet support.
> 
> If this is a near-term thing, can we get an ETA? Would be helpful to plan around. Is there any way we could contribute to the open source to add Polygon support to Opensea-js, would that PR be accepted?

Looking forward to your pr, I am willing to test it for you.

**Comment by rae89** [comment]
We Want Matic!

**Comment by IPIvliev** [comment]
+1 for Polygon

**Comment by fizyliftingdrnks** [comment]
+1

Also, update your SDK to something that isn't 5 years old.

**Comment by inso-** [comment]
+1
Is the API V1 already support it polygon/mumbai?
If so let me know the baseUrl please then I may be able to make a pull request.

**Comment by eskimm** [comment]
+1

**Comment by apoorvsingal** [comment]
+1

**Comment by eskimm** [comment]
Anyone have time estimates for Polygon support in this library?

**Comment by Lcressot** [comment]
It seems that some hue Polygon collections have found a way, for instance the ZED RUN collection. I really wonder how they do it

**Comment by willemaster** [comment]
+1

**Comment by rae89** [comment]
> +1 Is the API V1 already support it polygon/mumbai? If so let me know the baseUrl please then I may be able to make a pull request.

It does not look like the assets endpoint does not work for polygon contracts: the responses I get are `{
    "assets": []
}`

**Comment by Lcressot** [comment]
@rae89
Hi ! I would be very interseted in knowing more how you acheive to get the response ```{ "assets": [] ``` for a polygon contract ! I can't even get that. Thanks !

**Comment by zjpetersen** [comment]
Anyone figure out a way to get do bulk listings for Polygon assets?  Manually listing thousands of assets one at a time is going to take forever.

**Comment by fizyliftingdrnks** [comment]
Sadly no update yet.  I had to manually list 1500 items because there is no sale listing support on Polygon.

**Comment by Lcressot** [comment]
Opensea are paying to jost their nft data so I beleive they have no interest in letting you upload a big bunch if cheap Poly NFTs and that's why they don't provide batch create nor batch list methods ..

**Comment by LokartNFT** [comment]
I have found a way to automate item creation and listing on Opensea. Not straightforward, needs programming work, I can do it for you please contact me at https://twitter.com/PiXLPunks

**Comment by Lcressot** [comment]
@zjpetersen Yes my argument only stands for the item creation you are right

**Comment by Turtus** [comment]
+1

**Comment by Pouyar69** [comment]
+1

**Comment by cyberart2021** [comment]
+1

**Comment by velsa** [comment]
+100

**Comment by BjThAccount** [comment]
+101

**Comment by MyHeTai** [comment]
+101

**Comment by cerealkill** [comment]
+102 We need polygon and mumbai listing enabled ASAP!

**Comment by esteban-OpenSea** [comment]
We hear you! And it's coming soon, check this out: https://github.com/ProjectOpenSea/opensea-js/issues/168

**Comment by Turtus** [comment]
soon - having scanners db everything for polygon - but more than 6 monthes to create polygon. api point.... and "soon" - sorry but better opensource api and we will do it by ourselves

**Comment by bin0316** [comment]
so how can I use this SDK for Polygon network?
How can I set the networkName when I create seaport?
const seaport = new OpenSeaPort(provider, {
  networkName: Network.Main,
  apiKey: YOUR_API_KEY
})
It is for Ethereum mainnet.

**Comment by stpoa** [comment]
Any updates?

**Comment by onurozansahin** [comment]
+1 for Polygon!

**Comment by KlasikNormalBoy** [comment]
+1 for Polygon. It is outrages that Mumbai is supported on the page and in graphql but not here.
This will make many many a project consider going for another marketplace.

**Comment by MuhammadMinhaj** [comment]
Are there any updates about the Polygon API?

**Comment by ryanio** [comment]
This is coming soon!

**Comment by ryanio** [comment]
The new endpoints have landed! https://docs.opensea.io/changelog/new-release-multichain-nft-endpoints We will be adding to opensea-js shortly.

**Comment by munimdev** [comment]
> The new endpoints have landed! https://docs.opensea.io/changelog/new-release-multichain-nft-endpoints We will be adding to opensea-js shortly.

Will this allow to create offers and create buy/sell orders just like Ethereum?

**Comment by ryanio** [comment]
Support added now with the latest release https://github.com/ProjectOpenSea/opensea-js/releases/tag/v6.1.1
