### ISSUE TITLE
Simple test of getAssets returns nothing

### ISSUE THREAD

**Issue by imkane** [ProjectOpenSea/opensea-js#151]
I apologize if I'm doing something really dumb, but I thought this would output 20 NFTs from this particular collection, just like in the demo here: https://docs.opensea.io/reference/getting-assets

```
var Web3 = require("web3");
var { OpenSeaPort, Network } = require("opensea-js");

const asset_contract_address = "0xbe6e3669464e7db1e1528212f0bff5039461cb82";
console.log("asset_contract_address = " + asset_contract_address);

// This example provider won't let you make transactions, only read-only calls:
const provider = new Web3.providers.HttpProvider("https://mainnet.infura.io");

const seaport = new OpenSeaPort(provider, {
  networkName: Network.Main,
});

// Get assets
const OpenSeaAssets = async () =>
  await seaport.api.getAssets({
    asset_contract_address: asset_contract_address,
    order_direction: "desc",
    offset: 0,
    limit: 20,
  });

console.log(JSON.stringify(OpenSeaAssets));
```

However, this is all I see in my terminal:

```
$ node getAssets.js 
asset_contract_address = 0xbe6e3669464e7db1e1528212f0bff5039461cb82
undefined
```

Is there no way to at least get some verbose debug output from this API?

Thanks in advance!

**Comment by jonathanjm** [comment]
You're assigning a function to OpenSeaAssets. Try this instead:

`const OpenSeaAssets = await seaport.api.getAssets({
    asset_contract_address: asset_contract_address,
    order_direction: "desc",
    offset: 0,
    limit: 20,
  });`
console.log(OpenSeaAssets);

**Comment by imkane** [comment]
@jonathanjm thank you! That helped :smile:
