### ISSUE TITLE
TypeError: hash mismatch

### ISSUE THREAD

**Issue by parthbisht** [ProjectOpenSea/opensea-js#1512]
### Component

Utils

### Have you ensured that all of these are up to date?

- [X] opensea-js
- [X] Node (minimum v16)

### What version of opensea-js are you on?

7.1.10

### What function is the bug in?

fulfillOrder

### Operating System

macOS (Apple Silicon)

### Describe the bug

getting this error on this function  'fulfillOrder' 
 TypeError: hash mismatch (argument="tx", value={ "_type": "TransactionReceipt", "accessList": null, "blockHash": null, "blockNumber": null, "chainId": null, "data": "0xfb0f3ee10000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007efb54856ed30000000000000000000000000000ba8c0d1d9ed1de4be0a25433a7198ce3699147570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000251be3a17af4892035c37ebf5890f4a4d889dcad7c6f80b5a5295ef26c43e5c1502d78144f03becefe1e51651db8bc9036a27c3400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006683d53a0000000000000000000000000000000000000000000000000000000066acb3ba0000000000000000000000000000000000000000000000000000000000000000360c6ebe0000000000000000000000000000000000000000cb4ba69085a398ea0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f00000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002e0000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000003782dace9d900000000000000000000000000000000a26b00c1f0df003000390027140000faa7190000000000000000000000000000000000000000000000000853a0d2313c0000000000000000000000000000732134d7f99b90c704d736b360db45425073380f00000000000000000000000000000000000000000000000000000000000000404a8af3e154dfaf783eb86122889c43ebd13bfe832737a8372f17c02b3b737a6340a64c15ec53036989efac95b5a22c548d3399289bd45d972c77864e1da903e9", "from": "0xDb34bAda3C49d2f9624e60EA3dc3efC250548c16", "gasLimit": "213403", "gasPrice": "30000000044", "hash": "0x299396d3758fd4b508c312a7d733e266205f53391aaac6cf2efa67203c149e2f", "index": null, "maxFeePerGas": "30000000044", "maxPriorityFeePerGas": "30000000000", "nonce": 2, "signature": { "_type": "signature", "networkV": null, "r": "0x1109e6e16e435841cae2cbf5c3abd18e25e03376b295cadaa4728b75d8384cac", "s": "0x0637ac31023c5fbef300adb23990b402195ed564667110490e63e490b1d59abd", "v": 28 }, "to": "0x0000000000000068F116a894984e2DB1123eB395", "type": 2, "value": "10000000000000000000" }, code=INVALID_ARGUMENT, version=6.9.1)

**Comment by rishisha19** [comment]
Is there any resolution to this issue?

**Comment by ryanio** [comment]
i've never seen this "hash mismatch" error before, can you share a reproducible code snippet?

**Comment by parthbisht** [comment]
> i've never seen this "hash mismatch" error before, can you share a reproducible code snippet?
   

    fulfillOrder = async (order: any, address: string) => {

    try {
      if (!window.ethereum) {
        throw new Error('Ethereum provider not found');
      }

      const provider = new ethers.BrowserProvider(window.ethereum);

      const signer = await provider.getSigner();

      if (!provider.send) {
        throw new Error('Ethereum provider does not support required methods');
      }

      const accountAddress = address;

      const openSeaSDK = new OpenSeaSDK(signer, {
        chain: this.chain,
        apiKey: this.apiKey,
      });

      const transaction = await openSeaSDK.fulfillOrder({
        order,
        accountAddress,
      });

      return [null, transaction];

      } 
    
     catch (error) {
      HELPERS.handleWalletError(error);
      return [error, null];
    }
    }

**Comment by rishisha19** [comment]
I am still looking for a fix to this. Can someone help?

**Comment by ryanio** [comment]
just cut a release that fixes this, [`v7.3.2`](https://github.com/ProjectOpenSea/opensea-js/releases/tag/v7.3.2)
