### ISSUE TITLE
How to limit gas used in fulfillOrder()?

### ISSUE THREAD

**Issue by imkane** [ProjectOpenSea/opensea-js#155]
I read through the docs but couldn't figure this out.

Just spent almost $150 in gas on one Buy transaction ... ugh.

Does anyone have any sample code that will estimate and limit gas?

**Comment by p-real96** [comment]
I have the same question and did not find any specification about this

**Comment by ANG3L0** [comment]
@imkane - which node version do you use?

When I try to fulfillOrder() it just says:
"Sell order is valid: true" and the program quits and nothing happens for me.

Not sure if I'm missing something obvious or if I need some particular config to get this to work.

**Comment by imkane** [comment]
> @imkane - which node version do you use?
> 
> When I try to fulfillOrder() it just says:
> "Sell order is valid: true" and the program quits and nothing happens for me.
> 
> Not sure if I'm missing something obvious or if I need some particular config to get this to work.

Node 12 works for me.

**Comment by fabdarice** [comment]
+1

**Comment by vasinl124** [comment]
+1

**Comment by amzfcy** [comment]
+1
