### ISSUE TITLE
Max priority fee EIP-1559

### ISSUE THREAD

**Issue by walruzperil** [ProjectOpenSea/opensea-js#158]
Since  EIP-1559 need setup Max priority fee. By default it set 1 i think. How we can increase Max priority fee?

**Comment by overfocus** [comment]
I also need to be able to do this. Does this sdk even support EIP-1559 transactions?

**Comment by nedosa** [comment]
It would be good to get some clarification on this. Has anyone managed to set a higher gas price in `fulfillOrder` ?

**Comment by workhard9999** [comment]
not here, but there is a solution. there are many bots out there executing with faster than average gas price. not sure if they are going directly through web3 or if they have figured out how to change code here. i have tried both gasPriceAddition and gasIncreaseFactor, neither work. is there a way to hardcode the the transaction data gas?

**Comment by nmduarteus** [comment]
Was anyone able to go around this problem using the SDK?

**Comment by hack3r-0m** [comment]
I have a fork https://github.com/hack3r-0m/opensea-js/commit/44feced07439ee48d9b07aa83fc83feb03ac7e1e which returns abi encoded transaction, you can then send that transaction using ethers.js

**Comment by nmduarteus** [comment]
> I have a fork [hack3r-0m@44feced](https://github.com/hack3r-0m/opensea-js/commit/44feced07439ee48d9b07aa83fc83feb03ac7e1e) which returns abi encoded transaction data, you can then send that transaction using ethers.js

Thanks. Will give it a try! Just adding your encoded transaction data to the sendTransaction would be enough then, is that it?

**Comment by hack3r-0m** [comment]
```js
(async () => {
    const order = await seaport.api.getOrder({ side: OrderSide.Sell, asset_contract_address: asset_contract_address, token_id: token_id })
    const abiEncoded = await seaport.fulfillOrder({ order, accountAddress: wallet.address })

    const txn = {
        to: wyvern,
        type: 2,
        data: abiEncoded.encoded,
        value: ethers.BigNumber.from(abiEncoded.txnData.value.toString()),
        maxPriorityFeePerGas: ethers.utils.parseUnits(additionalGas, "gwei"),
        maxFeePerGas: ethers.utils.parseUnits(baseGas, "gwei") + ethers.utils.parseUnits(additionalGas, "gwei")
    }

    try {
        const response = await wallet.sendTransaction(txn)
        console.log(response)
    } catch (e) {
        console.log(e.name)
        console.log(e.message)
    }

})();
```

**Comment by nmduarteus** [comment]
thanks a lot. works great!

**Comment by emorling** [comment]
> 

Thanks, do you have a version for OpenSeaJS 2.0.1?

**Comment by emorling** [comment]
> 

Any news on this?

**Comment by Verrok** [comment]
> ```js
> (async () => {
>     const order = await seaport.api.getOrder({ side: OrderSide.Sell, asset_contract_address: asset_contract_address, token_id: token_id })
>     const abiEncoded = await seaport.fulfillOrder({ order, accountAddress: wallet.address })
> 
>     const txn = {
>         to: wyvern,
>         type: 2,
>         data: abiEncoded.encoded,
>         value: ethers.BigNumber.from(abiEncoded.txnData.value.toString()),
>         maxPriorityFeePerGas: ethers.utils.parseUnits(additionalGas, "gwei"),
>         maxFeePerGas: ethers.utils.parseUnits(baseGas, "gwei") + ethers.utils.parseUnits(additionalGas, "gwei")
>     }
> 
>     try {
>         const response = await wallet.sendTransaction(txn)
>         console.log(response)
>     } catch (e) {
>         console.log(e.name)
>         console.log(e.message)
>     }
> 
> })();
> ```

Where I can find what `wyvern` variable is stands for?

**Comment by Verrok** [comment]
> > ```js
> > (async () => {
> >     const order = await seaport.api.getOrder({ side: OrderSide.Sell, asset_contract_address: asset_contract_address, token_id: token_id })
> >     const abiEncoded = await seaport.fulfillOrder({ order, accountAddress: wallet.address })
> > 
> >     const txn = {
> >         to: wyvern,
> >         type: 2,
> >         data: abiEncoded.encoded,
> >         value: ethers.BigNumber.from(abiEncoded.txnData.value.toString()),
> >         maxPriorityFeePerGas: ethers.utils.parseUnits(additionalGas, "gwei"),
> >         maxFeePerGas: ethers.utils.parseUnits(baseGas, "gwei") + ethers.utils.parseUnits(additionalGas, "gwei")
> >     }
> > 
> >     try {
> >         const response = await wallet.sendTransaction(txn)
> >         console.log(response)
> >     } catch (e) {
> >         console.log(e.name)
> >         console.log(e.message)
> >     }
> > 
> > })();
> > ```
> 
> Where I can find what `wyvern` variable is stands for?

nvm, I've understood

**Comment by robotesteves** [comment]
> ```js
> })();
> ```

Could you get this to work with the new contract? I can't seem to get it

**Comment by esteban-OpenSea** [comment]
Hey, is everyone still having issue with this?

**Comment by simonare** [comment]
we really need EIP-1559 support to be added to the library (not limited to fulfilorder, but needed to be extended to all transactional operations)

**Comment by DavydenkovM** [comment]
> ```js
> (async () => {
>     const order = await seaport.api.getOrder({ side: OrderSide.Sell, asset_contract_address: asset_contract_address, token_id: token_id })
>     const abiEncoded = await seaport.fulfillOrder({ order, accountAddress: wallet.address })
> 
>     const txn = {
>         to: wyvern,
>         type: 2,
>         data: abiEncoded.encoded,
>         value: ethers.BigNumber.from(abiEncoded.txnData.value.toString()),
>         maxPriorityFeePerGas: ethers.utils.parseUnits(additionalGas, "gwei"),
>         maxFeePerGas: ethers.utils.parseUnits(baseGas, "gwei") + ethers.utils.parseUnits(additionalGas, "gwei")
>     }
> 
>     try {
>         const response = await wallet.sendTransaction(txn)
>         console.log(response)
>     } catch (e) {
>         console.log(e.name)
>         console.log(e.message)
>     }
> 
> })();
> ```

Could someone please explain what `wyvern` is stands for? It isn't clear how to get this address (@hack3r-0m, @Verrok)

**Comment by simonare** [comment]
wyvern is the contract address of Opensea's [Wyvern Exchange Protocol](https://etherscan.io/address/0x7f268357a8c2552623316e2562d90e642bb538e5)

**Comment by bernardovski** [comment]
The transaction to wyvern with the returned abi encoded data keeps failing. I compared the returned abi with the original hex data when buying through OS and it doesn't match.

**Comment by jerryfane** [comment]
> I have a fork [hack3r-0m@44feced](https://github.com/hack3r-0m/opensea-js/commit/44feced07439ee48d9b07aa83fc83feb03ac7e1e) which returns abi encoded transaction data, you can then send that transaction using ethers.js

How can I make this same change on my code?

**Comment by Slers** [comment]
@hack3r-0m Thanks for the code, do you happen to have a version which works with the new Opensea-js contracts by any chance?

**Comment by Verrok** [comment]
> ```js
> wallet.sendTransaction(
> ```

Sry for long reply, I've replaced `wyvern ` with invoking `seaport.api.getOrderCreateWyvernExchangeAddress()`

**Comment by WebScripti** [comment]
> > ```js
> > (async () => {
> >     const order = await seaport.api.getOrder({ side: OrderSide.Sell, asset_contract_address: asset_contract_address, token_id: token_id })
> >     const abiEncoded = await seaport.fulfillOrder({ order, accountAddress: wallet.address })
> > 
> >     const txn = {
> >         to: wyvern,
> >         type: 2,
> >         data: abiEncoded.encoded,
> >         value: ethers.BigNumber.from(abiEncoded.txnData.value.toString()),
> >         maxPriorityFeePerGas: ethers.utils.parseUnits(additionalGas, "gwei"),
> >         maxFeePerGas: ethers.utils.parseUnits(baseGas, "gwei") + ethers.utils.parseUnits(additionalGas, "gwei")
> >     }
> > 
> >     try {
> >         const response = await wallet.sendTransaction(txn)
> >         console.log(response)
> >     } catch (e) {
> >         console.log(e.name)
> >         console.log(e.message)
> >     }
> > 
> > })();
> > ```
> 
> Where I can find what `wyvern` variable is stands for?

Hi, i tried 20 hours this code.
My all code below list. This code bought nft but not change gas setting.
Please help to me 

const Web3 = require('web3');
const express = require('express');
const opensea = require("opensea-js");
const BigNumber = require('bignumber.js');
const from = require('from');
const OrderSide = require("opensea-js/lib/types");
const http = require('http');
const OpenSeaPort = opensea.OpenSeaPort;
const Network = opensea.Network;
const EventType = opensea.EventType;
const ethers = require("ethers");

const privateKey = (walletprivatekey).toString('hex');
const wallet = new ethers.Wallet(privateKey);

const address = wallet.address;
console.log("Public Address:", address);


  (async () => {

let provider = new HDWalletProvider(walletprivatekey, "https://mainnet.infura.io/v3/MYINFURAKEYINHERE");
const web3 = new Web3(provider);
web3.setProvider(provider);

  const seaport = new OpenSeaPort(provider, {
    networkName: Network.Main,
    apiKey: "MYOPENSEAAPIKEYINHERE"
  }

  let estimatedGasPrice = (await seaport._computeGasPrice()).toString()/1e9*2
  seaport.gasPriceAddition = estimatedGasPrice;

console.log(estimatedGasPrice);

  const order = await seaport.api.getOrder({ side: 1, asset_contract_address: asset_contract_address, token_id: token_id })
  console.log(order);
  const abiEncoded = await seaport.fulfillOrder({ order, accountAddress: walletno, gasMultiplier: 4 })

const txn = {
  to: wyvern,
  type: 2,
  data: abiEncoded.encoded,
  value: ethers.BigNumber.from(abiEncoded.txnData.value.toString()),
  gasLimit: "500000", // basic transaction costs exactly 21000
  maxPriorityFeePerGas: ethers.utils.parseUnits('150','gwei'), // Recommended maxPriorityFeePerGas
  maxFeePerGas: ethers.utils.parseUnits('170','gwei') // Recommended maxFeePerGas
}



      try {
        console.log("geliyor");
          const response = await wallet.sendTransaction(txn)
          console.log(response)
      } catch (e) {
          console.log(e.name)
          console.log(e.message)
      }

  })();

**Comment by bernardovski** [comment]
@hack3r-0m since atomic match has been relegated to legacy due to the implementation of the new seaport protocol, is there a way to get abiencoded data from the new seaport fulfillorder method?
I managed to get the arguments before transaction is made:
![image](https://user-images.githubusercontent.com/62177972/174835987-9dd6583b-b630-4b7c-bcf7-85094be6e0c0.png)
however i don't know how to convert that into this:
![image](https://user-images.githubusercontent.com/62177972/174836098-a6e2d16e-738a-48f9-bb53-e33e963d9af9.png)

**Comment by cheungchingli** [comment]
> @hack3r-0m since atomic match has been relegated to legacy due to the implementation of the new seaport protocol, is there a way to get abiencoded data from the new seaport fulfillorder method? I managed to get the arguments before transaction is made: ![image](https://user-images.githubusercontent.com/62177972/174835987-9dd6583b-b630-4b7c-bcf7-85094be6e0c0.png) however i don't know how to convert that into this: ![image](https://user-images.githubusercontent.com/62177972/174836098-a6e2d16e-738a-48f9-bb53-e33e963d9af9.png)

Do you solve this problem?

**Comment by dcapeluto** [comment]
> @hack3r-0m since atomic match has been relegated to legacy due to the implementation of the new seaport protocol, is there a way to get abiencoded data from the new seaport fulfillorder method? I managed to get the arguments before transaction is made: ![image](https://user-images.githubusercontent.com/62177972/174835987-9dd6583b-b630-4b7c-bcf7-85094be6e0c0.png) however i don't know how to convert that into this: ![image](https://user-images.githubusercontent.com/62177972/174836098-a6e2d16e-738a-48f9-bb53-e33e963d9af9.png)

How were you able to get the list of args?

**Comment by riessnico** [comment]
Any news on this issue? I really need to be able to set the gas params.

**Comment by Slers** [comment]
You need to reconstitute the order and send it using ethers.js

**Comment by Alotrobo** [comment]
Hi, still no solution with the new version? The abiEncoded is not working anymore with ethers.js

**Comment by emorling** [comment]
We need someone to make a wrapper for this overcomplicated library. Simply:

list()
bid()
acceptOffer()
etc.

**Comment by maka1500** [comment]
I will send you the instructions what to modify... Please email to maka1500@proton.me

**Comment by dcapeluto** [comment]
Re controlling the gas, download the source of opensea-js and look for the references to seaport-js. Instead of assuming the reference as a dependency, get seaport-js straight from ProjectOpenSea's repo, and compile it yourself (https://github.com/ProjectOpenSea/seaport-js). You can update the references in opensea-js to seaport-js instead of the default packaged dependency, to your compiled (e.g. yarn tsc in the root folder of seaport-js) (`import { Seaport } from "./seaport-js/src/seaport";`). Then you can peep into the code that creates the fulfillOrder and update it to give you just the order params.

**Comment by walruzperil** [comment]
any news for new version opensea-js, seaport.fulfillOrder still send transaction in Legacy type)

**Comment by frxncisjoseph** [comment]
Any update on this? The code no longer works (returns a 404)

**Comment by walruzperil** [comment]
Finally I was able to send a transaction with Max priority and maxFeePerGas
![image](https://user-images.githubusercontent.com/7361881/203957253-460b8b1f-40d1-40be-834d-a9a50096eaeb.png)

**Comment by max1404** [comment]
> Finally I was able to send a transaction with Max priority and maxFeePerGas!)

Very nice! Can you explain it? Thanks <3

**Comment by YsingKitchen** [comment]
> Finally I was able to send a transaction with Max priority and maxFeePerGas ![image](https://user-images.githubusercontent.com/7361881/203957253-460b8b1f-40d1-40be-834d-a9a50096eaeb.png)

Can you give me some hints I've been stuck with it for days
