### ISSUE TITLE
People doing fake bids on opensea loophole

### ISSUE THREAD

**Issue by pixelpawnshop** [ProjectOpenSea/opensea-js#1580]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] opensea-js
- [ ] Node (minimum v16)

### Operating System

None

### Describe the bug

Hello,

there are people who found a loophole and do fake bids on opensea that cant be accepted. Their strategy is to make very high bids (which cant be accepted) and then do another real bid. This way they get around competing with bidding bots as the bidding bots think the top bid is a real one. Besides that for other users thats annoying as well not only for the bots. This guy here is doing this for example 

0x6DacbE6Ca453c0c39ABaA1F212D173B053B4e396

But there are many more using this loophole. This issue was already reported in the past, but I heard that OS only reaction was to bann those accounts. However thats not solving the issue and these people just create new accounts. Please do something about this.

**Comment by ryanio** [comment]
we have added additional order validations to prevent these types of unfulfillable orders, please let us know if you see any other similar issues
