### ISSUE TITLE
Why can getAssets only handle offset up to 10,000?

### ISSUE THREAD

**Issue by imkane** [ProjectOpenSea/opensea-js#159]
There's plenty of collections with more assets than that. [For example](https://opensea.io/collection/adam-bomb-squad).

To see what I mean, try the demo here:
https://docs.opensea.io/reference/getting-assets

You'll get a 400 error:
```
{
  "offset": [
    "ensure this value is less than or equal to 10000"
  ]
}
```

**Comment by J888** [comment]
I'd also be interested to know why.

I am working around it for now by using the `token_ids` array query param which can support 30 values at a time.

**Comment by pravin-d** [comment]
I'm also having similar problems.. However I think this is related to the issues of using Limit and offset pagination methods along with SQL or MongoDb or similar databases. 
In short, each query will have to OFFSET amount of items before sending back the response. This has to happen every time an API is called. So in effect when u call with OFFSET=10000 - 10K items need to skipped. The next call will be OFFSET=10100, then again 10K+100 items have to be skipped this becomes very compute expensive. So don't think it is very arbitrary either.
This is just my opinion.. Also check this out
https://shopify.engineering/pagination-relative-cursors
So something in the same lines as shopify should also be fine

**Comment by esteban-OpenSea** [comment]
Pagination past 10k is not yet supported

I will go ahead and close this issue since it's a duplicate. Please follow this ticket for the latest updates on this issue: https://github.com/ProjectOpenSea/opensea-js/issues/438
