### ISSUE TITLE
receiving type error:  field  to fetch

### ISSUE THREAD

**Issue by hekmatnajafi** [ProjectOpenSea/opensea-js#162]
when getting orders, or creating sell orders, making offers or buying assets, it gives me the "type error:  field  to fetch"
any solution?

**Comment by esteban-OpenSea** [comment]
Are you still running into this issue? Are you using the most recent version of the SDK and Node? Also, check this: https://stackoverflow.com/questions/49343024/getting-typeerror-failed-to-fetch-when-the-request-hasnt-actually-failed
