### ISSUE TITLE
Retrieve asset on polygon network?

### ISSUE THREAD

**Issue by editorai** [ProjectOpenSea/opensea-js#168]
Hi, how can I retrieve assets on polygon network from opensea api. Doese opensea have APIs supporting polygon network?

**Comment by rae89** [comment]
+1

**Comment by cjgammon** [comment]
The network seems to be utilizing definitions from [wyvern-js](https://github.com/ProjectWyvern/wyvern-js) which only defines ETH networks and has an [issue](https://github.com/ProjectWyvern/wyvern-js/issues/3) asking about polygon support already.  It would be great to support polygon mainnet and mumbai.  wyvern-js doesn't seem to have been updated for some time.

**Comment by Turtus** [comment]
+1111

**Comment by esteban-OpenSea** [comment]
Our API doesn't support Polygon yet, but we are working on it!

In the meantime check this out: https://docs.opensea.io/docs/polygon-basic-integration

**Comment by Turtus** [comment]
so why closed if not solved?

**Comment by wandriputra** [comment]
hi, @esteban-OpenSea any update for Polygon Mainnet and Mumbai Testnet?
