### ISSUE TITLE
getAssets function has no mentions in documentation

### ISSUE THREAD

**Issue by stanta** [ProjectOpenSea/opensea-js#169]
Hi, I found this function (getAssets) and like to use this for integration OpenSea exchange in our wallet (Unique wallet). But I can't find it's description in public documentation. Can we use this function or it deprecated?
https://github.com/ProjectOpenSea/opensea-js/blob/dadc216a3adadc5506bc159c597da2090cf78636/lib/api.d.ts#L79

**Comment by esteban-OpenSea** [comment]
Check out SDK documentation here: https://github.com/ProjectOpenSea/opensea-js#fetching-assets
