### ISSUE TITLE
yarn failure on wyvern-js import

### ISSUE THREAD

**Issue by stanta** [ProjectOpenSea/opensea-js#170]
Hi, 
We try to integrate OpenSea as subpackage in our wallet, but yarn fails packing when wyvern-js imports.
error log: 

[pack.log](https://github.com/ProjectOpenSea/opensea-js/files/7142572/pack.log)

Separately, OpenSea-js builds ok.

[link to our repo... ]( https://github.com/UniqueNetwork/unique-wallet/tree/feature/NFTPAR-780-fromether2unique/packages/)

**Comment by esteban-OpenSea** [comment]
Hello, is this still an issue for you? Please use the latest version of node and the SDK.

**Comment by JoshuaSchmidt-OpenSea** [comment]
This package will be removed in version 6
