### ISSUE TITLE
buyOrders is null on getAssets response

### ISSUE THREAD

**Issue by jonathanjm** [ProjectOpenSea/opensea-js#171]
```
 const OpenSeaAssets = await seaport.api.getAssets({
      asset_contract_address: collectibleData.address,
      order_direction: "desc",
      offset: offset,
      limit: limit,
    });
```
getAsset returns the buyOrders but getAssets returns null.

**Comment by AbdelHajou** [comment]
This is a limitation of the OpenSea API, the sellOrders, buyOrders and orders fields will always be null when retrieving multiple assets. To get the orders you'd have to retrieve the single asset.

**Comment by jonathanjm** [comment]
Thank you. Is this something being worked on? I want to display the last offer/price on a list of assets but if I have to call the API for every single asset I get throttled.

**Comment by AbdelHajou** [comment]
I'm not sure, I personally just use a [rate limiter ](https://www.npmjs.com/package/limiter) to make sure I don't send too many requests, but my application is not very performance critical.

**Comment by esteban-OpenSea** [comment]
Are you still getting throttled? As a reminder the rate limit is 4/sec
