### ISSUE TITLE
createSellOrder causes Error: Must be authenticated !

### ISSUE THREAD

**Issue by webevasion** [ProjectOpenSea/opensea-js#172]
I try to use the opensea sdk in javascript but I receive an error when I use `createSellOrder` method.

Here is my code :
```
const provider = new Web3.providers.HttpProvider('https://rinkeby.infura.io/v3/123456789_My_Key')
const seaport = new OpenSeaPort(provider, {
    networkName: Network.Rinkeby
})

let opts = {
    asset: {
        'The token ID',
        '0x88b48f654c30e99bc2e4a1559b4dcf1ad93fa656', // It's the address of opensea collection on rinkeby
    },
    accountAddress: '0x...', //The account who want to sell his asset
    startAmount: 0.1, //0.1 ETH
}
const listing = await seaport.createSellOrder(opts) // Cause the error
```

Received error : `Error: Must be authenticated !`

Node version is `8.11.0` as asked in the docs.

I searched everywere but I can't find a solution for "authenticating" the request, anyone can help me ?

**Comment by azflin** [comment]
You need a provider with a private key.

**Comment by esteban-OpenSea** [comment]
@azflin is correct! Please update your config file with the private key!
