### ISSUE TITLE
Error on createBuyOrder : eth_sendTransaction does not exist

### ISSUE THREAD

**Issue by BoraVivek** [ProjectOpenSea/opensea-js#175]
How to fix The method eth_sendTransaction does not exist/is not available issue.

```
(node:11020) UnhandledPromiseRejectionWarning: Error: The method eth_sendTransaction does not exist/is not available
    at Object.InvalidResponse (C:\laragon\www\nfts\node_modules\opensea-js\node_modules\web3\lib\web3\errors.js:38:16)
    at C:\laragon\www\nfts\node_modules\opensea-js\node_modules\web3\lib\web3\requestmanager.js:86:36
    at exports.XMLHttpRequest.request.onreadystatechange (C:\laragon\www\nfts\node_modules\web3-providers-http\lib\index.js:98:13)
    at exports.XMLHttpRequest.dispatchEvent (C:\laragon\www\nfts\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:591:25)
    at setState (C:\laragon\www\nfts\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (C:\laragon\www\nfts\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:447:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:11020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by CrazyOptimist** [comment]
I got the same issue trying to implement making offers. To make an offer or to create a buy order, we need to sign the transaction before submitting it, which will spend some fee, but it's missing in the nodejs code because it's not clear in the sdk docs.
Any help would be appreciated.

**Comment by goodaytar** [comment]
@CrazyOptimist  I'm also struggling to make offers. I was using infura but you can't sign transactions through them so you need to use an HD Wallet Provider, like truffle's. That said, I've done that and still getting 403 errors.

Have you figured out how to get it to work?

**Comment by wahab054** [comment]
Has anyone found a solution yet?

**Comment by goodaytar** [comment]
For me, I was using the deprecated version of HD Wallet Provider and, crucially, you need an API key from OpenSea. If you don't have one, think you'll find it hard to put offers in. Their API also goes down on a daily basis, so even when you get the API key your site will lack the ability to put offers in, regularly.

**Comment by wahab054** [comment]
@goodaytar I don't understand from the documentation how to create an OpenSeaPort with the HDWalletProvider. Can you please help out?
Here's my sample code:
`let provider = new HDWalletProvider({
	mnemonic: {
	  phrase: <mnemonicPhrase>
	},
	providerOrUrl: "https://mainnet.infura.io/v3/<projectId>"
});
const web3 = new Web3(provider);
const seaport = new OpenSeaPort(web3.provider, {
	networkName: Network.Main,
	apiKey: <key>
})`

**Comment by goodaytar** [comment]
Have you got discord? Send me your address and I'll DM you

**Comment by wahab054** [comment]
Same, wahab054

**Comment by goodaytar** [comment]
Need your four digit tag, there are a number of wahab054s

**Comment by wahab054** [comment]
6977

**Comment by wahab054** [comment]
@BoraVivek @CrazyOptimist Were you guys able to solve this issue?

**Comment by miguelmigs24** [comment]
No solution still?

**Comment by wahab054** [comment]
I was able to solve it. Lemme know if you still need help.



*Wahab Hassan Butt**LinkedIn <https://www.linkedin.com/in/wahabhassan/>*

**Comment by CrazyOptimist** [comment]
Yes, need help still. Could you post your solution here?

**Comment by ruskid** [comment]
also interested in solutions

**Comment by EmrahSignorini** [comment]
```js
let provider = new HDWalletProvider({
    mnemonic: {
        phrase: "test test test test test test test test test test test test"
    },
    providerOrUrl: 'https://rinkeby.infura.io/v3/YOUR_INFURA_APIKEY'
});

const seaport = new OpenSeaPort(provider, {
    networkName: Network.Rinkeby,
    apiKey: OPENSEA_APIKEY
});
````
This one worked for me on testnets, thank you @wahab054

**Comment by esteban-OpenSea** [comment]
Is this still an issue? The solution posted above seems valid. Also, you need to either sign the transaction yourself and then send via eth_sendRawTransaction or use a provider that can hold private keys like MetaMask in the browser.
