### ISSUE TITLE
Bugs on Bugs

### ISSUE THREAD

**Issue by Ssbnft** [ProjectOpenSea/opensea-js#177]
I can’t sell any NFT’s bought with a SafePal wallet and it’s passcode protected so I can’t even open my SafePal wallet with another service. 

In additional an NFT I have purchases instantly got relisted at a price I wouldn’t sell for.

I was unable to sell ANYTHING I’ve purchased and it’s created incredible opportunity loss getting into projects such as society of vamps.

Please help.

**Comment by esteban-OpenSea** [comment]
Regarding the SafePal issue, please reach out to their support team: https://docs.safepal.io/report-a-bug

For the NFT issues, please open a ticket with OpenSea support: https://support.opensea.io/hc/en-us/requests/new
