### ISSUE TITLE
Opensea integration with other blockchains

### ISSUE THREAD

**Issue by vi-dangvu** [ProjectOpenSea/opensea-js#178]
I came across this article: https://docs.opensea.io/docs/other-blockchains

But it does not say much about how we can integrate Opensea with other blockchain. Could you please give me some more clarity on this? 

Thank you,
Vi

**Comment by esteban-OpenSea** [comment]
You can use that link to check the latest updates on other blockchains. We also have a tutorial for the polygon blockchain here: https://docs.opensea.io/docs/polygon-basic-integration

We are also working on a developer newsletter to provide the community with updates. Please stay tuned for that! Check our [dev discord](https://discord.com/channels/397566282729390110/434175585745633280) for updates.
