### ISSUE TITLE
Sending Enjin items with transfer Error

### ISSUE THREAD

**Issue by nickjuntilla** [ProjectOpenSea/opensea-js#18]
Using 
"opensea-js": "0.5.0-rc15",
"web3": "1.0.0-beta.55",

In trying to send any Enjin item I get

" Error sending token:  { code: -32000.."

I'm using this code:

`const transactionHash = await seaport.transfer({
      asset: { tokenId, tokenAddress },
      fromAddress, 
      toAddress,
      quantity,
      schemaName
    });`

Where schema name is 'ERC1155'

This also seems to be a problem when trying to place an Enjin item for sale.

**Comment by alexanderatallah** [comment]
Looking into this!

**Comment by alexanderatallah** [comment]
@nickjuntilla what's the tokenAddress you're using? Enjin locked their old contract address - none of those items are transferrable anymore

**Comment by nickjuntilla** [comment]
Yeah after more research it’s definitely because they locked their contract. Thanks @alexanderatallah

**Comment by nickjuntilla** [comment]
@alexanderatallah I closed it since it's not really a code issue, but do you know when you might update their contract to the new one? I think the correct contract address is here: 0xfaafdc07907ff5120a76b34b731b278c38d6043c

as per this:
https://forum.enjin.io/threads/contract-address-abi.175/
