### ISSUE TITLE
How to get the REAL floor of a collection?

### ISSUE THREAD

**Issue by imkane** [ProjectOpenSea/opensea-js#181]
It appears that this API returns very outdated data:
https://docs.opensea.io/reference/retrieving-collections

For example, for https://opensea.io/collection/sneaky-vampire-syndicate it's been saying that the floor is **1.111** for 4 days now ;)

**Comment by dcts** [comment]
Its a known issue that the API returns inaccurate floor prices:
```js
const axios = require("axios");

async function getFloorPrice(slug) {
  try {
    const url = `https://api.opensea.io/collection/${slug}`;
    const response = await axios.get(url);
    return response.data.collection.stats.floor_price;
  } catch(err) {
    console.log(err);
    return undefined;
  }
}

const result = await getFloorPrice("lostpoets");
const result = await getFloorPrice("treeverse");
const result = await getFloorPrice("cool-cats-nft");
```
the floor price fetched with above method is NOT updated in realtime but every given time period (but nobody knows what the time intervall is and there is no documentation on it). 

You can try to scrape the data from the webpagepage (for example by using https://github.com/dcts/opensea-scraper) but its really not sustainible for a large amount of requests, might be a better strategy to use the unaccurate data from above and hope OpenSea adapts the API fairly quickly. At least that's what I am doing :)

Hope that helps.

**Comment by imkane** [comment]
@dcts you sir, are a gentleman and a scholar! :grinning:
