### ISSUE TITLE
getOrders() returns deleted items

### ISSUE THREAD

**Issue by 0xFriend** [ProjectOpenSea/opensea-js#182]
Hi all,

the getOrders() JavaScript SDK call seems to also return open orders for assets that have already been deleted in the OpenSea UI https://docs.opensea.io/reference/retrieving-orders

- When visiting the OpenSea URL from the order asset it shows 404 on OpenSea.
- Tested on rinkeby and mainnet - same results.

Main problem is that fulfillOrder() against such an object does still work and eats ETH from the user but the user does not receive the asset as it is deleted. Already lost $100 on mainnet.

I have not found a way to remove or ignore those invalid assets:

- Tried to work around by checking owner address of the asset in the order response to see if it is the null address.
- But this seems to have another bug: assets that I own and did not delete for whatever reason sometimes give me the null address as owner somehow.
- If the API was intended to also return open orders for deleted items there is no way to filter them out currently.
 
Desperately trying to find out if I overlooked something or if this really is a bug?
Happy to provide test calls and any additional info so that this issue can get resolved.

**Comment by anassh23** [comment]
unsubscribe

**Comment by esteban-OpenSea** [comment]
Hello, are you still having issues with this?
