### ISSUE TITLE
What is the typescript version of this project?

### ISSUE THREAD

**Issue by yyidota** [ProjectOpenSea/opensea-js#186]
Hi all:
I want to know what the version number of the SDK TypeScript compiler is. I have tried many versions of Typescript and will report tslint detection errors on the console, so I hope the developers can tell, thanks!

**Comment by esteban-OpenSea** [comment]
You can see the latest version of TS in the package.json file. Check here: https://github.com/ProjectOpenSea/opensea-js/blob/master/package.json#:~:text=%22typescript%22%3A%20%224.5.4%22
