### ISSUE TITLE
Do listeners monitor all of OpenSea?

### ISSUE THREAD

**Issue by Astrophe** [ProjectOpenSea/opensea-js#187]
Hi there,

I am trying to create a listener that will monitor all of my outstanding offers, and fire whenever one of them is accepted, but I am not getting how to do that from the limited info in the README. Could someone provide some guidance on a) is this even possible, and b) a template to get me started?

Thanks!

**Comment by 0x7An** [comment]
@Astrophe They are not global listeners, and cannot be used to listen to events that happen on the opensea website.

The SDK implements the [fbemmiter](https://www.npmjs.com/package/fbemitter) library, which is a lib that works only with the instance of opensea SDK that fired the action. So you can only listen to orders that you created with your instance of seaport.

**Comment by Astrophe** [comment]
Thanks @0x7An !

Could I attach a listener to any seaport.createbuyorder to get notified if my offer is accepted? Any prototype or example code you could provide would be greatly appreciated as well.

**Comment by imkane** [comment]
I'm also curious about this :grinning: 

> Thanks @0x7An !
> 
> Could I attach a listener to any seaport.createbuyorder to get notified if my offer is accepted? Any prototype or example code you could provide would be greatly appreciated as well.
