### ISSUE TITLE
seaport.createBuyOrder is not working - returns 429 error every time.

### ISSUE THREAD

**Issue by SourceSafe** [ProjectOpenSea/opensea-js#189]
Hi Team

I'm using code from the opensea-creatures project (sell.js) to create an OpenSeaPort instance and call seaport.createBuyOrder()

**My Node & npm versions**
  C:\Users\Owner>node -v
  v12.18.4
  
 C:\Users\Owner>npm -v
 6.14.6

**Script**
const {OpenSeaPort,Network} = require('opensea-js')
const RPCSubprovider = require('web3-provider-engine/subproviders/rpc')
const Web3ProviderEngine = require('web3-provider-engine')
const  {MnemonicWalletSubprovider}  = require('@0x/subproviders');
const accountAddress = "0x2c649A72529FfB801825a52136e0D5C8F171f6Bd"
const API_KEY =  ""; 
const NFT_CONTRACT_ADDRESS_SVS = "0x219b8ab790decc32444a6600971c7c3718252539";
const NFT_TOKEN_ID = "3400";
const NETWORK = "mainnet";
const NODE_API_KEY = "e1d6858ba67049bc934a9b764efb9c31";
const isInfura = true;//!!process.env.INFURA_KEY;
const MNEMONIC = "My Metamask Mneumonic here";
const BASE_DERIVATION_PATH = `44'/60'/0'/0`;
const network = NETWORK === "mainnet" || NETWORK === "live" ? "mainnet" : "rinkeby";

const mnemonicWalletSubprovider = new MnemonicWalletSubprovider({
  mnemonic: MNEMONIC,
  baseDerivationPath: BASE_DERIVATION_PATH,
});

const infuraRpcSubprovider = new RPCSubprovider({
  rpcUrl: isInfura
    ? "https://" + network + ".infura.io/v3/" + NODE_API_KEY
    : "https://eth-" + network + ".alchemyapi.io/v2/" + NODE_API_KEY,
});

const providerEngine = new Web3ProviderEngine();
providerEngine.addProvider(mnemonicWalletSubprovider);
providerEngine.addProvider(infuraRpcSubprovider);
providerEngine.start();

const seaport = new OpenSeaPort(
  providerEngine,
  {
    networkName:
      NETWORK === "mainnet" || NETWORK === "live"
        ? Network.Main
        : Network.Rinkeby,
    apiKey: API_KEY,
  },
  (arg) => console.log(arg)
);

placeOffer(NFT_CONTRACT_ADDRESS_SVS, NFT_TOKEN_ID, 0.0000001, Math.round(Date.now() / 1000 + 60 * 3))    

async function placeOffer(address, tokenId, price , expirationTime) {    
    const asset = {
    tokenId: tokenId, 
     tokenAddress: address,
   }
   try{            
       const  makeOffer  =  await seaport.createBuyOrder({
        asset: asset,
          accountAddress,          
          startAmount: price,
          expirationTime
        })  
        console.log(`Successfully created a offer! ${makeOffer.asset.openseaLink}`);
   }
   catch(ex)
   {
     console.log(ex)
   }    
  }

**packages.json**

{
  "name": "newscript",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@0x/subproviders": "^6.4.1",
    "opensea-js": "^1.1.5"
  },
  "engines": {
    "node": "^12.18.x"   
  }
}
  

When i run the script the sdk outputs the following log to console :-
Already approved enough currency for trading
Order hashes match

but then it  always returns the 429
Error: API Error 429: Message: {"detail":"Request was throttled."}

I understand throttling. Why is it that I'm getting the 429 when I have never once called this function successfully. I've most certainly not called it  multiple times a second or at any rate to induce throttling limits.. In fact even when I leave it for 24 hrs plus and try again it give me the 429. 

I have the correct node version installed as specified in the engines section in the opensea-creatures package.json.

I also have the same node module dependencies as opensea-creatures

  "@0x/subproviders": "^6.4.1",
    "opensea-js": "^1.1.5"

My code to create the OpenSeaPort client is identical to the opensea-creatures script file. Yet it still return 429.

I know all the the code is OK because when I run the same code from a react-app the buy order is placed successfully. But I cannot get it to run from script. 

I  know that I don't need an API key because the code runs successfully from my react-app.

please help ! I much appreciate the sdk but why the persistent 429?

**Also what is the magic combination of latest node and opensea modules that I can use to place a buy order ??**

**Comment by pguardiario** [comment]
Maybe another device on your network is hitting opensea very fast.

**Comment by pguardiario** [comment]
This one should probably get closed since there's no solution other than to slow down.

**Comment by SourceSafe** [comment]
I don’t think you understand the problem. How can I slow down  anymore . Even if I call it once a week it throws a 429.

Someone needs to solve it it give explanation.

Regards

**Comment by alexandera73** [comment]
I have posted answer here.
[(https://github.com/ProjectOpenSea/opensea-js/issues/193)]

I faced same error and I fixed it with 1 min 20 s delay when I got 429 error.
**Even if I call the method one time, it throws the 429 error about my request.**

So you need to wait when you got the error.
Hope you to solve this problem.

**Comment by river-korbit** [comment]
@alexandera73 Was it fixed by that way? I call createBuyOrder just once, but I god 429 error.

**Comment by SourceSafe** [comment]
So the expected behaviour  is :-

   * try and place a buy order
   * you will get a 429 on the first call - why is this ? surely it should not always fail on the first call.
   * then sleep for 1min 20 sec / 2 mins
  * repeat till order is place

Why is the expected behaviour that It will always fail on the first call ? - surely this is BUG.

**Comment by alexandera73** [comment]
Please use createBundleBuyOrder() function then.

**Comment by Blaschuko** [comment]
I'm using it, but still getting the same response.

**Comment by fabdarice** [comment]
same error :(

**Comment by datakarma186282** [comment]
same

**Comment by ANG3L0** [comment]
Were you even able to get this working with the hack? I wasn't able to create a sell order successfully even if I were to wait 80 seconds or 2 minutes or whatever. It just always 429s.

**Comment by river-korbit** [comment]
Me, too. I got alway 429s!!!!! @ANG3L0

**Comment by esteban-OpenSea** [comment]
Please follow https://github.com/ProjectOpenSea/opensea-js/issues/86 issue for the latest update on the 429 issues.

Also, the rate limit is 4/sec
