### ISSUE TITLE
CERT_HAS_EXPIRED

### ISSUE THREAD

**Issue by overfocus** [ProjectOpenSea/opensea-js#190]
Just started getting this tonight when calling the events API.. anyone else?

**Comment by IrishVoltik** [comment]
Yes, I got the same problem and wanted to open issues, but you was first! I will look here and wait for a solution.

**Comment by avm70** [comment]
node --use-openssl-ca should work

**Comment by IrishVoltik** [comment]
> node --use-openssl-ca should work

This is work for me, thank you, and overfocus for ask!

**Comment by WoutervDijk** [comment]
@avm70 and @IrishVoltik I have the same problem. Just adding --use-openssl-ca does not work for me. I get the error "unable to get local issuer certificate". I am on Windows btw. What did you do to fix this issue?

**Comment by avm70** [comment]
I have not faced such a problem. I'm using linux. 
@WoutervDijk do you have installed openssl?

**Comment by cozycole** [comment]
@WoutervDijk Did you find a solution to that? I'm getting the same error.

**Comment by cre-mer** [comment]
> node --use-openssl-ca should work

How exactly did you use this command? What do you do when it opens the node terminal?

**Comment by davidqw** [comment]
> @avm70 and @IrishVoltik I have the same problem. Just adding --use-openssl-ca does not work for me. I get the error "unable to get local issuer certificate". I am on Windows btw. What did you do to fix this issue?

got the same error, which version of node.js should I use?

**Comment by esteban-OpenSea** [comment]
Hello, are you still running into this issue? Make sure you are using the latest version of node. Also, check [this](https://stackoverflow.com/questions/20433287/node-js-request-cert-has-expired) out.

**Comment by davidqw** [comment]
> Hello, are you still running into this issue? Make sure you are using the latest version of node. Also, check [this](https://stackoverflow.com/questions/20433287/node-js-request-cert-has-expired) out.

Thanks, use node version 16.13.1 and this works

**Comment by esteban-OpenSea** [comment]
Great to hear! I will close out this ticket.
