### ISSUE TITLE
Server Error (500) In case of collection and order_by query param

### ISSUE THREAD

**Issue by bkulcsar** [ProjectOpenSea/opensea-js#192]
Hi!

In case of retrieving Assets, if we provide both the **collection** filter and the **order_by** query param the API gives back an 500 status code.

**Repro steps:**
1. Try to retrieve assets with collection and order_by query param:
https://api.opensea.io/api/v1/assets?order_by=sale_date&order_direction=desc&offset=0&limit=20&collection=rarible
2. See the response: Server Error (500)

**Expected behavior:**
List of asset object should be in the response.

Thanks,
Bálint

**Comment by frabrg** [comment]
Did you find a workaround ? I encountered this error too

**Comment by esteban-OpenSea** [comment]
Is this still an issue for you?

**Comment by gobit0dic** [comment]
It's still an issue. I encounter the same problem if I use the events endpoint and use a filter for "cursor" and/or "occured_before".  

E.g. this is working: https://api.opensea.io/api/v1/events?cursor=LWV2ZW50X3RpbWVzdGFtcD0yMDIxLTEyLTI0KzE4JTNBMDklM0EyNyYtcGs9MjU5NzE5ODY2OQ%3D%3D

If I use the "next"-value from the response (https://api.opensea.io/api/v1/events?cursor=LWV2ZW50X3RpbWVzdGFtcD0yMDIxLTEyLTI0KzE4JTNBMDklM0EyNi45NTY1ODAmLXBrPTI1OTcxOTU4NzI), I encounter a 500 Server-Error. 

The issue exists in my implementation as well as in the API explorer on the opensea page. So I think it's maybe a database issue. Sometimes it helps to lower the limit, e.g. 500 Error with limit = 300 but it works with limit=50 oder limit=20. Sometimes nothing helps 

Also it is more common for events from specific years, especially April-August 2019 and June-December 2021

**Comment by babarhussain47** [comment]
Did anyone foud some work arrounfld for the issue?
