### ISSUE TITLE
createSellOrder() 429s

### ISSUE THREAD

**Issue by ANG3L0** [ProjectOpenSea/opensea-js#193]
Tried to do the following with:

1. HD Truffle Wallet Provider
2. The mnemonicWalletSubprovier + infuraRpcSubprovider as shown in examples.

  const expirationTime = Math.round(Date.now() / 1000 + 3600)

```
  const listing = await seaport.createSellOrder({
    asset: asset,
    accountAddress: OWNER_ADDRESS,
    startAmount: .3,
    // If `endAmount` is specified, the order will decline in value to that amount until `expirationTime`. Otherwise, it's a fixed-price order:
    endAmount: 0.1,
    expirationTime:expirationTime
  }).catch( (err) => {
    console.log(err)
  })
  console.log(listing)
```

Just returns 429. This call allows me to approve the token on my wallet. But it doesn't allow me to actually create the sell order, rendering it useless.

`Error: API Error 429: Message: {"detail":"Request was throttled."}`

**Comment by avm70** [comment]
Opensea API throttle part of requests. To prevent API from being overwhelmed by too many requests.

**Comment by river-korbit** [comment]
I got a same issue. any news? @ANG3L0

**Comment by alexandera73** [comment]
I also faced same error so I fixed that with 1 min 20 s delay when I got the error.

My script in NodeJS.
const creatBuyOrder = async (tokenId, tokenAddress, reAuctionPrice, schemaName = "ERC721") => {
  try {
    const offer = await seaport.createBuyOrder({
      asset: {
        tokenId,
        tokenAddress,
        schemaName: schemaName
      },
      accountAddress: WALLET_ADDRESS,
      startAmount: reAuctionPrice / (10 ** 18),
      expirationTime: Math.round(Date.now() / 1000 + 60 * 60 * 24) // One day
    });
  
    console.log(chalk.yellow(`Your new auction was made successfully on ${tokenAddress}/${tokenId}`));
    console.log(chalk.yellow(`Hash code: ${offer.hash}`));
  } catch (error) {
    throw new Error(error);
  }
}

try {
      await creatBuyOrder(tokenId, tokenAddress, reAuctionPrice);
    } catch (error) {
      if (error.message.includes("429")) {
        console.log(chalk.yellow("Waiting 1 min 20s..."));  delay(80);  // 1min 20s
        await creatBuyOrder(tokenId, tokenAddress, reAuctionPrice);
      } else if (error.message.includes("400")) {
        console.log("ERC1155 Contract Token.");
        console.log(chalk.yellow("Waiting 1 min 20s..."));  delay(80);  // 1min 20s
        await creatBuyOrder(tokenId, tokenAddress, reAuctionPrice, "ERC1155");
      } else {
        console.log(chalk.red("Buy Order Error: \t" + error.message));
      }
    }

**Comment by fabdarice** [comment]
same error :(

**Comment by river-korbit** [comment]
@alexandera73 Do you have a api key for opensea-js sdk?

**Comment by esteban-OpenSea** [comment]
Please make sure you have a valid API key. The rate limit for is 4/sec. Also, since we have a duplicate issue I will close this one. Please follow this issue for the latest updates on the 429's: https://github.com/ProjectOpenSea/opensea-js/issues/259
