### ISSUE TITLE
createSellOrder elementaryName is not a function error

### ISSUE THREAD

**Issue by angryDev67** [ProjectOpenSea/opensea-js#197]
Ive got a strange error in my React application: 

On localhost and with builded version createSellOrder method works fine. But on production/staging i've got an error: ```l.elementaryName is not a function```

l = ethABI (require ethereumjs-abi). seems like after webpack build ethABI is undefined somehow, but only on production.
Any suggestions? Maybe i should change the version? Current is 1.1.13

**Comment by voskart** [comment]
Having the same issue. Anybody found a solution yet?
