### ISSUE TITLE
Feature request: list assets for sale of a specific contract

### ISSUE THREAD

**Issue by yonathan06** [ProjectOpenSea/opensea-js#199]
I think the ability to list items for sale (auction or non) of a specific contract can be helpful for NFT creators that have their own website, and want to direct the users to buy an item at opensea

Is it something you plan to add to the API?

**Comment by esteban-OpenSea** [comment]
You can retrieve assets from a specific contract! Check this out: https://docs.opensea.io/reference/getting-assets
