### ISSUE TITLE
Bug report for OpenSea: URLs Etheremon (EMONA) are wrong in the API results

### ISSUE THREAD

**Issue by James-Sangalli** [ProjectOpenSea/opensea-js#2]
URLs Etheremon (EMONA) are returned in the API results as

https://www.etheremon.com/#/mons/2

They should be:

https://www.etheremon.com/mons/2

**Comment by dfinzer** [comment]
Turns out there's actually a better URL, that uses the token ID: https://www.etheremon.com/mons-info/36602 we will switch to this!
