### ISSUE TITLE
Add `refererAddress` returns 'cannot read property toArray of undefined'

### ISSUE THREAD

**Issue by dani69654** [ProjectOpenSea/opensea-js#204]
Following the docs: https://github.com/ProjectOpenSea/opensea-js#referring-offers
I do create buy order adding `referrerAddress` but then the seller cannot confirm the order due to the error `cannot read property toArray of undefined`.

Fails here:

schema.ts ->> `ethABI.rawEncode(inputTypes, parameters)`

Info:

- Network: Rinkeby
- OrderHash: `0xd92e835c94bfedeeae3c940661cad8bb962af7db2944e8f9733275cea648831d`
- Order on OpenSea: https://testnets.opensea.io/assets/0xa438d6323ea624ff440055a45ab3451240827c61/1
- Amount: 0.0001 WETH
![Screenshot 2021-10-14 at 09 10 23](https://user-images.githubusercontent.com/60792849/137268766-f2d53793-3da5-4cc3-b43d-0f8ffe87f097.png)

**Comment by dani69654** [comment]
This function is still broken. Any news?

**Comment by esteban-OpenSea** [comment]
Hey, just wanted to check in. Is this function still not working for you?
