### ISSUE TITLE
Can't build with vite due to `0xproject` dependency from `wyvern-schemas`

### ISSUE THREAD

**Issue by cchyung** [ProjectOpenSea/opensea-js#211]
I did `yarn add opensea-js` and when I try to build with `vite` and `svelte-kit` I am getting the following errors:

```
 > ../node_modules/@0xproject/utils/tsconfig.json:2:15: error: Cannot read file "../node_modules/tsconfig": is a directory
    2 │     "extends": "../../tsconfig",
      ╵                ~~~~~~~~~~~~~~~~

 > ../node_modules/@0xproject/assert/tsconfig.json:2:15: error: Cannot read file "../node_modules/tsconfig": is a directory
    2 │     "extends": "../../tsconfig",
      ╵                ~~~~~~~~~~~~~~~~
```

Why are these packages not able to resolve the parent-level tsconfig?  I tried adding the `.json` extension and that resolves the error but that is only a temporary solution

Node version is 14.18
MacOS 11.4

**Comment by 0x7An** [comment]
@cchyung Have you tried downgrading your node version? Try again using `v12.22.4`. Or even `8.11` like the docs mention

**Comment by cchyung** [comment]
Actually found the solution on the [yarn page](https://yarnpkg.com/package/@0xproject/utils) for `0xproject`:

Just need to add the following flag to the `tsconfig.json` project and it will compile successfully.
```
"compilerOptions": {
    "typeRoots": ["node_modules/@0xproject/typescript-typings/types", "node_modules/@types"],
}
```

**Comment by esteban-OpenSea** [comment]
Glad to see you found the solution to this! I will go ahead and close this issue out.
