### ISSUE TITLE
Support for the Events API

### ISSUE THREAD

**Issue by stevef** [ProjectOpenSea/opensea-js#212]
Hi,

The HTTP API has an endpoint for retrieving asset events. https://docs.opensea.io/reference/retrieving-asset-events

This is fine for pulling, but what if I want events pushed to me? The closest I can find is https://github.com/ProjectOpenSea/opensea-js#listening-to-events. The problem here is I believe this is not related to the events HTTP API listed above. There is no way to filter by project slug/contract address. I do not believe these two are related, but could use some clarification. 

Is there any plan to support getting asset events pushed to the SDK?

**Comment by wong2** [comment]
Did you solve this?

**Comment by DishantPal** [comment]
Hi any luck on this?
