### ISSUE TITLE
npm install --save opensea-js ; install fail

### ISSUE THREAD

**Issue by jmxazd** [ProjectOpenSea/opensea-js#213]
fatal: unable to find remote helper for 'git+https'
✖ Install fail! Error: [opensea-js@1.2.1 › wyvern-schemas@0.10.7 › wyvern-js@github:ProjectOpenSea/wyvern-js#semver:^3.2.1] Run "sh -c git clone git+https://github.com/ProjectOpenSea/wyvern-js.git /Users/zxa/Desktop/opensea-creatures-master/node_modules/.tmp/f83ec6e5-aa82-4a2e-9150-caed15841108" error, exit code 128
Error: [opensea-js@1.2.1 › wyvern-schemas@0.10.7 › wyvern-js@github:ProjectOpenSea/wyvern-js#semver:^3.2.1] Run "sh -c git clone git+https://github.com/ProjectOpenSea/wyvern-js.git /Users/zxa/Desktop/opensea-creatures-master/node_modules/.tmp/f83ec6e5-aa82-4a2e-9150-caed15841108" error, exit code 128
    at module.exports (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/download/git.js:51:11)
    at module.exports.throw (<anonymous>)
    at onRejected (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:81:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by workhard9999** [comment]
install win-git using npm. make sure you are using node js version 14 or below.

**Comment by hpy-lhj** [comment]
I also encountered the same problem. Have you solved it?

**Comment by workhard9999** [comment]
Yes. Install win git. And use node v14. Worked perfectly.

**Comment by wsf1214** [comment]
> install win-git using npm. make sure you are using node js version 14 or below.

What is win-git?

**Comment by workhard9999** [comment]
You need git on your installs. Git allows you to install from GitHub. Look
up any git downloader on google. The one that I use is win-git. DYOR. I
like to only install packages that are well known or I’ve thoroughly
researched so I don’t get malware. Good luck.

**Comment by mcwxxx** [comment]
win-git is not found on github,who can tell me how to fix it

**Comment by esteban-OpenSea** [comment]
We are looking into this. In the meantime please use yarn.

```
npm install --global yarn
yarn add opensea-js
```

There is already a duplicate issue regarding this problem, I will close this ticket to avoid confusion. Please follow this ticket for the latest updates: https://github.com/ProjectOpenSea/opensea-js/issues/471
