### ISSUE TITLE
Warning! Error encountered during contract execution [Out of gas] |  Why no option to add extra gas?

### ISSUE THREAD

**Issue by Jamucy** [ProjectOpenSea/opensea-js#214]
Warning! Error encountered during contract execution [Out of gas]

This is happening more and more recently.

Please can you you give some clear instruction on how to add extra gas to fulfillOrder purchases.

Nothing i have tried seems to work, i see other people also looking for the same answer here.

Thanks

**Comment by esteban-OpenSea** [comment]
Check [this](https://support.opensea.io/hc/en-us/articles/1500006315941-What-are-gas-fees-on-Ethereum-#:~:text=check%20this%20resource.-,Out%20of%20gas%3A,-this%20occurs%20when) out.
