### ISSUE TITLE
 Trading for this asset ([object Object]) is not yet supported. Please contact us or check back later!

### ISSUE THREAD

**Issue by AqeelKazmi** [ProjectOpenSea/opensea-js#215]
So this is my testnet code

const tokenAddress= "0x88b48f654c30e99bc2e4a1559b4dcf1ad93fa656"
const tokenId= '79630473148403579200232510153367869810807992404435473599666936435606164602881'
const accountAddress = address.toString()
await seaport.createBuyOrder({
    asset: {
      tokenId,
      tokenAddress,
      schemaName: WyvernSchemaName,
    },
    accountAddress, // Address of the bidder
    startAmount: 0.1,
  })
  
  
  I have already done with fullfillOrder function and is working fine, but facing this issue in createBuyOrder function. Also tried without passing schemaName but then it says  "Failed to extract transfer calldata"
  
  Any solution?

**Comment by esteban-OpenSea** [comment]
Are you still having this issue? Check out the solution for the "failed to extract calldata": https://github.com/ProjectOpenSea/opensea-js/issues/92
