### ISSUE TITLE
Rest API RESPONSE for collections: offset – ensure this value is less than or equal to 50000

### ISSUE THREAD

**Issue by JohannesHoppe** [ProjectOpenSea/opensea-js#217]
I found a bug in the REST API and this seems to be the best place to write an issue.

Try this in your browser:

```
fetch('https://api.opensea.io/api/v1/collections?offset=' + 50000 + '&limit=300', {method: 'GET'})
  .then(response => response.json())
  .then(x => console.log(x));
```
You get a response with 300 collections, so there must be more.

Now this:

```
fetch('https://api.opensea.io/api/v1/collections?offset=' + (50000+1) + '&limit=300', {method: 'GET'})
  .catch(err => console.error(err));
```

RESPONSE:

`{"offset":["ensure this value is less than or equal to 50000"]}`

So the huge amount of collections has hit an internal limit of the API. That value must be increased.

**Comment by SourceSafe** [comment]
any solution for this? Where is the best place to get all the slugs ?

**Comment by JohannesHoppe** [comment]
Certainly not on this Web 2.5 platform.
LooksRare is also supposed to be nice...

**Comment by esteban-OpenSea** [comment]
Thanks for bringing this up to us! We are looking into this.

**Comment by BenjaminTardy** [comment]
Hello guys, some news about this limit?

**Comment by BenjaminTardy** [comment]
Hello guys, some news?

**Comment by passabilities** [comment]
still seems to be an issue 😕

**Comment by labralords** [comment]
> Thanks for bringing this up to us! We are looking into this.

@alexanderatallah @esteban-OpenSea One year has passed... What is the reason that this still is a issue?

**Comment by labralords** [comment]
> Thanks for bringing this up to us! We are looking into this.

@alexanderatallah @esteban-OpenSea @JoshuaSchmidt-OpenSea One year has passed... What is the reason that this still is a issue?

**Comment by thenerdassassin** [comment]
Unfortunately, this is a limitation of the current v1 implementation because the offset is not performant at high values. The plan is to build a more sensible, and scalable, implementation for V2 and eventually deprecate this endpoint.

**Comment by JohannesHoppe** [comment]
After how many years?!

**Comment by thenerdassassin** [comment]
This feature is in active development and should be announced in the near future. Make sure to follow the [API changelog](https://docs.opensea.io/changelog) to be updated when the V2 collections endpoint is released.

**Comment by ryanio** [comment]
v1 api is now deprecated, being removed next week, see our [V2 APIs](https://docs.opensea.io/reference/api-overview) which should have this pagination issue fixed with `next` cursors.
