### ISSUE TITLE
npm error when trying to install the package

### ISSUE THREAD

**Issue by gouffreNFT** [ProjectOpenSea/opensea-js#219]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ProjectWyvern/ethereumjs-abi.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

When trying to npm install opensea-js
Can someone help me?

**Comment by workhard9999** [comment]
you need to make sure git is installed on your system. i think npm has win-git. make sure to install global. also, use node js version 14x.

**Comment by arishabh** [comment]
> you need to make sure git is installed on your system. i think npm has win-git. make sure to install global. also, use node js version 14x.

How to install win-git?

**Comment by esteban-OpenSea** [comment]
A temporary fix for this is using yarn instead of npm. 

```
npm install --global yarn
yarn add opensea-js
```

We are looking into why this is an issue with npm. In the meantime, please follow the issue here for the latest updates: https://github.com/ProjectOpenSea/opensea-js/issues/471
