### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Event')

### ISSUE THREAD

**Issue by cchyung** [ProjectOpenSea/opensea-js#220]
We are trying to use `opensea-js` on the client (svelte-kit).  The library imports perfectly fine on the dev server but after building, when we try and use the library we are getting the following error:  
```
TypeError: Cannot read properties of undefined (reading 'Event')
```

It looks like it has something to do with the Wyvern schemas.  This is what chrome points us to in the built JS package.  

```js
events: {
        transfer: [{
            type: iv.AbiType.Event, // This is the line it's complaining about
            name: "Transfer",
            target: "0x06012c8cf97bead5deae237070f9587f8e7a266d",
            anonymous: !1,
            inputs: [{
                kind: Li.EventInputKind.Source,
                indexed: !1,
                name: "from",
                type: "address"
            }, {
                kind: Li.EventInputKind.Destination,
                indexed: !1,
                name: "to",
                type: "address"
            }, {
                kind: Li.EventInputKind.Asset,
                indexed: !1,
                name: "tokenId",
                type: "uint256"
            }],
            assetFromInputs: e=>eO(void 0, void 0, void 0, function*() {
                return e.tokenId
            })
        }]
    },
```

**Comment by egarson** [comment]
I am experiencing the same error using Vue3 / Vite / Composition API / TypeScript.
If I include a line to create a new OpenSeaPort instance, this error occurs in the same place in the build output, but works fine in development mode....

**Comment by aceprince** [comment]
> I am experiencing the same error using Vue3 / Vite / Composition API / TypeScript. If I include a line to create a new OpenSeaPort instance, this error occurs in the same place in the build output, but works fine in development mode....

the same error with me, do you fix it now?
