### ISSUE TITLE
How to get buy orders of bundles

### ISSUE THREAD

**Issue by jonathanjm** [ProjectOpenSea/opensea-js#225]
How can I get the buy orders of bundles? The getBundles api doesn't return buy orders and I can't see in the docs a call to get orders for bundles. I tried getOrders passing the token ids of the assets in a bundle but it returns an empty array.

**Comment by esteban-OpenSea** [comment]
Check these out: https://docs.opensea.io/reference/retrieving-bundles and https://docs.opensea.io/reference/retrieving-orders
