### ISSUE TITLE
createSaleOrder error when using ethers.js with MetaMask

### ISSUE THREAD

**Issue by hchouhan02** [ProjectOpenSea/opensea-js#226]
Hi, 

I am trying to use OpenSea-js to sell my minted token using MetaMask provider with the help of ethers.js, I am getting the following error.
<img width="702" alt="Screenshot 2021-10-28 at 3 20 25 AM" src="https://user-images.githubusercontent.com/2250979/139152631-4069dd65-a3fa-4d4e-b422-5bb925143ca7.png">

Anyone can help me to fix this, it's very urgent.

My code snippets.
<img width="570" alt="Screenshot 2021-10-28 at 3 23 39 AM" src="https://user-images.githubusercontent.com/2250979/139153056-3dd34bd0-ac31-4bad-b724-ed19f77b481b.png">

**Comment by hchouhan02** [comment]
I switched to web3 and it works.

**Comment by cycorax12** [comment]
Can you share me code snippet, i am trying to buy NFT using metamask from own site on Opensea. Will appreciate any help.
