### ISSUE TITLE
Validation errors: instance.basePrice does not match pattern "^\\d+(\\.\\d+)?$"

### ISSUE THREAD

**Issue by chanzer0** [ProjectOpenSea/opensea-js#227]
I am trying to create a sell order for ERC-1155 assets in this manner:
```
seaport.createSellOrder({
        asset: {
            tokenId: asset.tokenId,
            tokenAddress: asset.assetContract.address,
            schemaName: asset.assetContract.schemaName,
        },
        accountAddress: account,
        startAmount: price * quantityToList
        expirationTime: Math.round(new Date().getTime() / 1000),
        quantity: quantityToList,
})
```
and I'm encountering an error when entering a large `price * quantityToList` for startAmount:
![image](https://user-images.githubusercontent.com/25206712/140104334-e4e31934-eca5-4320-b0e1-a005ea245fb8.png)

As you can see, `2500` was converted into `2.5e+21` scientific notation in the library/api for the `basePrice` field. I have 5 of these assets and want to list each of them for 500 eth, thus `5 * 500`.

Is there any way to allow for larger numbers to be entered here? It works just fine if I list them for 100 eth each, e.g. `startAmount: 100 * 5`.

**Comment by hoangchien97** [comment]
i am having the same problem when price is greater than or equal to 1000. you have resolve it yet ? pls support me @chanzer0

**Comment by hoangchien97** [comment]
<img width="1235" alt="Screen Shot 2022-03-07 at 14 19 58" src="https://user-images.githubusercontent.com/38011123/156985750-3692c8eb-72fc-41d5-a72b-a038248ae9c8.png">

This is my code:
const res = await seaport.createSellOrder({
        asset: {
          tokenId: options.token_id,
          tokenAddress: options.asset_contract_address,
          schemaName: options.schema_name
        },
        accountAddress: options.account_address,
        paymentTokenAddress: options.payment_token_address,
        startAmount: options.price * 1
      });

**Comment by esteban-OpenSea** [comment]
Hello, for this issue you need to use the unit amount. For instance, use Eth and not wei when setting prices. Also, it should be small numbers, no scientific notation is allowed. Let me know if that worked for you.

**Comment by hoangchien97** [comment]
i has created a new project and createSellOrder basic then it work, but old project still error above. Can you tell me where it could go wrong ? Thanks @esteban-OpenSea
