### ISSUE TITLE
npm install --save opensea-js fails

### ISSUE THREAD

**Issue by valeriagrazzini** [ProjectOpenSea/opensea-js#228]
I am trying to install opensea sdk but it fails:

npm ERR! npm ERR! gyp ERR! node -v v16.13.0
npm ERR! npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! npm ERR! gyp ERR! not ok

I've also tried with node version 14.18.1 and I get the same error. Please which node version is supported? I can not run the 8 version since is too old!!

**Comment by Ignas1337** [comment]
I am having the same problem.

**Comment by cchyung** [comment]
Unfortunate as it is you need to use `yarn` to install the library.

**Comment by valeriagrazzini** [comment]
Yes, using yarn it works

Il ven 5 nov 2021, 17:58 Conner Chyung ***@***.***> ha
scritto:

**Comment by esteban-OpenSea** [comment]
Glad to hear you found a workaround for this! Please follow the latest issue on this here: https://github.com/ProjectOpenSea/opensea-js/issues/471
