### ISSUE TITLE
New Collecton stats endpoints docs misreference the actual constructued url

### ISSUE THREAD

**Issue by Tulle121** [ProjectOpenSea/opensea-js#230]
https://docs.opensea.io/reference/retrieving-collection-stats
the official docs say /collections/

Failing: (as per docs suggestion): https://api.opensea.io/api/v1/collections/cool-cats-nft/stats
Working (as per trial/error discovery, remove the plurality): https://api.opensea.io/api/v1/collection/cool-cats-nft/stats

Thank you,

**Comment by Tulle121** [comment]
Apologies if this is the wrong repo. Please direct me accordingly if so.

**Comment by michael-cohen-eth** [comment]
Fixed! Thanks for spotting this out 😄
