### ISSUE TITLE
Error: ADDRESS_NOT_FOUND by createSellOrder

### ISSUE THREAD

**Issue by dala00** [ProjectOpenSea/opensea-js#231]
I'm trying createSellOrder by documented example of Opensea Creatures sell.js.
https://github.com/ProjectOpenSea/opensea-creatures/blob/master/scripts/sell.js

opensea-js@^1.1.5

But such error occurs (rinkeby)

```
Initializing proxy for account: 0xF7e30A3da5a25F3c11d12ec3938F2c953E2a475f
(node:58884) UnhandledPromiseRejectionWarning: Error: ADDRESS_NOT_FOUND: 0xF7e30A3da5a25F3c11d12ec3938F2c953E2a475f
    at MnemonicWalletSubprovider._findDerivedKeyInfoForAddress (D:\users\documents\github\opensea-creatures\node_modules\@0x\subproviders\src\subproviders\mnemonic_wallet.ts:144:19) 
    at MnemonicWalletSubprovider._privateKeyWalletForAddress (D:\users\documents\github\opensea-creatures\node_modules\@0x\subproviders\src\subproviders\mnemonic_wallet.ts:132:37)   
    at MnemonicWalletSubprovider.<anonymous> (D:\users\documents\github\opensea-creatures\node_modules\@0x\subproviders\src\subproviders\mnemonic_wallet.ts:88:39)
```

I checked the function `_findDerivedKeyInfoForAddress` then, there is a loop to find HD key from Derived Key. So stopped at default 1000 loop limit. I increased addressSearchLimit, but same.

Should I find my HD key by this search? If then, I think it becomes more slow on mainnet. Or any other way to execute simply and fast?

**Comment by xavi-99** [comment]
It's happening the same to me.
using 
` "opensea-js": "^1.2.1",`

**Comment by richardWei93** [comment]
same

**Comment by richardWei93** [comment]
> I'm trying createSellOrder by documented example of Opensea Creatures sell.js. https://github.com/ProjectOpenSea/opensea-creatures/blob/master/scripts/sell.js
> 
> opensea-js@^1.1.5
> 
> But such error occurs (rinkeby)
> 
> ```
> Initializing proxy for account: 0xF7e30A3da5a25F3c11d12ec3938F2c953E2a475f
> (node:58884) UnhandledPromiseRejectionWarning: Error: ADDRESS_NOT_FOUND: 0xF7e30A3da5a25F3c11d12ec3938F2c953E2a475f
>     at MnemonicWalletSubprovider._findDerivedKeyInfoForAddress (D:\users\documents\github\opensea-creatures\node_modules\@0x\subproviders\src\subproviders\mnemonic_wallet.ts:144:19) 
>     at MnemonicWalletSubprovider._privateKeyWalletForAddress (D:\users\documents\github\opensea-creatures\node_modules\@0x\subproviders\src\subproviders\mnemonic_wallet.ts:132:37)   
>     at MnemonicWalletSubprovider.<anonymous> (D:\users\documents\github\opensea-creatures\node_modules\@0x\subproviders\src\subproviders\mnemonic_wallet.ts:88:39)
> ```
> 
> I checked the function `_findDerivedKeyInfoForAddress` then, there is a loop to find HD key from Derived Key. So stopped at default 1000 loop limit. I increased addressSearchLimit, but same.
> 
> Should I find my HD key by this search? If then, I think it becomes more slow on mainnet. Or any other way to execute simply and fast?

Can you help to disclose your solution which will becomes more slow on mainnet? thanks

**Comment by jordipolo87** [comment]
Same here, using opensea-js 1.2.7.

**Comment by esteban-OpenSea** [comment]
Hello, are you still running into this issue? Even with the latest sdk version? Make sure to set the default account. You have to assign a default account and unlock it.

**Comment by zWavey** [comment]
> Hello, are you still running into this issue? Even with the latest sdk version? Make sure to set the default account. You have to assign a default account and unlock it.

Yes i am still getting this error. What do you mean by "set the default account"?
