### ISSUE TITLE
tokenMetadata missing from getAssetResponse

### ISSUE THREAD

**Issue by oveddan** [ProjectOpenSea/opensea-js#232]
If you call the opensea api `https://api.opensea.io/api/v1/asset/{tokenAddress}/{tokenId}` via http, you get a field back `token_metadata` which contains the link to the ipfs file where you can retrieve token metadata;  this `tokenMetadata` field is missing from the js api

**Comment by esteban-OpenSea** [comment]
Are you still running into this issue? If so, can you send some screenshots?
