### ISSUE TITLE
Several security issues reported by Snyk open source

### ISSUE THREAD

**Issue by v0n0** [ProjectOpenSea/opensea-js#233]
Do you scan for vulnerabilities on your dependencies? In my current project the Opensea library introduces most of the security issues. I'll be looking into removing it ASAP and just using the API.

Examples:
<img width="503" alt="Screen Shot 2021-11-06 at 2 29 23 PM" src="https://user-images.githubusercontent.com/10123945/140624336-bebabd74-536a-4b97-988e-e45dd0c1cdac.png">
<img width="513" alt="Screen Shot 2021-11-06 at 2 32 19 PM" src="https://user-images.githubusercontent.com/10123945/140624417-f9cc1eb4-346e-4a4b-bc78-0f5916a2a89e.png">
<img width="503" alt="Screen Shot 2021-11-06 at 2 32 30 PM" src="https://user-images.githubusercontent.com/10123945/140624421-bf4c3934-02d1-4e0e-bd5e-6562ffe78c76.png">

(there are more)

**Comment by esteban-OpenSea** [comment]
Are you using the latest version of the SDK?

**Comment by ryanio** [comment]
v6 branch is heavily eliminating and updating dependencies
