### ISSUE TITLE
api.get("/collections) data not returning the same data their official doc try out does

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#234]
When I am using the SDK and use seaport.api.get("/collection) 
the results dont hold the same amount of data it does when using their official documentation try out feature.

I am missing stuff layke payment_tokens, editors and also the stats differ as the floor_price is always returned as 0 when using the SDK unlike the try out feature which shows correct data.

Can anybody explain to me why this is?

**Comment by sreyemnayr** [comment]
Just reported the same re: floor_price to the discord

**Comment by csidi90** [comment]
> Just reported the same re: floor_price to the discord

did you get any response for that yet?

**Comment by wenzhouyang** [comment]
we have same issue

**Comment by NFTylerjet** [comment]
bump. 
having this same issue as well, api returns floor_price as 0 while the test in api docs shows correct price

**Comment by esteban-OpenSea** [comment]
Please follow the latest issue related to this: https://github.com/ProjectOpenSea/opensea-js/issues/465

I will close this one out since it's a duplicate.
