### ISSUE TITLE
createBuyOrder not work

### ISSUE THREAD

**Issue by icoinguide** [ProjectOpenSea/opensea-js#235]
node 8.11
i use the MnemonicWalletSubprovider funciton to init seaport,and use the createBuyOrder function , but nothing happen , no error output,or success, what can i do , i use node 8.11.

**Comment by lynnsir-102** [comment]
Have you solved this problem @icoinguide

**Comment by icoinguide** [comment]
no, you have the same problem ?

**Comment by lynnsir-102** [comment]
> no, you have the same problem ?

Yes, I have the same problem as you

**Comment by icoinguide** [comment]
i talk this  in the discord, but nobody help

**Comment by esteban-OpenSea** [comment]
Are you still running into this issue? As a reminder, please use the latest version of Node and the SDK.
