### ISSUE TITLE
You must approve assets for trading before creating an order

### ISSUE THREAD

**Issue by cchyung** [ProjectOpenSea/opensea-js#236]
Currently running into a problem where I can't approve an asset for sale.  I am trying to approve sale on behalf of another contract through a proxy call.  The proxy signature seems to be generating correctly and  on etherscan (https://rinkeby.etherscan.io/tx/0xde7ee87487b4b678cc94352bfaf23b42e04abce44d3d2581097d1b9108eb21e7#eventlog) you can see that the correct events are getting fired but when I call publishOrder() to create the listing on openSea it gives me the following error: You must approve assets Hole for trading before creating an order

Here's a link to the asset: https://testnets.opensea.io/assets/0x8cfd4fbb3e30030929bcef43fef4ca2fe45659fc/7

**Comment by mehranhydary** [comment]
Did you figure this out?

**Comment by cchyung** [comment]
Yes - two separate resolutions:
1. You must approve the asset to your address's assigned proxy
2. After making the contract call with the order, you have to ensure that the same salt is being used when calling `seaport.publishOrder()`

**Comment by mehranhydary** [comment]
Oh nice... so instead of setting approval for the exchange contract I have to approve it for the assigned proxy?

**Comment by mehranhydary** [comment]
Outstanding! I got it to work. Thanks a ton

**Comment by esteban-OpenSea** [comment]
Great to hear you solved this! I will close this issue out.
