### ISSUE TITLE
Always get http 403 Forbidden error calling /collections and /collection endpoints

### ISSUE THREAD

**Issue by wenzhouyang** [ProjectOpenSea/opensea-js#237]
We have an api key to call /collections and /collection two endpoints. From yesterday afternoon, we got http 403 Forbidden error for every time calling the two endpoints. Do we reach the rate limit and can you tell us how much the rate limit is? Or is this due to opensea service issue?

**Comment by esteban-OpenSea** [comment]
Please follow [this](https://github.com/ProjectOpenSea/opensea-js/issues/86) issue for the latest update on this/

Rate limit is 4/sec
