### ISSUE TITLE
How I get a API Key from opensea?

### ISSUE THREAD

**Issue by river-korbit** [ProjectOpenSea/opensea-js#238]
I found this page 
( https://docs.opensea.io/reference/request-an-api-key )
and I send my request for opensea api key. But There was no response from opensea dev team.
Are you guys have an api key?
If so, how did you get the key??

**Comment by Superpassteque** [comment]
No api key for me they said website is mandatory which i don't understand. seems that only people with money can built

Things get even worst on production. For example I can't even do 1 bid on a asset without triggering the throttle. ( so it's not even rate limited but just inaccessible)

**Comment by river-korbit** [comment]
I got key. thanks.

**Comment by lukaskai** [comment]
Hey @river-korbit, how did you get your key? Maybe you any tips? It's been a few weeks already, but I got no response.
