### ISSUE TITLE
getAssets with provided account address returns empty array

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#239]
I have a metamask wallet connected to opensea and I hold several NFTs on my account. However, when I use the SDK/API to retrieve Assets where I am the owner (my eth address) I get assets: [] <- empty in return

 return this.seaport.api.getAssets({ owner: this.activeAccount.address });
 
 Using this api for a few days now I get more and more frustraded, many things dont work correctly. Can somebody give me a hint?

**Comment by sThReal** [comment]
opensea?.api
        .getAssets(
          {
            owner: 'yourAddr'
            limit: 10,
            offset: 0,
          },
          100,
        )
        .then((res) => console.log(res))

that's seems work to me

**Comment by esteban-OpenSea** [comment]
Hello, are you still running into this issue?
