### ISSUE TITLE
install opensea-js faill

### ISSUE THREAD

**Issue by mcwxxx** [ProjectOpenSea/opensea-js#240]
I have tried to download OpenSea-js using NPM CNPM YARN but failed to download openSea-js. Has anyone encountered this situation?

**Comment by mcwxxx** [comment]
erro log
Error: [opensea-js@1.2.1 › wyvern-schemas@0.10.7 › wyvern-js@github:ProjectOpenSea/wyvern-js#semver:^3.2.1] Run "sh -c git clone git+https://github.com/ProjectOpenSea/wyvern-js.git /Users/machengwei/code/metaItem/pc-metaItem/node_modules/.tmp/412fdaa2-588e-4a65-8f2c-9980275300a1" error, exit code 128

**Comment by mcwxxx** [comment]
Error log
 [opensea-js@1.2.1 › wyvern-schemas@0.10.7 › wyvern-js@github:ProjectOpenSea/wyvern-js#semver:^3.2.1] Run "sh -c git clone git+https://github.com/ProjectOpenSea/wyvern-js.git /Users/xxx/code/metaItem/pc-metaItem/node_modules/.tmp/412fdaa2-588e-4a65-8f2c-9980275300a1" error, exit code 128

**Comment by osc707** [comment]
you need to use `yarn add opensea-js`

**Comment by esteban-OpenSea** [comment]
Please follow this ticket: https://github.com/ProjectOpenSea/opensea-js/issues/471, it's the most recent one regarding this issue!
