### ISSUE TITLE
getOrder with undefined contract / token returns a random order

### ISSUE THREAD

**Issue by cap10bad** [ProjectOpenSea/opensea-js#241]
Issue: 
If you request an order with seaport.api.getOrder and provide undefined values for asset_contract_address and token_id, a totally random order is returned.

Reproduction:
```
const order = await seaport.api.getOrder({
            side: OrderSide.Sell,
            asset_contract_address: undefined,
            token_id: undefined
        });
```

Expected:
An error or no order returned.

Actual:
A random item is returned.

Thank you. Let me know if there's anything else I can provide to help.

**Comment by alex-bormotov** [comment]
Use seaport.api.getOrderLegacyWyvern - works for me
