### ISSUE TITLE
createBundleOrder - wEth sent from my wallet but no bids / offers appearing in opensea dashboard

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#242]
I used the SDK to create a bundlebuyorder for a collection. Before doing so I converted some ETH into wETH and then when I called the function createBundleBuyOrder, wEth got sent from my account like it should. Somehow, I dont see any bids / offers placed when I login to opensea.io but the funds are gone lol. What am I missing here?

**Comment by DeanShaked** [comment]
Is it still down ?
I still get the "Asset not tradable" error..

**Comment by codingbeast** [comment]
make sure add schemeName in asset you can check the schemaName in opensea nft page
asset: {
                  tokenId,
                  tokenAddress,
                  schemaName: "ERC1155"
                },
