### ISSUE TITLE
every attempt to create an order returns Error: API Error 429: Message: {"detail":"Request was throttled."}

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#243]
Do I need to have an API key in order to create orders using the SDK / API ? Everytime I try to create an order for an asset or a bundled order I get this response:

Error: API Error 429: Message: {"detail":"Request was throttled."}

**Comment by esteban-OpenSea** [comment]
@machieajones hit it on the nail! Although sometimes there might be some issues with the site. Follow this thread: https://github.com/ProjectOpenSea/opensea-js/issues/86
