### ISSUE TITLE
createSellOrder Have a problem

### ISSUE THREAD

**Issue by mcwxxx** [ProjectOpenSea/opensea-js#244]
![image](https://user-images.githubusercontent.com/58460343/142190307-22b468cf-4b6f-4cf8-819f-f87b5b3eb8ad.png)
The order of network calls on OpenSea looks like this
![image](https://user-images.githubusercontent.com/58460343/142190603-3f94345e-902d-4820-b951-68d7ce4af1d6.png)
but this is the order of network calls on my application
![image](https://user-images.githubusercontent.com/58460343/142190814-ed622077-325b-4cef-ad11-df8a6030c843.png)
This error was reported
![image](https://user-images.githubusercontent.com/58460343/142190975-b38a5184-dcc2-4e04-ab80-589fea584e04.png)
i don't know what went wrong

**Comment by mcwxxx** [comment]
Unable to call the Metamask signature

**Comment by esteban-OpenSea** [comment]
Are you still running into this issue? As a reminder, please use the latest versions of the SDK and Node.
