### ISSUE TITLE
What is the actual rate limit when using an API key?

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#247]
I have an API key but still get throttled, Im wondering what is the actual rate limit? Its not documented anywhere, at least I can't find it.

**Comment by samparmenter** [comment]
They won't say.

**Comment by bmayen** [comment]
I've heard 250ms, but it's completely inconsistent. I've also seen feedback stating that 429s may be thrown when there's a problem with the platform. So it seems impossible to effectively build something around this. Barring reliable implementation and documentation, my strategy is falling back to hammering away and catching/retrying whenever a 429 is returned. I would much rather be more respectful in the approach, but opensea doesn't make that easy.

**Comment by krjii** [comment]
I think the limit is 2 requests per second.
