### ISSUE TITLE
Can't see my NFT on OpenSea

### ISSUE THREAD

**Issue by iboxgithub** [ProjectOpenSea/opensea-js#252]
My collection: 0x1165e51243aa6bc8f32085156595398d07636e52
is visible on Rarible: https://rinkeby.rarible.com/token/0x1165e51243aa6bc8f32085156595398d07636e52:2?tab=bids

But not on OpenSea, is there a reason for that?

thanks for your help!

**Comment by DoctorWhoFR** [comment]
same issue seen today no answer on discord.

**Comment by esteban-OpenSea** [comment]
The Rinkeby link you sent doesn't show collection either. Seems like you don't have any collections on OpenSea as well.

Also, what you mentioned is the wallet address. Check out these docs: https://docs.opensea.io/reference/retrieving-collections.

If you want to search by asset and look up collection name, check this out: https://docs.opensea.io/reference/getting-assets
