### ISSUE TITLE
Cloud flair restrictions on multiple endpoints again

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#253]
I am receiving unauthorized error messages pointing towards cloud flare restrictions again on several endpoints. Anyone else experiencing these issues?

**Comment by velmoorthi** [comment]
Site under maintenance https://status.opensea.io/
Hoping everything will function shortly.

**Comment by esteban-OpenSea** [comment]
Closing this since out. Recently helped csidi90 with API issues!
