### ISSUE TITLE
Error: Trading for this asset ([object Object]) is not yet supported. Please contact us or check back later!

### ISSUE THREAD

**Issue by owklama** [ProjectOpenSea/opensea-js#254]
The following endpoints `seaport.createBundleBuyOrder` , `seaport.createBuyOrder` are still returning the same error it was before the server maintenance...

Is there any update regard to this issue ?
Is there a way to workaround this endpoint via provider or something ?

**Comment by esteban-OpenSea** [comment]
Hi, are you still running into this issue? As a reminder please use the latest SDK and version of Node
