### ISSUE TITLE
overcome offset >= 10000

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#255]
If the only way to retrieve all assets of a collection is to use pagination using offsets, why does the API return errors if you try to fetch more than 10K assets? Most of the highly traded collections have more than 10K assets. Is there some kind of a workarround or will this get fixed anytime soon?

Regards

**Comment by gsmachado** [comment]
I'm also interested in this.

It would be great to know more details of the rationale behind this limitation... and also, if the team has plans to change it any time soon.

**Comment by Njerschow** [comment]
Minor workaround -> use the flipScan flag to go from highest token_id to lowest (i think order_by = pkey).

Still limited to getting collections of max size 20k

**Comment by esteban-OpenSea** [comment]
Pagination past 10k is not yet supported

I will go ahead and close this issue since it's a duplicate. Please follow this ticket for the latest updates on this issue: https://github.com/ProjectOpenSea/opensea-js/issues/438
