### ISSUE TITLE
createBuyOrder API Error 404: Not found

### ISSUE THREAD

**Issue by kula0826** [ProjectOpenSea/opensea-js#256]
Error: API Error 404: Not found. Full message was '{"success":false}'

does anyone have a clue?

**Comment by amzfcy** [comment]
same problem

**Comment by cre-mer** [comment]
I'm getting this with createSellOrder:
`API Error 404: Not found. Full message was '{"success":false}'`

**Comment by nighca** [comment]
Hey guys I've got this error, too, while calling `createSellOrder`.

After a little digging in, I found that it is caused by some latency for OpenSea to fetch the asset's detail. So there is a workaround: put off the `createSellOrder` call until the asset is ready (we can check if the asset's ready with `seaport.api.getAsset`).

The workaround code is like this:

```ts
class {

  async waitForOpenseaAssetReady(seaport: OpenSeaPort, tokenAddress: string, tokenId: string) {
    while (true) {
      try {
        await seaport.api.getAsset({ tokenAddress, tokenId })
        break // the asset is ready, exit the loop
      } catch (e) {
        // `API Error 404 ...` means asset not ready
        if (!/API Error 404/.test(e + '')) throw e // If other errors found, that's not expected, just throw
        await delay(5) // retry after 5 seconds
      }
    }
  }

  async createOpenseaOrder(nft: NFTItemWithContract, account: string, price: number) {
    // prepare params...
    await this.waitForOpenseaAssetReady(seaport, tokenAddress, tokenId)
    return seaport.createSellOrder({ ... })
  }

}

```

**Comment by esteban-OpenSea** [comment]
Hello, is everyone still having this issue? As a reminder, please use the latest version of the SDK and Node.

**Comment by nighca** [comment]
@esteban-OpenSea Could u plz link here the related PR, which is expected to solve this issue.

**Comment by muhtashimali** [comment]
Getting this error on createSellOrder

Error: API Error 404: Not found. Full message was '{"success":false}'

const seaport = new OpenSeaPort(provider, {
    networkName: Network.Rinkeby,
});

const listing = await seaport.createSellOrder({
    asset: {
    tokenId,
    tokenAddress,
    },
    quantity: 1,
    accountAddress,
    startAmount,
    expirationTime
});
Log of object:
{
asset: {
tokenId: '2252',
tokenAddress: '0x230B03Af0e9917B89FDFECc4380E70c15371297b'
},
quantity: 1,
accountAddress: '0x1a7a4121d7527f9ccf538fa748a73455d8c5005a',
startAmount: 0.5,
expirationTime: 1650340141
}

**Comment by muhtashimali** [comment]
> Hey guys I've got this error, too, while calling `createSellOrder`.
> 
> After a little digging in, I found that it is (in my case) caused by some latency for OpenSea to fetch the asset's detail. So there is a workaround: put off the `createSellOrder` call until the asset is ready (we can check if the asset's ready with `seaport.api.getAsset`).
> 
> The workaround code is like this:
> 
> ```ts
> class {
> 
>   async waitForOpenseaAssetReady(seaport: OpenSeaPort, tokenAddress: string, tokenId: string) {
>     while (true) {
>       try {
>         await seaport.api.getAsset({ tokenAddress, tokenId })
>         break // the asset is ready, exit the loop
>       } catch (e) {
>         // `API Error 404 ...` means asset not ready
>         if (!/API Error 404/.test(e + '')) throw e // If other errors found, that's not expected, just throw
>         await delay(5) // retry after 5 seconds
>       }
>     }
>   }
> 
>   async createOpenseaOrder(nft: NFTItemWithContract, account: string, price: number) {
>     // prepare params...
>     await this.waitForOpenseaAssetReady(seaport, tokenAddress, tokenId)
>     return seaport.createSellOrder({ ... })
>   }
> 
> }
> ```

@nighca 
I'm getting the same error on fetching asset
        await seaport.api.getAsset({ tokenAddress, tokenId })
