### ISSUE TITLE
429 Error - with API Key

### ISSUE THREAD

**Issue by machieajones** [ProjectOpenSea/opensea-js#259]
Receiving a 429/Failed to fetch error today using the `createBuyOrder` function

`Access to fetch at 'https://api.opensea.io/wyvern/v1/orders/post/' from origin 'http://localhost:9000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I have recently received an API key and it was working yesterday. 

Anyone else encountering the same?

**Comment by IrishVoltik** [comment]
I get maybe same error now, on `createSellOrder`
`Error: API Error 429: Message: {"detail":"Request was throttled."}`

**Comment by joventuraz** [comment]
Same here.

**Comment by velmoorthi** [comment]
same error, 
they mentioned api partial outage, they are fixing on that https://status.opensea.io/
i hope it will be fixed shortly

**Comment by sebastianvaliente** [comment]
Did anyone figure out the root of this issue. I keep getting this as well.

**Comment by huyredfox** [comment]
I have exact same issue

**Comment by esteban-OpenSea** [comment]
For throttled requests, please follow this issue: https://github.com/ProjectOpenSea/opensea-js/issues/86

For CORS issues, this might be a problem with your requests. It says that it failed from the access control (CORS) header on the request. See [this](https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe/43881141#43881141).

**Comment by kaankilic** [comment]
Same here. Any solution?
