### ISSUE TITLE
How to create an asset?

### ISSUE THREAD

**Issue by ysig** [ProjectOpenSea/opensea-js#267]
Hi,

Is there a way to create an asset through this package?
I.e. upload a file (e.g. image) and metadata (description etc) and get a token id, a url etc?

I couldn't understand by looking at the package.

**Comment by ktalebian** [comment]
Looking for this endpoint as well.

**Comment by esteban-OpenSea** [comment]
You mean an endpoint for a single asset correct?

You can create a bundle of assets: https://github.com/ProjectOpenSea/opensea-js#creating-bundles
