### ISSUE TITLE
opensea-js accountAddress?

### ISSUE THREAD

**Issue by asafd11** [ProjectOpenSea/opensea-js#269]
trying to learn how to use opensea-js going over https://github.com/ProjectOpenSea/opensea-js#buying-items
as pic show i am requesting/need an account address and am not sure what it is?
 is it my meta mask id
or opensea api key
or infura project key ?
am really not sure wich one it is
where do i get the account address?

**Comment by esteban-OpenSea** [comment]
Account address is the wallet address, typically your waller. I encourage you to continue reading the documents! Check this out too: https://metamask.zendesk.com/hc/en-us/articles/360015488791-How-to-view-your-account-details-public-address
