### ISSUE TITLE
Error: API Error 400: Buy order maker has too many outstanding orders

### ISSUE THREAD

**Issue by velmoorthi** [ProjectOpenSea/opensea-js#271]
When i call createbuyorder i'm getting error like below 
Error: API Error 400: ['Buy order maker (__OS__HiddenChirpyUakari) (ethereum) has too many outstanding orders.']

do you guys know why its happening?
does any of you guys getting the same?

**Comment by brent1x** [comment]
Hi - I'm getting the same error. Still trying to diagnose the problem - please let me know if you find a solution.

**Comment by CryptusChrist** [comment]
I saw somewhere that you can't have offers outstanding that are 100x your current wallet balance.  Ex. 1 ETH wallet balance = 100 ETH total offers allowed.

**Comment by brent1x** [comment]
> I saw somewhere that you can't have offers outstanding that are 100x your current wallet balance. Ex. 1 ETH wallet balance = 100 ETH total offers allowed.

Interesting. I have zero outstanding offers but am still getting this error returned. Perhaps it is related to the major AWS outage that occurred today?

**Comment by velmoorthi** [comment]
> Hi - I'm getting the same error. Still trying to diagnose the problem - please let me know if you find a solution.

still the same, let me know if you find out.

**Comment by simonare** [comment]
I also have zero outstanding offers but am still getting this error returned. Any progress?

**Comment by tlafargue** [comment]
Experiencing problems with this for days with no solution. Has anyone figured it out ?

**Comment by rcanpahali** [comment]
Yes, same situation here. Still looking for the solution.

**Comment by STRsplit** [comment]
Have been running the calculations and logging to dashboard. Seems the ratio calculation of 10k x wallet balance of WETH is incorrect and inconsistent. Can't find an exact formula that is applied. Any help would be appreciated.

**Comment by Chokeey** [comment]
Did anyone manage to fix it? I've got the same problem!

**Comment by opensea111** [comment]
> When i call createbuyorder i'm getting error like below Error: API Error 400: ['Buy order maker (__OS__HiddenChirpyUakari) (ethereum) has too many outstanding orders.']
> 
> do you guys know why its happening? does any of you guys getting the same?

I saw in opensea update files, that it works like this: wallet balance x 10000 = possible offers to make

but i tested it out and from experience I would say its half of that. I used 1eth wallet, and after 3-5k bids, got wallet outsatdning error. 

but it aslo depends on how fast u bid. I bid 150offers per min, so may be that i get this error faster. 

If you want opensea api keys for bot, dm on discord, got 13 on sale. CEO of Brazzers#9133

**Comment by SourceSafe** [comment]
This is impacting me also - it has been a long running problem. Makes things impossible as once the error throws your wallet is toast!

**Comment by tlafargue** [comment]
> This is impacting me also - it has been a long running problem. Makes things impossible as once the error throws your wallet is toast!

You should be able to place more orders when some of your other orders expire.

**Comment by SourceSafe** [comment]
> 

Yes you say 'should' and I agree but I have zero orders outstanding ..

**Comment by SourceSafe** [comment]
> > This is impacting me also - it has been a long running problem. Makes things impossible as once the error throws your wallet is toast!
> 
> You should be able to place more orders when some of your other orders expire.


Yes you say 'should' and I agree but I have zero orders outstanding ..

**Comment by SourceSafe** [comment]
Two things going on here 

Yes this is expected behaviour when you are over your limit and it does kick in.

But it also kicks in on wallets way before they hit their limit. My wallet has zero bids and is still affected .

It is a bug .

**Comment by Toeplitz** [comment]
Same kind of issue. Getting 
API Error 400: ['Outstanding order to wallet balance ratio exceeds allowed limit.'] when trying to submit orders.

All my orders are expired several days ago.

**Comment by simonare** [comment]
All my offers are expired but this is my third day that 3 of my wallets are having same error.

**Comment by rcanpahali** [comment]
OS developers are new grad. I'm very sure about it.

**Comment by imekinox** [comment]
Still happening, no orders and getting the same error.

**Comment by csidi90** [comment]
I have 0 open orders for almost 24 hours and still get this error message. Seems like they are not able to free up the available orders in realtime or anything close to it. Looks like they just randomly click a button once or twice per day (if at all) that resets all users limits

**Comment by itsthedoom** [comment]
Thank you for surfacing this issue.
We deployed performance changes last week that have resolved this issue.

No updates are required on the developer side; you can place your order as usual.

Please let us know if you still see the timeout error

**Comment by JBowen** [comment]
> 

yes, im getting the error right now. 

what is the expected functionality of this? is there a limit? if so, what is it?

**Comment by SourceSafe** [comment]
I don’t think this is fully fixed. It is better then before but it still snows the error on occasions ..

**Comment by chrisackermann** [comment]
@JBowen @SourceSafe Thanks for the heads and sorry that you're still hitting some error responses.

Can you please confirm that it's the same error response that you were experiencing before?  And are there any additional details on repro that triggers the error response that you could share?

**Comment by STRsplit** [comment]
@chrisackermann - Still receiving the error: `API Error 400: ['Outstanding order to wallet balance ratio exceeds allowed limit.']` which is incorrectly assessed at 450x - 600x wallet balance not the 1000x stated in the docs. Every few days the limits are correctly assessed, but lately its almost always at 500x wallet balance.

**Comment by velmoorthi** [comment]
> @chrisackermann - Still receiving the error: `API Error 400: ['Outstanding order to wallet balance ratio exceeds allowed limit.']` which is incorrectly assessed at 450x - 600x wallet balance not the 1000x stated in the docs. Every few days the limits are correctly assessed, but lately its almost always at 500x wallet balance.

Yes mate you are right. But I figured something, after reaching 500x ratio wait 2-4mins and then try it will then go upto 800x ratio and then wait 2-4mins and try it will go upto 1000x. Let me know if it works.

**Comment by STRsplit** [comment]
@velmoorthi - giving it a shot, thanks for the tip. Will report back how it goes.

**Comment by esteban-OpenSea** [comment]
@STRsplit , is this working properly for you now?

**Comment by SourceSafe** [comment]
I was getting this today when I clearly had more exposure available to me . The limits kicked in to early when I was only 75% into my allowance

**Comment by csidi90** [comment]
I dont have that issue anymore, was accurate lately. Now I can not backtest this due to other errors the API has since April 1st where all requests to create an order get throttled immediatly with over 80K seconds delay (check newest issue)

**Comment by SourceSafe** [comment]
Hi
I noticed it was more accurate. Allows me to reach 100% now.

Can you please confirm that even if we hit the limit the previous bids are still valid.

Some feel that hitting the 100% invalidates placed bids for that wallet . Can you confirm that by design this is not the case and by design if we hit the 100% then existing bids are valid?

**Comment by velmoorthi** [comment]
> We made a few changes on order validation logic - is this resolved for everyone?

All my request getting throttled and saying expired api key. What we can do now? Please assist asap

**Comment by SourceSafe** [comment]
Hi 
This Bug is still **not** fixed. I keep track of my bid count and exposure and I'm getting this bug when I'm < 75% of my allowance

It is  'better' than  before (it threw when I had 0 Bids outstanding) but it has not been fixed properly.

**Comment by SourceSafe** [comment]
Hi
There does not seem to be any rhyme or reason behind this bug. It is intermittent and non deterministic. I think it has something to do with the volume of bid history. If I use a brand new wallet then I have no issues for a while but then it throws the same error eventually. I also get 'too may orders query timed out' which is possibly related. My hunch is it's simply having difficulties calculating current exposure under load and throws the error as a result.  At times it throws when I'm at only 75% capacity. Today it is throwing this error on all my wallets (2) at only 30%  capacity... these are now unusable.

**Comment by SourceSafe** [comment]
I am getting this all the time .... Any ETA for the fix?

API Error 400: ['Outstanding order to wallet balance ratio exceeds allowed limit.']

**Comment by SourceSafe** [comment]
Here is the error accompanied with the 'time out' message.. hope this helps you solve the bug - I suspect this is related. Fix the timeout and you probably fix the BUG

 ['Cannot validate the order. Query times out due to too many existing orders.']
Error 400: ['Cannot validate the order. Query times out due to too many existing orders.']

**Comment by SourceSafe** [comment]
No - still throws error when I’m only 75% of allowance
