### ISSUE TITLE
Transfer NFT on Polygon without gas

### ISSUE THREAD

**Issue by romanspotpower** [ProjectOpenSea/opensea-js#277]
Hi,
I'm trying to build a node.js app wth opensea-js that will transfer (gifting) nft to some wallet.
The NFT is on Polygon network.

I get the following error when trying to transfer:
`{ code: -32000, message: 'insufficient funds for gas * price + value' }`

Is this because you don't support Polygon network in opensea-js or it maybe other issue?

Transfers on Polygon in Opensea are gas less so why I get this error?

Please help.

**Comment by scottcanoni** [comment]
I do believe it is because OpenSea does not yet support Polygon.  This may help: https://github.com/ProjectOpenSea/opensea-js/issues/72

**Comment by romanspotpower** [comment]
Hi,
I saw this thread https://github.com/ProjectOpenSea/opensea-js/issues/72.
The issue is that I can get the NFT information the only issue I have is transfering the NFT from my address (the owner) to other address.
I believe that the issue is with opensea-js library not fully supporting Matic network.

**Comment by CombainerA19** [comment]
@romanspotpower

**Comment by alexburciu** [comment]
ping

**Comment by esteban-OpenSea** [comment]
Check this out: https://docs.opensea.io/docs/polygon-basic-integration
