### ISSUE TITLE
API Key for testnet?

### ISSUE THREAD

**Issue by HaoCherHong** [ProjectOpenSea/opensea-js#279]
Hi,
The testnet api endpoint doc says the endpoint requires API Key.
https://docs.opensea.io/reference/retrieving-orders-testnets-1
So I used my API Key for production and found out the API key for production is invalid for testnets.
But I cannot find where do I request an API key for testnet use.

As the doc says, there should be a page where I can find one:
```
Don't have an API Key? Hop on over to our testnets /events endpoint page, where we've supplied a default API key for developers to use in this documentation reference
```
But the link in the doc seems broken. And I tried https://testnets.opensea.io/events but it gave me 404.

Please help and thank you.

**Comment by hubba-bubba-776** [comment]
Have you find a solution? Have the same issue ..

**Comment by HaoCherHong** [comment]
> Have you find a solution? Have the same issue on Rinkeby. Tho working fine on mainnnet
> 
> > Error: API Error 401: Unauthorized. Full message was '"Invalid API key"'

Hey, yes. I asked them to send me testnet key in the same form for requesting live key
https://docs.opensea.io/reference/request-an-api-key
And they sent me the key to use in testnet.
Cheers

**Comment by hubba-bubba-776** [comment]
Thanks, dude :)

**Comment by HaoCherHong** [comment]
Oh you'll want to write that you're requesting testnet key in the Project Description field.

**Comment by esteban-OpenSea** [comment]
Please send us an email at [api@opensea.io](mailto:api@opensea.io) and we will help you out!
