### ISSUE TITLE
Port to ethers.js?

### ISSUE THREAD

**Issue by bnolan** [ProjectOpenSea/opensea-js#28]
Web3.js pulls in a bunch of stuff to my bundle and breaks my build (has an old version of the `websocket` module that has a .git folder in it and confuses heroku).

**Comment by alexanderatallah** [comment]
@bnolan we're wondering about this! when i search package-lock though, or do `npm list websocket`, i don't see `websocket`. We've never seen any heroku issues. How did you get this installed?

**Comment by bnolan** [comment]
Heya, I finally managed to remove web3 from my server side code, everything deploys much faster now, and I really enjoy the ethers.js api. This is the issue that convinved me to try and get rid of web3:

https://github.com/ethereum/web3.js/issues/1178

I'm going to try and implement in-world item buying, which will use the opensea api - but I'd love to remove my web3 dependency - so if you decide to make the migration, I would be heaps stoked.

**Comment by parthagarwal** [comment]
Interested in using this API and my project is currently using ethers... I'd also like to not have to add a web3 dependency!

**Comment by joeyiny** [comment]
Would love to see a port to ethers.js as well

**Comment by overfocus** [comment]
upvoting ethers port

**Comment by DaShak** [comment]
+1 upvote

**Comment by BenjaminGrabow** [comment]
+1 upvote

**Comment by fabdarice** [comment]
+1

**Comment by Nisthar** [comment]
+1

**Comment by eugenioclrc** [comment]
+1

**Comment by brennanfife** [comment]
@sunwrobert any thoughts on this? Ethers.js has surpassed Web3.js as the more popular Ethereum-Javascript library since this SDK was initially created and is also ~5x smaller than Web3.js according to Bundlephobia ([web3](https://bundlephobia.com/package/web3@1.7.0) vs [ethers](https://bundlephobia.com/package/ethers@5.5.4))

**Comment by zendevil** [comment]
+10^100

**Comment by 0xshawn** [comment]
+1

**Comment by DaShak** [comment]
was this solved @esteban-OpenSea ?

**Comment by brennanfife** [comment]
@esteban-OpenSea is it safe to assume now there’ll be no refactoring done in the near future to use ethers?

**Comment by esteban-OpenSea** [comment]
This is an issue request we want to implement!

**Comment by kebian** [comment]
Pretty desperate for this tbh.

**Comment by talentlessguy** [comment]
has anyone partially ported to ethers? or started porting

**Comment by kebian** [comment]
> 



> has anyone partially ported to ethers? or started porting

I found this, which seems to be an official ethers version of their library.
https://github.com/ProjectOpenSea/seaport-js
