### ISSUE TITLE
Have official API, getting rate limited (throttled) - what is the api's rate limit?

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#282]
I made all the steps in order to program a tool which provides opensea with liquidity and generate fees for them but they are not able to tell what is the official rate limit. I am tired of getting limited on every other request. I want to place a bunch of orders for multiple collection assets and I always run into rate limits. I dont want to sleep for 10 seconds after every request, what is the official limit rate? Anybody knows?

**Comment by jordipolo87** [comment]
Also interested in know the API rate limit, hope someone can answer this question... :)

**Comment by koin-marian** [comment]
Me too. Hello? Nobody replies here after 29 days?

**Comment by peduarte** [comment]
I was told it's 5 requests per second, but not clear if it's to a specific endpoint. 

I'm getting throttled left, right and centre, and it has made my project completely unusable. AND I have an API key. 

Would be nice if we could at least get a response from one of the members here.

**Comment by esteban-OpenSea** [comment]
API rate limits are 4/sec! If you are in need of an api key, please apply here: https://docs.opensea.io/reference/request-an-api-key
