### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by Iroh-Omolola** [ProjectOpenSea/opensea-js#285]
Access to XMLHttpRequest at 'https://testnets-api.opensea.io/assets?asset_contract_address=0xF42029DD93A9B20805152b804114380d6acba959&order_direction=asc' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by faizan-karigar** [comment]
Facing the same issue.

**Comment by lewis-kori** [comment]
Seems like they're ignoring this issue for some reason.
I raised the same [here](https://github.com/ProjectOpenSea/opensea-js/issues/210#issuecomment-993412498) in another similar open issue

**Comment by noahlozevski** [comment]
This isnt a problem with the api, this is a problem with your requests. It says exactly that it failed from the access control (CORS) header on the _request_. See [this](https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe)

**Comment by Iroh-Omolola** [comment]
Help me with solutions@noahlozevski

**Comment by NotScar** [comment]
They ignore the issue because it's not an issue caused by them, but caused mainly by how you've setup the request, for more information search on stackoverflow or on google in general: "CORS Access Control Allow Origin"

**Comment by lewis-kori** [comment]
@Iroh-Omolola I found two solutions to this but they aren't very straightforward.

1. if you're using nextjs/nuxtjs you could make those API calls server-side through `getServerSideProps` or `asyncData` respectively
2. you can also move your API calls to a backend server. In my case, I made a HTTP client using python so I call opensea using that and relay the results to my frontend.

check out [this StackOverflow](https://stackoverflow.com/a/43881141/11461118) answer to understand the cors error.

**Comment by Iroh-Omolola** [comment]
Thank you all.
