### ISSUE TITLE
Can't access images from API served by Google Cloud Storage in China

### ISSUE THREAD

**Issue by hboon** [ProjectOpenSea/opensea-js#3]
It looks like Google Cloud Storage isn't accessible in China so returned by the OpenSea API can't be downloaded. e.g. https://storage.googleapis.com/opensea-prod.appspot.com/0xf5b0a3efb8e8e4c201e2a935f110eaaf3ffecb8d/5057.png

Is there a way around this?

**Comment by alexanderatallah** [comment]
Interesting, we tested it in Shanghai in July and it was working, but yeah I'm not sure why it wasn't blocked like other google CDNs. If you can't use a proxy, there's no immediate workaround, but we'll add a task to our queue now to make one!

**Comment by hboon** [comment]
Thanks. Do you have an ETA? Even the order of magnitude like days, weeks, etc would be helpful, so we can make plans.

**Comment by alexanderatallah** [comment]
@hboon thinking 2 weeks, for an approximate ETA

**Comment by hodlmodl** [comment]
@alexanderatallah Does this technology allow you to actually create your market place for ERC721's on your own domain or is it leveraged by the opensea site?

**Comment by hodlmodl** [comment]
I'm trying to figure out whether to try and recreate an opensea like market for my site or would it be easier to just leverage the API's from the opensea market and view it through my website?

**Comment by dfinzer** [comment]
@hodlmodl The SDK allows you to create your own marketplace! You can use all of the OpenSea marketplace functionality, like creating auctions, buying items, etc. directly on your own website. Let us know if you have any trouble.

**Comment by hodlmodl** [comment]
@dfinzer OK awesome.  Do you still have to pay the opensea fees when using it? And also can you use this marketplace for a custom private ethereum blockchain, not mainnet or test?

**Comment by dfinzer** [comment]
If you use our orderbooks, we take a 2.5% fee on successful sales, but you also get to set your own buyer and seller fees that go to you (so if you want to charge a 5% fee on successful sales, you can do that as well)

We leverage https://github.com/ProjectWyvern for the underlying protocol. To run on a private Ethereum blockchain, you would need to deploy the Wyvern contracts on your blockchain and run your own orderbooks (the OpenSea fee would not apply in this case). Happy to provide more guidance there if that's something you're interested in!

**Comment by hodlmodl** [comment]
Thanks a lot.  I’d love to learn more about how to put up an instance of projectwyvern for my private ETH chain. Where would I find guidance on the steps required for that. @devinfinzer

On Nov 4, 2018, at 3:33 PM, Devin Finzer <notifications@github.com<mailto:notifications@github.com>> wrote:


If you use our orderbooks, we take a 2.5% fee on successful sales, but you also get to set your own buyer and seller fees that go to you (so if you want to charge a 5% fee on successful sales, you can do that as well)

We leverage https://github.com/ProjectWyvern for the underlying protocol. To run on a private Ethereum blockchain, you would need to deploy the Wyvern contracts on your blockchain and run your own orderbooks (the OpenSea fee would not apply in this case). Happy to provide more guidance there if that's something you're interested in!

**Comment by hodlmodl** [comment]
Right on looking forward to reading it.

Cheers,
HodlModl

On Nov 7, 2018, at 12:06 PM, Devin Finzer <notifications@github.com<mailto:notifications@github.com>> wrote:


@hodlmodl<https://github.com/hodlmodl> We'll be putting together some docs on this in the next week or so, but currently there isn't a comprehensive guide. At a high level, it would require deploying the Wyvern contracts to your private testnet and creating your own orderbook server. You can read more about how Wyvern works here: https://github.com/ProjectWyvern and we're also happy to answer questions and help out on our Discord channel (https://discord.gg/ga8EJbv)

**Comment by hboon** [comment]
@alexanderatallah any luck going with this?

**Comment by alexanderatallah** [comment]
@hboon it's in progress! @jordanmessina will send you a test

**Comment by jordanmessina** [comment]
@hboon we're working on this now. Would you be willing to help us test? We're trying to test the following URLs in China: [image 1](https://storage.googleapis.com/opensea-rinkeby/0x16baf0de678e52367adc69fd067e5edd1d33e3bf/504.svg) and [image 2](https://rinkeby-storage.opensea.io/0x16baf0de678e52367adc69fd067e5edd1d33e3bf/504.svg). image1 should get blocked by the firewall and image2 should work. 🤞

**Comment by hboon** [comment]
@jordanmessina sorry just back from holidays (got the email). Will check and report back.

**Comment by James-Sangalli** [comment]
@hboon do you have a Chinese VPN to test it on?

**Comment by hboon** [comment]
@James-Sangalli I asked Wen to help. Have replied to Jordan’s mall earlier :)

**Comment by alexanderatallah** [comment]
@hboon @James-Sangalli Just wanted to post an update - we added the CDN last week, so images should be showing up fine in China! Let me know if there are any issues - going to close this issue now though.

**Comment by James-Sangalli** [comment]
Verified this working, thanks @alexanderatallah
