### ISSUE TITLE
'Outstanding order to wallet balance ratio exceeds allowed limit.

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#305]
I am getting this error and I dont know why, today is the first time I am seeing this. Can anyone elaborate on this?

**Comment by rcanpahali** [comment]
Hi, I have same issua and still looking for fix.

**Comment by dani69654** [comment]
Same here.
Once the buy order is signed by the user, the SDK calls this endpoint to post it:

`${apiBaseUrl}${openseaConstants.ORDERBOOK_PATH}/orders/post/` but that call fails with the error message reported above.

**Comment by simonare** [comment]
Same here, all my offers are expired but still getting this error.

**Comment by esteban-OpenSea** [comment]
Hello, are you still running into this issue? As a reminder please use the most recent SDK and Node version.
