### ISSUE TITLE
500 Internal servor error

### ISSUE THREAD

**Issue by fran6brg** [ProjectOpenSea/opensea-js#308]
Did someone encountered this issue ?

![image](https://user-images.githubusercontent.com/31159436/146687638-cc3a2c4b-bd85-4ffd-96e7-ed34717ebcaf.png)

**Comment by underswitch** [comment]
Can confirm I am getting constant errors when trying to upload svgs to the "Create NFTs" page after clicking "Create"

`[500] Error occurred while processing your request. Please try again later. Error id: 0eb2dead70f340d09e8b408d0d82975b`

**Comment by esteban-OpenSea** [comment]
Hello, is this still an issue for you? And are you getting them in the last cursor page? Check out this similar issue: /event API returns 500 internal server error on last used cursor
