### ISSUE TITLE
CORS error after invoking getOrder SDK method 

### ISSUE THREAD

**Issue by Verrok** [ProjectOpenSea/opensea-js#310]
Hello!

I issued with this when I try to invoke getOrder SDK method
```
Access to fetch at 'https://api.opensea.io/wyvern/v1/orders/?asset_contract_address=0x07bbdaf30e89ea3ecf6cadc80d6e7c4b0843c729&limit=1&side=1&token_id=63' from origin 'https://opensea.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Does someone have the similar issue and/or it's fix?

**Comment by faizan-karigar** [comment]
also getting cors error on open api's

**Comment by amzfcy** [comment]
the same

**Comment by Haugen** [comment]
Having the same issue over here. Haven't been able to find a solution yet.

**Comment by sayhicoelho** [comment]
Have you tried to set `X-API-KEY` in headers?

**Comment by Verrok** [comment]
> Have you tried to set `X-API-KEY` in headers?

Forgot to close this issue. Sending requests with API keys works propeply

**Comment by allenchuang** [comment]
@sayhicoelho  @Verrok - how do we set the `X-API-KEY` if i'm calling directly using the SDK?

```
const orderResponse: Order = await seaport.api.getOrder({
  side: OrderSide.Sell,
  asset_contract_address: tokenAddress,
  token_id: tokenId,
});
```

**Comment by Verrok** [comment]
> @sayhicoelho @Verrok - how do we set the `X-API-KEY` if i'm calling directly using the SDK?
> 
> ```
> const orderResponse: Order = await seaport.api.getOrder({
>   side: OrderSide.Sell,
>   asset_contract_address: tokenAddress,
>   token_id: tokenId,
> });
> ```

You need to specify apikey while you creating `OpenSeaPort` instance, e.g.
```
const seaport = new OpenSeaPort(window.ethereum, {
    networkName: "main",
    apiKey: "<your key>"
  })
```
