### ISSUE TITLE
getOrders() don't returns an ordered list

### ISSUE THREAD

**Issue by Ghijo1** [ProjectOpenSea/opensea-js#311]
Hi everyone,

in order to fetch the purchase offers I used the SeaPort getOrders function:

   const {orders: ordersBuy, countBuy} = await seaport.api.getOrders ({
         asset_contract_address: "xxx",
         token_id: "yyy",
         side: OrderSide.Buy
     })

obviously instead of "xxx" and "yyy" I entered the correct values.
The problem is the "ordersBuy" list of objects is almost never sorted.
I tried to insert token_ids instead of token_id and insert it before the contract address but I didn't solve the problem.
Thanks so much

**Comment by esteban-OpenSea** [comment]
Hello, are you still running into this issue? As a reminder, please update to the latest SDK and Node version.
