### ISSUE TITLE
Rest API dart wrapper

### ISSUE THREAD

**Issue by copypasteearth** [ProjectOpenSea/opensea-js#312]
Hi, i created a Dart wrapper that people can use in Flutter apps. Everything is done except testnet, which I'll probably get to after the holidays.

https://pub.dev/packages/opensea_dart

**Comment by esteban-OpenSea** [comment]
Although we love seeing what developers are working on, this isn't an issue related to the SDK or API. I do encourage you yo share in our [dev discord](https://discord.com/channels/397566282729390110/434175585745633280)!
