### ISSUE TITLE
ERROR: Project ID required.  What does that mean?

### ISSUE THREAD

**Issue by Marc477** [ProjectOpenSea/opensea-js#313]
I'm just following the tutorial on the main page to load a provider in read-only and then check an asset balance.

I load the provider on infuria mainnet.
Then I get "Project ID is required" as error when calling seaport.getAssetBalance
What does that mean? In the doc there is no parameter Project ID, only the asset object (which i loaded successfully with seaport.api.getAsset) and the accountAddress, which i guess is the wallet address of the user ??

This is the function that cause the error: https://projectopensea.github.io/opensea-js/classes/OpenSeaPort.html#getAssetBalance

**Comment by Marc477** [comment]
Ok apparently this goes through infura so i need an account and project. I created one on infura.io. But now I have a new error when calling the same function getAssetBalance :
Unable to get current owner from smart contract

What is that?

**Comment by esteban-OpenSea** [comment]
Hello, just wanted to check in and see if you are still having this issue? This is a duplicate ticket, so I will close. Please refer to this case in order to get the latest updates: https://github.com/ProjectOpenSea/opensea-js/issues/83
