### ISSUE TITLE
change to flashbot with opensea-js

### ISSUE THREAD

**Issue by asafd11** [ProjectOpenSea/opensea-js#316]
hello am trying to change to flashbot and am not sure how to do it
createing openseaport like this right now:
const mnemonicWalletSubprovider = new MnemonicWalletSubprovider.MnemonicWalletSubprovider
  ({
    mnemonic: MNEMONIC,
    baseDerivationPath: BASE_DERIVATION_PATH,
  });

  const network =
    NETWORK === "mainnet" || NETWORK === "live" ? "mainnet" : "rinkeby";
  const infuraRpcSubprovider = new RPCSubprovider({
    rpcUrl: isInfura
      ? "https://" + network + ".infura.io/v3/" + NODE_API_KEY
      : "https://eth-" + network + ".alchemyapi.io/v2/" + NODE_API_KEY,
  });

  const providerEngine = new Web3ProviderEngine();
  providerEngine.addProvider(mnemonicWalletSubprovider);
  providerEngine.addProvider(infuraRpcSubprovider);
  providerEngine.start();

  //providerEngine.max_gass_fee=200;

  const seaport = new OpenSeaPort(
    providerEngine,
    {
      networkName:
        NETWORK === "mainnet" || NETWORK === "live"
          ? Network.Main
          : Network.Rinkeby,
      apiKey: YOUR_API_KEY,
    },
    (arg) => console.log(arg)
  );

i tryed to replace this part :

const authSigner = Wallet.createRandom();
  const flashbotsProvider = await FlashbotsBundleProvider.create(
  infuraRpcSubprovider, // a normal ethers.js provider, to perform gas estimiations and nonce lookups
  authSigner // ethers.js signer wallet, only for signing request payloads, not transactions
)

  const providerEngine = new Web3ProviderEngine();
  providerEngine.addProvider(mnemonicWalletSubprovider);
  providerEngine.addProvider(flashbotsProvider);
  providerEngine.start();

but this not working 😫
anyone here done it befor ? 
work with flashbot and opensea sdk?

**Comment by esteban-OpenSea** [comment]
Hello, are you still running into this issue?

**Comment by nickvarterian** [comment]
Hello, I am running into the same issue. Is there anyway to use the opensea sdk with flashbots relay? @esteban-OpenSea
