### ISSUE TITLE
TypeError: Cannot read property 'metadata' of undefined

### ISSUE THREAD

**Issue by markusmak** [ProjectOpenSea/opensea-js#318]
Trying to send an order, but has metadata undefined error. Please advise! Thanks:)
![Screenshot 2022-01-03 at 12 16 58 AM](https://user-images.githubusercontent.com/54108129/147901311-b8fea7f5-bcf7-48ad-9b1e-a9e68258bb8b.png)
![Screenshot 2022-01-03 at 12 17 09 AM](https://user-images.githubusercontent.com/54108129/147901321-6f8e8691-c498-45f3-9e26-08e1ae82121f.png)

**Comment by esteban-OpenSea** [comment]
Hello, are you still having this issue? As a reminder, please use the latest SDK and Node versions
