### ISSUE TITLE
I can not add a new Payment tokens!!!

### ISSUE THREAD

**Issue by smkplus** [ProjectOpenSea/opensea-js#319]
I want to create an NFT Game in which users can buy NFT with my custom token.
for example, Decentraland has a token called Mana. as you can see they listed the NFT with Mana!

![image](https://user-images.githubusercontent.com/16706911/147934901-37fbcfde-9b26-41c5-a5b8-41aceee4da80.png)

I tried to add the new token but it seems this solution is deprecated!

Payment tokens
These tokens can be used to buy and sell your items.

![image](https://user-images.githubusercontent.com/16706911/147934493-89912cec-4821-432d-b01f-dabd8a831582.png)

![image](https://user-images.githubusercontent.com/16706911/147934698-53ebabfd-7467-4193-abd8-c56dd2648dfb.png)

**Comment by esteban-OpenSea** [comment]
This seems to be working for me. Are you still having this issue?

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/99999009/163591242-56fb7734-d053-4670-a80c-262e1f05433d.png">

**Comment by zepp-pp** [comment]
Also no 'add token' selection on Arbitrum ERC1155 token
