### ISSUE TITLE
API Error 403: Unauthorized when sending a single offer

### ISSUE THREAD

**Issue by migsdeving** [ProjectOpenSea/opensea-js#324]
`Already approved enough currency for trading
Order hashes match
(node:23408) UnhandledPromiseRejectionWarning: Error: API Error 403: Unauthorized.`

Is this because I don't have an API key? Opensea claims you don't need one to a certain limit of requests. 
Do they provide you an API if you're just developing a bot or do they only give out keys to "legit" projects?

**Comment by derwaldgeist** [comment]
Is this library even actively maintained? I can't understand that an issue like that is open for weeks, without any response.

**Comment by esteban-OpenSea** [comment]
Hi, I apologize for the delay! Please apply for an API key here: [typo in readme?](https://docs.opensea.io/reference/request-an-api-key)

**Comment by derwaldgeist** [comment]
Ok, Thanks for your fast response. I just applied again.
