### ISSUE TITLE
[SDK] Update SDK to use new resolved fee recipient

### ISSUE THREAD

**Issue by sunwrobert** [ProjectOpenSea/opensea-js#331]
Modify `makeBundleBuyOrder`, `makeBundleSellOrder`, `makeBuyOrder`, `makeSellOrder` to read from `asset.collection.resolvedOrderFeeRecipient` and populate the feeRecipient in the order to be that.

**Comment by esteban-OpenSea** [comment]
@sunwrobert , have these changes been made?

**Comment by sunwrobert** [comment]
they have not, actually forgot the context of this..

**Comment by sunwrobert** [comment]
Think this is no longer relevant
