### ISSUE TITLE
Error resolving metadata image

### ISSUE THREAD

**Issue by prasad-kumkar** [ProjectOpenSea/opensea-js#332]
trying to get the image validated https://rinkeby-api.opensea.io/asset/0xbde4d099da0d780f8c519ea9d0c6a4118191645c/50861132186756506624178836675162951190216332378860869098644345490426120110080/validate/
throws error `ImageConversionException: SVG Conversion failure for conversion`

Metdata - https://chainid-metadata.herokuapp.com/one/50861132186756506624178836675162951190216332378860869098644345490426120110080

Image - https://chainid-metadata.herokuapp.com/one/prasad/image

Opensea - https://testnets.opensea.io/assets/0xbde4d099da0d780f8c519ea9d0c6a4118191645c/50861132186756506624178836675162951190216332378860869098644345490426120110080

I tried using image_data instead of image, still getting the same error

**Comment by esteban-OpenSea** [comment]
Are you still having this issue?

As a reminder, SVG for mobile is not supported yet but will be soon!

**Comment by prasad-kumkar** [comment]
Solved, it was due to cors
