### ISSUE TITLE
execution reverted - web3-provider-engine used by this SDK

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#334]
I keep getting execution reverted errors from the web3-provider-engine that is used by this SDK and I dont know why this happens due to lack of proper logging in the SDK. Anyone else having issues?

`Error: execution reverted
nftapi_1    |     at WebsocketSubprovider._handleSocketMessage (/app/node_modules/web3-provider-engine/subproviders/websocket.js:121:18)
nftapi_1    |     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
nftapi_1    |     at WebSocket.emit (events.js:400:28)
nftapi_1    |     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:720:20)
nftapi_1    |     at Receiver.emit (events.js:400:28)
nftapi_1    |     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:414:14)
nftapi_1    |     at Receiver.getData (/app/node_modules/ws/lib/receiver.js:346:17)
nftapi_1    |     at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:133:22)
nftapi_1    |     at Receiver._write (/app/node_modules/ws/lib/receiver.js:69:10)
nftapi_1    |     at writeOrBuffer (internal/streams/writable.js:358:12)
nftapi_1    |     at Receiver.Writable.write (internal/streams/writable.js:303:10)
nftapi_1    |     at TLSSocket.socketOnData (/app/node_modules/ws/lib/websocket.js:795:35)
nftapi_1    |     at TLSSocket.emit (events.js:400:28)
nftapi_1    |     at addChunk (internal/streams/readable.js:293:12)
nftapi_1    |     at readableAddChunk (internal/streams/readable.js:267:9)
nftapi_1    |     at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
`

**Comment by antLongjumping** [comment]
There might be many reasons, but the core to not get reverted is to have your own nodes or node provider that can provide you with a service, where your transaction will be picked and processed by miners in milliseconds, to be sure to be in the next block. As far as I know, this is the only one, but let's share if you have something else: https://zmok-io.medium.com/no-more-reverted-transactions-in-nft-war-6c4a18e02037

**Comment by esteban-OpenSea** [comment]
Just wanted to check in, are you still having issues with this?
