### ISSUE TITLE
Getting 1020 Error when trying to access API

### ISSUE THREAD

**Issue by jamiewtam** [ProjectOpenSea/opensea-js#335]
Whenever I try to access the opensea API I get the response 'error code: 1020'

**Comment by escwdev** [comment]
I'm encountering the same issue when last time I used the same script (a month or so ago) it worked fine. Interestingly, it works if I open the endpoint in browser. Not sure what changed on their end.

I'm waiting on an API key at the moment so these are non-API key REST calls to the public endpoints (collections and assets).

**Comment by travisw** [comment]
Same here. It seems some endpoints work and others return the 1020 error. I _am_ using an API key.
Sounds like some kind of CloudFlare issue.

**Comment by escwdev** [comment]
Yeah it's unfortunate, hope it's resolved soon. In the meantime, I wrote up a work around using Puppeteer at least.

**Comment by bujoralexandru** [comment]
Me too, https://api.opensea.io/api/v1/asset/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb/2 the following GET request works from a browser context, but does not work from a plain request done from a web server.

**Comment by esteban-OpenSea** [comment]
Are you still having issues with this?

**Comment by caijamin** [comment]
> Are you still having issues with this?

Yes, it's still happening

**Comment by sirkitree** [comment]
Also having this problem making requests from a VR platform, but works fine in a browser.

**Comment by ihssaneDev** [comment]
Hi , i have the same issue when i try to get asset from opensea api
