### ISSUE TITLE
 Error: Trading for this asset (ERC721) is not yet supported. Please contact us or check

### ISSUE THREAD

**Issue by WUBOSS** [ProjectOpenSea/opensea-js#338]
seaport.fulfillOrder 
but
Error: Trading for this asset (ERC721) is not yet supported. Please contact us or check

**Comment by esteban-OpenSea** [comment]
Are you still having this issue? I don't have a lot of context for this issue but please ensure it's a valid asset and that you are using the latest SDK and Node version.
