### ISSUE TITLE
cors error while fetching events

### ISSUE THREAD

**Issue by rapendivya** [ProjectOpenSea/opensea-js#339]
i'm getting cors error

'https://api.opensea.io/api/v1/events?account_address=0x99a901abb995f849b2b12b01e46f4d45ae50dd47&event_type=successful&only_opensea=false&offset=0&limit=300' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by davidthomasparks** [comment]
Same here.

**Comment by chrisco255** [comment]
Also getting this.

**Comment by esteban-OpenSea** [comment]
Are you using a valid API key? If you don't have one you can apply here: https://docs.opensea.io/reference/request-an-api-key

**Comment by esteban-OpenSea** [comment]
Also check this solution: https://github.com/ProjectOpenSea/opensea-js/issues/285#issuecomment-1008575614
