### ISSUE TITLE
Bulk offers

### ISSUE THREAD

**Issue by Escartel** [ProjectOpenSea/opensea-js#341]
Hello, guys I am trying to make a bulk offer bot, I have seeing that everything shown in the opensea-js is to retrieve just one NFT of a determine collection, but what if I want to retrieve all assets with one characteristic of a collection? How would I do that?
For example, from X collection just retrieve assets with the characteristic background Yellow
Thanks!

**Comment by esteban-OpenSea** [comment]
Check this out: https://docs.opensea.io/reference/getting-assets
