### ISSUE TITLE
How to Increase Bidding Speed on Assests?

### ISSUE THREAD

**Issue by MetalGear-cmd** [ProjectOpenSea/opensea-js#345]
So I have created a Bidding Not using opensea-js. Everything works great but there is just one thing bothering me. It's the speed of bidding, right now my bot only makes 15-20 offers per minute. I have seen people claiming more then 100 bids per minute. How can I boost my bot speed? Any help would be appreciated.

**Comment by esteban-OpenSea** [comment]
Please email api@opensea.io for help with this. Closing since it is not an issue related to SDK
