### ISSUE TITLE
Wallet balance to order ratio exceeded - ZERO active orders on opensea

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#347]
So why am I getting this error again even tho I dont have a single bid or sell order open? I have plenty of eth in my wallet as well.. This keeps getting annoying if you have to deal with this day by day.

**Comment by suspiciousseaweed** [comment]
Having the same issue

**Comment by esteban-OpenSea** [comment]
Just wanted to follow up on this. Are you still running into this issue?

**Comment by esteban-OpenSea** [comment]
Remember to upgrade to the latest SDK and Node version
