### ISSUE TITLE
Content Security Policy (CSP) for cached animation_uri pages

### ISSUE THREAD

**Issue by 0xprincess** [ProjectOpenSea/opensea-js#348]
I guess it's not the most appropriate place to start an issue, because it's an OpenSea backend-related one. But it's affecting the frontend as a result.

Our case is the following: we want to make an on-chain interactive (html + js) nft, so the html + **inline** js will be generated inside smart contract and put into the animation_uri metadata field.

It almost works, however, we faced an issue: opensea caches generated html page to its own severs (`https://storage.opensea.io/files/<hash>.html`), and when cached html is requested, server adds the following CSP headers: `default-src 'self'; script-src 'none'; ...` which makes impossible to use any inline js code, and thus impossible to display mentioned nft on an item page.

Can it be resolved somehow?

**Comment by esteban-OpenSea** [comment]
Just wanted to follow up on this, are you still having the same problem?
