### ISSUE TITLE
GasPriceAddition not working for fulfillOrder

### ISSUE THREAD

**Issue by cagrisungur** [ProjectOpenSea/opensea-js#354]
Hi there.

I'm trying to set custom ``gasPriceAddition `` for ``fullfillOrder`` method. I read tons of documents and issues and never get a correct answer.

Any update or any suggestion?

**Comment by clovisjohn** [comment]
They removed the feature, if you want to use it you must use opensea-js 1.1.11 or below

**Comment by esteban-OpenSea** [comment]
Please upgrade to the latest version of the SDK and Node
