### ISSUE TITLE
GET request giving 403 error

### ISSUE THREAD

**Issue by hugos** [ProjectOpenSea/opensea-js#356]
I'm trying to retrieve the asset info from a specific collection using the asset endpoint.

Example:

`https://api.opensea.io/api/v1/asset/0x1a92f7381b9f03921564a437210bb9396471050c/2000/?format=json
`

Now, if you open that on your browser, it works flawlessly, but on your app or postman it just gives a 403 error by CloudFlare. 

What is going on and how do I fix this? Any ideas?

**Comment by kubtseas** [comment]
Yup same here, started having the issue this morning (was working fine last night and made no changes since)

**Comment by hugos** [comment]
> Yup same here, started having the issue this morning (was working fine last night and made no changes since)

Ok so, was it working yesterday without the need for an API key?

If this is the case I find it poor on their part not to warn developers on their social media and/or status page.

**Comment by derwaldgeist** [comment]
Same here. I only get a CloudFlare 403.

**Comment by Funst3r** [comment]
Guys they mentioned it in discord and wrote it in the documentation. They had many bots using theire API so they decided that everyone need to request an API key.

**Comment by hugos** [comment]
> Guys they mentioned it in discord and wrote it in the documentation. They had many bots using theire API so they decided that everyone need to request an API key.

I do have one, yet it doesn't work still.

Can you access it with postman using an api key?

**Comment by esteban-OpenSea** [comment]
You need to request an API key. You can request it here: https://docs.opensea.io/reference/request-an-api-key

**Comment by derwaldgeist** [comment]
I requested mine ages ago. When will they be processed?!
