### ISSUE TITLE
https://api.opensea.io/api/v1/asset_contract/ API returns HTTP 403 unless API-KEY is specified.

### ISSUE THREAD

**Issue by Brucbbro** [ProjectOpenSea/opensea-js#361]
As per title, this is not how the API is documented and how it used to work a couple days ago. (docs page says, "Your **optional** API Key")
But now, unless I add the API KEY to the headers I'll get a 403 status code.

Is this intended? Is this temporary? My API key is badly rate limited (4 rps) and as such it will significantly hinder my dapp

**Comment by bujoralexandru** [comment]
Same issue, every request is 403 unless executed from a browser.

**Comment by nftchance** [comment]
Having the same issue here.

**Comment by derwaldgeist** [comment]
Same here when trying to access assets.

**Comment by Funst3r** [comment]
No issue, this is intended. You need to get an API key.
Depending on the project it takes more or less. Could take ours or weeks.
They check the need and decide wether you get a key or not.

**Comment by Brucbbro** [comment]
> No issue, this is intended. You need to get an API key. Depending on the project it takes more or less. Could take ours or weeks. They check the need and decide wether you get a key or not.

While it might very well be intended, it is still an issue, as it worked differently up to ~2 weeks ago.
API key header is also marked as optional in the docs.
![image](https://user-images.githubusercontent.com/3133958/153153406-daf1a5a2-d7f7-4f05-9c77-f6b17b158739.png)

This means a lot of users can't access the API and others who can are now rate limited according to their API key instead of the "public" rate limit.

**Comment by esteban-OpenSea** [comment]
An API key is required, you can request one here: https://docs.opensea.io/reference/request-an-api-key
