### ISSUE TITLE
Unable to add opensea-js 1.2.8 with yarn 3.x

### ISSUE THREAD

**Issue by SMLaursen** [ProjectOpenSea/opensea-js#365]
With Yarn 3.1.1, yarn add opensea-js@1.2.8 fails while transitively importing wyvern-schemas.
I'm a little unsure what the actual failure is, as I got a few variations and I'm not that well versed in this tech-stack.
Everything is in order when using Yarn 1.22.17 for my project.

I'm using node 16.13.1 and Windows 10

**Comment by Funst3r** [comment]
How did you make it work with node 16? Most of us had to downgrade to node 8 or 10. Try to downgrade and please post your result if it helps.

**Comment by SMLaursen** [comment]
I eventually got it to work with Yarn 3.1.1, by packing wyvern-Schemas with Yarn 1.22.17 and then forcing a resolution to that, i.e.;
```
"resolutions": {
    "wyvern-schemas": "file:./packages/wyvern-schemas-v0.13.0.tgz"
},
```
I had node-errors initially and had to downgrade, not sure how I got around those. Best bets are that using Yarn 3.1.1 actually fixes it or that I fiddled with MSBuild.

**Comment by sunela** [comment]
Fixed.
This is no longer an issue with version 2.0.0, I can pull it in using Yarn 3.1.1 and Node 16 without any additional hoops.

**Comment by SMLaursen** [comment]
FIXED! 
This is no longer an issue in version 2.0.0
