### ISSUE TITLE
seaport.transferAll returns "cb is not a function"

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#366]
I keep getting this error even tho I am passing all required parameters.

`seaport.transferAll({fromAddress: sdasdada, toAddress: sdasdasd, assets: [{tokenId:1, tokenAddress: 232342424])`

**Comment by Irantwomiles** [comment]
I am getting the same issue, when trying to fulfill and order.
` const transaction = await seaport.fulfillOrder({order, accountAddress: 'account_address'});`

**Comment by Irantwomiles** [comment]
@csidi90 were you able to fix this problem by any chance?

**Comment by csidi90** [comment]
No i had to downgrade to 1.8 again

**Comment by Irantwomiles** [comment]
@csidi90 any luck with this issue? I still haven't found any answers.

**Comment by esteban-OpenSea** [comment]
Closing out since upgrading to the most recent sdk and node version should fix this issue
