### ISSUE TITLE
Wyvern post order: Server Error (500)

### ISSUE THREAD

**Issue by tymmesyde** [ProjectOpenSea/opensea-js#370]
Version 2.0.0

I get a `Server Error 500` when trying to execute `postOrder` from seaport api
```
const confirmedOrder = await seaport.api.postOrder(orderToJSON(orderWithSignature), 3)
 ```
 It wasn't happening yersterday, i updated the package today to see if the issue was resolved with lastest version

**Comment by SMLaursen** [comment]
Similar issue here when calling createSellOrder()

**Comment by tymmesyde** [comment]
Resolved
