### ISSUE TITLE
fulfillOrder throws error: Must match target

### ISSUE THREAD

**Issue by Kukiezi** [ProjectOpenSea/opensea-js#371]
I've been trying to buy NFT using this SDK. As of right now when I am trying to perform this action, I am getting the following error:

`Error: Error matching this listing: Must match target. Please contact the maker or try again later!`

Not sure, what can be the source of this error.

This is how I initialize seaport:
```
const provider = new HDWalletProvider({
  mnemonic: {
    phrase: MNEMONIC
  },
  providerOrUrl: `https://mainnet.infura.io/v3/${INFURA_API_KEY}`
});

const seaport = new opensea.OpenSeaPort(
    provider, {
        networkName: opensea.Network.Main,
        apiKey: API_KEY
    },
    (arg) => {
        console.log("From OpenSeaPort CB:");
        console.log(arg);
    }
);
```
And buyItem method I created to try performing order. But as of right now it gets stuck at mentioned error.
```
const buyItem = async (contractAddress, tokenId) => {
    const accountAddress = BUYER_ADDRESS;
    const order = await seaport.api.getOrder({
        side: types.OrderSide.Sell,
        asset_contract_address: contractAddress,
        token_id: tokenId
    });

    try {
        const transactionHash = await seaport.fulfillOrder({ order, accountAddress });
        return transactionHash;
    } catch (error) {
        console.log(error);
    }
}
```

Any help or tips are appreciated.

**Comment by gary02** [comment]
same problem

**Comment by gary02** [comment]
> get same error msg when `fulfillOrder` the orders created in Opensea site, while no proplem with those created by opensea-js(v1.2.1).

opensea-js v2.0.0 seem fix this proplem

**Comment by Kukiezi** [comment]
Tjamls @gary02, updating helped.
