### ISSUE TITLE
[question] fulfillOrder doesn't prompt metamask to confirm purchase.

### ISSUE THREAD

**Issue by Kukiezi** [ProjectOpenSea/opensea-js#373]
In this issue I had problems with fulfillOrder working [371](https://github.com/ProjectOpenSea/opensea-js/issues/371)

Now after updating opensea-js to version 2.0 it started working. But something I didn't expect happen and the purchase just happened without prompting my metamask to confirm this and now I got new NFT in my wallet.

Is there a way to force purchase confirmation in Metamask? The same way it happens in OpenSea where you can set gas price etc.

**Comment by JeroenJADS** [comment]
Having the same problem @Kukiezi. I'm using Moralis in combination with OpenSea fulfillOrder, and it instantly completes the transaction. Have you found a solution for this already?

**Comment by esteban-OpenSea** [comment]
Are you using the most recent version of opensea-js (3.0.2)?

**Comment by SimonsOnLine** [comment]
Did opensea-js support approve and sign when send transctions on Metamask?
