### ISSUE TITLE
Unban me on OpenSea Please

### ISSUE THREAD

**Issue by SaucyOfficiale** [ProjectOpenSea/opensea-js#374]
My username is saucyy and address is 0x2c8bc318c3ffed54ef3efb4f5d646d096f628810 I'm really sorry I made fake collections as a joke (didn't know I could get banned) and you removed them from my account. It will never happen again and I have very valuable NFTs on my account I need access to. Learned my lesson. Please unban me I'm worried and need my account back. Thanks.

**Comment by esteban-OpenSea** [comment]
This is not related to an issue on the sdk/api. Please open a support case with the OpenSea support team. https://support.opensea.io/hc/en-us
