### ISSUE TITLE
fulfillOrder Error: Failed to validate buy order parameters.

### ISSUE THREAD

**Issue by Barq17** [ProjectOpenSea/opensea-js#376]
I've been trying to buy asset by invoking `fulfillOrder` method but I'm getting error:

`Error: Failed to validate buy order parameters. Make sure you're on the right network!`

seaport creation code:

```
const seaport = new OpenSeaPort(providerEngine, {
  networkName: Network.Main,
  apiKey: OpenseaAPIKey,
});
```

So network is `Main` and I guess it's right

fulfillOrder code:

```
const orderToBuy = await seaport.api.getOrder({
  side: OrderSide.Sell,
  asset_contract_address: CONTRACT_ADDRESS,
  token_id: tokenId,
});

const transactionHash = await seaport.fulfillOrder({
  order: orderToBuy,
  accountAddress,
});
```

What could be the cause?

**Comment by mlesterdampios** [comment]
im experiencing same problem. 
do you have solution for this?

**Comment by cjkhoo** [comment]
upgrade opensea js 2.0.0 above will solved

**Comment by zWavey** [comment]
im on the latest opensea js and i am still experiencing this, has anyone got a fix yet?
