### ISSUE TITLE
OpenSea-js 2.0.0 : createSellOrder() on Rinkeby leads to a 500 Error without API-Key

### ISSUE THREAD

**Issue by SMLaursen** [ProjectOpenSea/opensea-js#378]
Hi,

When trying to call `createSellOrder()` I get an `500`. I consistently see that the `getOrderCreateWyvernExchangeAddress()` call fails due to throttling, which makes it use a default of `0xdd54d660178b28f6033a953b0e55073cfa7e3744` (Specified in `utils/deployed`) instead of the actual `0x5206e78b21ce315ce284fb24cf05e0585a93b1d9`.

Hardcoding `getOrderCreateWyvernExchangeAddress()` to always return `0x5206e78b21ce315ce284fb24cf05e0585a93b1d9` (without issuing any calls) makes everything work.

I think simple calls, such as these should be allowed through the throttling, possibly by adding retries/wait - and maybe the default of `0xdd54d660178b28f6033a953b0e55073cfa7e3744` also needs to be changed?

**Comment by alexanderatallah** [comment]
Is this still a problem? we switched over to the new exchange today and there shouldn't be throttling on the exchange address (if there is, that's a bug). cc @sunwrobert

**Comment by sunela** [comment]
![image](https://user-images.githubusercontent.com/88385740/154838244-6a0fd47f-d4b1-49ae-9424-f4d39dd6b37d.png)

I'm still getting throttled on the `https://testnets-api.opensea.io/wyvern/v1/exchange/?` request (Here shown with https://github.com/ProjectOpenSea/opensea-js/pull/382, such that it eventually succeeds)

**Comment by sunela** [comment]
But now at least the default `0xdd54d660178b28f6033a953b0e55073cfa7e3744` is the same as what is returned by `https://testnets-api.opensea.io/wyvern/v1/exchange/?`

**Comment by SMLaursen** [comment]
![image](https://user-images.githubusercontent.com/7354598/154838490-7579ca61-fbe1-4b33-8426-0c8e2e27ad40.png)

I'm still getting throttled on the https://testnets-api.opensea.io/wyvern/v1/exchange/? request (Here shown with https://github.com/ProjectOpenSea/opensea-js/pull/382, such that it eventually succeeds)

But now at least the default `0xdd54d660178b28f6033a953b0e55073cfa7e3744 `is the same as what is returned by `https://testnets-api.opensea.io/wyvern/v1/exchange/?`

**Comment by alexanderatallah** [comment]
@SMLaursen we just updated the caching config for testnets - can you try again?

**Comment by SMLaursen** [comment]
> @SMLaursen we just updated the caching config for testnets - can you try again?

Hmm, I'm still being throttled, see below. This was captured using vanilla 2.0.1 in an Incognito window.
![image](https://user-images.githubusercontent.com/7354598/155084416-873d5924-8aa7-40db-a22f-38017bff674b.png).

**Comment by esteban-OpenSea** [comment]
@SMLaursen , just wanted to follow up and see if you are still having this issue?

**Comment by SMLaursen** [comment]
Hi Esteban

Thanks for getting back to me. I still get an 429 on the Exchange call (See below). 
But as the currently used fallback now points to the working exchange-contract, the rest of the (sell) flow appears to be working as intended.

But when you need to migrate to a new exchange contract again, I'm pretty convinced we'll end up getting 500s again due to this. 

![image](https://user-images.githubusercontent.com/7354598/156511178-e473bdb2-743b-4518-9b81-2055f0338c48.png)

**Comment by esteban-OpenSea** [comment]
So besides the 429's everything else is working? Just want to confirm. Also, are you using the most recent version of opensea-js?

**Comment by SMLaursen** [comment]
Yes, everything is working for now - I believe It'll first become an issue when needing to migrate to a new exchange-contract again (where the 429s will cause the then outdated default contract to be read instead of the new contract-address from your servers). I'm currently "stuck" on 2.0.1 due to #421.
