### ISSUE TITLE
Unknown ENS name via opensea results 

### ISSUE THREAD

**Issue by James-Sangalli** [ProjectOpenSea/opensea-js#38]
![photo_2020-03-26_11-37-10](https://user-images.githubusercontent.com/16630514/77598544-3547f400-6f56-11ea-98ea-bc8612f51a30.jpg)

Is this related to the ENS migration?

**Comment by alexanderatallah** [comment]
@James-Sangalli no it's not - ENS keeps your name private by default (though now most names are known on OpenSea), so rainbow tables are responsible for figuring on the names of each name hash. This question mark means that we weren't able to look up the name and the owner hasn't specified it. Owners can specify their ENS names' name-value on the OpenSea page directly.

**Comment by James-Sangalli** [comment]
@alexanderatallah thanks for your reply.

Are you suggesting that the `event NameRegistered(string name, bytes32 label, address owner, uint cost, uint expires)` is no longer used after the migration?

**Comment by alexanderatallah** [comment]
that event gets omitted from the `register()` method, and calling that isn't required I believe (correct me if I'm wrong)

**Comment by James-Sangalli** [comment]
@alexanderatallah indeed. 

`event NameRegistered(string name, bytes32 indexed label, address indexed owner, uint cost, uint expires)` no longer exists. Instead there is only: `event NameRegistered(uint256 indexed id, address indexed owner, uint expires)`
