### ISSUE TITLE
Bithool.NFTs

### ISSUE THREAD

**Issue by hool1475** [ProjectOpenSea/opensea-js#380]

**Comment by hool1475** [comment]
> 

https://github.com/ProjectOpenSea/opensea-js/issues/380

**Comment by esteban-OpenSea** [comment]
No description has been provided. Closing this ticket, if you have any issues with the sdk or api please open one here and provide a detailed description or check the [dev discord](https://discord.com/channels/397566282729390110/434175585745633280).
