### ISSUE TITLE
Getting execution reverted errors when using estimateGas and fulfillOrder

### ISSUE THREAD

**Issue by AGTGreg** [ProjectOpenSea/opensea-js#383]
Hi all,
So the last time I was able to make a successful call to fulfillOrder was at 11-Feb. Since 14-Feb that I re-tried until now, I'm getting `execution reverted` errors.

Here's a part of the code that fails:
```js
    // Make a buy order to match the sell order.
    console.log("Creating matching order...")
    const matchingOrder = seaport._makeMatchingOrder({
        order: sellOrder,
        accountAddress: accountAddress,
        recipientAddress: accountAddress
    })

    const { buy, sell } = openseaUtils.assignOrdersToSides(sellOrder, matchingOrder)
    const referrerAddress = null;
    const metadata = seaport._getMetadata(sellOrder, referrerAddress)
    
    console.log("Estimating gas fee...");
    const gas = await seaport._estimateGasForMatch({ buy, sell, accountAddress, metadata })

    if (gas == null || gas <= 0) {
        console.log("No gas returned...")
        return {"error": "This order is not fullfillable"}
    }

    const gasPrice = await seaport._computeGasPrice().then(data => {
        return data.toNumber()
    });
```

So I got a sample of a sell order were I was successful to estimate the gas for and 2 samples of sell orders where I was unsuccessful and got `execution reverted`. 

What I noticed was that the `howToCall` field of the sell order that was successful was 0 (call) where the other 2 where 1 (delegate). Also the successful order had a `null` `payoutAddress` and the other 2 didn't.

Any ideas why this is happening? Is this a bug?
ps 
 - I have updated opensea-js to version 2.0.0 and the same problem persists.
 - I am using Infura as a provider

**Comment by a290079770** [comment]
hello, v2.0.1 can use

**Comment by esteban-OpenSea** [comment]
Hello is this still an issue? If it is please let me know about the following:

1. Have you upgraded to the latest version of opensea-js?
2. Ensure you have enough for the gas fees. In some cases I've seen 'execution reverted' error = 'not enough for gas fees'
2. Execution reverted usually means there's an issue with the token contract that prevents it from being sent. Consider whether you have an old version of the token. If so, the contract could be outdated, and contact the project for more information.
