### ISSUE TITLE
Install on Unity

### ISSUE THREAD

**Issue by koljanich** [ProjectOpenSea/opensea-js#386]
Hello! How install this great plugin to Unity?

**Comment by esteban-OpenSea** [comment]
Hello, thanks for your question. The issues posted here should be related to the sdk or api. For your question, I recommend asking the [dev discord](https://discord.com/channels/397566282729390110/434175585745633280) channel or check out [this](https://www.youtube.com/watch?v=5rwrL5T-Wso) video.
