### ISSUE TITLE
unlock network / polygon consistent failure

### ISSUE THREAD

**Issue by dcsan** [ProjectOpenSea/opensea-js#387]
On trying to use polygon on opensea, I'm consistently getting an error on the "unlock network" button.
can anyone suggest workarounds for this?

I have both matic (for gas) and weth in my wallet - both on polygon mainnet.

![image](https://user-images.githubusercontent.com/514002/154706763-f5239b51-8c5a-4043-a9bb-371ae256da0e.png)

I know opensea is generally flaky but wondering if this is also due to polygon network congestion? Sometimes it works and sometimes not, and I can't imagine OS codebase is changing that much. 
if that's the case, any pointers on how to monitor network congestion?

**Comment by dcsan** [comment]
also: 
- refresh funds

![image](https://user-images.githubusercontent.com/514002/154722773-00b1cc13-fcdf-48b9-9244-b00a965a810d.png)

**Comment by esteban-OpenSea** [comment]
Just wanted to check in with you. Are you still running into this issue?
