### ISSUE TITLE
opensea-js v2.0.0  code: -32601,   message: 'The method eth_signTypedData_v4 does not exist/is not available'

### ISSUE THREAD

**Issue by asafd11** [ProjectOpenSea/opensea-js#389]
i just update to v2 try to test a bid
and its not working
anyone run in to this problem and know how to fix it?

useing 
`import MnemonicWalletSubprovider from "@0x/subproviders"
`
do i need to change it to other wallet if so which one works with v2?

**Comment by asafd11** [comment]
got help on discord 
update to v2.0.1 fix the problem

**Comment by sunwrobert** [comment]
thanks for the report and the accurate fix!
