### ISSUE TITLE
Order creation failes on the first 429 response of the API GET /wyvern/v1/exchange/

### ISSUE THREAD

**Issue by meena-erian** [ProjectOpenSea/opensea-js#391]
The library seems to repeat the request whenever it receives status ```429 too many requests``` on any endpoint except on this one https://testnets-api.opensea.io/wyvern/v1/exchange/.

I used to use an older version of the library and it used to work perfectly fine until a very recent update where it stared showing some error saying "Expected exchange address to match" so I updates it to the latest version "2.0.0" but now I'm facing other errors.

**Comment by esteban-OpenSea** [comment]
Are you still having this issue? You might be exceeding your rate limit.
