### ISSUE TITLE
sdk without api

### ISSUE THREAD

**Issue by hamedbaftam** [ProjectOpenSea/opensea-js#392]
Hi there, can i use this sdk without api key ?

**Comment by qkqkgy** [comment]
Yes

**Comment by 4myr** [comment]
> Yes

how?

**Comment by esteban-OpenSea** [comment]
It is recommended you apply for an API key for using SDK: https://github.com/ProjectOpenSea/opensea-js#getting-started.

Closing this since it's a more general question and not an issue with the sdk or api.
