### ISSUE TITLE
Execution reverted (API Error 400: ["Transfer calldata doesn't match."]) Trying to create listing

### ISSUE THREAD

**Issue by georgeamine** [ProjectOpenSea/opensea-js#395]
I'm using the vanilla sdk listing function. Can successfully createBuyOrder using my API key however trying to list gives me the following errors.

{ code: -32000, message: 'execution reverted' }

followed by:

API Error 400: ["Transfer calldata doesn't match."]

Please help, thanks!

**Comment by sunela** [comment]
I believe this could be what you're experiencing;
https://github.com/ProjectOpenSea/opensea-js/issues/385

**Comment by SMLaursen** [comment]
I believe this could be your issue : https://github.com/ProjectOpenSea/opensea-js/issues/385

**Comment by esteban-OpenSea** [comment]
Is this still an issue @georgeamine ? Did you try #385 and using the most upgraded opensea-js version?
