### ISSUE TITLE
Question: can non-owner address be used to initialize OpenSeaPort?

### ISSUE THREAD

**Issue by ongchinkai** [ProjectOpenSea/opensea-js#398]
I create a new OpenSeaPort using the following code:

```
const providerEngine = new Web3ProviderEngine();
const walletSubprovider = new PrivateKeyWalletSubprovider(config.privateKey, config.chainId);
providerEngine.addProvider(walletSubprovider);
const rpcSubprovider = new RPCSubprovider({
  rpcUrl: config.rpcEndpoint
});
providerEngine.addProvider(rpcSubprovider);
providerEngine.start();

const seaport = new OpenSeaPort(
  providerEngine,
  {
    networkName: config.network,
    apiKey: config.openseaAPIKey,
  },
  (arg) => console.log(arg)
);
```

And subsequently I create sell orders using code like this:

```
const fixedPriceSellOrder = await seaport.createSellOrder({
  asset: {
    tokenId: req.body.tokenId,
    tokenAddress: req.body.contractAddress,
  },
  startAmount: req.body.startAmount,
  expirationTime: req.body.expirationTime,
  accountAddress: req.body.ownerAddress,
});
```

Can I have `config.privateKey` and `req.body.ownerAddress` be from different accounts (e.g one is deployer account, the other is owner account)? Or must the token owner credentials be used to create OpenSeaPort?

**Comment by esteban-OpenSea** [comment]
I recommend asking this question in our [dev discord](https://discord.com/channels/397566282729390110/434175585745633280), it doesn't seem like it's a bug in opensea-js but more of a question.

**Comment by Haianh9999** [comment]
@esteban-OpenSea I cannot init seaport error is provider.getNetwork is not a function.
