### ISSUE TITLE
MP SDK v2.0 changes

### ISSUE THREAD

**Issue by jtaaa** [ProjectOpenSea/opensea-js#400]
MoonPay uses ethers.js for signing which our SDK does not support. Some changes were made in a custom branch to allow MoonPay to get transaction call data through the SDK (with same validation etc.) and sign and submit themselves. Now that SDK v2.0 is released, the branch needs to be updated to support the merkle validator. Getting those changes merged in will prevent these issues in the future.

**Comment by jtaaa** [comment]
I've updated [MoonPay's branch](https://github.com/ProjectOpenSea/opensea-js/pull/265) of the SDK and published a [new version to NPM](https://www.npmjs.com/package/opensea-js/v/2.0.1-beta.2) for them to use. Once the update is applied, tested and merged by MoonPay this should unblock MP checkout for the ETH primary drop on Monday cc [@Parth](https://ozone-networking.slack.com/team/U02ERSRK8P5) (gotta test it on our side too)
Longer term we want the MoonPay team to use the [Ethers.js' EIP 1193 bridge](https://docs.ethers.io/v5/api/experimental/#experimental-eip1193bridge) for compatibility with the SDK without MP specific changes. We also have a public gas estimation method that can replace the MP specific method exposed on the MP branch.

**Comment by esteban-OpenSea** [comment]
Are you using the latest version of opensea-js and nodejs?
