### ISSUE TITLE
https://api.opensea.io/api/v1/assets blocked by cloudflare

### ISSUE THREAD

**Issue by DiginationTeam** [ProjectOpenSea/opensea-js#401]
It seems that "asset" interface works fine but "assets" is not. 
I saw threads in Nov 2021. Is this ever solved?

**Comment by metaherosuper** [comment]
do you request the api with an API key?
it looks like there are multiple endpoints requiring api keys since last Nov
https://twitter.com/apiopensea/status/1461135305193443334

**Comment by DiginationTeam** [comment]
> do you request the api with an API key? it looks like there are multiple endpoints requiring api keys since last Nov https://twitter.com/apiopensea/status/1461135305193443334

Yes. I did.

In fact in my understanding, The CloudFlare blocking happens before the API key check. It does not reach Opensea server. 
Btw I can call the API with nodejs server code, but it does not work if I embed the SDK in a webapp.

**Comment by sunela** [comment]
> > do you request the api with an API key? it looks like there are multiple endpoints requiring api keys since last Nov https://twitter.com/apiopensea/status/1461135305193443334
> 
> Yes. I did.
> 
> In fact in my understanding, The CloudFlare blocking happens before the API key check. It does not reach Opensea server. Btw I can call the API with nodejs server code, but it does not work if I embed the SDK in a webapp.

Do you care to elaborate on the nodejs server code you are using? I can't seem to get past the 1020s

**Comment by SMLaursen** [comment]
> > do you request the api with an API key? it looks like there are multiple endpoints requiring api keys since last Nov https://twitter.com/apiopensea/status/1461135305193443334
> 
> Yes. I did.
> 
> In fact in my understanding, The CloudFlare blocking happens before the API key check. It does not reach Opensea server. Btw I can call the API with nodejs server code, but it does not work if I embed the SDK in a webapp.

Do you care to elaborate on the nodejs server code you are using? I can't seem to get past the 1020s

**Comment by DiginationTeam** [comment]
> > > do you request the api with an API key? it looks like there are multiple endpoints requiring api keys since last Nov https://twitter.com/apiopensea/status/1461135305193443334
> > 
> > 
> > Yes. I did.
> > In fact in my understanding, The CloudFlare blocking happens before the API key check. It does not reach Opensea server. Btw I can call the API with nodejs server code, but it does not work if I embed the SDK in a webapp.
> 
> Do you care to elaborate on the nodejs server code you are using? I can't seem to get past the 1020s on Orders, Events and Post (internal SDK) endpoints

In fact, I figured out the reason yesterday. 
If you remove all the browser headers (only sending "Host" and "X-API-KEY") from Postman, it will get through. In browser, directly calling the endpoints with axios will work.

I will rather believe this is by design of the team. Although I think they haven't figured out a clear way about how to balance the accessibility and abuse.

**Comment by nawangwe** [comment]
It seems this issue has rendered server side rendered apps useless at the moment.

**Comment by esteban-OpenSea** [comment]
Is this still an issue?
