### ISSUE TITLE
seaport.fulfullOrder gives back "sell.maker.tolowerCase is not a function?

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#405]
Im trying to fulfill a sell order by doing this

`public async fulfillOrders(listings: any) {
    const order = listings[0];

    console.log('trying to fulfil order', order);

    const tx = await this.openseaService.seaPort.fulfillOrder({
      order: order,    //order object coming from /order API unexpired, valid and not finalized
      accountAddress: this.accountService._activeAccount.address,  //my ethaddress
    });

    console.log('fulfil tx', tx);

    return tx;
  }`

the order object I am passing is an order I get from calling the /orders API, so the structure of the object is identical. I dont know how to fix this error I am getting.

**Comment by allenchuang** [comment]
seeing this as well! but for `TypeError: order.taker.toLowerCase is not a function`
I think this has to do with `taker` and `maker` being objects not string.

**Comment by csidi90** [comment]
I had to use the utility function orderFromJSON to parse the api response object to Opensea Order Type. In case anyone has same issue. Its Not documented in their docs

**Comment by MetalGear-cmd** [comment]
> I had to use the utility function orderFromJSON to parse the api response object to Opensea Order Type. In case anyone has same issue. Its Not documented in their docs

How did you solve this issue? can please explain in a little detail?
