### ISSUE TITLE
Remove git-based dependencies

### ISSUE THREAD

**Issue by Jack-Works** [ProjectOpenSea/opensea-js#407]
Hi! We're cleaning up our lock file. I'm wondering if it is possible to not use git-based dependency and release it to npm:

https://github.com/ProjectOpenSea/opensea-js/blob/27d865db7f619492bba0876cadad32ed5e01030e/package.json#L35
https://github.com/ProjectOpenSea/opensea-js/blob/27d865db7f619492bba0876cadad32ed5e01030e/package.json#L42-L43

Thanks!

**Comment by esteban-OpenSea** [comment]
Thanks for bringing this up! We will review this.

**Comment by Jack-Works** [comment]
ping

**Comment by ryanio** [comment]
this is solved now with v6, take a look at the new dependencies :)
