### ISSUE TITLE
API inconsistency HTTP request /orders different schema from SDK getOrders() 

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#408]
I am a little confused as to why the API responses arent unified.

When I use axios or fetch and hit the /orders Endpoint, I get objects that hold properties like "order_hash" however, when I use the sdk getOrders() method I am receiving "hash" instead of "order_hash", this applies for most of the properties. 

Now when I am fetching data using axios and I want to use this data to fulfill orders, it is not working because of the unmatched structure the fulfillOrder() method takes. 

My questions:
1) Why is http request response different structure than the sdk?
2) How would I be able to fulfill  orders with data I get from regular httprequests? Is there any helper method to parse the http request  data objects to OpenseaOrder type used by the SDK?

**Comment by allenchuang** [comment]
there is `orderToJSON` and `orderFromJSON`

**Comment by csidi90** [comment]
there is
import { orderFromJSON } from 'opensea-js/lib/utils';

**Comment by esteban-OpenSea** [comment]
Just wanted to follow up on this, is this still an issue? Even after using the latest opensea-js version?

**Comment by esteban-OpenSea** [comment]
Following up on this, can you send screenshots of a couple of the inconsistencies you're seeing between the api and sdk?
