### ISSUE TITLE
Adding SVG with image url

### ISSUE THREAD

**Issue by hskang9** [ProjectOpenSea/opensea-js#410]
I have a svg generatig server that returns base64 encoded svg data from url param asynchrounously. For example, if you make url like [https://artsandscience.standard.tech/nft/V1/4/0](https://artsandscience.standard.tech/nft/V1/4/0), you get encoded image data that can be displayed in one's browser. I linked this link in my ERC721 metadata, but opensea does not seem that it is able to detect. Does opensea support asynchronous request to the image servers or Should I make the server return the svg code? 

Here are the projects that I refer to:

[SVG generating server](https://github.com/digitalnativeinc/nft-arts)

[NFT metadata](https://github.com/digitalnativeinc/standard-evm/blob/master/contracts/vaults/meter/svg/NFTDescriptor.sol)

**Comment by hskang9** [comment]
@alexanderatallah @Meemaw @taylorjdawson

**Comment by esteban-OpenSea** [comment]
I just checked in with the mobile team, seems like svg is currently not supported but will be supported soon! I will keep this thread open to provide an update.

**Comment by ITzWick** [comment]
> I just checked in with the mobile team, seems like svg is currently not supported but will be supported soon! I will keep this thread open to provide an update.

Oh thanks

**Comment by ManuLpz4** [comment]
My raw SVG (image_data) doesnt work if it contains image tags, any solution?
