### ISSUE TITLE
/event API cursor based pagination throws internal server error on last cursor

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#412]
I was updating code to cursor based pagination for the event api. Using SDK and POstman, the last cursor (next prop) always returns internal server error 500. 

If I have 5 pages of 20 items. so 4 cursor values, everything works until the 4th cursor. Something seems broken there

**Comment by esteban-OpenSea** [comment]
Closing this since it's a duplicate issue you opened here: https://github.com/ProjectOpenSea/opensea-js/issues/433
