### ISSUE TITLE
createSellOrder and /collection/stats API randomly return ERR_ACCESS_DENIED C\n

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#413]
Since March 1st I am getting random error log outputs stating "ERR_ACCESS_DENIED C\n" 

This occurs on createSellOrder() fnc of the SDK at no particular tokens as well as on retrieving data from the /collection/stats API

**Comment by esteban-OpenSea** [comment]
Are you still getting this error?

**Comment by esteban-OpenSea** [comment]
I have not heard back from you in a while, so I will go ahead and close this issue. If you are still running into this issue, let me know and I can reopen.
