### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by bmayen** [ProjectOpenSea/opensea-js#415]
Lots of warnings on deprecated dependencies. Packages should be updated. To name a few:

```
npm WARN deprecated eth-sig-util@1.4.2: Deprecated in favor of '@metamask/eth-sig-util'
npm WARN deprecated eth-sig-util@3.0.1: Deprecated in favor of '@metamask/eth-sig-util'
npm WARN deprecated ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated bignumber.js@6.0.0: Custom ALPHABET bug fixed in v7.0.2
npm WARN deprecated ethereumjs-vm@2.6.0: New package name format for new versions: @ethereumjs/vm. Please update.
npm WARN deprecated axios@0.17.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated ethereumjs-block@1.7.1: New package name format for new versions: @ethereumjs/block. Please update.
npm WARN deprecated ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.

```

There are also deps that point directly at github repos instead of semver. This requires our docker containers to install git just to pull down deps.

**Comment by esteban-OpenSea** [comment]
What version of nodejs are you using?

**Comment by bmayen** [comment]
LTS 16. Curious why would that matter for this?

**Comment by esteban-OpenSea** [comment]
This is a duplicate ticket, please follow [this](https://github.com/ProjectOpenSea/opensea-js/issues/471) ticket for the latest updates on this issue to avoid confusion. I will go ahead and close.

https://github.com/ProjectOpenSea/opensea-js/issues/471

**Comment by bmayen** [comment]
How is this related to #471? This specifically applies to deprecated dependencies and hardcoded github dependencies. #471 is about not being able to install opensea-js due to "idealTree:Crypto: sill idealTree buildDeps" error, which is not the problem described here. I can install it, it's dependencies are just old and poorly defined. This is not a duplicate and should remain open.
