### ISSUE TITLE
Basic example doesn't work

### ISSUE THREAD

**Issue by roman-raizen** [ProjectOpenSea/opensea-js#419]
https://github.com/roman-raizen/os-error

```
npm run start
```

```
TypeError: supportedProvider.send.toString(...).replaceAll is not a function
```

**Comment by pguardiario** [comment]
Same issue here

**Comment by infoseckev** [comment]
this is not a question. It is a bug.

I like how a company worth 13 billion ignore breaking issues in their sdk.

Keep up the good work @esteban-OpenSea

**Comment by jay58** [comment]
Update your Nodejs version to 16+

The error will get resolved.

**Comment by esteban-OpenSea** [comment]
Are you running an upgraded opensea-js along with Node.js v16+?

**Comment by esteban-OpenSea** [comment]
Hi everyone, just wanted to follow up on this.

@jay58 is correct. Using the latest version of node and the sdk should fix this.
