### ISSUE TITLE
fulfillOrder Error: Failed to validate buy order parameters.

### ISSUE THREAD

**Issue by allenchuang** [ProjectOpenSea/opensea-js#420]
I've been trying to buy asset by invoking fulfillOrder method but I'm getting error:

`Error: Failed to validate buy order parameters. Make sure you're on the right network!`

seaport creation code:
```
const seaport = new OpenSeaPort(providerEngine, {
  networkName: Network.Main,
  apiKey: OpenseaAPIKey,
});
```
So network is Main and I guess it's right

fulfillOrder code:

```
const orderToBuy = await seaport.api.getOrder({
  side: OrderSide.Sell,
  asset_contract_address: CONTRACT_ADDRESS,
  token_id: tokenId,
});

const transactionHash = await seaport.fulfillOrder({
  order: orderToBuy,
  accountAddress,
});
```

What could be the cause?

**Comment by allenchuang** [comment]
facing the same issue here: https://github.com/ProjectOpenSea/opensea-js/issues/376 if OP has a solution, please do share! much appreciated!

**Comment by NoamN** [comment]
I have the same issue. Anyone can think of a solution?
Thanks in advance!

**Comment by cchyung** [comment]
Also looking for any updates on this issue.

**Comment by esteban-OpenSea** [comment]
We are looking into this!

**Comment by kaiqiangh** [comment]
any updates on this issue? Thanks

**Comment by zWavey** [comment]
im on the latest opensea js and i am still experiencing this, has anyone got a fix yet?

**Comment by koinfox** [comment]
I am experiencing the same issue, please let me know if anyone got it fixed.
I am using the opensea version 2.0.2

**Comment by koinfox** [comment]
Anyone got it fixed?

**Comment by esteban-OpenSea** [comment]
Hi everyone, I wanted to follow up on this. Just curious, is this still happening when using the latest version of node and the sdk?
