### ISSUE TITLE
Error when compiling next js project after importing OpenSeaPort

### ISSUE THREAD

**Issue by kseikyo** [ProjectOpenSea/opensea-js#421]
Steps to reproduce
1. Create a brand new project with `yarn create next-app`, `npx create-next-app@latest`, or `pnpm dlx create-next-app@latest`
2. Using your package manager of choice, add opensea-js
3. Open `pages/index.js`
4. Add this import `import { OpenSeaPort } from "opensea-js";`
5. Save and run the project

OS: Garuda Linux x86_64
Kernel: 5.16.10-zen1-1-zen
Node version: v16.13.2

Stack trace
```
error - ./node_modules/rustbn.js/lib/index.asm.js:1:1279
Module not found: Can't resolve 'fs'

Import trace for requested module:
./node_modules/rustbn.js/index.js
./node_modules/ethereumjs-vm/dist/evm/precompiles/06-ecadd.js
./node_modules/ethereumjs-vm/dist/evm/precompiles/index.js
./node_modules/ethereumjs-vm/dist/evm/evm.js
./node_modules/ethereumjs-vm/dist/runCode.js
./node_modules/ethereumjs-vm/dist/index.js
./node_modules/@0x/base-contract/lib/src/index.js
./node_modules/wyvern-js/lib/abi_gen/wyvern_d_a_o.js
./node_modules/wyvern-js/lib/wyvernProtocol.js
./node_modules/wyvern-js/lib/index.js
./node_modules/opensea-js/lib/seaport.js
./node_modules/opensea-js/lib/index.js
```

**Comment by SMLaursen** [comment]
Same issue here. **OpenSea-js 2.0.1** didn't have this issue.

**Comment by zackbiernat** [comment]
Adding this to the `next.config.js` fixed the compile error for us 
```
        config.resolve.fallback = {
            ...config.resolve.fallback,
            fs: false,
          };
```
but we still get a bunch of critical dependency errors in the console.
![Screen Shot 2022-03-07 at 4 39 23 PM](https://user-images.githubusercontent.com/29643486/157130154-1fe7dc7b-1d63-4d31-a9ae-43533cb73d2d.png)

**Comment by kseikyo** [comment]
> Adding this to the `next.config.js` fixed the compile error for us
> 
> ```
>     future: {
>         webpack5: true,
>     },
>     webpack: (config, {}) => {
>         config.resolve.fallback = {
>             ...config.resolve.fallback,
>             fs: false,
>           };
>      },
> ```
> 
> but we still get a bunch of critical dependency errors in the console. ![Screen Shot 2022-03-07 at 4 39 23 PM](https://user-images.githubusercontent.com/29643486/157130154-1fe7dc7b-1d63-4d31-a9ae-43533cb73d2d.png)

Thank you, but I was aware of the possible workaround. 

I created the issue as an SDK shouldn't need a workaround just to use it. but this project seems abandoned when it comes to issues and PRs anyway 😔

**Comment by Monte9** [comment]
I ran into this issue as well on our project. The workaround suggested by @zackbiernat worked for us in our Next.JS app. Hopefully someone from OS team will take a look at this and put in a fix!

**Comment by esteban-OpenSea** [comment]
We are looking into this!

**Comment by teawaterwire** [comment]
issue also happening when compiling for Cloudflare workers

**Comment by Priyanshu1609** [comment]
Yes, I am also facing the same issue.
Please fix this.
![image](https://user-images.githubusercontent.com/79529908/167252052-46a11eef-84d0-423f-83ff-0a09181b06a9.png)

**Comment by tudormunteanu** [comment]
In case folks are wondering where the snippet from @zackbiernat actually fits, please see: https://stackoverflow.com/a/67478653/111804

**Comment by esteban-OpenSea** [comment]
Hi everyone, I wanted to follow up on this. Just curious, is this still happening when using the latest version of node and the sdk?

**Comment by SMLaursen** [comment]
> Hi everyone, I wanted to follow up on this. Just curious, is this still happening when using the latest version of node and the sdk?

I still got this issue on OpenSea-js 4.0.1, Node 16.13.1 and Next 12.0.8 - https://github.com/ProjectOpenSea/opensea-js/issues/421#issuecomment-1061214437 still applies

**Comment by sunela** [comment]
> > Hi everyone, I wanted to follow up on this. Just curious, is this still happening when using the latest version of node and the sdk?
> 
> I still got this issue on OpenSea-js 4.0.1, Node 16.13.1 and Next 12.0.8 - [#421 (comment)](https://github.com/ProjectOpenSea/opensea-js/issues/421#issuecomment-1061214437) still applies

Hmm, actually seems to work with Node 16.15.1 - still get the following warn during build though;
`../node_modules/ethers/dist/ethers.min.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`

**Comment by SMLaursen** [comment]
> > Hi everyone, I wanted to follow up on this. Just curious, is this still happening when using the latest version of node and the sdk?
> 
> I still got this issue on OpenSea-js 4.0.1, Node 16.13.1 and Next 12.0.8 - [#421 (comment)](https://github.com/ProjectOpenSea/opensea-js/issues/421#issuecomment-1061214437) still applies

Hmm, actually seems to work with Node 16.15.1 - still get the following warn during build though;
../node_modules/ethers/dist/ethers.min.js Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by Blizard** [comment]
> > Hi everyone, I wanted to follow up on this. Just curious, is this still happening when using the latest version of node and the sdk?
> 
> I still got this issue on OpenSea-js 4.0.1 and Node 16.15.1- [#421 (comment)](https://github.com/ProjectOpenSea/opensea-js/issues/421#issuecomment-1061214437) still applies

Same for me...

**Comment by MuhammadMinhaj** [comment]
> Adding this to the `next.config.js` fixed the compile error for us
> 
> ```
>     future: {
>         webpack5: true,
>     },
>     webpack: (config, {}) => {
>         config.resolve.fallback = {
>             ...config.resolve.fallback,
>             fs: false,
>           };
>      },
> ```
> 
> but we still get a bunch of critical dependency errors in the console. ![Screen Shot 2022-03-07 at 4 39 23 PM](https://user-images.githubusercontent.com/29643486/157130154-1fe7dc7b-1d63-4d31-a9ae-43533cb73d2d.png)

Thank you. it worked. Don't forget to return the Config object from the Webpack method. Use dynamic import when a server error occurs in NextJS.
