### ISSUE TITLE
The method eth_sendTransaction does not exist/is not available

### ISSUE THREAD

**Issue by acechauminh** [ProjectOpenSea/opensea-js#422]
![Screen Shot 2022-03-03 at 15 42 11](https://user-images.githubusercontent.com/68000569/156528377-9ac14f11-65c4-4a35-962e-a860a92cd2a1.png)

when I use function fulfillOrder

**Comment by esteban-OpenSea** [comment]
I haven't heard back from you in a while. I provided a potential solution, so hopefully by now this issue is fixed for you. I'll go ahead and close this.
