### ISSUE TITLE
Someone introduced breaking changes the other day

### ISSUE THREAD

**Issue by pguardiario** [ProjectOpenSea/opensea-js#427]
I'm getting errors like this when I install:
 Authentication failed for 'https://github.com/ProjectOpenSea/ships-log/'

**Comment by chrisackermann** [comment]
@pguardiario Sorry for the headache here; should be good to go now - can you please let us know if you're still running into this issue?

**Comment by pguardiario** [comment]
Thanks @chrisackermann it looks good now.
