### ISSUE TITLE
Transfer vs Sale activity

### ISSUE THREAD

**Issue by quantix-nft** [ProjectOpenSea/opensea-js#428]
Hello, I make this actions on rinkeby:
1) mint on OpenSea
2) transfer to me
3) I sell outside - in my marketplace (transfer to see https://rinkeby.etherscan.io/tx/0x2b58a7d0b1364b801881d9bd8cd9acb045850910c133495cc30e63463eab1c47)
4) in my Item Activity (on opensea) I see the sale as transfer without price, how it comes?

**Comment by esteban-OpenSea** [comment]
Is this still an issue for you? Does it still show as a transfer?

**Comment by quantix-nft** [comment]
Hello, yes, I'm still waiting for an answer :(

Inviato con l'email sicura di [ProtonMail](https://protonmail.com/).

------- Original Message -------
Il venerdì 8 aprile 2022 17:28, Esteban ***@***.***> ha scritto:

**Comment by esteban-OpenSea** [comment]
Hello, I know it's been a while but I wanted to follow up with you and see if this is still an issue. If you can provide more details on steps with screenshots that would be great..

Also, is this only happening with rinkeby for you?
