### ISSUE TITLE
/api/v1/events   occurred_after:extra fields not permitted

### ISSUE THREAD

**Issue by qi62062012** [ProjectOpenSea/opensea-js#429]
testnet : https://testnets-api.opensea.io/events?asset_contract_address=0xc2a2afd4c98aea11064ac4ab9da6ff5476a350f2&occurred_after=1646794914&occurred_before=1646794934&only_opensea=true

**Comment by qi62062012** [comment]
It was normal a few days ago

**Comment by chrisackermann** [comment]
The `occurred_after` field is no longer supported on the /events endpoint as of March 8, as the endpoint has moved to using cursor-based pagination instead.  [This post](https://docs.opensea.io/changelog/cursor-pagination) outlines more details on the context for the change.

**Comment by qi62062012** [comment]
OK
