### ISSUE TITLE
V 3.0.0 TypeError: supportedProvider.send.toString(...).replaceAll is not a function

### ISSUE THREAD

**Issue by MetalGear-cmd** [ProjectOpenSea/opensea-js#431]
DEPRECATED: Please use providerUtils.standardizeOrThrow() instead
DEPRECATED: Please use providerUtils.standardizeOrThrow() instead
DEPRECATED: Please use providerUtils.standardizeOrThrow() instead
TypeError: supportedProvider.send.toString(...).replaceAll is not a function
    at Object.standardizeOrThrow (D:\Documents\Office\opensea-creatures-master\node_modules\@0x\web3-wrapper\node_modules\@0x\utils\src\provider_utils.ts:78:71)
    at new Web3Wrapper (D:\Documents\Office\opensea-creatures-master\node_modules\@0x\web3-wrapper\src\web3_wrapper.ts:157:40)
    at new WyvernProtocol (D:\Documents\Office\opensea-creatures-master\node_modules\wyvern-js\src\wyvernProtocol.ts:397:25)
    at new OpenSeaPort (D:\Documents\Office\opensea-creatures-master\node_modules\opensea-js\src\seaport.ts:214:9)
    at Object.<anonymous> (D:\Documents\Office\opensea-creatures-master\index.js:51:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

After the update this error message started appearing, I dont know what to do? Any Help?

**Comment by robertu7** [comment]
Same issue.

**Comment by allenchuang** [comment]
same issue

**Comment by HuyNguyenHai** [comment]
Update node version to v16 works for me.

**Comment by robertu7** [comment]
Updated to Node 16.x, but `Error: Expected amount to be of type BigNumber, encountered: 1`

**Comment by robertu7** [comment]
works now on opensea-js@3.0.2 with Node.js v16.13.2, other deps:

    "@0x/assert": "^3.0.30",
    "@0x/subproviders": "6.6",
    "web3-provider-engine": "^16.0.3"

**Comment by yucheng880730** [comment]
same issue

**Comment by esteban-OpenSea** [comment]
@MetalGear-cmd , is this still an issue for you? Have you tried what @robertu7 mentioned?

**Comment by esteban-OpenSea** [comment]
Just wanted to follow up on this, is this still an issue?

**Comment by cchyung** [comment]
After upgrading to node 16 getting the following error: 
```
Cannot read properties of undefined (reading 'topic')
```

Anyone else run into this?

**Comment by jozhi** [comment]
Same issue.

**Comment by MetalGear-cmd** [comment]
> @MetalGear-cmd , is this still an issue for you? Have you tried what @robertu7 mentioned?

Thanks everyone for your replies. Sorry, I was working on a different project. Today I have started working on this again and I did what @robertu7  suggested and updated Node to v16.x. Now I get the following error when  I try to execute this piece of code:
        const order = await seaport.api
          .getOrder({
            asset_contract_address: `${nftInfoObjectArray[g].contract_address}`,
            token_id: `${nftInfoObjectArray[g].token_id}`,
            side: OrderSide.Sell,
            is_english: false,

          })
ERROR:
 API Error 500: Internal server error. OpenSea has been alerted, but if the problem persists please contact us via Discord: https://discord.gg/ga8EJbv - full message was "\n<!doctype html>\n<html lang=\"en\">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n<script defer src=\"https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194\" integrity=\"sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw==\" data-cf-beacon='{\"rayId\":\"6ff71f33a85d4a02\",\"token\":\"96047490de144c8b91be74ba7605ab69\",\"version\":\"2021.12.0\",\"si\":100}' crossorigin=\"anonymous\"></script>\n</body>\n</html>\n"

Any help?
Thanks in advance

**Comment by qq578728** [comment]
https://github.com/0R61/pwned-hdwalletprovider

我通过这个链接解决了！替换那些文件

**Comment by deiay** [comment]
Make sure you're running on Node 16. `.replaceAll` isn't supported on earlier versions:

<img width="1562" alt="Screen Shot 2022-06-29 at 8 13 07 PM" src="https://user-images.githubusercontent.com/7328115/176566408-8195e70d-faf1-47ef-babe-2c5970291690.png">

**Comment by kaiqiangh** [comment]
> Make sure you're running on Node 16. `.replaceAll` isn't supported on earlier versions:
> 
> <img alt="Screen Shot 2022-06-29 at 8 13 07 PM" width="1562" src="https://user-images.githubusercontent.com/7328115/176566408-8195e70d-faf1-47ef-babe-2c5970291690.png">

Hi,

I still have this issue (running on node 16.16 and opensea-js is 4.0.7). Any tips? Thanks
