### ISSUE TITLE
/event API returns 500 internal server error on last used cursor

### ISSUE THREAD

**Issue by csidi90** [ProjectOpenSea/opensea-js#433]
No matter what query params I use, the /event API for type successful always returns 500 internal server error once I reach the last cursor page. This has to be a bug since all previous pages work.

**Comment by esteban-OpenSea** [comment]
Is this working for you now?

**Comment by csidi90** [comment]
now Its not working for over 6 weeks

**Comment by babarhussain47** [comment]
Any solution to this issues?
