### ISSUE TITLE
Random 495 Errors

### ISSUE THREAD

**Issue by esteban-OpenSea** [ProjectOpenSea/opensea-js#435]
Users on 3/17 reported getting multiple 495 errors.

**Comment by Cookiezzz** [comment]
Some time ago 7-10 days I started getting random HTTP 495 errors. 
It seems to be related to the SSL certificate. For me it happens around 1000 times a day.
I'm mostly using the /events endpoint but it also happens on others.
![image](https://user-images.githubusercontent.com/2996654/158899113-d06a5f4b-b559-41ef-b716-40e478f76dd6.png)


It's 100% random when the error occurs.
If I just make an instant retry request, there is a 99% change that the request will be good.
![image](https://user-images.githubusercontent.com/2996654/158899006-b97da694-fd37-4e76-b12f-5ddd4f4577fa.png)

This is a Cloudlflare from someone else who has the same issue. (@Cluciano)
'cf-ray': '6ed7b757bd8c9c4e-IAD'
this is a header that comes back from cloudflare during the 495 error and they can use it to lookup the request/response on their side
should help them pinpoint the request, data center, etc...

**Comment by JustasJan** [comment]
Errors are pretty much random, at least i could not find any pattern to it. Doesn't matter if i provide api key or not, it changes nothing. Errors are not very common though and sometimes i get it after like 50 requests, sometimes after 500.
StatusCode is 495 and response text is `SSL certificate error`.

I am requesting these endpoints: `https://api.opensea.io/api/v1/asset_contract/` (api key provided, errors less frequent) and `https://api.opensea.io/api/v1/collection/${slug}/stats` (no api key, errors more frequent, but in api docs it doesn't say that key is required).

Some rayIds with such responses: `6edd955dc8b6940e`, `6edd94fa1e2c6623`, `6edd94a2fcfa602a`...

**Comment by dpjnguyen** [comment]
Any insight into this. i too am getting this for https://api.opensea.io/api/v1/assets

**Comment by Cookiezzz** [comment]
Today is really bad.
Day isn't finished and I'm nearing 2000 requests with SSL errors.
![image](https://user-images.githubusercontent.com/2996654/159573181-f6797f7f-895a-4882-86b0-0e5475c1c96c.png)

**Comment by thunderball1** [comment]
Same here

**Comment by simonare** [comment]
Guys my case is little different. When I get error I am retrying up to 10 times and I am consistently continue getting same 495 error. I don't know what to do. It looks like there is no solution.

**Comment by dpjnguyen** [comment]
> 

I did a retry logic where increasing throttle by 5 seconds if failed and upon success scale back the throttling by 5 seconds until no longer throttling. i.e. on first consecutive fail, i wait 5 seconds, on second consecutive fail i wait 10 seconds, and so on. If successful on retry i decrease throttle by 5 seconds until it gets back down to 0.

**Comment by esteban-OpenSea** [comment]
Thank you everyone for your feedback! Just wanted to let you know that we are actively investigating this. I will provide updates here! Thanks again for your providing feedback!

**Comment by Cookiezzz** [comment]
Unless I broke my logging, I haven't seen a 495 in 5 days.
Anyone else on this thread can confirm?

@esteban-OpenSea something has been changed?

**Comment by esteban-OpenSea** [comment]
This has been fixed and I am officially closing this issue. There was a small issue with an upstream networking provider, but it is fixed!
