### ISSUE TITLE
How to get latest orders for a particular collections?

### ISSUE THREAD

**Issue by DishantPal** [ProjectOpenSea/opensea-js#437]

**Comment by esteban-OpenSea** [comment]
Can you elaborate a little more on what you would like to do exactly? Because with the [collection stats](https://docs.opensea.io/reference/retrieving-collection-stats) you can view a lot of fata.

**Comment by velmoorthi** [comment]
use orders endpoint (https://docs.opensea.io/reference/retrieving-orders)

**Comment by DishantPal** [comment]
# use orders endpoint (https://docs.opensea.io/reference/retrieving-orders)

this doesnt simply take collection slug like https://docs.opensea.io/reference/getting-assets

also it does takes contract_address but that also have to be supplied with list of token_ids refer(https://i.imgur.com/NsvTP2A.png)

also i don't think it will take all 10k or more token ids together

just need some ability to get latest orders for a particular collection just like i get for asses (would be awesome if i can simply pass coll slug and get the orders)

**Comment by esteban-OpenSea** [comment]
Pagination past 10k is not yet supported

I will go ahead and close this issue since it's a duplicate. Please follow this ticket for the latest updates on this issue: https://github.com/ProjectOpenSea/opensea-js/issues/483
