### ISSUE TITLE
Can't Create Buy order

### ISSUE THREAD

**Issue by t-ermis** [ProjectOpenSea/opensea-js#439]
Here is the payload of seaport.createBuyOrder:
`{"asset":{"tokenId":"40564810494803150405413508554397890369838338565727533024787874484878955249665","tokenAddress":"0x88b48f654c30e99bc2e4a1559b4dcf1ad93fa656"},"paymentTokenAddress":"0xc778417E063141139Fce010982780140Aa0cD5Ab","accountAddress":"0xfdf9a81abdb01c73179886aede4eb457db10d4c3","startAmount":"0.005"}`
I can sign the txn but it never goes through and I get the response:
`Error: API Error 400: ['Expected exchange contract address to match']`      
Any Idea what is wrong? The asset in question is:
[https://testnets.opensea.io/assets/0x88b48f654c30e99bc2e4a1559b4dcf1ad93fa656/40564810494803150405413508554397890369838338565727533024787874481580420366337](https://testnets.opensea.io/assets/0x88b48f654c30e99bc2e4a1559b4dcf1ad93fa656/40564810494803150405413508554397890369838338565727533024787874481580420366337)

**Comment by esteban-OpenSea** [comment]
Did you update opensea.js to the latest version?

**Comment by esteban-OpenSea** [comment]
I haven't heard back from you in a while. Updating to the latest sdk and version of node should fix this error. Feel free to open a new issue if you are still running into this.
