### ISSUE TITLE
Add Unstoppable Wallet to the list of integrated API products 

### ISSUE THREAD

**Issue by Dadybayo** [ProjectOpenSea/opensea-js#442]
In release 24 we added NFT support for Unstoppable wallet users (iOS & Android). We are happy to use the OpenSea API and would appreciate it if you could add us to the list of products integrated with the API (https://docs.opensea.io/reference/api-overview) 

https://unstoppable.money/

**Comment by esteban-OpenSea** [comment]
Although we appreciate you sharing your wallet with us. This issues page is specifically for bugs/issues that limit you from using the sdk and api. Please reach out to OpenSea support regarding this manner. I will close this issue.
