### ISSUE TITLE
Mumbai wallet balance not showing - bug!!!

### ISSUE THREAD

**Issue by vladx777** [ProjectOpenSea/opensea-js#445]
Wallet on https://testnets.opensea.io/ showing 0 for any mumbai addresses despite them having Matic.

Bug is easy to reproduce - connect a mumbai address with matic via Metamask to Opensea and you'll see 0

**Comment by esteban-OpenSea** [comment]
Are you still having issues with this? When you originally posted I believe we were having some issues with the testnetes network but it should be fixed now. As a reference, you can always check the status of the site [here](https://status.opensea.io/).

**Comment by vladx777** [comment]
Yes, same issue persists. Are you saying you can see your Matic when you connect to Mumbai testnet?

**Comment by esteban-OpenSea** [comment]
We don't support polygon (matic) in the SDK/API. 

_Looking for [Polygon](https://polygon.technology/) APIs? Our V2 API is not quite ready yet, but stay tuned for more updates soon!_

Source: https://docs.opensea.io/reference/api-overview

**Comment by vladx777** [comment]
It's not about your API. It's about UI on your site. Rather than just closing, a good customer service would mean passing it on to the relevant colleagues
