### ISSUE TITLE
Can't get an API key.

### ISSUE THREAD

**Issue by web3protocol** [ProjectOpenSea/opensea-js#446]
Me and my team requested for an API key TWICE.
Our product is nftranks.xyz

The first request didn't got any response for a month.
I'm afraid that I won't get any response this time too, already several days passed after the new request.
Is there any tip for getting a key?

**Comment by binhnguyen98** [comment]
I do have some spar OpenSea API keys. If you're interested, you can DM me on discord: duc#8262

**Comment by esteban-OpenSea** [comment]
This is not an issue/bug related to the sdk or api. I believe the API key was already sent to you. I am closing this issue.

**Comment by web3protocol** [comment]
> This is not an issue/bug related to the sdk or api. I believe the API key was already sent to you. I am closing this issue.

Actually no, Never got any keys, Never replied. 
Only API key seller (of course not guaranteed individual) offered me some keys with decent price.
Is there any way I can get one or two API keys? Me and my team already requested several times(more than 8 times) but never got a response and this is the only response I ever got from Opensea.
If you know any way I can get the key, please help.
