### ISSUE TITLE
use seaport.createBuyOrder retun a error value 🔢 You declined to authorize your offer

### ISSUE THREAD

**Issue by yangyuecoding** [ProjectOpenSea/opensea-js#448]

**Comment by esteban-OpenSea** [comment]
Can you elaborate a little more on the issue you are having?

**Comment by JustHwj** [comment]
> Can you elaborate a little more on the issue you are having?
I have the same problem when I try to make offer
![image](https://user-images.githubusercontent.com/29752695/161250364-9ac037d7-f794-48d3-b3b0-75493648c2b7.png)
![image](https://user-images.githubusercontent.com/29752695/161250252-11671dd1-01fe-419f-b33e-d07878b2faa2.png)

**Comment by esteban-OpenSea** [comment]
Did you start getting this error after updating the OpenSea SDK?

**Comment by fmaduakor** [comment]
Check out this example https://github.com/ProjectOpenSea/opensea-creatures/blob/master/scripts/sell.js It helped me to get it working

**Comment by jimmyjimmy94** [comment]
> Check out this example https://github.com/ProjectOpenSea/opensea-creatures/blob/master/scripts/sell.js It helped me to get it working

May I ask what have u done to make it works? Are you using MnemonicWalletSubprovider or PrivateKeyWalletSubprovider?
