### ISSUE TITLE
Outdated response for bundles?

### ISSUE THREAD

**Issue by creazy231** [ProjectOpenSea/opensea-js#45]
I recently notices, that the response of **bundles** using opensea-js is different than the response of the API.

Can't find `"orders"` inside the json response which is a part of the API response.

**Comment by alexanderatallah** [comment]
@creazy231 we'll add that!

should be just copying some of the lines from `assetFromJSON` into `assetBundleFromJSON` and a little bit of refactoring to reduce code duplication, in case you want to take a stab

**Comment by Jshanks21** [comment]
@alexanderatallah I'd like to take a stab at it. I added `orders `and `buyOrders` to `assetBundleFromJSON`.
