### ISSUE TITLE
[Request] /events endpoint support for event_type arrays

### ISSUE THREAD

**Issue by Cookiezzz** [ProjectOpenSea/opensea-js#450]
For the /events endpoint we can supply the following event_types according to the docs. 
https://docs.opensea.io/reference/retrieving-asset-events

- Created
- Successful
- cancelled
- bid_entered
- bid_withdrawn
- transfer
- approve

As an example there currently is no way to get created and successful in one API call.
We could leave out the event, but then we'd also get all other events.
bid_entered events make up a massive portion of events, which in a lot of cases are unwanted.
Let's say we want the sales and listings for the last 5 minutes, this would save a lot of API calls and unnecessary data transfer.

If we could supply an array for event_type like we can for asset_contract_addresses in the /assets endpoint that would solve this.

**Comment by esteban-OpenSea** [comment]
We appreciate you bringing this up! Our team has made note of this. Although we love hearing feedback from our community, this isn't a bug or issue that is directly hindering you from using the sdk or api. But instead a feature request. That being said I will close this ticket out, but will keep this in mind as we continue improving the api

**Comment by Cookiezzz** [comment]
Might be somewhat of a feature request but this is something that's really preventing me from using the API in a good way.
If this option would exist I could make way less API calls.

Most likely a lot of other people also can use this.
Thus you receiving less calls and having less load on the API.
