### ISSUE TITLE
Error: API Error 404: Not found. Full message was '{"success":false}'

### ISSUE THREAD

**Issue by ozgur3512** [ProjectOpenSea/opensea-js#455]
![image](https://user-images.githubusercontent.com/35203662/161855431-f08ad44f-a9f4-4c54-a84e-3ec6eb4ae558.png)

I have an error as this, I was trying to send offer

**Comment by esteban-OpenSea** [comment]
Are you using query parameter instead of a url parameter?

**Comment by esteban-OpenSea** [comment]
Haven't heard back from you in a while, is this still an issue?

**Comment by tullahnazari** [comment]
> Haven't heard back from you in a while, is this still an issue?

It's still an issue I am running into and Node and SDK is up to date.

**Comment by tullahnazari** [comment]
The error is specifically derived from opensea-js/src/api.ts:454:11
