### ISSUE TITLE
List all "buy now" from a contract

### ISSUE THREAD

**Issue by Philigane** [ProjectOpenSea/opensea-js#459]
Hello,

I am facing a problem. I am trying to list all "buy now" NFTs from a contract (or a collection) but i am not sure my approach is good.

I list all tokens id via Moralis API (to not overcharger Opensea API).
Then i get orders from each token and i consider that if there is an order which can be paid in ETH it's the buy now.
Then i complete the order.

This method works but occurs many many useless request and i am not even sure of it.

Is there any other solution ?

**Comment by esteban-OpenSea** [comment]
We appreciate your feedback! We have a similar ticket open for this, check here: https://github.com/ProjectOpenSea/opensea-js/issues/475

Please follow that ticket for the latest updates. I will close this to avoid confusion.
