### ISSUE TITLE
Please verify the Rinkeby OpenSea exchange contract on etherscan

### ISSUE THREAD

**Issue by e-nikolov** [ProjectOpenSea/opensea-js#460]
Currently it's not verified and failed transactions on rinkeby made through the SDK are hard to debug.

I tried verifying it myself with the version from the mainnet, but it did not work due to some differences in the hard coded values for CHAIN_ID and DOMAIN_SEPARATOR. I think the correct values for those are 

CHAIN_ID=4
DOMAIN_SEPARATOR=0xd38471a54d114ee69fbb07d1769a0bbecd4f429ddf5932c7098093908e24bd9d

but verification is still failing, probably because of differences in compiler settings (version, optimization passes)

**Comment by e-nikolov** [comment]
After a bit of trial and error, I managed to verify it myself.

**Comment by my-Gem** [comment]
Can you tell me how you set these hardcoded values

**Comment by e-nikolov** [comment]
Do you mean how I figured out the correct values? I used a disassembler on the bytecodes of both the unverified rinkeby version and the verified mainnet version. When I found a difference, I'd try to figure out what the original code looked like. In the cases of the CHAIN_ID and the DOMAIN_SEPARATOR it was relatively easy because it was just the value of a variable.

There were a couple of other differences for which I also compared with the old verified version of the rinkeby exchange and was able to make some guesses on how the functions could have changed.

**Comment by esteban-OpenSea** [comment]
Great to hear this was solved! Thanks for the explanation as well. I'll go ahead and close this out.
