### ISSUE TITLE
Unable to search assets using OpenSeaAssetQuery

### ISSUE THREAD

**Issue by jay58** [ProjectOpenSea/opensea-js#463]
As per the code for [OpenSeaAssetQuery](https://github.com/ProjectOpenSea/opensea-js/blob/60acf392d31700c9ceb7d31c4a3e58fbbf9f4ec8/src/types.ts#L692) structure and [getAssets](https://github.com/ProjectOpenSea/opensea-js/blob/60acf392d31700c9ceb7d31c4a3e58fbbf9f4ec8/src/api.ts#L232) method one can perform search on top of assets.

I wrote the following code
```
try {
    const assets = await seaport.api.getAssets({search: "bored ape"})
    console.log(assets);
} catch(err) {
    console.log(err)
}
```

The above code will give me the following error:
`
Error: API Error 400: Invalid request: {"search":["extra fields not permitted"]}
`

Digging more into the code behind the scene this method is calling the /assets API as shown [here](https://github.com/ProjectOpenSea/opensea-js/blob/60acf392d31700c9ceb7d31c4a3e58fbbf9f4ec8/src/api.ts#L243) and /assets API doesn't support search as query parameter.

I cannot understand if there is no search support in API why the SDK has the parameter? Will this be rolled out in future updates of backend APIs?

**Comment by esteban-OpenSea** [comment]
We are looking into this!
