### ISSUE TITLE
 collection.stats.floor_price always = 0 on asset/{asset_contract_address}/{token_id}/

### ISSUE THREAD

**Issue by chefbobj** [ProjectOpenSea/opensea-js#465]
Issue is happening on API endpoint https://api.opensea.io/api/v1/asset/{asset_contract_address}/{token_id}/

You can easily reproduce the issue by using the demo here: https://docs.opensea.io/reference/retrieving-a-single-asset
Just click 'Try It!' with any contract address and token id, and check the json response.
Check the property collection.stats.floor_price
You will see that is it always equal to 0 (zero), whatever the collection is.

![image](https://user-images.githubusercontent.com/90320494/163537788-847ad20b-6c56-4d7c-b40b-ec0de35a1c68.png)

floor_price works well on other endpoints though

**Comment by esteban-OpenSea** [comment]
Thanks for bringing this up to us! We will look into this!

**Comment by esteban-OpenSea** [comment]
This is working for me
<img width="440" alt="image" src="https://user-images.githubusercontent.com/99999009/172982129-aeba40c8-b81a-43d2-9d91-d0df6a9683b1.png">

**Comment by esteban-OpenSea** [comment]
Is this happening for a specific collection?

**Comment by lihao6485** [comment]
Hi @esteban-OpenSea 

The collection stats api is working fine but retrieve collections api is returning 0 for all collection `/api/v1/collections`

You can see the below example: 
https://api.opensea.io/api/v1/collections?asset_owner=0xE301165f506ca59B766389624DF1F51Ad0A341DF

**Comment by GianlucaSolinas** [comment]
Hi! 
I can confirm that for the endpoint `https://api.opensea.io/api/v1/collections?asset_owner={wallet_address}&offset=0&limit=300` all the floor prices are 0

**Comment by GoldLiondev** [comment]
Hi!
I got same issue, how can I solve this?

**Comment by Webber455** [comment]
> Hi!
> I got same issue, how can I solve this?
Have you been able to resolved this issue yet? @GoldLiondev
