### ISSUE TITLE
Retrieving Events endpoint has huge performance deterioration spikes and inconsistent rate limiting strategy

### ISSUE THREAD

**Issue by bujoralexandru** [ProjectOpenSea/opensea-js#468]
![image](https://user-images.githubusercontent.com/17970235/163596541-231161cd-b1f4-4b2f-b7cc-ad96702dd36f.png)

Image serves as proof. I'm doing 2 requests at a time that do the following:
only_opensea: true
cursor (if present, but because of the spikes I always can't keep even a 1 minute delay to the OS platform),
event_type: "created" (for the first request) | "successful" (for the second request).

My aim is to stick with the platform in a close to real-time manner.

Can someone point me to what information should I provide further or why does this happen?

**Comment by bujoralexandru** [comment]
Hello @esteban-OpenSea, double posting because of another issue that has been weird and also because you asked me to create some more context regarding the performance issues.

**Performance** - This issue seem to have been fixed, endpoint returns after 4-500ms which is decent enough.

**Rate-Limitation**
So, my use-case is as follows:
- I'm doing one request at a time.
- Everything works fine, till I get rate-limited (for whatever reason).
- I read the "retry-after" header that is present on the 429 response, that says to me 1, which means I must wait 1 s before making another request.
- All done, I delay my next call with a second, but I'm getting another 429 response, which then again tells me to wait another second.
- After 3-4 429 responses, everything starts working again. But repeating this pattern gives me a 180s waiting time, which is unacceptable.

You can verify for yourself that this endpoint's rate-limit with an API Key is behaving inconsistend.

**Comment by Trontor** [comment]
+1

**Comment by LookRain** [comment]
+1
