### ISSUE TITLE
can't install opensea-js

### ISSUE THREAD

**Issue by July-Jio** [ProjectOpenSea/opensea-js#471]
can't install opensea-js on Mac mini (M1 chip) with node v17.9.0 and npm V8.7.0. it stay at ` idealTree:Crypto: sill idealTree buildDeps`

**Comment by shawns19** [comment]
use yarn add instead of npm. that worked for me

**Comment by rayeaster** [comment]
> use yarn add instead of npm. that worked for me

```
npm install --global yarn
yarn add opensea-js
```

**Comment by esteban-OpenSea** [comment]
We are looking into this! @July-Jio , did you try using yarn?

**Comment by July-Jio** [comment]
> We are looking into this! @July-Jio , did you try using yarn?

yes, tried `yarn add opensea-js` and here is the error info.

```
yarn add v1.22.18
warning package.json: No license field
warning ../../package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] 🔍  Resolving packages...
warning opensea-js > fbemitter > fbjs > core-js@1.2.7: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote https://github.com/ProjectWyvern/ethereumjs-abi.git HEAD
Directory: /Users/julyjiao/Documents/Crypto/opensea-sdk
Output:
fatal: unable to access 'https://github.com/ProjectWyvern/ethereumjs-abi.git/': LibreSSL SSL_read: error:02FFF03C:system library:func(4095):Operation timed out, errno 60
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/ProjectOpenSea/wyvern-schemas.git
Directory: /Users/julyjiao/Documents/Crypto/opensea-sdk
Output:
fatal: unable to access 'https://github.com/ProjectOpenSea/wyvern-schemas.git/': LibreSSL SSL_read: error:02FFF03C:system library:func(4095):Operation timed out, errno 60
    at ProcessTermError.ExtendableBuiltin (/Users/julyjiao/.nvm/versions/node/v16.14.2/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/Users/julyjiao/.nvm/versions/node/v16.14.2/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/Users/julyjiao/.nvm/versions/node/v16.14.2/lib/node_modules/yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/Users/julyjiao/.nvm/versions/node/v16.14.2/lib/node_modules/yarn/lib/cli.js:25783:17)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Error: Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/ProjectOpenSea/wyvern-js.git
Directory: /Users/julyjiao/Documents/Crypto/opensea-sdk
Output:
fatal: unable to access 'https://github.com/ProjectOpenSea/wyvern-js.git/': error:02FFF036:system library:func(4095):Connection reset by peer
    at ProcessTermError.ExtendableBuiltin (/Users/julyjiao/.nvm/versions/node/v16.14.2/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/Users/julyjiao/.nvm/versions/node/v16.14.2/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/Users/julyjiao/.nvm/versions/node/v16.14.2/lib/node_modules/yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/Users/julyjiao/.nvm/versions/node/v16.14.2/lib/node_modules/yarn/lib/cli.js:25783:17)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by ai323** [comment]
same here, tried both npm & yarn, not working

**Comment by freemavis** [comment]
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
warning opensea-js > fbemitter > fbjs > core-js@1.2.7: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/ProjectWyvern/ethereumjs-abi.git
Directory: /Users/***/_src/***/avatar/***-avatar
Output:
fatal: unable to access 'https://github.com/ProjectWyvern/ethereumjs-abi.git/': LibreSSL SSL_read: error:02FFF03C:system library:func(4095):Operation timed out, errno 60
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/ProjectOpenSea/wyvern-js.git
Directory: /Users/***/_src/***/avatar/***-avatar
Output:
fatal: unable to access 'https://github.com/ProjectOpenSea/wyvern-js.git/': LibreSSL SSL_read: error:02FFF03C:system library:func(4095):Operation timed out, errno 60
    at ProcessTermError.ExtendableBuiltin (/Users/***/.yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/Users/***/.yarn/lib/cli.js:750:123)
    at new ProcessTermError (/Users/***/.yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/Users/***/.yarn/lib/cli.js:25783:17)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
Error: Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/ProjectOpenSea/wyvern-schemas.git
Directory: /Users/***/_src/***/avatar/***-avatar
Output:
fatal: unable to access 'https://github.com/ProjectOpenSea/wyvern-schemas.git/': LibreSSL SSL_read: error:02FFF03C:system library:func(4095):Operation timed out, errno 60
    at ProcessTermError.ExtendableBuiltin (/Users/***/.yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/Users/***/.yarn/lib/cli.js:750:123)
    at new ProcessTermError (/Users/***/.yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/Users/***/.yarn/lib/cli.js:25783:17)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by guoweifu** [comment]
+1

**Comment by charlesgiovanniello** [comment]
Also having issues, whats weird is i wasnt having this issue with another project i built last week.

**Comment by charlesgiovanniello** [comment]
Looks like i got it to work by switching to node version 14, I know thats not recommended but i at least got the dependencies to install and can pull data.

**Comment by cyberscape-labs** [comment]
Also can't seem to install with npm install opensea-js

**Comment by metacopy** [comment]
Same here. Not helped npm & yarn

**Comment by austinHodge** [comment]
> Looks like i got it to work by switching to node version 14, I know thats not recommended but i at least got the dependencies to install and can pull data.

Can you let me know which version, specifically?  Tried 14.18.3 and 14.19.3 with no luck.  Mind posting your package.json?

**Comment by freemavis** [comment]
> 
I suggest you check your network, like this:
1. run a single test  `git clone your-failed-repository`, if still failed, swich your proxy.
2. search the ip of `raw.githubusercontent.com` `api.opensea.io` ,append to your host config .
this is my experiment, it worked.

**Comment by freemavis** [comment]
> > Looks like i got it to work by switching to node version 14, I know thats not recommended but i at least got the dependencies to install and can pull data.
> 
> Can you let me know which version, specifically? Tried 14.18.3 and 14.19.3 with no luck. Mind posting your package.json?

I suggest you check your network, like this:

run a single test git clone your-failed-repository, if still failed, swich your proxy.
search the ip of raw.githubusercontent.com api.opensea.io ,append to your host config .
this is my experiment, it worked.

**Comment by keganfer** [comment]
> use yarn add instead of npm. that worked for me

what version of yarn and node are you using?

**Comment by tomerds** [comment]
Still failing to install 4.0.3, can install 4.0.1 fine but I need createSellOrder which is broken on that version

**Comment by tomerds** [comment]
Update: worked after upgrading to an npm version >= 8.5.2, was previously on 8.5.0

**Comment by Deathwing** [comment]
Version 4.0.3 can still only be installed via yarn instead of npm... and the issue exists since 3 months.... any updates?

**Comment by Rizwankmc** [comment]
Not able to install opensea-js neither with npm nor with yarn
this is the yarn-error.log file please   check -
`Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\websu\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js add opensea.js

PATH: 
  C:\Users\websu\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\websu\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Go\bin;C:\Program Files\Java\jdk-17.0.3.1\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\websu\AppData\Local\Android\Sdk\platform-tools;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;%GOPATH%\bin;C:\HaxeToolkit\haxe;C:\HaxeToolkit\neko;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\websu\Desktop\javatext\gson-2.2.2.jar;C:\Program Files\Amazon\AWSSAMCLI\bin;C:\Users\websu\AppData\Local\Microsoft\WindowsApps;C:\Users\websu\AppData\Roaming\npm;C:\Users\websu\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\websu\go\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl

Yarn version: 
  1.22.17

Node version: 
  14.17.3

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/opensea.js: Not found
      at Request.params.callback [as _callback] (C:\Users\websu\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:67029:18)
      at Request.self.callback (C:\Users\websu\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:140883:22)
      at Request.emit (events.js:375:28)
      at Request.<anonymous> (C:\Users\websu\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141855:10)
      at Request.emit (events.js:375:28)
      at IncomingMessage.<anonymous> (C:\Users\websu\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141777:12)
      at Object.onceWrapper (events.js:481:28)
      at IncomingMessage.emit (events.js:387:35)
      at endReadableNT (internal/streams/readable.js:1317:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)

npm manifest: 
  {
    "name": "opensea-react",
    "version": "0.1.0",
    "private": true,
    "dependencies": {
      "@testing-library/jest-dom": "^5.16.4",
      "@testing-library/react": "^13.3.0",
      "@testing-library/user-event": "^13.5.0",
      "react": "^18.2.0",
      "react-dom": "^18.2.0",
      "react-scripts": "5.0.1",
      "web-vitals": "^2.1.4"
    },
    "scripts": {
      "start": "react-scripts start",
      "build": "react-scripts build",
      "test": "react-scripts test",
      "eject": "react-scripts eject"
    },
    "eslintConfig": {
      "extends": [
        "react-app",
        "react-app/jest"
      ]
    },
    "browserslist": {
      "production": [
        ">0.2%",
        "not dead",
        "not op_mini all"
      ],
      "development": [
        "last 1 chrome version",
        "last 1 firefox version",
        "last 1 safari version"
      ]
    },
    "resolutions": {
  	"@0x/utils": "https://github.com/ProjectOpensea/0x-tools/raw/provider-patch/utils/0x-utils-6.5.0.tgz"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
`

**Comment by nabe14** [comment]
> Version 4.0.3

How can I switch version?

**Comment by mstudda1** [comment]
1 info using npm@8.15.1
2 info using node@v16.15.1

Not able to install using npm, can anyone install?

**Comment by PetrucciLuca** [comment]
Hi all!
If it's useful my workaround that work for me:

Admin Console
1) nvm install 14.20.0
2) nvm use 14.7.0

Project console
3) npm install --global yarn
4) npm uninstall --save opensea-js
5) npm cache clean –force
6) yarn add opensea-js

Note: not work with node 16.8.0 and 14.7.0

**Comment by luoyeETH** [comment]
> 
solved  
node 16.16.0

**Comment by luoyeETH** [comment]
> Hi all! If it's useful my workaround that work for me:
> 
> Admin Console
> 
> 1. nvm install 14.20.0
> 2. nvm use 14.20.0
> 
> Project console 3) npm install --global yarn 4) npm uninstall --save opensea-js 5) npm cache clean –force 6) yarn add opensea-js
> 
> Note: not work with node 16.8.0 and 14.7.0

solved  
node 16.16.0

**Comment by devendra-DWT** [comment]
use yarn instead of npm ,
use node 14.17 or above

**Comment by Ataxia123** [comment]
Node 18 isnt working
