### ISSUE TITLE
Not expired order not accepted if over 1 hour old.

### ISSUE THREAD

**Issue by stewart-lore** [ProjectOpenSea/opensea-js#474]
I have a valid sell order I want to submit to the off chain orderbook using `POST /wyvern/v1/orders/post/`. The order has a `listingTime` of over one hour in the past and expiration time in the future of just less than 23 hours from the time I submit it to the opensea api. The response is:

```
{
    "success": false,
    "errors": [
        "[\"Expected the listing time to be at or past the current time. Make sure your device's time is correct! Diff from now is                 3608 seconds (time entered is 1650316600.0).\"]"
    ]
}
```

So the order is being rejected because listingTime is too far in the past. However expiration time is in the future so the order is still valid. Is it possible for order, and similar orders with listing time in the recent, to be accepted by the Orders api given the expiration time is in the future?

**Comment by esteban-OpenSea** [comment]
This error typically occurs when your computer system clock is not synced with the internet/server time.

Follow the instructions to turn on automatic timezone syncing. After you've reset the time, please retry the transaction again. Additionally, please make sure your hardware wallets firmware is up-to-date, or consider trying again with a digital wallet.

Let me know if that helps!

**Comment by stewart-prysm** [comment]
Hi @esteban-OpenSea. My computer clock is correct. To be clear, for my use case, I am intentionally waiting some time to submit the order to list on chain and post to opensea api. I want to be able to post orders to the opensea API that are older than an hour but still non-expired.

**Comment by esteban-OpenSea** [comment]
@stewart-prysm , just wanted to follow up again on this. Are you still getting this error? Are you only running into it when intentionally waiting for some time? Or is it also happening when you are attempting to submit normal orders? Additionally, please make sure your wallet is [up to date](https://metamask.zendesk.com/hc/en-us/articles/360060268452-How-to-update-the-version-of-MetaMask).

**Comment by stewart-prysm** [comment]
@esteban-OpenSea Hello yes I'm intentionally waiting this time.. the reason is because my application is listing NFTs from a multi-sig gnosis safe. Sometimes it can take hours for all of the owners to approve a list transaction. So there is a delay. As a workaround we list for some time in the future. But always the restriction is in place by the API-- if I post a listing an hour after the `listingTime`, the api rejects the order even though it still is not expired.

**Comment by stewart-prysm** [comment]
This is for v1, I haven't tested on the v2 listings api
