### ISSUE TITLE
Provide an API for retrieving listing information

### ISSUE THREAD

**Issue by LookRain** [ProjectOpenSea/opensea-js#475]
- current listings(the result shown with the `Buy Now` filter on)
![image](https://user-images.githubusercontent.com/11829847/164054931-b49f2582-cdd9-44ec-b42d-4d665b3adb1a.png)

I was quite surprised to find out that such information are not in the existing APIs. I would be happy even with just the number of listings, but that's sadly not available either...

**Comment by esteban-OpenSea** [comment]
Just to clarify, you would want the "buy now" option to be a parameter when fetching listings?

**Comment by LookRain** [comment]
> Just to clarify, you would want the "buy now" option to be a parameter when fetching listings?

Right. The main problem now is that there doesn't seen to be an API to fetch listings for **a collection** at all. The current API is only for fetching listings for a single asset(collection with an token_id).

**Comment by Philigane** [comment]
+1

**Comment by emorling** [comment]
+1

**Comment by aweiu** [comment]
Is there a query parameter that can implement status filtering? @esteban-OpenSea

**Comment by krjii** [comment]
It's easy enough ti implement a scraper to full the listing off the page although it would be great if the api provided this info. 

An option would to retrieve all items for a collection and count once retrieved.

**Comment by LookRain** [comment]
> It's easy enough ti implement a scraper to full the listing off the page although it would be great if the api provided this info.
> 
> An option would to retrieve all items for a collection and count once retrieved.

Did you actually implement a scraper to do so?

I did some testing and it seems OS does a lot of detection for this kind of page visit. Using puppeteer headless mode would be detected and blocked, unless you change the user agent header manually, also OS would prompt CAPTCHA i guess

**Comment by krjii** [comment]
> > It's easy enough ti implement a scraper to full the listing off the page although it would be great if the api provided this info.
> > An option would to retrieve all items for a collection and count once retrieved.
> 
> Did you actually implement a scraper to do so?
> 
> I did some testing and it seems OS does a lot of detection for this kind of page visit. Using puppeteer headless mode would be detected and blocked, unless you change the user agent header manually, also OS would prompt CAPTCHA i guess

I use Selenium in both headless and normal modes. One of the main things is ensuring you are sending requests to quickly. That's one of the main ways to get blocked.

**Comment by esteban-OpenSea** [comment]
Thank you everyone for your feedback! We will look into this and adding an option to filter by buy now. In the meantime, check this out for collections

- Fetch Collections: https://docs.opensea.io/reference/retrieving-a-single-collection
- Collection Stats: https://docs.opensea.io/reference/retrieving-collection-stats
- Stream API: https://docs.opensea.io/reference/stream-api-overview

**Comment by usmanashraf678** [comment]
Any update on this?

**Comment by ahjohnwon** [comment]
something new?

**Comment by usmanashraf678** [comment]
@esteban-OpenSea is there a timeline for this?

**Comment by eriqferrari** [comment]
@esteban-OpenSea i would like to test it but cannot get an API key. Tried several times but always no reply... someone can help me to get it??? Thanks

**Comment by SeanNFT** [comment]
Has this been implemented yet? Any updates?

**Comment by mekanoid55** [comment]
Hi @esteban-OpenSea any view to add listing data to the Collections endpoint? Thanks, Scott

> Thank you everyone for your feedback! We will look into this and adding an option to filter by buy now. In the meantime, check this out for collections
> 
> * Fetch Collections: https://docs.opensea.io/reference/retrieving-a-single-collection
> * Collection Stats: https://docs.opensea.io/reference/retrieving-collection-stats
> * Stream API: https://docs.opensea.io/reference/stream-api-overview
