### ISSUE TITLE
Metadata properties not displaying properly when using max_value

### ISSUE THREAD

**Issue by alpinevm** [ProjectOpenSea/opensea-js#476]
### Problem
Firstly, not sure if this is the correct place to post but I don't see another repo for reporting bugs regarding the OpenSea platform.
As per the OpenSea [documentation](https://docs.opensea.io/docs/metadata-standards): 
>> Adding an optional max_value sets a ceiling for a numerical trait's possible values. It defaults to the maximum that OpenSea has seen so far on the assets on your contract. If you set a max_value, make sure not to pass in a higher value.

Thus in my (base64 encoded) `tokenURI` response, I pass a `max_value` (1000 in my case) parameter for every numerical trait. Note that every numerical trait in my collection is displayed as a "boost number".
When I deploy, mint, and check the asset on OpenSea rinkeby, I see this:
![image](https://user-images.githubusercontent.com/33703995/164168773-8fb38e1e-13db-417d-8b16-a33e18462d08.png)
As you can see, the boost dial (the blue outer circle) doesn't seem to display relative to the `max_value` of 1000 set in the `tokenURI` response. (In fact, it seems to display the indicator randomly)

Am I misunderstanding the purpose of that indicator or is this a bug?

 ### Resources for debugging:
`tokenURI` response: (decoded from base64 and response shortened for brevity)
```
{
    ...
    {
      "trait_type": "Overlay",
      "value": "White Overlay"
    },
    {
      "display_type": "boost_number",
      "trait_type": "Midrange",
      "value": 420,
      "max_value": 1000
    },
    ...
]
}
```
[Test Asset Example](https://testnets.opensea.io/assets/0xe5324f52f28434405dbdc14a3200b93df72761ed/0)
[Smart Contract](https://rinkeby.etherscan.io/address/0xe5324f52f28434405dbdc14a3200b93df72761ed#readProxyContract)

**Comment by esteban-OpenSea** [comment]
Thank you for the detailed post, we are looking into this!

**Comment by YJ224** [comment]
Hello @c4syner, hope you are doing well
I've created metadata like this but Opensea didn't display only one trait_type named Division.
Others are showing well. :(
How can I fix it?
Thank you
"attributes": [
                {
                    "trait_type": "State", 
                    "value": "Undead"
                },
                {
                    "trait_type": "Statue Type", 
                    "value": "Lava"
                },
                {
                    "trait_type": "Division",
                    "Value": "Soldier"
                },
                {
                    "trait_type": "Special", 
                    "value": "Winner"
                }
]
