### ISSUE TITLE
Can't get an OpenSea API key  

### ISSUE THREAD

**Issue by Guardiano744** [ProjectOpenSea/opensea-js#479]
Hello,

so we've been trying for the past 1 1/2 month to get an OpenSea API key, we applied multiple times and included a detailed description of our use case and filled the form with a clear conscience.

We haven't even received any reply from OpenSea yet. 
We're are really keen to get started on mainnet OpenSea, so does anyone have any tips on getting an OpenSea API key?

**Comment by binhnguyen98** [comment]
I do have some spare OpenSea API keys. If you're interested, you can DM me on discord: duc#8262

**Comment by Guardiano744** [comment]
> Dont buy a key. Will get blocked. Resubmit your application and join discord.

I got provided one and my requests are going through.

**Comment by esteban-OpenSea** [comment]
+1 to the users that mentioned to not buy an API key. Please apply [here](https://docs.opensea.io/reference/request-an-api-key) and feel free to follow up on our [developer discord](https://discord.com/channels/397566282729390110/434175585745633280).

**Comment by matthewklinko** [comment]
Yes its hard, they currently stopped giving out keys as well
I've been using Rapid API as well , they do sell API keys as well
https://rapidapi.com/openseatools/api/opensea15
