### ISSUE TITLE
Provide a Web3.js based events API

### ISSUE THREAD

**Issue by LookRain** [ProjectOpenSea/opensea-js#481]
I see that the event listener API in this SDK is based on Web3.js instead of the OpenSea HTTP APIs. 

I'm wondering if it's possible for you guys to provide an alternative to the `https://api.opensea.io/api/v1/events` API based on the `getPastEvents` from web3.js. 
With that we don't overburden your API servers, and we also don't need to worry about the rate limits. If you guys don't have the capacity to do it, I'm happy to contribute.

**Comment by LookRain** [comment]
However, I imagine the web3js based API won't offer the same functionality as the HTTP api. The events can only be queried by `EventType` and won't support stuff like the collection's contract address... (or if there's any way to do that I'll be very very happy)

**Comment by LookRain** [comment]
I also just found out that the listings are not stored in the Wyvern smart contract, so events like `created` are impossible to get from the blockchain directly....

**Comment by emorling** [comment]
> I also just found out that the listings are not stored in the Wyvern smart contract, so events like `created` are impossible to get from the blockchain directly....

Listings and bundles are stored off chain.

**Comment by esteban-OpenSea** [comment]
Thank you for your feedback! We hear you and will look into this
