### ISSUE TITLE
EIP 2981 Support

### ISSUE THREAD

**Issue by maxper4** [ProjectOpenSea/opensea-js#482]
Hello, 

Could OpenSea please support EIP 2981 ? It's been out since a couple of months and openzeppelin realeased a standard contract supporting it since 9 Feb 2022. 
Many other NFT Marketplace allow users to use it.

Thank you !

https://eips.ethereum.org/EIPS/eip-2981
https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v4.5.0

**Comment by esteban-OpenSea** [comment]
Thanks for your feedback!

**Comment by cjmyles** [comment]
Firstly, is there an intention from OpenSea to implement this (I would very much love to see this) and if so, what would the timeline be for it? Thanks in advance.

**Comment by vybgss** [comment]
OpenSea, please give as some information about plans to implement EIP-2981 support.

**Comment by loocurse** [comment]
Hi, would appreciate if opensea can give a reply on this issue

**Comment by vrde** [comment]
Related: https://github.com/ProjectOpenSea/seaport/issues/306

**Comment by devenus98** [comment]
hi. Opensea.
Does Opensea support EIP2981(royalty) in the NFT smart contract?

**Comment by claude-eric-steiner** [comment]
Hi Opensea.
Why is EIP2981 not yet implemented!??

**Comment by heypran** [comment]
Support this 🙏

**Comment by WoodsFiend** [comment]
I wonder how many requests its going to take to get Opensea onboard with this. As the original NFT marketplace they are rapidly falling behind.

**Comment by esodot** [comment]
it's high time to implement the 2981

**Comment by heypran** [comment]
Listen to the users

**Comment by Aeddon** [comment]
@ryanio That's a bit a shocking statement from a tech company like Opensea!

https://eips.ethereum.org/EIPS/eip-2981

This paper clearly specifies that, if you support EIP-2981, you MUST consult the IERC2981 interface of each contract by calling the folling method:
`royaltyInfo(
        uint256 _tokenId,
        uint256 _salePrice
    )`
And then guarantee to execute a royalty transaction to the returned address with the returned amount.

If you don't, then you are simply NOT supporting EIP-2981.
I'm aware of the Opensea account based royalty approach, but to be exact, this has nothing to do with EIP-2981.

If it's "a bit complicated with our current system", then maybe it would be time to "change your system".
It can not be that hard to overrule your current account based approach if an IERC2981 is present in the contract.

Cheers

**Comment by WoodsFiend** [comment]
For anyone looking for a marketplace that supports EIP-2981, Rarible does an even allows you to build your own marketplace. I will be advising my user's not to use opensea and having an increased royalty rate on it to dissuade sellers from using it.

The only way to force a change is to apply pressure.

**Comment by Sh1Tt** [comment]
When will 2981 Be fully implemented?
