### ISSUE TITLE
Feedback: Fetch Assets with Cursor Slow

### ISSUE THREAD

**Issue by emorling** [ProjectOpenSea/opensea-js#483]
Fetching a 10K collection with a cursor, and pages of 50 at a time is far too slow. Its 4-5 times slower than the prior ability to use an offset. 

The reason its' slower is that with limit you could do 4-5 requests per second at once, and with cursor you can only do one at a time to find out the next cursor.

Please remedy this and allow larger limits. Or ability to fetch all the cursors separately so that it's possible to fetch multiple pages at once....

**Comment by simonare** [comment]
so, actually it is not slow but makes multi-threading impossible. I believe that what you are  looking for is not easily achievable with cursor approach.

**Comment by emorling** [comment]
> @emorling thanks for the feedback. just curious, why are you pulling the whole collection?

There are several use cases:

- I have a Rarity Tool that pulls the entire collection to calculate the rarity
- I have a Stats tool that needs the listings of every item in the collection to provide an analysis of the foors

**Comment by emorling** [comment]
> so, actually it is not slow but makes multi-threading impossible. I believe that what you are looking for is not easily achievable with cursor approach.

So there is no way to provide multiple cursors in the result? For example to query upcoming 4 pages at once?

**Comment by esteban-OpenSea** [comment]
Thanks again for your feedback, we will look into this.
