### ISSUE TITLE
Request: Open up the GraphQL API to developers

### ISSUE THREAD

**Issue by emorling** [ProjectOpenSea/opensea-js#484]
It would be way faster as the current API is sending wasteful information.

**Comment by chrisackermann** [comment]
Hey @emorling, would love to better understand as we work on evolving/improving the current API.  Re: wasteful information - is your concern the general size of the response payloads?  Are there specific use cases/requests that would be helpful that we support directly?

**Comment by LookRain** [comment]
+1. an example would be the assets API, https://docs.opensea.io/reference/getting-assets

The response contains the collection and the traits, which are quite unnecessary for most use cases I guess.

**Comment by emorling** [comment]
> Hey @emorling, would love to better understand as we work on evolving/improving the current API. Re: wasteful information - is your concern the general size of the response payloads? Are there specific use cases/requests that would be helpful that we support directly?

Correct, this is in regards to the very large response payloads. With a GraphQL we could indicate exactly which fields we need. OpenSea already has and is using GraphQL so why not open that up to developers?

Another benefit of GraphQL would be more filtering of the queries.

**Comment by esteban-OpenSea** [comment]
Thanks for your feedback! We will make note of this.

I also recommend checking out the stream api: https://docs.opensea.io/reference/stream-api-overview

**Comment by manishrjain** [comment]
I'd be interested in supporting a GraphQL API for OpenSea via Outserv. Can probably get it working in the coming week.

https://manishrjain.com/outserv-graphql-blockchain-search
