### ISSUE TITLE
Update dependencies, please

### ISSUE THREAD

**Issue by bdvorianov** [ProjectOpenSea/opensea-js#485]
I have a ton of such warnings when building my project with latest opensea-js. Could someone from the team please check it?

![Screenshot 2022-04-22 at 12 02 09](https://user-images.githubusercontent.com/33183223/164673961-0a5eb692-fc1b-4d7a-9741-a9c4ce6a720a.png)

**Comment by bmayen** [comment]
Another to update dependencies: #415

**Comment by esteban-OpenSea** [comment]
Please refer to [this ](https://github.com/ProjectOpenSea/opensea-js/issues/471) ticket to track the latest dependency and sdk installation issues.
