### ISSUE TITLE
Testnet 525 error

### ISSUE THREAD

**Issue by bmayen** [ProjectOpenSea/opensea-js#486]
Requests to Testnet https://rinkeby-api.opensea.io/ return 525 error  from Cloudflare.

Error 525 Ray ID: 7002873b2e793b69 • 2022-04-23 00:37:01 UTC
SSL handshake failed

**Comment by bmayen** [comment]
Looks like the url changed but documentation wasn't updated.

https://docs.opensea.io/reference/rinkeby-api-overview claims the url is https://rinkeby-api.opensea.io/api/v1/

Actual examples are CURLing https://testnets-api.opensea.io/api/v1/

**Comment by chrisackermann** [comment]
Yes, that's right - thanks for the catch!

We've just updated [that page in our docs](https://docs.opensea.io/reference/rinkeby-api-overview) to reflect the correct base URL.
