### ISSUE TITLE
Intermittent cors issues with opensea-js

### ISSUE THREAD

**Issue by pguardiario** [ProjectOpenSea/opensea-js#487]
Some of my requests are getting blocked today from https://api.opensea.io/wyvern/v1/orders/post/
It looks like opensea changed the cors headers or has something misconfigured.
Can someone weigh in on if this was intentional or not please?

**Comment by esteban-OpenSea** [comment]
Check out this issue for CORS https://github.com/ProjectOpenSea/opensea-js/issues/210

Your issue must have occurred when there was some sort of outage. So it was only temporary. Please confirm if you are still running into issues.

**Comment by pguardiario** [comment]
I'm still seeing cors errors at this endpoint:
https://api.opensea.io/wyvern/v1/orders/post/

**Comment by asghaier76** [comment]
@esteban-OpenSea still seeing the CORS issue, there was a change in the API path url to remove the api segment and that has caused now all api calls to retrun CORS error
