### ISSUE TITLE
opensea-js is sending empty payloads in production

### ISSUE THREAD

**Issue by pguardiario** [ProjectOpenSea/opensea-js#491]
For some reason createBuyOrder is sending enpty payloads in production:

![image](https://user-images.githubusercontent.com/58795222/165009989-daa22474-cd5a-41a4-830f-33af676c3b0a.png)

The same thing is working fine in development though.

![image](https://user-images.githubusercontent.com/58795222/165010227-5ff4bffb-8413-49b1-bea3-ba79ae321a18.png)

Can someone suggest what might cause that?

**Comment by esteban-OpenSea** [comment]
Can you send more information? Or specific steps to reproduce this?
