### ISSUE TITLE
No "sell_orders" in api call for Decentraland

### ISSUE THREAD

**Issue by spoonknife22** [ProjectOpenSea/opensea-js#50]
For an api call for assets in Decentraland I get and empty []. 

https://api.opensea.io/api/v1/assets?asset_contract_address=0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d&order_by=sale_count&order_direction=desc&on_sale=true&offset=0&limit=20'

result:
"sell_orders": []

**Comment by yyh1102** [comment]
Same issue. Seams like the response from `/api/v1/asset` has changed.
