### ISSUE TITLE
HTTP eror 503

### ISSUE THREAD

**Issue by Cookiezzz** [ProjectOpenSea/opensea-js#500]
Since about a day I'm getting loads of 503 errors.

```
10:31:43 [Warning] : Request failed with ServiceUnavailable. Waiting 00:00:01 before next retry. Retry attempt 3. Response: StatusCode: 503, ReasonPhrase: 'Service Temporarily Unavailable', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Wed, 27 Apr 2022 08:31:45 GMT
  Connection: keep-alive
  CF-Ray: 702634220b622e14-BRU
  Strict-Transport-Security: max-age=0; includeSubDomains; preload
  Vary: Accept-Encoding
  CF-Cache-Status: EXPIRED
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  X-Content-Type-Options: nosniff
  Server: cloudflare
  Content-Type: application/json; charset=utf-8
  Content-Length: 58
}
```

Also have been seeing the message below sometimes. Not sure if related.
`{"message":"failure to get a peer from the ring-balancer"}`

**Comment by yanisbakh** [comment]
Also having the  {"message":"failure to get a peer from the ring-balancer"} error since yesterday.
It happens randomly, for requests that usually work.

**Comment by Cookiezzz** [comment]
Additionally I'm getting a ton of request timeouts. Pages just not responding.

**Comment by 0xTC0** [comment]
Can confirm "failure to get a peer from the ring-balancer"} error as well.. Request is being made with api key.

**Comment by misterjame** [comment]
+1

**Comment by sebastiantimwagner** [comment]
This is also happening to me. I'm assuming this is due to a problem of the API Gateway reaching the Backend services in the underlying Kubernetes cluster and not a `opensea-js` issue at all. The error message seems to come from [Kong](https://github.com/Kong/kong), which acts as an Ingress to the API pods.

**Comment by chrisackermann** [comment]
Hey everyone - just a heads up that we're working on a fix for these 503s coming from the API and we'll update here once it's in place.  Thanks!

**Comment by LuciooF** [comment]
Also having this issue, commenting to get notified when fixed! <3

**Comment by chefmike01** [comment]
Same here

**Comment by chefmike01** [comment]
> Hey everyone - just a heads up that we're working on a fix for these 503s coming from the API and we'll update here once it's in place.  Thanks!

Any update?

**Comment by esteban-OpenSea** [comment]
Is this still an issue for some of you?

**Comment by esteban-OpenSea** [comment]
Additionally, can you send over some specific steps so I can reproduce this issue?

**Comment by josephkelada** [comment]
Hey, still getting this error using this endpoint, I have a loop runs with request with a different wallet at every iteration 
url_events = f"https://api.opensea.io/api/v1/events?account_address={current_wallet}&event_type=successful&limit=10&occurred_before=1661538780.0&occurred_after=1661437980.0"
