### ISSUE TITLE
Can I create a new NFT using opensea sdk?

### ISSUE THREAD

**Issue by omkarwemoveideas** [ProjectOpenSea/opensea-js#503]
Hi,

I am planning to create a new NFT using opensea sdk from my dapp is there any sdk which helps me create a nft from my dapp?

**Comment by esteban-OpenSea** [comment]
I recommend going through this tutorial: https://docs.opensea.io/docs/creating-an-nft-contract

Considering this isn't an issue affecting the sdk, I will go ahead and close this ticket. Feel free to reach out on the [developer discord](https://discord.com/channels/397566282729390110/434175585745633280) if you have any other questions.
