### ISSUE TITLE
set a price for the collection

### ISSUE THREAD

**Issue by geforce092** [ProjectOpenSea/opensea-js#504]
Hello community. I mint a collection of nft at opensea for myself (1000 nft). now i want to sell the minted collection - and for each nft i have to click "sell" and enter the price and period. for 1000 nft this is a very long time. Can I get help here? to make it faster?

**Comment by geforce092** [comment]
I'm using the "hashlips" contract

![ScreenShot_20220428132745](https://user-images.githubusercontent.com/103051819/165700090-2e9ee349-40e1-4c50-a8dc-5b437136257c.png)

**Comment by esteban-OpenSea** [comment]
Check this out: https://github.com/ProjectOpenSea/opensea-js#making-listings--selling-items

I also recommend going through this tutorial: https://docs.opensea.io/docs/opensea-initial-item-sale-tutorial

Considering this isn't an issue affecting the sdk, I will go ahead and close this ticket. Feel free to reach out on the [developer discord](https://discord.com/channels/397566282729390110/434175585745633280) if you have any other questions.
