### ISSUE TITLE
DEPRECATED: Please use providerUtils.standardizeOrThrow() instead

### ISSUE THREAD

**Issue by cto-aarchik** [ProjectOpenSea/opensea-js#509]
I'm having trouble using the openseas.js library. I'm trying to do a getAsset call on a random asset on openseas I found, but I keep getting

Error: DEPRECATED: Please use providerUtils.standardizeOrThrow() instead

**Comment by jozhi** [comment]
I ran into the same problem and couldn't find an answer. I suspected something was wrong with the project itself.

**Comment by jimmyjimmy94** [comment]
Got the same problem too for both node 16 and node 14.
Node 14 will throw:
`DEPRECATED: Please use providerUtils.standardizeOrThrow() instead
TypeError: supportedProvider.send.toString(...).replaceAll is not a function`

whilte Node 16 gives
`DEPRECATED: Please use providerUtils.standardizeOrThrow() instead
DEPRECATED: Please use providerUtils.standardizeOrThrow() instead`

**Comment by nguyenkduywork** [comment]
I can confirm this is my case as well

**Comment by esteban-OpenSea** [comment]
Make sure you are using the latest version of the sdk and ensure your dependencies are up to date.

**Comment by adamskrodzki** [comment]
They are, 
i have same problem on 


    "opensea-js": "^4.0.13",

**Comment by alandotcom** [comment]
This is still an issue
