### ISSUE TITLE
API Error "WyvernV2.3 exchange data not valid"

### ISSUE THREAD

**Issue by JTskinz** [ProjectOpenSea/opensea-js#513]
When trying to place an order I am getting a confirmation that the funds are available and hashes match but then am getting the following error:  

Already approved enough currency for trading
Order hashes match
(node:16496) UnhandledPromiseRejectionWarning: Error: API Error 400: ["WyvernV2.3 exchange data not valid.

**Comment by david043** [comment]
Up

**Comment by Medivhus** [comment]
Getting the same error on main, scripts all worked on testnet and now that we want to open the real sale it always ends up with the error from above.

Tried having a fixed price sale for 1 object or 10 (thought maybe 10 was "too much" and being throttled, but nope, 1 has the same error)

Any advice on what might be the issue would be great.
