### ISSUE TITLE
Error in API getOrder  return result

### ISSUE THREAD

**Issue by kenneyLee** [ProjectOpenSea/opensea-js#514]
Api getOrder return an order object, in it,  this field 'saleKind'  should represent a fixed price or auction. However, whether NFT is a fixed price or auction on opensea website,  this field is always 0 - fixedprice in the data returned by the API.

for example：

https://opensea.io/assets/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/2655
https://opensea.io/assets/0x306b1ea3ecdf94ab739f1910bbda052ed4a9f949/2280

 
<img width="403" alt="image" src="https://user-images.githubusercontent.com/1628572/167449748-504178e1-30e7-40a7-90c2-3af2bdf907d8.png">

**Comment by esteban-OpenSea** [comment]
Does this happen when using hdwallet?

Also, please ensure you are using the latest version of node and the sdk
