### ISSUE TITLE
Owner of Collection

### ISSUE THREAD

**Issue by damianlluch** [ProjectOpenSea/opensea-js#515]
Hi, we are using the opensea API to bring in collections, assets, etc.
The issue is that the collection doesn't have the owner.....
How can we get it?
It could be that the onwer address of the collection is the payout_address ? field (which is a proxy contract). So I would have to find the address of the creator of that contract somehow.

thanks

**Comment by kolbis** [comment]
+1

**Comment by esteban-OpenSea** [comment]
That’s only for ERC1155 items, which do not have any single owner. ERC721 collections do.

For instance, check this out: https://api.opensea.io/asset/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/1
