### ISSUE TITLE
testnets API `wyvern/v1/orders` returns 401 even if without X-API-KEY in headers

### ISSUE THREAD

**Issue by nekoze1210** [ProjectOpenSea/opensea-js#516]
It was occurred since 3 hours ago (about 2022-05-10 10:00 UTC) 

```
$ curl --location --request GET 'https://testnets-api.opensea.io/wyvern/v1/orders?limit=20&offset=1&side=1'  --header 'Accept: application/json'

Invalid API key
```

**Comment by yoss1209** [comment]
Me either

**Comment by microHoffman** [comment]
Same here

**Comment by neocho** [comment]
Same here!

**Comment by alexreyes** [comment]
Yup getting this same error as of a couple of hours ago. Pretty frustrating

**Comment by alexreyes** [comment]
@alexanderatallah @sunwrobert @Meemaw is this a known issue?

**Comment by nick** [comment]
According to William on the OpenSea Discord, you now need a separate testnet API key

**Comment by pguardiario** [comment]
> According to William on the OpenSea Discord, you now need a separate testnet API key

Wonderful, does he say where we get one of those?

**Comment by yoss1209** [comment]
![image](https://user-images.githubusercontent.com/46311444/167759229-8c2a7a82-5b83-4124-a036-1cde4bb10380.png)

**Comment by yoss1209** [comment]
> > According to William on the OpenSea Discord, you now need a separate testnet API key
> 
> Wonderful, does he say where we get one of those?

https://docs.opensea.io/reference/rinkeby-api-overview

**Comment by pguardiario** [comment]
This just redirects to the mainnet request form...

**Comment by kenneyLee** [comment]
Same

**Comment by OlegDO** [comment]
Same error

**Comment by pguardiario** [comment]
This is clearly a mistake, right? Nobody thinks separate api keys for testnet makes sense I hope...

**Comment by KenRandall** [comment]
Really annoying!

**Comment by yoss1209** [comment]
Updates. I have got the API key for testnet so now I can use API as usual.

**Comment by nekoze1210** [comment]
@yoss1209 Where did you get testnets API key from?
In my own perception, testnets API did not require API Key, but it has updated?

**Comment by yoss1209** [comment]
> @yoss1209 Where did you get testnets API key from? In my own perception, testnets API did not require API Key, but it has updated?

- I got it from opensea's team. They sent me via DM.
 - Yes, it's updated, it requires API for testnet separately.

**Comment by KenRandall** [comment]
Did you have to go through the request process again or did you just email them?

**Comment by pguardiario** [comment]
Can someone share it here please? I just need to make a few requests with it and then hopefully never deal with this again.

**Comment by yoss1209** [comment]
> Did you have to go through the request process again or did you just email them?

I was asking for an API key for testnet on Discord (developer channel) then opensea's team sent me the API key via private message.

**Comment by fernandojs** [comment]
some here.

Invalid API key

**Comment by kenneyLee** [comment]
> > Did you have to go through the request process again or did you just email them?
> 
> I was asking for an API key for testnet on Discord (developer channel) then opensea's team sent me the API key via private message.

I also applied on discord, but so far there has been no official response. It's a bunch of swindlers trying to let me use their wallet.

**Comment by nekoze1210** [comment]
I also received a scam link from a friend request after sending a request in Discord. We should be careful.
I think that this is just a bug of testnets API. We have to wait for an official announce

**Comment by KenRandall** [comment]
I find it difficult to know whether you are actually talking to someone from OpenSea or not. If what I have been told is true you need at leat 0.09 of real ETH to get an API Key!!!

**Comment by KenRandall** [comment]
Do OpenSea look at these issues?

**Comment by fernandojs** [comment]
Alert: Never answer DM on Discord. It's 100% scammers.

**Comment by MetalGear-cmd** [comment]
Can anyone share the testnet API Key?

**Comment by cz0634** [comment]
https://testnets-api.opensea.io/wyvern/v1/orders

The result returned by this API is "API Error 401: Unauthorized. Full message was 'Invalid API key'",How can I make it work?

**Comment by esteban-OpenSea** [comment]
@kenneyLee is correct, you no longer need an api key for testnets
