### ISSUE TITLE
I get "Transfer calldata doesn't match"

### ISSUE THREAD

**Issue by pastet89** [ProjectOpenSea/opensea-js#517]
Issue #385 does not refer to me. Everything was working until today and I started to get this error when I try to make an offer.

Edit: Interestingly, it happens on this collection (which has long token ids): `0x495f947276749ce646f68ac8c248420045cb7b5e`

**Comment by theboxer** [comment]
I have same issue, using the 3.0.4 version of the SDK. Submitting offer to this collection `0x497a9A79e82e6fC0FF10a16f6F75e6fcd5aE65a8` which is ERC1155 doesn't work and I get the `"Transfer calldata doesn't match"` error.

Sending offer for example to `0x8a90cab2b38dba80c64b7734e58ee1db38b8992e` works fine.

**Comment by kenneyLee** [comment]
I've been in the same issue，Because But I'm missing the 'schemaname'

**Comment by kenneyLee** [comment]
I've been in the same issue，But I'm missing the 'schemaname' field

**Comment by theboxer** [comment]
@kenneyLee That resolved my issue as well. Not sure why I thought the SDK will fetch the correct schemes name on its own

**Comment by esteban-OpenSea** [comment]
So are you only running into the issue for ERC1155 assets?
