### ISSUE TITLE
Is it possible to submit orders through Opensea SDK from a multisig (like gnosis safe)?

### ISSUE THREAD

**Issue by Priyanshu1609** [ProjectOpenSea/opensea-js#518]

**Comment by blokboy** [comment]
have also been inquiring about this since the upgrade.

**Comment by Priyanshu1609** [comment]
Did you get any solutions?

**Comment by blokboy** [comment]
none at the moment. bids seem to be okay but buy/sell orders are flat out rejected by contract addresses at the moment it would appear.

**Comment by mbotboi** [comment]
Are you sure it doesnt work at all?
Maybe OS is checking for whether or not the contract can receive an nft with something like onERC721Received?

either that or the signatures done was not accurate?

**Comment by detroitcoder** [comment]
I am also unable to list via Open Sea and Gnosis Safe via Wallet Connect. Also unable to list on Looks Rare and Gem all using Wallet Connect. Tried with Chrome and MS Edge using Wallet Connect while authing through Gnosis Safe desktop and iOS app. No combination seems to work for listing.

**Comment by esteban-OpenSea** [comment]
These are the wallets you can use with OpenSea: https://support.opensea.io/hc/en-us/articles/1500007978402-What-crypto-wallets-can-I-use-with-OpenSea-
