### ISSUE TITLE
Support with safeTransferFrom

### ISSUE THREAD

**Issue by damianlluch** [ProjectOpenSea/opensea-js#521]
Hi, now I have the problem with the safeTransferFrom(..) after running the setApprovalForAll() with an OpenSea erc1155 (my token).
The setApprovalForAll() runs fine, and I can see its hash and transaction check.
Now, with the safeTransferFrom() I get the hash, but when I go to look it up in Rinkeby, it doesn't exist.
I'm using Alchemy.

Any suggestions?

thanks

**Comment by lkc93** [comment]
Hey @damianlluch I'm having a similar problem, how did you resolve? :)
