### ISSUE TITLE
Support with safeTransferFrom

### ISSUE THREAD

**Issue by damianlluch** [ProjectOpenSea/opensea-js#523]
Hi, I am doing a job to load collections and their opensea tokens in another project and sell them with user approval.

The issue is that I have created a token in Rinkeby, and from my script, I setApprovalForAll() with my address to an address X to the OpenSea contract that is in the token and it runs without problems.
The problem is when I want to transfer that token from the approved address. When I call safeTransferFrom()... I get 

Fail with error 'AssetContractShared#_requireMintable: ONLY_CREATOR_ALLOWED'.

I've been reading around, and some say it's because you have to mine the token from the owner first...but I've tried that too, and I get the same message as when I call safeTransferFrom().

Any suggestions?

thanks

**Comment by esteban-OpenSea** [comment]
Please send over the contract address so i can review
