### ISSUE TITLE
How can I fix this warnings?

### ISSUE THREAD

**Issue by carlosbalsas** [ProjectOpenSea/opensea-js#525]
Hi, after version 3.x I received these warnings, anyone knows how I can solve this?

> Compiled with problems:
> 
> WARNING in ./node_modules/ethers/dist/ethers.min.js 1:484-485
> 
> Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

and this 

> inpage.js:1 MetaMask: The event 'close' is deprecated and may be removed in the future. Please use 'disconnect' instead.

> log_utils.js:20 DEPRECATED: Please use providerUtils.standardizeOrThrow() instead

**Comment by esteban-OpenSea** [comment]
For the ethers issue, try deleting all your node_modules files, deleting yarn.lock or package.lock. Then upgrade your dependencies to the latest version, then download them again.

For metamask, try using the latest node version. I would also encourage you to use the latest version of the sdk.

**Comment by carlosbalsas** [comment]
> For the ethers issue, try deleting all your node_modules files, deleting yarn.lock or package.lock. Then upgrade your dependencies to the latest version, then download them again.
> 
> For metamask, try using the latest node version. I would also encourage you to use the latest version of the sdk.

I tried that method for the ethers issue, but this still appears.

**Comment by javiercr** [comment]
I'm also finding the `DEPRECATED: Please use providerUtils.standardizeOrThrow() instead` error.

It seems it comes from here:
https://github.com/0xProject/0x-monorepo/blob/53b5bb16d8b4c9050a46978b6f347ef7595fe103/packages/assert/src/index.ts#L78

Which is invoked by wyvern-js:
https://github.com/ProjectOpenSea/wyvern-js/blob/master/src/wyvernProtocol.ts#L395

**Comment by Raketa-Kotleta** [comment]
I solved the problem about "Critical dependency: require function is used in a way in which dependencies cannot be statically extracted". 
If you use webpack, just add module.unknownContextCritical: false. It is just warning, thats why you can ignore it. It is not good practice, but it works.

**Comment by ryanio** [comment]
please try with the latest version, this should be fixed now
