### ISSUE TITLE
TransferProxy question

### ISSUE THREAD

**Issue by damianlluch** [ProjectOpenSea/opensea-js#529]
Hi, I've been trying to sell an OpenSea token on another marketplace for a few days now, and I can't quite figure out how to do it.
I have tested that from OpenSea to Rarible, and vice versa it is possible to synchronize, and sell tokens from one marketplace in the other.
I'm trying to do the same, but with another marketplace.
I'm reading some article out there, that says that in OpenSea, each user has a proxy contract? 
Where is that contract? with that contract I should interact to give setApprovalForAll() to another contract (in this case erc1155) ?

Thanks!

**Comment by esteban-OpenSea** [comment]
Can you provide what steps you've been attempting to do this?

Is [this](https://docs.opensea.io/docs/1-structuring-your-smart-contract#:~:text=On%20OpenSea%2C%20each%20user%20has,they%20wish%20to%20do%20so.) the article you were referring to?

Regarding setApprovalforAll(), you have to be careful. When using setApprovalForAll you are trusting the smart contract to be able to transfer 100% of the token. In some cases, some smart contracts have bugs or can be broken.
