### ISSUE TITLE
createBuyOrder calls contract and costs ETH

### ISSUE THREAD

**Issue by 1Demo** [ProjectOpenSea/opensea-js#530]
Hi, I have programmed an Opensea bidding bot, which worked perfectly fine some days ago. Suddely it doesn't without changing anything in the code. 
Now if I start my bot again, it calls the "approve" method Wrapped Ether contract, as you can see on my [Etherscan account](https://etherscan.io/address/0x164e0fa20e869af37e5fad9709b845ce0399e851). This costs me around $1-$2 for each bid I do and the bids aren't even placed. I am using version 3.0.4

Did something got changed without me noticing it? 

Thanks in advance

**Comment by Superpassteque** [comment]
It can happen when api is down and request are not passing correctly

**Comment by 1Demo** [comment]
It's happening for the last few days for me. Is this for everyone right now?

**Comment by 1Demo** [comment]
Hi, I've tried it again, got this error again. I'm not sure if I'm the only one.

```
[ERROR] 2022-06-08T20:56:56.779Z Offer failed Error: API Error 429: Message: {"detail":"Request was throttled."}
[EXIT]  2022-06-08T20:56:56.850Z OS Request-Limit reached

```

**Comment by esteban-OpenSea** [comment]
Hey, are you still running into that last error you sent over?

Have you checked our status page for potential interruptions? OpenSea Status [https://status.opensea.io/](https://status.opensea.io/) 

Please try retesting to ensure it was not a temporary interruption.
