### ISSUE TITLE
Some bots still able to submit orders

### ISSUE THREAD

**Issue by simonare** [ProjectOpenSea/opensea-js#532]
Guys, how does some bots continue to use programmatic order submission? here is one @[flash-boi-4](https://opensea.io/flash-boi-4)

I couldn't understand this. Is he using something low level? what is it?

**Comment by Superpassteque** [comment]
probably a god api key. Or region dependant, or somehow submit directly to endpoint behind cloudfare but odds are low imo.

To submit order you have to sign the tx and submit it to opensea database so I don't see many way to do it that fast ( he is bidding every second)

**Comment by SourceSafe** [comment]
Hi  I have the same issue.

When I createBuyOrder() using the SDK all of my calls are now giving me 429 errors.

This is irrespective of whether order submission is enabled or not. This has been an issue for approx 2 weeks and is still a problem when order submission is enabled and GREEN. But yeah I appreciate that the status has been down a lot but even when it's green i cannot bid.

My keys used to work perfectly.

I have submitted a ticket, please take a look :-

563139

**Comment by esteban-OpenSea** [comment]
@simonare , although we appreciate your concern. This isn't an issue necessarily related to the SDK, so I will go ahead and close it.

If you want us to take a look at your api key, please open a ticket [here](https://support.opensea.io/hc/en-us/requests/new) and we can help there.
