### ISSUE TITLE
Version 4.0.0 of SDK. Where is it?

### ISSUE THREAD

**Issue by laaaaaaka** [ProjectOpenSea/opensea-js#535]
Hello,

When is the new Version 4.0.0 of SDK with seaport support is going live? I can still only see 3.0.4, but this Opensea article https://nft.mirror.xyz/Bi_UbdXOi4AU3LtHT3WoLAN0a9YIWE2gYQmkyZ5whVM refers to 4.0.0, which is not available for this npm package / this repo?

**Comment by kebian** [comment]
Their docs are missing a lot of critical data too.  They don't even specify what the endpoint url is for mainnet.

**Comment by chrisackermann** [comment]
@laaaaaaka v4.0.0-beta is going live today (May 26) - will comment here when it's available.

**Comment by chrisackermann** [comment]
@laaaaaaka just wanted to follow up that v4.0.0-beta is now live: https://www.npmjs.com/package/opensea-js/v/4.0.0-beta.0

Closing this issue out, but please re-open if any other questions on this.

**Comment by laaaaaaka** [comment]
Hello @chrisackermann. I started integrating it, but it seems there is no assets on Rinkeby yet listed on new Seaport contracts. Like what is the way to test now the whole thing? I tried listing asset on test.opensea, but it seems to be listing/making offers to old wyvern contracts. What is the way to list on Seaport through UI and to test everything: like buying / making offer? Thanks

**Comment by chrisackermann** [comment]
Hi @laaaaaaka - we don't yet have the ability to create listings/offers through our UI yet.  Currently this is only supported through the SDK/API for testing.
