### ISSUE TITLE
Can I retrieve more than 50k collections?

### ISSUE THREAD

**Issue by metacopy** [ProjectOpenSea/opensea-js#537]
Hello! In "Retrieve collections" there are limit of 300 and offset for max 50k as I found out. So I can not retrieve all collections? There are too many trash collections. So I need to retrieve all to filter them at least by sales (exclude 0 sales collections). But I can not retrieve more than 50k. Any workaround? Thank you!

**Comment by consigliere23** [comment]
No you can't.

**Comment by metacopy** [comment]
But what is the point then to get 50k collections 99% of which are just trash?

**Comment by consigliere23** [comment]
I am not sure, I have been trying to get more but could not get it, wrote on discord but without any solution to this. Sadly it's just like that.

**Comment by esteban-OpenSea** [comment]
We only paginate up to 10k items in our API

**Comment by metacopy** [comment]
> We only paginate up to 10k items in our API

How then I could get active collection filtered from trash? If first 10k items are 90% or even 50% spam collections - what is the use case for these?
