### ISSUE TITLE
Retrieving Orders endpoint - "count" attribute seems to be broken

### ISSUE THREAD

**Issue by MarekBiczysko** [ProjectOpenSea/opensea-js#539]
Hi!

There seems to be an issue in below endpoint:
https://docs.opensea.io/reference/retrieving-orders
https://api.opensea.io/wyvern/v1/orders

"count" attribute in all response is hardcoded to value "1".

**Comment by esteban-OpenSea** [comment]
Thanks for bringing this up, we note this in our documentation.

`Side is now a required parameter. Please pass side=0 for buy orders and side=1 for sell orders. As a note, when you call the orders endpoint, count will always return 1.`

https://docs.opensea.io/reference/retrieving-orders
