### ISSUE TITLE
GetAssetBalance outdated?

### ISSUE THREAD

**Issue by Benjythebee** [ProjectOpenSea/opensea-js#54]
I tried the code in the example to obtain the asset Balance of an ERC1155
I have the following asset variable:
```
    this.asset = {
      tokenAddress: asset.asset_contract.address, 
      tokenId: asset.token_id, 
      schemaName:'ERC1155'
    }
```
   
 and then the following code to obtain the asset balance

```

let accountAddress = this.parcel.owner
    let asset= this.asset
    const balance = await this.seaport.getAssetBalance({
      accountAddress, // string
      asset, // Asset
    })

```

   However I keep obtaining the following error:
   
![image](https://user-images.githubusercontent.com/38708022/104271096-da8c8280-54fe-11eb-8733-6b166398935c.png)
the `contract` function does not exists on web3.eth anymore?

According to [https://github.com/ChainSafe/web3.js/issues/985](https://github.com/ChainSafe/web3.js/issues/985)
it's now `web3.eth.Contract()` but I'm not certain of that.

**Comment by alexanderatallah** [comment]
Look like two different versions of web3 being used. Try using yarn instead of npm

**Comment by Benjythebee** [comment]
That's likely, we also try to use ethers.js more but it seems Opensea won't port the api to ethers.js as mentioned in #28

**Comment by Benjythebee** [comment]
Ok so I re-installed `opensea-js@latest` and it automatically updated web3 to `"web3": "^1.0.0-beta.37",`
However now when doing 
```js
const transactionHash = await this.seaport.fulfillOrder({ order, accountAddress })
```

it returns
```
TypeError: web3.isAddress is not a function
    at Object.validateAndFormatWalletAddress (utils.js:911)
    at OpenSeaPort._makeMatchingOrder (seaport.js:2320)
    at OpenSeaPort.<anonymous> (seaport.js:867)
    at step (seaport.js:40)
    at Object.next (seaport.js:21)
    at seaport.js:15
    at new Promise (<anonymous>)
    at __awaiter (seaport.js:11)
    at OpenSeaPort.fulfillOrder (seaport.js:861)
```

**Comment by Benjythebee** [comment]
I downgraded the web3 version to 0.20.7 - which is the same as the one used by opensea-js and now it works fine.
Weird though
