### ISSUE TITLE
Can we use opensea-js for testnet environment with testnet APIs without any API Key?

### ISSUE THREAD

**Issue by koinfox** [ProjectOpenSea/opensea-js#542]
Is it possible to use opensea-js sdk with Testnet APIs without API Key?
If any testnet API Key is required, from where we will get that?

**Comment by esteban-OpenSea** [comment]
Yes, you no longer need an api key for Testnets.

**Comment by koinfox** [comment]
How to provide the infura project id to the opensea sdk?

**Comment by koinfox** [comment]
Replying to my own question just for the other people in case they also don't know,
When providing the provider url to the opensea sdk, just pass the project id in the url.

`https://ropsten.infura.io/v3/PROJECT_ID`

**Comment by hasseneafif** [comment]
For the people that said that it's possible, how, like what do i put as a api key
