### ISSUE TITLE
OpenSea-sdk always return nullAddress owner

### ISSUE THREAD

**Issue by JavierBrooktec** [ProjectOpenSea/opensea-js#543]
When calling seaPort.api.getAsset({ tokenAddress, tokenId }) always returns this inside the owner object.

```javascript
{
  "user": {
    "username": "NullAddress"
  },
  "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
  "address": "0x0000000000000000000000000000000000000000",
  "config": ""
}
```

**Comment by esteban-OpenSea** [comment]
The individual asset endpoint should have the correct owners under "top_ownerships". But I will look into this a bit further.

**Comment by JavierBrooktec** [comment]
@esteban-OpenSea if you want an example, for this asset I get that output, if you need more 
 just tell me 🙂 , the API is fine but the SDK not https://opensea.io/assets/ethereum/0xf12c994fd8e3aa2bf6ecafcd82181f6c9d8111a5/58

**Comment by esteban-OpenSea** [comment]
That’s only for ERC1155 items, which do not have any single owner. ERC721 collections do.

For instance, check this out: https://api.opensea.io/asset/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/1
