### ISSUE TITLE
how to make connection to the Klaytn network(cypress, baobab) using seaport sdk

### ISSUE THREAD

**Issue by HaeSim** [ProjectOpenSea/opensea-js#545]
Currently, SDK seems to support Ethereum only. But, the Opensea API seems to support Klaytn, can I customize it to connect to the Cypress/Baobab network using caver.js?

**Comment by esteban-OpenSea** [comment]
As of now, we only support ethereum. But we hear you and are working on making our SDK better!

**Comment by HaeSim** [comment]
ok, thank you🥲
