### ISSUE TITLE
Unable to use transferAll

### ISSUE THREAD

**Issue by wholelott4** [ProjectOpenSea/opensea-js#549]
Hello, how can I use transferAll to generate a transaction to send to the frontend to be signed or something like this?
I mean, is it possible to create a raw transaction through the transferAll endpoint or something like this? So I can send it to the frontend to be signed? Instead of writing the code in the frontend..

Because, what about if I have a wallet with the privateKey? how can I use it to sign the transfer

**Comment by simonare** [comment]
I think you are lost in the concept. 

If you want your transactions to be signed via Metamask, you can attach to MetaMask Wallet Provider.  In this case, you dont need to use private key to connect to the wallet. your app will connect with a wallet via metamask.

If you dont want to use Metamask ( user interaction), you can use HDWalletProvider. But then, you will need to access wallet via private key or mnemonic. If that is the case, you need to decouple your application's front-end with back-end. your secrets are needed to be in your backend.

**Comment by wholelott4** [comment]
> I think you are lost in the concept.
> 
> If you want your transactions to be signed via Metamask, you can attach to MetaMask Wallet Provider. In this case, you dont need to use private key to connect to the wallet. your app will connect with a wallet via metamask.
> 
> If you dont want to use Metamask ( user interaction), you can use HDWalletProvider. But then, you will need to access wallet via private key or mnemonic. If that is the case, you need to decouple your application's front-end with back-end. your secrets are needed to be in your backend.

Yes, but I want the user to transfer NFTS to one wallet, and then I have my own wallets with private key that I want to use this method too. Using the private key..

**Comment by esteban-OpenSea** [comment]
@simonare makes a good point. It depends on how you want your transactions to be signed. You can use [web3.js](https://docs.ethers.io/v5/api/providers/) or [ethers](https://docs.ethers.io/v5/api/providers/).
