### ISSUE TITLE
Cannot read property 'EIP712Domain' error on Version 4.0.0

### ISSUE THREAD

**Issue by Racherin** [ProjectOpenSea/opensea-js#550]
There was an error about signing data after migrating to V 2.0.0 based on issue #372 .

I'm facing with same issue again after trying to use 4.0.0-beta.1 version.  @truffle/hdwallet-provider throws same error again. 

```shell
/node_modules/@truffle/hdwallet-provider/node_modules/eth-sig-util/dist/index.js:172
        if (results.includes(primaryType) || types[primaryType] === undefined) {
                                                  ^
TypeError: Cannot read properties of undefined (reading 'EIP712Domain')
```

Using a eth_signTypedData fallback should fix this issue but I see that it's implemented already.
```javascript
export async function signTypedDataAsync(
  web3: Web3,
  message: object,
  signerAddress: string
): Promise<ECSignature> {
  let signature: JsonRpcResponse | undefined;
  try {
    // Using sign typed data V4 works with a stringified message, used by browser providers i.e. Metamask
    signature = await promisify<JsonRpcResponse | undefined>((c) =>
      (web3.currentProvider as AbstractProvider).sendAsync(
        {
          method: "eth_signTypedData_v4",
          params: [signerAddress, JSON.stringify(message)],
          from: signerAddress,
          id: new Date().getTime(),
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
        } as any,
        c
      )
    );
  } catch {
    // Fallback to normal sign typed data for node providers, without using stringified message
    // https://github.com/coinbase/coinbase-wallet-sdk/issues/60
    signature = await promisify<JsonRpcResponse | undefined>((c) =>
      (web3.currentProvider as AbstractProvider).sendAsync(
        {
          method: "eth_signTypedData",
          params: [signerAddress, message],
          from: signerAddress,
          id: new Date().getTime(),
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
        } as any,
        c
      )
    );
  }
```

**Comment by esteban-OpenSea** [comment]
Did you see this?

https://github.com/ProjectOpenSea/opensea-js/issues/372#issuecomment-1093117092

**Comment by Racherin** [comment]
@esteban-OpenSea Hey, I checked out mentioned comment but couldn't find any solution.

**Comment by matthewklinko** [comment]
> @esteban-OpenSea Hey, I checked out mentioned comment but couldn't find any solution.

Hey sis you end up finding a solution ? I can’t make any buy orders without this error ?

**Comment by perioh** [comment]
same issue @4.0.1

**Comment by gv1122** [comment]
the new protocol isnt available on that version though, anyone got any other solutions?

**Comment by MetalGear-cmd** [comment]
Getting same error while trying to make bid on an asset using the sdk version 4.0.2

**Comment by andrewlwn77** [comment]
I am also seeing the same error with the hardware wallet. 3.0.4 works still, but for how long?

**Comment by nextmove** [comment]
Getting this error when I run createBuyOrder with 4.0.0-beta.2, @truffle/hdwallet-provider.

**Comment by andrewlwn77** [comment]
The fallback function createSellOrderLegacyWyvern is still currently working, but when will the old contract be mothballed?

**Comment by nextmove** [comment]
> The fallback function createSellOrderLegacyWyvern is still currently working, but when will the old contract be mothballed?

On June 21, offers and listings can no longer be posted to the Wyvern 2.3 contract using OpenSea - and on July 13, offers and listings can no longer be fetched from the Wyvern 2.3 contract using OpenSea.
https://twitter.com/apiopensea/status/1536822790354894848

**Comment by Racherin** [comment]
@esteban-OpenSea any update on this ? there's only 1 day left before endpoint deprecated.

**Comment by xiaoyannzbbb** [comment]
same issue @4.0.1

**Comment by andrewlewinphsa** [comment]
> > The fallback function createSellOrderLegacyWyvern is still currently working, but when will the old contract be mothballed?
> 
> On June 21, offers and listings can no longer be posted to the Wyvern 2.3 contract using OpenSea - and on July 13, offers and listings can no longer be fetched from the Wyvern 2.3 contract using OpenSea. https://twitter.com/apiopensea/status/1536822790354894848

I really hope we can find a way forward on this. 1 day left before we can't make orders anymore.

**Comment by MarkMoranNZ** [comment]
> > @esteban-OpenSea Hey, I checked out mentioned comment but couldn't find any solution.
> 
> Hey did you end up finding a solution ? I can’t make any buy orders without this error ?

Hey Matthew. Would you mind contacting me re graphql? Se my profile for email. Cheers, Mark

**Comment by k-fujiwara-19** [comment]
I get the same issue with 4.0.3.

I used @3.0.4. 

However, when I run the script, I get the following error.
```
Error: API Error 400: Invalid request: "['Wyvern orders posted to the API are deprecated, except for shared storefront orders']"
```
So I updated @4.0.3 and ran the script one more time.
However, I got the following error.
```
TypeError: Cannot read properties of undefined (reading 'EIP712Domain')
```


The following is the actual script in which the error occurred.

```typescript
import Web3 from "web3";
import { Network, OpenSeaSDK } from 'opensea-js'
import HDWalletProvider from "@truffle/hdwallet-provider";
import { Asset } from "opensea-js/lib/types";


async function main(): Promise<void> {
  const provider = new HDWalletProvider({privateKeys: ["0x0"], providerOrUrl: "https://rinkeby.infura.io/v3/hoge"})
  const openseaSDK = new OpenSeaSDK(provider, {networkName: Network.Rinkeby});

  const assets: Asset[] = [
    {
      tokenAddress: "0x0",
      tokenId: "2",
    },
    {
      tokenAddress: "0x0",
      tokenId: "1"
    }
  ]

  const expirationTime = new Date("2022-07-31 23:59:59").getTime() / 1000;

  await openseaSDK.createSellOrder({
    asset: assets[0],
    accountAddress: "0x0",
    startAmount: 5,
    endAmount: 0.1,
    expirationTime,
  })
  console.log("done");
}

main();

process.on("unhandledRejection", (reason) => {
  console.error(reason);
  process.exit(1);
});
```
