### ISSUE TITLE
No Endpoint for Getting All Owners of an 1155 Token

### ISSUE THREAD

**Issue by johnnyshankman** [ProjectOpenSea/opensea-js#551]
The asset endpoint currently does not return all ownership information for an 1155. There is `top_ownerships` but that is incomplete. `ownerships` requires a account address. There is no way to query for all owners or anything like that, not even paged.

This issue is somewhat related but not the same: https://github.com/ProjectOpenSea/opensea-js/issues/543#issuecomment-1151749791

**Comment by caupcakes** [comment]
You can get this easily without opensea-js, using eth_call.

**Comment by esteban-OpenSea** [comment]
ERC1155 differs from ERC721 in that there can be multiple owners of the same erc1155 token index.  So it could potentially be a list of owners.
