### ISSUE TITLE
'listingTime is a required parameter' error message while sending order requests

### ISSUE THREAD

**Issue by Racherin** [ProjectOpenSea/opensea-js#554]
Hey, I've been getting lots of `listingTime is a required parameter` error message while sending offers using the https://api.opensea.io/wyvern/v1/orders/post/ endpoint. 

What could cause it, any ideas ?

**Comment by cwazuidema** [comment]
Hello @Racherin,

I have problems compiling the correct parameters to use the wyvern/v1/orders/post endpoint.

1. What part of the message needs to be signed?
2. How do I get the correct calldata for the message?

Do you maybe have a sample script for me?
