### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'asset' in undefined : seaport.js

### ISSUE THREAD

**Issue by koinfox** [ProjectOpenSea/opensea-js#555]
Facing the below issue while trying to call the fulfillOrder method of the Opensea sdk

opensea-js version 2.0.2

`ERROR Error: Uncaught (in promise): TypeError: Cannot use 'in' operator to search for 'asset' in undefined
TypeError: Cannot use 'in' operator to search for 'asset' in undefined
    at computeOrderParams (seaport.js:2615:1)
    at push.i51y.OpenSeaPort._makeMatchingOrder (seaport.js:2643:1)
    at OpenSeaPort.<anonymous> (seaport.js:951:1)
    at step (seaport.js:63:1)
    at Object.next (seaport.js:44:45)
    at seaport.js:38:1
    at new ZoneAwarePromise (zone-evergreen.js:1387:1)
    at push.i51y.__awaiter (seaport.js:34:1)
    at push.i51y.OpenSeaPort.fulfillOrder (seaport.js:945:1)`

**`const txnHash = await this.seaport_Client.fulfillOrder({
            order: order,
            accountAddress: user
        });`**
  
  Help would be appreciated.
  Thanks.

**Comment by itsthedoom** [comment]
@koinfox Can you upgrade to [Version 3.0.4](https://www.npmjs.com/package/opensea-js) and retest?

**Comment by koinfox** [comment]
Hi @itsthedoom ,

I have tried using the latest version, but I am working with node js version 12.16.1 and angular version 11.2.14
and
version 3.0.4 is not supporting on these configurations
Hence, cannot upgrade.

**Comment by koinfox** [comment]
Hi @itsthedoom 

I got it fixed in version 2.0.2 also.

In the below code,
`const txnHash = await this.seaport_Client.fulfillOrder({ order: order, accountAddress: user });`

order was undefined.

actual code to get order was 
`const order = await openseaSDK.api.getOrder({ side: OrderSide.Sell, ... })`
while I was using
`const { order, count } = await openseaSDK.api.getOrder({ side: OrderSide.Sell, ... })`

That was the reason.
Thanks for the help!


Though now I am facing another issue at next level.
**`Uncaught (in promise): Error: Failed to validate buy order parameters. Make sure you're on the right network!`**

Please help me in this issue.

**Comment by itsthedoom** [comment]
@koinfox When I run the npm test I see that all the tests are passing,  Can you share more info on the buy order you're validating?
