### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Deveshb15** [ProjectOpenSea/opensea-js#557]
Can't I use ethers.js instead of web3.js have been much more familiar with ethers.js

**Comment by esteban-OpenSea** [comment]
Check this out: https://github.com/ProjectOpenSea/seaport-js#:~:text=Instantiate%20your%20instance%20of%20seaport%20using%20your%20ethers%20provider%3A

**Comment by JoshuaSchmidt-OpenSea** [comment]
Starting with v6 web3 is no longer a dependency of this project and it will solely use ethers.
