### ISSUE TITLE
[Bug] Haven't been able to import modules

### ISSUE THREAD

**Issue by Deveshb15** [ProjectOpenSea/opensea-js#558]
Followed the installation guide using react 17 but when I import OpenseaSDK I get this error for wyvern-schemes
![image](https://user-images.githubusercontent.com/72264218/173591533-ff966a23-cac8-4642-a800-cffb3d172a66.png)

Any ideas what could be causing this issue?

**Comment by marcelltoth** [comment]
It's probably another instance of the complications I mentioned here: https://github.com/ProjectOpenSea/opensea-js/issues/560#issuecomment-1156650199

It'd be so much more stable if you just released wyvern-schemas (and wyvern-js) normally as an NPM package and reference that instead. Or bundle it, whatever. GIT dependencies are not as stable as we'd like them to be unfortunately.

**Comment by esteban-OpenSea** [comment]
This is a similar issue to https://github.com/ProjectOpenSea/opensea-js/issues/560#issuecomment-1156650199

I'll go ahead and close this one to avoid duplicates, please follow the issue I linked for the latest updates on this.

Also, I would recommend joining our Discord where active members of the community are online and can help troubleshoot in realtime https://discord.gg/opensea
