### ISSUE TITLE
Type 'OrderSide.Sell' is not assignable to type 'OrderSide'.

### ISSUE THREAD

**Issue by riessnico** [ProjectOpenSea/opensea-js#568]
Hi! I'm implementing the OS sdk and ran into this issue. I've been trying all day to make it work. 

I'm simply copying the docs

`import { OrderSide } from 'opensea-js/lib/types'`
` const seaport = new OpenSeaPort(Web3.givenProvider, {apiKey: API_KEY, networkName: Network.Rinkeby})`
`const order = await seaport.api.getOrder({ side: OrderSide.Sell, asset_contract_address: contractAddress, token_id: 1,})`
`const transactionHash = await seaport.fulfillOrder({ order, accountAddress: address })`
    
    
    
The error is on the 'side' var
    
throws: 
    
`Type OrderSide.Sell is not assignable to type 'OrderSide.`
    
I'm running Node 16.15 and OS sdk ^4.0.0-beta.2

**Comment by esteban-OpenSea** [comment]
What is the `side` returning for you?

**Comment by riessnico** [comment]
Hi Esteban, thanks for the answer!

side returns: 
(property) side: OrderSide.

There is also another part for the error message that mentions type.d.ts:
`The expected type comes from property 'side' which is declared here on type 'Omit<OrdersQueryOptions, "limit">'`

which leads me to a OrderSide
`export declare type OrderAPIOptions = {`
    `protocol: OrderProtocol;`
    `side: OrderSide };`

OrderSide = 'ask'  | 'bid'
