### ISSUE TITLE
getOrder issue

### ISSUE THREAD

**Issue by Sam53534512** [ProjectOpenSea/opensea-js#570]
const order = await seaport2.api.getOrder({
            protocol:"seaport",
            assetContractAddress: req.asset_contract_address,
            tokenIds: [req.token_id],
            side: OrderSide.Buy,
        })  use the new version of the sdk,still return Not found: no matching order found.But The document is not updated，I'm not sure if the parameters are correct

**Comment by Whitecx** [comment]
Are you importing OrderSide?

**Comment by cheungchingli** [comment]
protocol: "seaport",
      assetContractAddress: NFT_ADDRESS,
      tokenIds: [TOKEN_ID],
      side: "ask",

**Comment by esteban-OpenSea** [comment]
@Sam53534512 , have you tried importing OrderSide like @Whitecx recommended?

**Comment by esteban-OpenSea** [comment]
@cheungchingli solution seems to work.

Check out this ticket with someone who had a similar issue: https://github.com/ProjectOpenSea/opensea-js/issues/572

**Comment by Ghijo1** [comment]
don't work for me too.

in the OrderJSON interface there is side: number; so if i type side: "ask" i get error

**Comment by cheungchingli** [comment]
> don't work for me too.
> 
> in the OrderJSON interface there is side: number; so if i type side: "ask" i get error.
> 
> My opensea-js version: 4.0.2

```any``` is everything!!!hahaha

```
  const order: any = await openseaSDK.api
    .getOrder({
      protocol: "seaport",
      assetContractAddress: NFT_ADDRESS,
      tokenIds: [TOKEN_ID],
      side: "ask",
    } as any)
    .catch((err) => {
      console.log(err, "could not find sell order for the specified asset");
      return;
    });
    ```

**Comment by Ghijo1** [comment]
> order

i dont know "any" in JS

i get this error "Types are not supported by current JavaScript version"

**Comment by cheungchingli** [comment]
i see,maybe you can use typescript

**Comment by Ghijo1** [comment]
> i see,maybe you can use typescript

thank you, but OpenSea official doc say to use NodeJS. I wont use TS
