### ISSUE TITLE
Opensea testnet bug for Goerli network

### ISSUE THREAD

**Issue by zuuring** [ProjectOpenSea/opensea-js#571]
Bug happening on Opensea testnet where Goerli links are always adding `rinkeby/goerli` instead of just `goerli` which causes pages to break.

see url: https://testnets.opensea.io/assets/rinkeby/goerli/0x88694d0b8c8E800AB3D9eecBF9A8923B3b5825fA for error

**Comment by vicnaum** [comment]
Tried with another collection - same, it autoreplaces, adding "rinkeby/" to the url:
https://testnets.opensea.io/assets/goerli/0xa835add6e449862bae23531cff8639f7754caf9f

**Comment by briangershon** [comment]
I'm seeing this as well.

Will `Goerli` be supported by OpenSea now that Rinkeby is deprecated?

**Comment by freitasgouvea** [comment]
I was also trying to test on the Goerli network and got the same error. Is there any other way to test on the Goerli network? Thanks

**Comment by grnrth** [comment]
Since Rinkeby is getting deprecated, Goerli should be the preferred testnet.

**Comment by Nazariy995** [comment]
I don't think they have support for Goerli right now!

**Comment by jhubbardsf** [comment]
They don't, but since Rinkeby is getting deprecated a lot of companies are also closing their Rinkeby support and transitioning to Goerli. Alchemy won't support Rinkeby after October 5th. For end to end testing to work I hope OpenSea has plans to switch over or at least offer a Goerli subdomain for testing.

**Comment by ihorbond** [comment]
Alchemy already went and [announced it on their Twitter](https://twitter.com/AlchemyPlatform/status/1565855110084694017) yet here we are -__-

**Comment by haowang1013** [comment]
This must be a really difficult bug to fix as otherwise I don't understand why it's still broken, especially considering Rinkeby will be deprecated soon. Well unless opensea just doesn't care about us developers here?

**Comment by haowang1013** [comment]
I wonder if a "broken opensea" NFT collection will be trending...

**Comment by jhubbardsf** [comment]
Looks like Goerli is working now for OpenSea. Was able to test my stuff the other day.
