### ISSUE TITLE
Can't getOrder

### ISSUE THREAD

**Issue by xiaoyannzbbb** [ProjectOpenSea/opensea-js#572]
"opensea-js": "4.0.1"

https://opensea.io/assets/ethereum/0x8b44b715004020773e8da1cd730de2f47c7d88b8/6410

```
const order = await seaPort.api.getOrder({ 
    protocol: "seaport",
    side: openSeaTypes.OrderSide.Sell, 
    assetContractAddress: '0x8b44b715004020773e8da1cd730de2f47c7d88b8', 
    tokenIds: ['6410'] });
```

Why this return:
```
node_modules/opensea-js/lib/api.js:129
                            throw new Error("Not found: no matching order found");
```

**Comment by Whitecx** [comment]
Is ```openSeaTypes.OrderSide.Sell``` resolving to "ask" or "bid"?
I dont see a reference to openSeaTypes in this repo. OrderSide is defined here: 
https://github.com/ProjectOpenSea/opensea-js/blob/2e2d779cde7fcdda6298846de6b5f8dd32df8294/src/orders/types.ts#L14

Here's a sample of the syntax for retrieving orders: [src/__tests__/sdk/getOrders.ts](https://github.com/ProjectOpenSea/opensea-js/blob/2e2d779cde7fcdda6298846de6b5f8dd32df8294/src/__tests__/sdk/getOrders.ts)

**Comment by cheungchingli** [comment]
protocol: "seaport",
      assetContractAddress: NFT_ADDRESS,
      tokenIds: [TOKEN_ID],
      side: "ask",

**Comment by esteban-OpenSea** [comment]
Thanks for testing out our 4.0 sdk beta!

@xiaoyannzbbb , can you send over specific steps to reproduce?

**Comment by xiaoyannzbbb** [comment]
> ```
>   protocol: "seaport",
>   assetContractAddress: NFT_ADDRESS,
>   tokenIds: [TOKEN_ID],
>   side: "ask",
> ```

@cheungchingli thanks! But still the same error:
```
node_modules/opensea-js/lib/api.js:129
                            throw new Error("Not found: no matching order found");
```

And the code is:
```
import Web3 from 'web3'
import * as openSeaSdk from 'opensea-js'

const provider = new Web3.providers.HttpProvider('https://mainnet.infura.io/v3/xxxxx');
const seaPort = new openSeaSdk.OpenSeaPort(provider, {
  networkName: openSeaSdk.Network.Main,
  apiKey: process.env.OPENSEA_API_KEY || ''
});

const order = await seaPort.api.getOrder({ 
    protocol: "seaport",
    side: 'ask',
    assetContractAddress: '0x8b44b715004020773e8da1cd730de2f47c7d88b8', 
    tokenIds: ['6754'] });
console.log(JSON.stringify(order, null, 4));
```

If remove the `assetContractAddress` and `tokenIds` params, can get an order.

**Comment by esteban-OpenSea** [comment]
Great to hear that solution worked, I'll go ahead and close this.
