### ISSUE TITLE
Seaport OrderModel field side is supposed to be number not a string

### ISSUE THREAD

**Issue by TarmoKalling** [ProjectOpenSea/opensea-js#574]
According to this https://docs.opensea.io/v2.0/reference/model-reference#order-model the type of field `side` is supposed to be a number. 
But when I tried here: https://docs.opensea.io/reference/getting-assets with contract `0xcd041f40d497038e2da65988b7d7e2c0d9244619`, token `10096` and `include_orders: true` then it's value is either `ask` or `bid` which are strings not numbers

**Comment by esteban-OpenSea** [comment]
Side is now a required parameter. Please pass side=0 for buy orders and side=1 for sell orders. As a note, when you call the orders endpoint, count will always return 1.

https://docs.opensea.io/reference/retrieving-orders

Please send a screenshot of the side value? I am not seeing that issue.

**Comment by TarmoKalling** [comment]
<img width="1464" alt="Screen Shot 2022-06-21 at 11 52 48" src="https://user-images.githubusercontent.com/1407802/174759416-f6de1de3-856e-466d-8e0b-f284a9acaa34.png">
Here you go. That's what I'm talking about. This is under seaport_sell_orders. Shouldn't it be `"side": 1` not `"side": "ask"`?

Disclaimer: If you repeat this request then it might not be there anymore as the listing may be expired. But it's same with all tokens which have an active seaport_sell_order.
