### ISSUE TITLE
Not found: no matching order found

### ISSUE THREAD

**Issue by Sam53534512** [ProjectOpenSea/opensea-js#575]
const order2 = await seaport2.api.getOrderLegacyWyvern({
            asset_contract_address: "0x4C7060eA8239A4D64c04CFf3b9d24ddFa5eB6059",
            token_id: 9,
            side: OrderSide.Sell
        })
return  Error: Not found: no matching order found

i Confirm the sale status ，why

**Comment by Racherin** [comment]
Try this 

```javascript
const order2 = await seaport2.api.getOrder({
protocol : "seaport",
assetContractAddress: "0x4C7060eA8239A4D64c04CFf3b9d24ddFa5eB6059",
tokenIds: 9,
side: 'ask'
})
```
