### ISSUE TITLE
Fulfill Multiple Buy Orders in Single Transaction

### ISSUE THREAD

**Issue by MetalGear-cmd** [ProjectOpenSea/opensea-js#578]
Hey Everyone,
Is it possible to fulfill Multiple Buy Orders for multiple Assets in a single transaction, just like batch buy. Using the Opensea SDK?
Currently, I can fulfillOrder() for a single asset successfully, but I would like to batch buy multiple assets in single transaction to save Gas.
If anyone knows how this can be done please drop a comment.
Thanks in advance.

**Comment by omnigolp** [comment]
@MetalGear-cmd 
There is also `fulfillOrders` for multiple orders, but I am not sure if it does it in one transaction.
