### ISSUE TITLE
Order Endpoint Seems Broken

### ISSUE THREAD

**Issue by ANG3L0** [ProjectOpenSea/opensea-js#582]
Sometimes, the fetch order API works, and sometimes, it doesn't. For example:
https://opensea.io/assets/ethereum/0xda60730e1feaa7d8321f62ffb069edd869e57d02/9221 is currently listed at 0.25 ETH.

If I query the listings API:
https://api.opensea.io/api/v1/asset/0xda60730e1feaa7d8321f62ffb069edd869e57d02/9221/listings?limit=50
I get a response with the seaport listing.

```
{
    "listings": [],
    "seaport_listings": [
        {
            "created_date": "2022-06-17T06:07:16.477636",
            "closing_date": "2022-06-20T06:07:06",
            "listing_time": 1655446026,
            "expiration_time": 1655705226,
            "order_hash": "0x9d8077224d192bdc3fb56fc82f2f3366fd62ae1f787950f27b4936ccab94c667",
            "protocol_data": {
                "parameters": {
                    "offerer": "0x810c3243032f3ac57e9351812f116c3ee6953c18",
                    "offer": [
                        {
                            "itemType": 2,
                            "token": "0xDA60730E1feAa7D8321f62fFb069eDd869E57D02",
                            "identifierOrCriteria": "9221",
                            "startAmount": "1",
                            "endAmount": "1"
                        }
                    ],
...
```

If I query the fetch API where:
side = 1
limit = 50
asset_contract_address = 0xda60730e1feaa7d8321f62ffb069edd869e57d02
token_id = 9221

I get this response:
```
{
    "count": 1,
    "orders": []
}
```

But for some other listings, the order endpoint is working.

**Comment by shini-tm** [comment]
I'm getting the same issue, @ANG3L0 was there an explanation for why it doesn't work? I suspect it has something to do with having moved listing information from the wyvern to seaport
