### ISSUE TITLE
Error: API Error 400: Invalid request: {"protocol":["undefined is not a valid protocol"]}

### ISSUE THREAD

**Issue by WebScripti** [ProjectOpenSea/opensea-js#584]
Hi frined,

today my app started giving errors while performing the purchase of some nfts. I upgraded the version 3.0.4 to version 4.0.2. this time, all of them became inoperable, including the collections that were working in the past.
The error I get in the getorder command is as follows.

const order = await seaport.api.getOrder({ side: 1,
  asset_contract_address: contract,
  token_id: tokenid})

Error: Error: API Error 400: Invalid request: {"protocol":["undefined is not a valid protocol"]}

**Comment by ring0dev** [comment]
+++ same problem. In 3.0.4 work fine? I wanna downgrade

**Comment by ring0dev** [comment]
i think its may be with build dependencies, i dont know how to solve this for windows

**Comment by WebScripti** [comment]
> 

I downgraded. But 3.0.4 does not support the new collections released this week. For example, getorder cannot be assigned to lacosteundw3 collection.

I tried 6 hours, but not working code.

**Comment by marvinkennis** [comment]
@WebScripti @ring0dev You need to set the protocol in the getOrders API call: 
`  const { orders, count } = await openseaSDK.api.getOrders({
    onlyEnglish:false,
    limit:50,
    side:1,
    protocol: "seaport"
  })`

**Comment by ring0dev** [comment]
Do you have a telegram account?

сб, 18 июн. 2022 г., 17:00 WebScripti ***@***.***>:
