### ISSUE TITLE
fulfillAvailableOrders() and matchOrders() in SDK v 4+

### ISSUE THREAD

**Issue by MetalGear-cmd** [ProjectOpenSea/opensea-js#589]
Hey,
Does anyone here knows how to fulfill multiple assets orders, on the docs of the Seaport there is this, option thaT say fulfillAvailableOrders or matchOrders can be used for this, I dont know how to use these methods.
if some one here knows please leave a comment, would love your help.
Peace

Docs:
Calling one of two "fulfill available" functions, fulfillAvailableOrders and fulfillAvailableAdvancedOrders, where a group of orders are supplied alongside a group of fulfillments specifying which offer items can be aggregated into distinct transfers and which consideration items can be accordingly aggregated, and where any orders that have been cancelled, have an invalid time, or have already been fully filled will be skipped without causing the rest of the available orders to revert. Additionally, any remaining orders will be skipped once maximumFulfilled available orders have been located. Similar to the standard fulfillment method, all offer items will be transferred from the respective offerer to the fulfiller, then all consideration items will be transferred from the fulfiller to the named recipient.
Calling one of two "match" functions, matchOrders and matchAdvancedOrders, where a group of explicit orders are supplied alongside a group of fulfillments specifying which offer items to apply to which consideration items (and with the "advanced" case operating in a similar fashion to the standard method, but supporting partial fills via supplied numerator and denominator fractional values as well as an optional extraData argument that will be supplied as part of a call to the isValidOrderIncludingExtraData view function on the zone when fulfilling restricted order types). Note that orders fulfilled in this manner do not have an explicit fulfiller; instead, Seaport will simply ensure coincidence of wants across each order.

**Comment by jtaaa** [comment]
Hey @MetalGear-cmd, the opensea-js SDK currently doesn't support fulfilling multiple asset orders in a single transaction. While it is not supported, you can try using [seaport-js](https://github.com/ProjectOpenSea/seaport-js) which the SDK uses under the hood to do this with `fulfillAvailableOrders` or `matchOrders`

**Comment by MetalGear-cmd** [comment]
Hey @jtaaa thanks for your reply, is there any docs or example of how to use the seaport-js ?

**Comment by jtaaa** [comment]
There is an example folder in the repo where you can see how `matchOrders` is used to fulfill private listings. Unfortunately we don't have extensive examples right now. There is also documentation in the seaport repo of the smart contract methods that seaport-js allows you to use

**Comment by MetalGear-cmd** [comment]
Thanks a lot, I will check that out now.

**Comment by MetalGear-cmd** [comment]
Also this is an unrelated uestion, but would love to have your help on this:

"The method eth_signTypedData_v4 does not exist/is not available"
when trying to use createBuyOrder() in sdk version 4.0.2 when using the @0xsubprovider.

I also get the error
Getting "Cannot read property 'EIP712Domain' error with https://github.com/truffle hd wallet provider". When trying to use creatheBuyOrders() in sdk v4+.

And the same code starts working when using createBuyOrdersLegacyWyvern().

**Comment by jtaaa** [comment]
Here's the link for that issue https://github.com/ProjectOpenSea/opensea-js/issues/588

**Comment by validicetherian** [comment]
> 

Do you mind referring me to the folder As I am struggling to find it
