### ISSUE TITLE
Failed to Fetch / API Error 429: Message: {"detail":"Request was throttled."}

### ISSUE THREAD

**Issue by ApeLife24** [ProjectOpenSea/opensea-js#590]
Hello, so I own a collection on Opensea on the Shared StoreFront contract with 87 items, and I want to sell them all, I always did it "fast"I list one then start with the other and like that until the 87 are listed for 3 day's without problems but is been like a week or two that I can only list every 3-5 minutes because I get a Failed to Fetch or API Error 429, I'm doing this manually because I don't own a API KEY....

Is there some kind of limit? is my internet connection that is slow?
I can't understand... Hopefully someone can give me some guidance, or tell me if at least I'm not the only one with this problem... This happen always after I SIGN the metamask, it "stay" charging and then Failed to Fetch or API Error 429.

There was 1 day that the problem got "solved" and I was able to publish the 87 fast in a few minute, but the opensea "interface" was different... Like in the picture, on the left side I was able to post without this Failed to fetch problem, but now is "back" to the right side old interface and I'm having this problem again.... 

![Sin título](https://user-images.githubusercontent.com/103352465/174611845-87389f4b-a310-4912-b9c4-b47b1e19f467.png)

**Comment by jtaaa** [comment]
Hello @ApeLife24, you can request an API key here and you shouldn't get 429 errors anymore
https://docs.opensea.io/reference/request-an-api-key

**Comment by ApeLife24** [comment]
> 

Hello but would I get approved for an API Key? I don't really have a product or anything special, I just want to list my items without this problem, and not sure if I would be approved to get an API Key just because of this...

I never had this problem before so I thou was because my internet maybe was slow lately or something like that, so does Opensea has limits now for normal user's without API key?

**Comment by ApeLife24** [comment]
> Hello @ApeLife24, you can request an API key here and you shouldn't get 429 errors anymore https://docs.opensea.io/reference/request-an-api-key

Hello but would I get approved for an API Key? I don't really have a product or anything special, I just want to list my items without this problem, and not sure if I would be approved to get an API Key just because of this...

I never had this problem before so I thou was because my internet maybe was slow lately or something like that, so does Opensea has limits now for normal user's without API key?

**Comment by jtaaa** [comment]
> > Hello @ApeLife24, you can request an API key here and you shouldn't get 429 errors anymore https://docs.opensea.io/reference/request-an-api-key
> 
> Hello but would I get approved for an API Key? I don't really have a product or anything special, I just want to list my items without this problem, and not sure if I would be approved to get an API Key just because of this...
> 
> I never had this problem before so I thou was because my internet maybe was slow lately or something like that, so does Opensea has limits now for normal user's without API key?

You should be approved. Lmk if not. And yeah we have rate-limits by API key. Have had that for a while

**Comment by ApeLife24** [comment]
> 

How long do I need to wait? still nothing and still having the same issue.

**Comment by ApeLife24** [comment]
> > > Hello @ApeLife24, you can request an API key here and you shouldn't get 429 errors anymore https://docs.opensea.io/reference/request-an-api-key
> > 
> > 
> > Hello but would I get approved for an API Key? I don't really have a product or anything special, I just want to list my items without this problem, and not sure if I would be approved to get an API Key just because of this...
> > I never had this problem before so I thou was because my internet maybe was slow lately or something like that, so does Opensea has limits now for normal user's without API key?
> 
> You should be approved. Lmk if not. And yeah we have rate-limits by API key. Have had that for a while


How long do I need to wait? still nothing and still having the same issue.

**Comment by esteban-OpenSea** [comment]
@ApeLife24 , can you submit a ticket [here](https://support.opensea.io/hc/en-us/requests/new), click on the developer help. and then select the "API Request" subcategory. I have provided a screenshot below on what you should see.

Let me know when you submitted a ticket and we will make sure to get on it!

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/99999009/175986242-ce24b2d5-1e81-4428-aed6-66cfbcbdc07f.png">

**Comment by esteban-OpenSea** [comment]
Great! Please look at your email, the support team has replied to you.

**Comment by ApeLife24** [comment]
> 



> Great! Please look at your email, the support team has replied to you.

Hello sorry didn't see the message until now I just answered it.

**Comment by esteban-OpenSea** [comment]
No worries! Just replied and the issue should be solved. Feel free to reply to the ticket if you are still having issues. Thanks!
