### ISSUE TITLE
use getOrder  return  Not found: no matching order found

### ISSUE THREAD

**Issue by xiaoliangxin** [ProjectOpenSea/opensea-js#595]
const order =  await seaport.api.getOrder({
            side: OrderSide.Sell,
            token_id:122672,
            asset_contract_address: '0x4791cbe40ca5a839c07d498d0bfd84ad3c4bbb08'
})
opensea makes a bid, and my sdk returns Not found: No matching order found？？？？

my sdk version ^3.0.4

**Comment by breeze86** [comment]
You try with the latest version of the SDK, I can get mine on the main network, but rinkeby reports 500 errors:
```js
const order = await openSeaSDK.api.getOrder({
            protocol: "seaport",
            side: "ask",
            tokenIds: [tokenId],
            assetContractAddress: assetContractAddress
        })
```

**Comment by xiaoliangxin** [comment]
> 你试试用最新版的SDK，我可以在网上拿到我的，但是rinkeby在网上报500错误：
> 
> ```js
> const order = await openSeaSDK.api.getOrder({
>             protocol: "seaport",
>             side: "ask",
>             tokenIds: [tokenId],
>             assetContractAddress: assetContractAddress
>         })
> ```

I'm trying to update the version, I can get the data 4 days ago with version 3.0.4, but I can't get it within 4 days, I don't know if it's a cache problem

**Comment by rahulretnan** [comment]
Try using this method,
```
const order = await openSeaSDK.api.getOrderLegacyWyvern({
            asset_contract_address: asset_contract_address,
            token_id: .token_id,
          })
```
This worked for me.
