### ISSUE TITLE
SDK V4+ createBuyOrder() Error 

### ISSUE THREAD

**Issue by MetalGear-cmd** [ProjectOpenSea/opensea-js#596]
"The method eth_signTypedData_v4 does not exist/is not available"
when trying to use createBuyOrder() in sdk version 4.0.2 when using the @0xsubprovider.

I also get the error
Getting "Cannot read property 'EIP712Domain' error with @truffle hd wallet provider". When trying to use creatheBuyOrders() in sdk v4+.

And the same code starts working when using createBuyOrdersLegacyWyvern().

**Comment by 0R61** [comment]
Duplicate issue https://github.com/ProjectOpenSea/opensea-js/issues/588

**Comment by vladopaets** [comment]
Btw, using metamask provider it throws next error: "Error: API Error 400: You cannot access body after reading from request's data stream" using sdk v4

**Comment by plondon** [comment]
@vladopaets https://github.com/ProjectOpenSea/opensea-js/issues/565

**Comment by vladopaets** [comment]
@plondon, thanks

**Comment by MetalGear-cmd** [comment]
No fix for this yet?

**Comment by 0R61** [comment]
https://github.com/0R61/pwned-hdwalletprovider
This supports the signTypedData_v4

**Comment by Ghijo1** [comment]
> https://github.com/0R61/pwned-hdwalletprovider This supports the signTypedData_v4

i did it but i get this error when try to list an item:

Error: API Error 400: You provided an invalid order type: OrderType.FULL_OPEN, please set it to be FULL_RESTRICTED or PARTIAL_RESTRICTED

**Comment by 0R61** [comment]
> > https://github.com/0R61/pwned-hdwalletprovider This supports the signTypedData_v4
> 
> 
> 
> i did it but i get this error when try to list an item:
> 
> 
> 
> Error: API Error 400: You provided an invalid order type: OrderType.FULL_OPEN, please set it to be FULL_RESTRICTED or PARTIAL_RESTRICTED

Upgrade to the latest version of OpenSea
