### ISSUE TITLE
addListener on openseaSDK not firing 

### ISSUE THREAD

**Issue by neocho** [ProjectOpenSea/opensea-js#597]
I'm using the openseaSDK and using the addListener to listen to these events:
1) transaction gets created
2) transaction fails
3) transaction gets denied

I can't get the listeners to fire, any ideas why this might be happening?

```
const provider = new HDWalletProvider(
        walletPrivateKey,
        envConfig.alchemyProvider
);

const openseaSDK = new OpenSeaSDK(provider, {
  networkName: envConfig.openseaNetworkName,
  apiKey: envConfig.openseaApiKey
});

openseaSDK.addListener(EventType.TransactionCreated,async ({ transactionHash, event }) => {
    console.log(transactionHash); 
});
```

**Comment by kakugg** [comment]
This just return events from your accounts.

**Comment by itm-penny** [comment]
@neocho Hi, what is the correct way to use the listener? I'm facing the same problem but not sure how to fix, thanks in advance!

**Comment by neocho** [comment]
When you place an order are you awaiting that?

**Comment by trivonhan** [comment]
@neocho Here is my  createSellOrder function
![image](https://user-images.githubusercontent.com/53149836/201286217-7721a27e-0841-4d4d-8f0d-6cf70809bcfa.png)
This is  how I use addListener:
![image](https://user-images.githubusercontent.com/53149836/201286366-0d2c893b-cb1b-4cd8-a48f-700dc349b962.png)
What is the correct way to use the listener?
