### ISSUE TITLE
Store images on IPFS

### ISSUE THREAD

**Issue by filips123** [ProjectOpenSea/opensea-js#6]
If you want to be fully decentralized application, you should also store assets images on [IPFS](https://ipfs.io/). This will also be able to protect from things like #3 when hosting provider is blocked in some country.

**Comment by alexanderatallah** [comment]
We're not aiming to be fully decentralized. However, dapps are welcome to use IPFS, and we will too once latency is comparable to or better than using a CDN (which would also solve #3 and that's the plan there)

**Comment by filips123** [comment]
Is is currently possible to get images from IPFS? For forward compatibility you could save them both to IPFS and CDN but when it will be ready, switch to IPFS.

**Comment by alexanderatallah** [comment]
If the dapp does IPFS urls, then it will be available as `image_original_url` on the asset data you get from the OpenSea API. (Also, it really doesn't help decentralize the world if we make IPFS mirrors of a dapp's non-IPFS images. What matters is what the smart contract points to. If that's allowed to change, then our mirrors have to change.)
