### ISSUE TITLE
Monitor: english auction support for v2 api

### ISSUE THREAD

**Issue by plondon** [ProjectOpenSea/opensea-js#605]
I see that english auctions are not yet supported via the v2 seaport api

https://github.com/ProjectOpenSea/opensea-js/pull/561#discussion_r897240203

This issue can be used to monitor support so clients can know when they are able to re-implement.

**Comment by fepvenancio** [comment]
Hey, still no answer to this? 

I'm trying to get the API to do English Auctions and now I understand why it's not possible the UI works well but even having the order the same way, doesn't work.
Dutch Auction and listing are perfect. 

I know the seaport order doesn't take the  waitForHighestBid: true but maybe the API can use this field.  

Would be waiting for an answer, GLHF.

**Comment by nl0243** [comment]
What would be the best way to set an English auction for several 1000s NFTs, since API does not support this functionality yet?
