### ISSUE TITLE
We can't create Orders --> REINTRODUCE WYVERN PLEASE 

### ISSUE THREAD

**Issue by Ghijo1** [ProjectOpenSea/opensea-js#606]
Hello,

a few days ago I opened this issue:

https://github.com/ProjectOpenSea/opensea-js/issues/588

On discord the number of developers reporting my same problem is very high.

Nonetheless, OpenSea announced that "offers and listings can no longer be posted to Wyvern v2.3 contract" but the problem we reported has not yet been resolved, so at this time many projects are stopped.

Can you reintroduce the ability to execute orders on Wyvern as long as you solve the problem we reported to you?

Thank you

**Comment by qq578728** [comment]
https://github.com/0R61/pwned-hdwalletprovider

我通过这个链接解决了！替换那些文件

**Comment by xroussel** [comment]
https://github.com/ProjectOpenSea/opensea-js/issues/588#issuecomment-1189006490
