### ISSUE TITLE
CORS issue when retrieving offers

### ISSUE THREAD

**Issue by plondon** [ProjectOpenSea/opensea-js#607]
Clients can no longer retrieve offers from opensea's API.

https://api.opensea.io/v2/orders/ethereum/seaport/offers?asset_contract_address=0xbce3781ae7ca1a5e050bd9c4c77369867ebc307e&token_ids=4911

Despite the api being open and not requiring an API key to use, the request from another domain is blocked by CORS.

Our wallet needs to fetch offers so that users can Accept and Cancel offers.

**Comment by cterech** [comment]
hey @plondon thanks for pointing this out! pushed a fix to prod, should be resolved now.
