### ISSUE TITLE
cheapest items in a collection, via REST API

### ISSUE THREAD

**Issue by drandreaskrueger** [ProjectOpenSea/opensea-js#61]
(Question about the REST api not the JS library, but (a) perhaps you know what I am doing wrong, or (b) can point me elsewhere. Thanks a lot.)

### cheapest items in a collection =??

Is there an API endpoint which delivers the same results as this search?

https://opensea.io/assets/superrare?search[sortAscending]=true&search[sortBy]=PRICE&search[toggles][0]=BUY_NOW

I am building a workaround via the orders API endpoint, and then just throw out all more expensive orders for the same item. It mostly works, for some collections.

But for some reason, I am not always seeing the same results as on the opensea.io webpage. Now I am wondering whether it's a bug, or something that I haven't understood yet.

This Python code works:

    pip3 install requests
    python3 savethistofile.py

savethistofile.py:
```
import requests # pip install requests
url = "https://api.opensea.io/wyvern/v1/orders"
querystring = {"side" : 1,
               "limit":"10",
               "offset":"0",
               "order_by":"eth_price",
               "order_direction":"asc",
               "is_english" : "false",
               "include_invalid":"false",
               "asset_contract_address": "0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0"
               }
response = requests.request("GET", url, params=querystring)
orders=response.json()["orders"]
print ("%d cheapest sell orders in %s:" % (len(orders), orders[0]['asset']['asset_contract']['name']))
for o in orders:
    a=o["asset"]
    print ("%.4f ETH '%s' (%s)" % (float(o["current_price"])/1000000000000000000, a["name"], a["id"]))
```
results in:
```
10 cheapest sell orders in SuperRare:
0.1000 ETH 'meta.morphosis' (14399641)
0.1510 ETH 'meta.morphosis' (14399641)
0.1650 ETH 'meta.morphosis' (14399641)
0.1950 ETH 'meta.morphosis' (14399641)
0.2000 ETH 'The Cent Portal' (6843352)
0.2500 ETH 'Our Lady Of Crypto Vandalized' (13936180)
0.2500 ETH 'The Golden Evil' (15872088)
0.2500 ETH 'meta.morphosis' (14399641)
0.2900 ETH 'King Elvis' (13905469)
0.3000 ETH 'THISISAMERICA®' (13474165)
```
So e.g. 'meta.morphosis' and 'The Cent Portal' are found correctly.

BUT in contrast to ^ that, the webpage search gives MORE results, below 0.2 ETH:

![opensea io-search-superrare-cheapest](https://user-images.githubusercontent.com/7796035/107503241-02244880-6b9a-11eb-8783-3f113f8be52e.png)  
https://opensea.io/assets/superrare?search[sortAscending]=true&search[sortBy]=PRICE&search[toggles][0]=BUY_NOW

Can you please 

(a) check what is going on there, perhaps (a1) I understood the API call wrong, or (a2) something's bad in the backend.

(b) tell me a different way if there is one, to just query the **cheapest xx items in a collection**.

Thanks a lot!

**Comment by rtunazzz** [comment]
Hey @drandreaskrueger, did you ever get to resolve this? Having the same exact issue currently with fetching lowest orders and can't figure out why the OS API is giving me much higher results than the ones viewed on the site.

**Comment by randomnumb** [comment]
No solution, but I did get my ip blocked by cloudflare just for attempting to submit the query string above to the api.  Be warned friends.

**Comment by JohannesHoppe** [comment]
Closed without any comment or solution? 👎👎👎 Why do you even pretend to make OpenSource?!
