### ISSUE TITLE
 Please roll back to 2.0, 4.03 has so many bugs, bad experience! We can't use the API to create sell orders right now, it's a pain for people with a lot of NFTs

### ISSUE THREAD

**Issue by qq578728** [ProjectOpenSea/opensea-js#613]
Please roll back to 2.0, 4.03 has so many bugs, bad experience! We can't use the API to create sell orders right now, it's a pain for people with a lot of NFTs

**Comment by jtaaa** [comment]
Feel free to open another issue with details of a specific issue you are experiencing
