### ISSUE TITLE
HDWalletProvider  TypeError: Cannot read properties of undefined (reading 'EIP712Domain') 

### ISSUE THREAD

**Issue by Miridescen** [ProjectOpenSea/opensea-js#614]
How to resolve this error

**Comment by moon0712** [comment]
same error when openseaSDK.createBuyOrder

@truffle/hdwallet-provider: ^2.0.9,
opensea-js: ^4.0.3

**Comment by wuyunjiang** [comment]
> same error when openseaSDK.createBuyOrder
> 
> @truffle/hdwallet-provider: ^2.0.9, opensea-js: ^4.0.3

same error

**Comment by jtaaa** [comment]
This is a duplicate of https://github.com/ProjectOpenSea/opensea-js/issues/588

Also see https://github.com/trufflesuite/truffle/issues/5220
