### ISSUE TITLE
Most data in API are empty

### ISSUE THREAD

**Issue by Superpassteque** [ProjectOpenSea/opensea-js#617]
API return 0 offer for most NFT with offer on the website

using sdk seaport.api.getOrders()
and also on 
https://docs.opensea.io/reference/retrieving-orders
and
https://docs.opensea.io/reference/asset-offers

is it normal behavior? I can't get active offers since 4days.

I just downgraded to sdk v3 but also same behavior on sdk v4.

**Comment by Racherin** [comment]
It just doesn't fetch collection offers. Why collection offers are doesn't recognized by regular API, any idea about this issue @jtaaa @sunwrobert ?

**Comment by jtaaa** [comment]
> It just doesn't fetch collection offers. Why collection offers are doesn't recognized by regular API, any idea about this issue @jtaaa @sunwrobert ?

It doesn't currently support collection offers. Some support for collection offers will be added in the future
