### ISSUE TITLE
createSellOrder not processed as expected using WalletConnectProvider

### ISSUE THREAD

**Issue by itm-penny** [ProjectOpenSea/opensea-js#619]
I'm currently using WalletConnect to connect wallet to my DApp which contains a `createSellOrder` action on it. 
After firing a `createSellOrder`  action, my wallet app (MetaMask to be specific) shows the signature request content, but nothing happen after I click on sign button. No error message were shown. How can I fix the problem?

Library versions:

- walletconnect/web3-provider: 1.7.8
- opensea-js: 4.0.3

I try to do listing on OpenSea webpage also using WalletConnect, it doesn't work either.

**Comment by Lebski** [comment]
Did you use this on an "old" contract? If you added the old proxy to your contract, the function `setApprovalForAll` won't work properly. 

New proxy address is `0x1E0049783F008A0085193E00003D00cd54003c71`

**Comment by itm-penny** [comment]
> Did you use this on an "old" contract? If you added the old proxy to your contract, the function `setApprovalForAll` won't work properly.
> 
> New proxy address is `0x1E0049783F008A0085193E00003D00cd54003c71`

Thanks for the information, We've tried doing the action on an old contract and a new contract, and they both don't work. Both stuck at the signing stage on MetaMask APP, as shown in the image below: 

- Sell on OpenSea site using WalletConnet
![image](https://user-images.githubusercontent.com/67629180/176106150-26ce0b8e-1b93-40a4-a006-4bffeb2c9961.png)

- Sell on my project built with OpenSeaSDK using WalletConnect
![image](https://user-images.githubusercontent.com/67629180/176106532-f9a6ca42-9c7f-4dbf-90e5-06a9f1de5213.png)

Then I tried to connect with other wallet app, like 'Rainbow wallet' and it worked! So I am guessing there's something wrong using MetaMask wallet app to sign `createSellOrder` message. But this is a little bit inconvenient since MetaMask is the one our clients want and it is also more familiar to most users.. so I still need some help here!

**Comment by itm-penny** [comment]
Found this to be an issue on walletconnect side
>> https://github.com/WalletConnect/walletconnect-monorepo/pull/1191

Currently making change to their source code according to the pull request above to temporary solve this problem, just to let anyone meets the same issue know.
