### ISSUE TITLE
How can we make collection offer and fetch the status of collection offer using opensea-js?

### ISSUE THREAD

**Issue by wei-dai** [ProjectOpenSea/opensea-js#620]
Currently the createBuyOrder and getOrders can not get the detail of collection offer

**Comment by jtaaa** [comment]
The API and SDK currently do not support collection offers but some support will be added in the future

**Comment by davidseroussi** [comment]
@jtaaa do you have an approximate ETA for posting collection offers ?

**Comment by jtaaa** [comment]
> @jtaaa do you have an approximate ETA for posting collection offers ?

I don't currently have an ETA but it's a near term priority
