### ISSUE TITLE
getOrders() returns last offer across all collections instead of offers for provided item?

### ISSUE THREAD

**Issue by krzysztofmn** [ProjectOpenSea/opensea-js#621]
Hello All,

I'm struggling to get highest bid on a given item. On Wyvern API it was running smoothly for me. Now, regardless if I provide asset_contract_address and token_id, delete them or put some random strings inside, the function always returns last offer across all collections instead of offers for provided item. Please kindly help me solve this problem, am I missing something here?

```
seaport.api.getOrders({
          protocol: "seaport",
          asset_contract_address: "0xea917326e8a95299c02655fe947962c43a11487f",
          token_id: "4474",
          limit: 1,
          side: "bid"
        })
```

**Comment by asafd11** [comment]
happan to me to it return random orders
i was trying to test the new sdk 
on a high price nft with low offer ended up buying a random nft that was within the price i was offering :( 
i tryd the tokenIds: array didnt work

const sellOrder = await seaport.api.getOrder({
        asset_contract_address: tokenAddress,
        token_id: [tokenId],
        side: "ask",
        protocol: "seaport",
        limit: 1
      });

**Comment by krzysztofmn** [comment]
Thanks for trying to help out here!

I have changed the code as per your suggestions to:
```
assetContractAddress: "0xea917326e8a95299c02655fe947962c43a11487f",
tokenIds: ["4474"],
```
getOrders now return:
`{ next: null, previous: null, orders: [] }`

As you can see, there are a few offers on this item:
https://opensea.io/assets/ethereum/0xea917326e8a95299c02655fe947962c43a11487f/4474

**Comment by krzysztofmn** [comment]
Screehshot, because most will be expiring soon ;)
![image](https://user-images.githubusercontent.com/49908409/175972031-f72a2d77-a5b5-458d-969f-b5038f4030bf.png)

**Comment by krzysztofmn** [comment]
Thanks a lot, at last I was able to fetch an offer! However only one was returned even though there are four now. Do you have any ideas why is that the case? Does the function fetch only the highest offer or is there some kind of an issue, like not taking into account collection offers?

My current code:
```
return seaport.api.getOrder({
          protocol: "seaport",
          assetContractAddress: "0xea917326e8a95299c02655fe947962c43a11487f",
          tokenIds: ["4474"],
          side: "bid"
        }).then(response => {
          orders = response;
          console.log(orders);
        });
```

It would be much easier if documentation was up to date  ;), because https://www.npmjs.com/package/opensea-js for sure isn't.

**Comment by jtaaa** [comment]
> Thanks a lot, at last I was able to fetch an offer! However only one was returned even though there are four now. Do you have any ideas why is that the case? Does the function fetch only the highest offer or is there some kind of an issue, like not taking into account collection offers (which would be a killer to any project based on fetching exiting offers)?
> 
> My current code:
> 
> ```
> return seaport.api.getOrder({
>           protocol: "seaport",
>           assetContractAddress: "0xea917326e8a95299c02655fe947962c43a11487f",
>           tokenIds: ["4474"],
>           side: "bid"
>         }).then(response => {
>           orders = response;
>           console.log(orders);
>         });
> ```
> 
> It would be much easier if documentation was up to date ;), because https://www.npmjs.com/package/opensea-js for sure isn't.

The API currently doesn't support collection offers. This support is planned to be added in the near future.

We do definitely need to update the documentation as well. Will try to get this prioritized

**Comment by krzysztofmn** [comment]
Understood. Is there any specific timeline for supporting collection offers?

**Comment by georgep21** [comment]
@krzysztofmn did you manage to fetch sell orders on testnet using this sdk?

**Comment by krzysztofmn** [comment]
@georgep21 For my needs I'm fetching bids only. What I'm able to do is fetch one highest non-collection offer. I understand that including collections offers is under development, so I'll just have to wait.

In the meantime I have another problem, but opened a new issue for it - #635
