### ISSUE TITLE
How to bid on multiple tokens at once with API

### ISSUE THREAD

**Issue by 0R61** [ProjectOpenSea/opensea-js#623]
I understand this: The identifierOrCriteria represents either the ERC721 or ERC1155 token identifier or, in the case of a criteria-based item type, a merkle root composed of the valid set of token identifiers for the item. This value will be ignored for Ether and ERC20 item types, and can optionally be zero for criteria-based item types to allow for any identifier.

But how can I craft the merkle root from a set of token ids for example 3556,4557 and 3223? I have analyzed the collection offer popups when you do it manually through OpenSea website but and there the value of the identifierOrCriteria parameter is: 115209989443044873291111670937686544922043298494504882064979471203257419400307

How can I create this value?

**Comment by risingsun007** [comment]
Did you figure this out?

**Comment by kophyo1234** [comment]
#479

**Comment by risingsun007** [comment]
> #479

huh?

**Comment by 0R61** [comment]
> Did you figure this out?
> 
> 

Yes I created the merkle root value

**Comment by jeremicna** [comment]
> > Did you figure this out?
> 
> Yes I created the merkle root value

Were you able to calculate the exact value? I have been trying using the seaport-js utils but it doesn't return the correct root.

**Comment by risingsun007** [comment]
I haven't figured it out yet.
