### ISSUE TITLE
Error: API Error 400: Invalid request: "['Wyvern orders posted to the API are deprecated, except for shared storefront orders']" 

### ISSUE THREAD

**Issue by kakugg** [ProjectOpenSea/opensea-js#628]
I meet this issues have 4 days,but I don't know how to solve it.
Is anyone solved this proble?

**Comment by cterech** [comment]
@kakugg what kind of listing are you trying to create?

**Comment by Lebski** [comment]
Duplicate of https://github.com/ProjectOpenSea/opensea-js/issues/610

**Comment by kakugg** [comment]
> @kakugg what kind of listing are you trying to create?

make offer by createBuyOrder

**Comment by 0R61** [comment]
> > @kakugg what kind of listing are you trying to create?
> 
> make offer by createBuyOrder

Update your sdk to latest version

**Comment by kakugg** [comment]
> 

I update my sdk to the latest version,but run error make me diffcult,I can't solve it!
I develop project by VUE.

**Comment by kakugg** [comment]
> > > @kakugg what kind of listing are you trying to create?
> > 
> > 
> > make offer by createBuyOrder
> 
> Update your sdk to latest version

I update my sdk to the latest version,but run error make me diffcult,I can't solve it!
I develop project by VUE.

**Comment by huyredfox** [comment]
same issue here

**Comment by ahjohnwon** [comment]
latest SDK can't run.
