### ISSUE TITLE
Error: API Error 400: Invalid request: "['Wyvern orders posted to the API are deprecated, except for shared storefront orders']"

### ISSUE THREAD

**Issue by cto-aarchik** [ProjectOpenSea/opensea-js#629]
error while createSellOrder using opensea-js 4.0.3

**Comment by cterech** [comment]
@cto-aarchik can you provide some more details? what type of listing are you trying to create?

**Comment by Lebski** [comment]
Duplicate of Duplicate of https://github.com/ProjectOpenSea/opensea-js/issues/610
