### ISSUE TITLE
asset `owner` field is not update to date with current owner

### ISSUE THREAD

**Issue by Schwartz10** [ProjectOpenSea/opensea-js#63]
If a token has been sold, the asset's owner field does not seem to represent the latest owner. It shows the original asset owner

**Comment by matsko** [comment]
I'm experiencing this bug too. And this is almost two months after this issue was first reported. When will this be fixed?

**Comment by nawangwe** [comment]
Same here, any word on this?

**Comment by esteban-OpenSea** [comment]
@nawangwe, is this still an issue?
