### ISSUE TITLE
Network Changed Error

### ISSUE THREAD

**Issue by Tahseen96** [ProjectOpenSea/opensea-js#630]
Got this error while while using createBuyOrder function to place a bid. KIndly let me know how can I fix this.

(node:37175) UnhandledPromiseRejectionWarning: Error: underlying network changed (event="changed", network={"chainId":15042624,"name":"unknown"}, detectedNetwork={"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, code=NETWORK_ERROR, version=providers/5.6.8)

**Comment by Tahseen96** [comment]
@jtaaa Can you help me please.

**Comment by avikonduru** [comment]
I'm also getting this same error

**Comment by avikonduru** [comment]
@jtaaa Was this issue ever resolved?

**Comment by jtaaa** [comment]
Appears to be related to this. Issue is not resolved. Can anyone provide a reproducible example or maybe repro steps?
https://github.com/ethers-io/ethers.js/issues/1107

**Comment by shoaibatiq** [comment]
try signing up to infura and using a different infura API key. It worked for me

**Comment by alexreyes** [comment]
Also have this issue

**Comment by mintymento456** [comment]
@alexreyes did you find a fix for this? Did switch the API key work for you?

**Comment by alexreyes** [comment]
@mintymento456 no. I ended up having to make my own [fork](https://www.npmjs.com/package/opensea-js-wagmi-edition) to add event listeners to emit when the 'network changed error' type of problems happen. 

I haven't gotten a chance to work on it beyond that yet, but I'll keep investigating on my fork of the library and trying to fix it. For now though, I don't recommend using my fork and I don't have a solution.

**Comment by donnlee** [comment]
Wow, I just tried switching from infura to alchemy api (alchemy.com) and the issue has cleared!

`providerUrl = "wss://eth-mainnet.g.alchemy.com/v2/MY_API_KEY`

**Comment by jamesrwaugh** [comment]
I did a couple things to fix this

1. Use a self-hosted Geth instance instead of Infura or Alchemy. This might just be confirmation bias
2. Always make sure to specify `chainId` or `network` in providers, however the API looks. I suspect something somewhere is "guessing" the network if you don't specify it.

Examples:

```js
const provider = new HDWalletProvider({
  mnemonic: process.env["WALLET_PHRASE"]!,
  providerOrUrl: process.env["LOCAL_GETH_URL"]!,
  addressIndex: 0,
  chainId: 1,
});
```

```js
const provider = new ethers.providers.JsonRpcProvider(
  process.env["LOCAL_GETH_URL"]!,
  "homestead"
);
```
