### ISSUE TITLE
Cannot update 4.0.2 -> 4.0.3

### ISSUE THREAD

**Issue by krzysztofmn** [ProjectOpenSea/opensea-js#635]
Hello All,

I am currently using opensea-js v4.0.2. However, I have come across an issue with placing bids - createBuyOrder function (please find my code below) throws following error:
Error: API Error 400: You provided an invalid order type: OrderType.FULL_OPEN, please set it to be FULL_RESTRICTED or PARTIAL_RESTRICTED

According to what I found it is solved in v4.0.3 - #577

Unfortunately, for some reason I am not able to update to 4.0.3. I had no issues with updating to 4.0.2. Please find logs attached. Could you please kindly help me find a solution. I'm not advanced and haven't been able to solve this problem myself.

```
seaport.createBuyOrder({ asset: {
            tokenId: id,
            tokenAddress: address
          },
          accountAddress: cfg.wallet_address,
          expirationTime: exp_time,
          startAmount: amount,
          protocol: "seaport",
          restrictedByZone: true,
          allowPartialFills: true
        });

[2022-06-29T19_41_42_553Z-debug-0.log.txt](https://github.com/ProjectOpenSea/opensea-js/files/9013766/2022-06-29T19_41_42_553Z-debug-0.log.txt)
[2022-06-29T19_41_37_383Z-debug-0.log.txt](https://github.com/ProjectOpenSea/opensea-js/files/9013767/2022-06-29T19_41_37_383Z-debug-0.log.txt)

```

**Comment by jtaaa** [comment]
Hi @krzysztofmn as you've found, the issue is resolved in v4.0.3
Can you open a new thread with your installation issue? or look for one that already exists. You will need to upgrade to solve this issue

**Comment by krzysztofmn** [comment]
@jtaaa I believe this is exactly what I have done - opened a new thread named "Cannot update 4.0.2 -> 4.0.3". If there are any threads with similar upgrade issue, please kindly let me know. I've looked for them but haven't found any cases similar to mine.

**Comment by jtaaa** [comment]
@krzysztofmn can you provide some details on the installation issue?

**Comment by krzysztofmn** [comment]
I have attached 2 log files that are a result of unsuccessfully running the installation, please find them attached again below. Are there any more details that I could provide which would be helpful? I apologize if my problem turns out to be trivial, but as mentioned above, I'm not that advanced. Installation of v4.0.2 was a breeze, v4.0.3 on the other hand turned out to be a huge hurdle for me.

[2022-06-29T19_41_42_553Z-debug-0.log.txt](https://github.com/ProjectOpenSea/opensea-js/files/9015076/2022-06-29T19_41_42_553Z-debug-0.log.txt)
[2022-06-29T19_41_37_383Z-debug-0.log.txt](https://github.com/ProjectOpenSea/opensea-js/files/9015077/2022-06-29T19_41_37_383Z-debug-0.log.txt)

**Comment by jtaaa** [comment]
thanks @krzysztofmn those logs look unrelated to opensea-js. you could try to see if this helps:
https://stackoverflow.com/questions/66434750/npm-err-git-dep-preparation-failed-when-trying-to-install-package-json

**Comment by krzysztofmn** [comment]
@jtaaa unfortunately it does look like opensea-js related issue :(

- I have tried the solution in the link you provided, but it didn't help.
- I have removed node and npm entirely from my computer and reinstalled the latest recommended versions (node v16.15.1, npm v8.11.0).
- I have removed opensea-js dependency leaving all others and run npm install - everything went smoothly without any errors.
- I added opensea-js v4.0.4 dependency and run npm install again - I get the same errors as before. Please find attached latest logs below.

[2022-07-01T08_18_55_020Z-debug-0.log.txt](https://github.com/ProjectOpenSea/opensea-js/files/9027434/2022-07-01T08_18_55_020Z-debug-0.log.txt)
[2022-07-01T08_18_56_787Z-debug-0.log.txt](https://github.com/ProjectOpenSea/opensea-js/files/9027435/2022-07-01T08_18_56_787Z-debug-0.log.txt)

**Comment by krzysztofmn** [comment]
Ok, I've managed to make it work! Still I think it's an opensea-js issue though. I had to play with nvm trying different node versions, yarn install etc., but at last it is working :)
