### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by koin-marian** [ProjectOpenSea/opensea-js#639]
Hello,

Could you please update your README and documentation for this SDK? We have to look through your source code to figure out how to use it now. Also, why does the new SDK only support Seaport? Your website aggregates offers from both Wyvern and Seaport, which is why you show many more offers compared to marketplaces that use your latest SDK (and, hence, Seaport-only)... Will you be completely dropping support for Wyvern (consistently)?

Thank you

**Comment by jtaaa** [comment]
Support for wyvern will be dropped completely in the near future. We only accept and display new wyvern orders for shared storefront assets at this time.

And yes we definitely need to update README and docs
