### ISSUE TITLE
Including account_address=<address> returns 404

### ISSUE THREAD

**Issue by plondon** [ProjectOpenSea/opensea-js#640]
https://api.opensea.io/api/v1/asset/0x79fcdef22feed20eddacbb2587640e45491b757f/0?include_orders=true

vs

https://api.opensea.io/api/v1/asset/0x79fcdef22feed20eddacbb2587640e45491b757f/0?include_orders=true&account_address=0x354AFc54b8E9647F558d524ea4762c1a59F5b202

**Comment by cterech** [comment]
@plondon can you retry? when i tried to reproduce, i saw orders returned for both requests

**Comment by plondon** [comment]
Must've been a blip, will close
