### ISSUE TITLE
Svg containing <image> tag with external href link doesn't show on Opeasea

### ISSUE THREAD

**Issue by jiayi1992** [ProjectOpenSea/opensea-js#644]
Hi team! We meet a problem where we are trying to use SVG (base64) as the value of image_data in our NFT metadata. The SVG contains <Image> tag and doesn't work on Opensea. Could you help us to solve this problem? Thanks!

**Comment by jiayi1992** [comment]
Also found that the tokenURI of https://opensea.io/assets/ethereum/0x9b091d2e0bb88ace4fe8f0fab87b93d8ba932ec4/3095 only has image_data field and it works on opensea. Wondering how to achieve it?

**Comment by ManuLpz4** [comment]
We need to achieve this. Some suggestion? @jiayi1992

**Comment by erfan377** [comment]
> Also found that the tokenURI of https://opensea.io/assets/ethereum/0x9b091d2e0bb88ace4fe8f0fab87b93d8ba932ec4/3095 only has image_data field and it works on opensea. Wondering how to achieve it?

I'm also very curious how this has been done!

**Comment by wilks7** [comment]
Was anyone able to figure this out? Running into the same issue, I even tried copying and using the svg and data URI from the project linked and it still doesn't doesn't show on OpenSea

**Comment by shaesel** [comment]
Hello all,
experiencing the same issue. Coudlanyone already solve the problem?

**Comment by alexvobo** [comment]
> Was anyone able to figure this out? Running into the same issue, I even tried copying and using the svg and data URI from the project linked and it still doesn't doesn't show on OpenSea

Experiencing the same problem with `<image>` tags within an SVG. All other elements within the SVG will load properly.

![image](https://user-images.githubusercontent.com/20468109/217692339-8b2c9f92-0dfb-419d-9eca-65d87ac082f1.png)

The "View original media" button loads the SVG properly in a new tab.

**Comment by DavNej** [comment]
Same issue here !
