### ISSUE TITLE
No API Keys for months

### ISSUE THREAD

**Issue by kosso** [ProjectOpenSea/opensea-js#650]
Hi.

I applied months ago for an API Key and still no response. 

This particularly irks me, due to the rigmarole required to apply for one, with connecting wallets with a "non-zero amount of ETH" in it and generating signatures. 

Without API Keys, this SDK is unusable. 

What the heck is going on? I have jobs to do which require me to use the SDK for client who (I wish hadn't) created their collection using OpenSea's 'OPENSTORE" ERC1155 contract.  There's very little 'open' about it. Sadly.

**Comment by nnbp7** [comment]
Do you need an api key? i have them avaliable for sale.

**Comment by PeterCHK** [comment]
Hi @nnbp7, can you email me your appropriate asking price for the opensea api key? Many thanks. 
peter@centralin.io

**Comment by ryanio** [comment]
Sorry for the trouble, self-serve API keys are now slowly rolling out: https://twitter.com/apiopensea/status/1651650717546074112

**Comment by ryanio** [comment]
You can now get access to API keys in your account: https://docs.opensea.io/reference/api-keys#how-do-i-get-an-api-key
