### ISSUE TITLE
add to gas fee for faster transaction in the new version

### ISSUE THREAD

**Issue by asafd11** [ProjectOpenSea/opensea-js#651]
i am trying to add extra gwei to the gas fee for faster transactions 
this is what a change
```
 // Extra gwei to add to the mean gas price when making transactions
   this.gasPriceAddition = new bignumber_js_1.BigNumber(30);  // was 3 be default 
  // Multiply gas estimate by this factor when making transactions
  this.gasIncreaseFactor = constants_2.DEFAULT_GAS_INCREASE_FACTOR;  // i set it to 2 default was 1
```
this not working in the new version of the sdk :(

is there a way to add extra to the gas fee ?

**Comment by bernardovski** [comment]
would like to know this as well.. with the previous atomic match we could fetch the encoded abi and send it through normal transaction that could be customized with our prefered gas settings, but with this new one i haven't figured out how to do so.

**Comment by walruzperil** [comment]
any updates?

**Comment by nickyoung92** [comment]
Dying for custom gas.
