### ISSUE TITLE
Listing limit issue / failed to fetch...

### ISSUE THREAD

**Issue by ApeLife24** [ProjectOpenSea/opensea-js#652]
Hello so I wonder how people can do a listing of their items once every 10-15 seconds... But I'm "limited" and only can do one every 100-120 seconds.... If I don't wait that long I get failed to fetch error over and over...

Does that people is using a api key? I got an api key the other day but I don't know how I can use it to do the listing like that any documentation or help for this? 
This happens on the ethereum network... I have around 100 items I want to list but can't because of this is literally taking me 3-4 hours to list it all... a month ago I wasn't having this issue and was able to do it fast not sure how fast I was doing it for each nft but I didn't spend more than a hour listing the 100 items so probably was doing it every 30 seconds

**Comment by jsbskzbakwu6568** [comment]
same my issue brother

api 429 and failed to fetch have to wait 3 minute between listing
i have 5k items This take me for ever

they have limit to collections made in opensea This make no sense

the limit they says not true i stuck with this 2 weeks now in every day

**Comment by ApeLife24** [comment]
> same my issue brother
> 
> api 429 and failed to fetch have to wait 3 minute between listing i have 5k items This take me for ever
> 
> they have limit to collections made in opensea This make no sense
> 
> the limit they says not true i stuck with this 2 weeks now in every day

Exactly, same problem here, I don't have that many nfts to list but still a lot of time, is impossible for you, hopefully they give us a solution soon, seems like is on purpose or I don't know, everything start whent they migrate to seaport but they let the shared storefront items out of this protocol.... 

If they put a limit they should just say it, they give weird answer saying is been like this always but a month ago I never have this issue so is something they implement new... And they ignore this kind of thread or questions on the discord so yeah... 

Hopefully if they one day decide to open seaport to shared storefront items this get fixed, is been a month without an update.... And they keep saying soon but doesn't seems like they will let shared storefront to use seaport protocol to be honest, feel like they will keep using wyvern for this.

**Comment by jsbskzbakwu6568** [comment]
i cant sell now because of this i stuck with listing 200 items from yesterday
* they said the limit is
1000 item / in 1 day
15 item / in 1 minute
2 item / in sec
i dont think This true, i am not that fast at all but they can increase the limit in one day maybe it will fix the problem
like 3k or 4k item in 1 day it will be good, i dont have issue with other limit.
there is huge number of collection owners think This is bug and it will be fix which is not.

on the other Hand collection made on its own contract with seaport dont have This, and collection made exclusive in opensea website have it, This make no sense at all.

**Comment by ApeLife24** [comment]
> i cant sell now because of this i stuck with listing 200 items from yesterday
> 
> * they said the limit is
>   1000 item / in 1 day
>   15 item / in 1 minute
>   2 item / in sec
>   i dont think This true, i am not that fast at all but they can increase the limit in one day maybe it will fix the problem.
>   like 5k item in 1 day it will be good, i dont have issue with other limit.
>   there is huge number of collection owners think This is bug and it will be fix which is not.
> 
> on the other Hand collections made on its own contract with seaport dont have This, and collections made exclusive in opensea website have it, This make no sense at all.


Wow this is really sad, I wasn't aware of those limits at all, I'm not even that fast either tho I take around 30-40 seconds do list each of my items and I have right now 117, and I get limited too is weird... 

And I see some people that are on the shared storefront too and seems like they aren't limited at all...

**Comment by jsbskzbakwu6568** [comment]
yah i saw it too, seems not all collections have this or its bug happend with our collections when the protocol change to seaport and back again to wyvern

i dont think this is normal or its there from long time ethier its bug or something new they made 
cuz before 15 june we dont have this issue

**Comment by ApeLife24** [comment]
> yah i saw it too, seems not all collections have this or its bug happend with our collections when the protocol change to seaport and back again to wyvern
> 
> i dont think this is normal or its there from long time ethier its bug or something new they made cuz before 15 june we dont have this issue

Maybe is becuase those user use the api key, I got an api key but not idea how to use it at all. 
And asked but without help.

Our maybe that's why I remember that day the protocol change I was asked to pay a fee to list the items, but I didn't and then they return to wyvern, maybe those user pay the fee and that's why they can... I don't mind paying the $4-$5 fee if I can do my  listing without need to wait 120 second between each one...

**Comment by ApeLife24** [comment]
> my collection in opensea website why the hell i go to use api key
> 
> i dont want list fast i just want to list normal like before lol
> 
> hope they will fix this , cuz we dont even reach the limit they say but we got errors

Exactly that's why is weird, because those limits seems different for us....

https://twitter.com/z0age/status/1537276889504415744 

Hopefully they fix it soon but when I read thise weeks ago I feel there won't be anything solved soon.... Hopefully I'm wrong.

**Comment by jsbskzbakwu6568** [comment]
this problem only for etherem network , polygon collections they dont have this at all 

so its not limit just bug maybe

**Comment by jsbskzbakwu6568** [comment]
wow i wish i can list every 1 minute

**Comment by ApeLife24** [comment]
> wow i wish i can list every 1 minute

yes... Another one doing the same https://opensea.io/LiberatorApeGeneral?tab=activity I can't understand honestly...

**Comment by maximusrus** [comment]
I have the same issue though I was successfully uploaded and listed two days ago at a rate 4 items / sec so I think it's normal.

But you better look at these two collections which have enormous listing speed:
- https://opensea.io/collection/bored-ape-bros/activity?search[isSingleCollection]=true&search[eventTypes][0]=AUCTION_CREATED
- https://opensea.io/collection/boredbearfrens/activity?search[isSingleCollection]=true&search[eventTypes][0]=AUCTION_CREATED

**Comment by jsbskzbakwu6568** [comment]
> I have the same issue though I was successfully uploaded and listed two days ago at a rate 4 items / sec so I think it's normal.
> 
> But you better look at these two collections which have enormous listing speed:
> 
> * [https://opensea.io/collection/bored-ape-bros/activity?search[isSingleCollection]=true&search[eventTypes][0]=AUCTION_CREATED](https://opensea.io/collection/bored-ape-bros/activity?search%5BisSingleCollection%5D=true&search%5BeventTypes%5D%5B0%5D=AUCTION_CREATED)
> * [https://opensea.io/collection/boredbearfrens/activity?search[isSingleCollection]=true&search[eventTypes][0]=AUCTION_CREATED](https://opensea.io/collection/boredbearfrens/activity?search%5BisSingleCollection%5D=true&search%5BeventTypes%5D%5B0%5D=AUCTION_CREATED)

I think u mean with api key

which we dont use

**Comment by jsbskzbakwu6568** [comment]
> > > I have the same issue though I was successfully uploaded and listed two days ago at a rate 4 items / sec so I think it's normal.
> > > But you better look at these two collections which have enormous listing speed:
> > > 
> > > * [https://opensea.io/collection/bored-ape-bros/activity?search[isSingleCollection]=true&search[eventTypes][0]=AUCTION_CREATED](https://opensea.io/collection/bored-ape-bros/activity?search%5BisSingleCollection%5D=true&search%5BeventTypes%5D%5B0%5D=AUCTION_CREATED)
> > > * [https://opensea.io/collection/boredbearfrens/activity?search[isSingleCollection]=true&search[eventTypes][0]=AUCTION_CREATED](https://opensea.io/collection/boredbearfrens/activity?search%5BisSingleCollection%5D=true&search%5BeventTypes%5D%5B0%5D=AUCTION_CREATED)
> > 
> > 
> > I think u mean with api key
> > which we dont use
> 
> No, I've listed manually via the website. Every hour I stopped listing for an hour and then started again.

good to know This, but i cant with 5k items it will take long time

**Comment by maximusrus** [comment]
> > > > I have the same issue though I was successfully uploaded and listed two days ago at a rate 4 items / sec so I think it's normal.
> > > > But you better look at these two collections which have enormous listing speed:
> > > > 
> > > > * [https://opensea.io/collection/bored-ape-bros/activity?search[isSingleCollection]=true&search[eventTypes][0]=AUCTION_CREATED](https://opensea.io/collection/bored-ape-bros/activity?search%5BisSingleCollection%5D=true&search%5BeventTypes%5D%5B0%5D=AUCTION_CREATED)
> > > > * [https://opensea.io/collection/boredbearfrens/activity?search[isSingleCollection]=true&search[eventTypes][0]=AUCTION_CREATED](https://opensea.io/collection/boredbearfrens/activity?search%5BisSingleCollection%5D=true&search%5BeventTypes%5D%5B0%5D=AUCTION_CREATED)
> > > 
> > > 
> > > I think u mean with api key
> > > which we dont use
> > 
> > 
> > No, I've listed manually via the website. Every hour I stopped listing for an hour and then started again.
> 
> good to know This, but i cant with 5k items it will take long time

That's true but I think we just need to wait for a fix. I've checked the OpenSea's twitters yesterday and they said they are going to migrate all collections to Seaport soon and I believe they will fix that issue soon.

**Comment by ApeLife24** [comment]
> I have the same issue though I was successfully uploaded and listed two days ago at a rate 4 items / sec so I think it's normal.
> 
> But you better look at these two collections which have enormous listing speed:
> 
> * [https://opensea.io/collection/bored-ape-bros/activity?search[isSingleCollection]=true&search[eventTypes][0]=AUCTION_CREATED](https://opensea.io/collection/bored-ape-bros/activity?search%5BisSingleCollection%5D=true&search%5BeventTypes%5D%5B0%5D=AUCTION_CREATED)
> * [https://opensea.io/collection/boredbearfrens/activity?search[isSingleCollection]=true&search[eventTypes][0]=AUCTION_CREATED](https://opensea.io/collection/boredbearfrens/activity?search%5BisSingleCollection%5D=true&search%5BeventTypes%5D%5B0%5D=AUCTION_CREATED)

That's insane, don't know how people can do that, I'm doing it at 30-40 seconds I can't faster and still after like 3-4 I get failed to fetch and need to wait 100-120 seconds then can do it again.

I got a api key but no idea how to use it at all.
Hopefully they fix it, I read on the twiter 20 day's ago they will solve it soon, so I kinda lost any hope but well... Just keep waiting I suppose.

**Comment by jsbskzbakwu6568** [comment]
> 

its if you have 5k or 10k collection and more then half of them. not listed

**Comment by ApeLife24** [comment]
> > 
> 
> it is, if you have 5k or 10k collection and more then half of them. not listed

I can't even imagine, I don't even have 150 to list and I'm really frustrated for that amount will take weeks to list
