### ISSUE TITLE
Retrieve collections API response data's floor_price always zero

### ISSUE THREAD

**Issue by xiaoyannzbbb** [ProjectOpenSea/opensea-js#658]
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/107618564/177682791-b401864a-c7f4-436c-af80-b25178280f31.png">

**Comment by BLUEDERPY** [comment]
I am having the same issue and can verify it is working for the collection end point but not collections
Collections: 
<img width="503" alt="image" src="https://user-images.githubusercontent.com/74120282/178118024-45e9440b-d789-4966-b202-3940868e6251.png">
Collection: 
<img width="469" alt="image" src="https://user-images.githubusercontent.com/74120282/178118046-4f82fa70-b4a0-4a22-9a81-5b5bb888c6a9.png">

**Comment by metadanc** [comment]
This seems to be a continued problem... do we have an ETA on when this would be fixed?
