### ISSUE TITLE
Floor price always 0 from collections end point

### ISSUE THREAD

**Issue by BLUEDERPY** [ProjectOpenSea/opensea-js#660]
https://api.opensea.io/api/v1/collections/?asset_owner={address} is always returning 0 for the floor_price. If I use the collection endpoint instead of collections, the floor price is correct.

**Comment by GoldLiondev** [comment]
Hello, I got the same issue to use Opeansea collections endpoint.
They always return 0 for floor price. but it is incorrect and when I get the floor price via opensea stats endpoint, it return correct price.
please help me how to fix it asap.
Thanks

**Comment by marcosteixeira** [comment]
+1

**Comment by remigastaldi** [comment]
Up
