### ISSUE TITLE
does the sdk support  polygon network?

### ISSUE THREAD

**Issue by myst4** [ProjectOpenSea/opensea-js#662]
hello there I was wondering is this sdk is actually supporting polygon blockchain?

I cant found any related this in the docs

thanks!

**Comment by onurozansahin** [comment]
It would have made an awesome change if SDK started supporting Polygon. When can we expect this? Or can we expect this at all?

**Comment by ashitosh03** [comment]
Hello, is there any plan adding support for Polygon network?

**Comment by ryanio** [comment]
we are planning to add more of our supported networks soon

**Comment by ryanio** [comment]
closing as duplicate of #150
