### ISSUE TITLE
error: Either signer or a JsonRpcProvider must be provided

### ISSUE THREAD

**Issue by Meloneat** [ProjectOpenSea/opensea-js#663]
Strange with error "Either signer or a JsonRpcProvider must be provided" while using `createSellOrder` method after upgrading the opensea@4.0.4 and @truffle/hdwallet-provider@2.0.10.
In fact, several hours before, use opensea@4.0.3, the createSellOrder is still worked.

**Comment by jokereven** [comment]
> Strange with error "Either signer or a JsonRpcProvider must be provided" while using `createSellOrder` method after upgrading the opensea@4.0.4 and @truffle/hdwallet-provider@2.0.10. In fact, several hours before, use opensea@4.0.3, the createSellOrder is still worked.

兄弟一样的问题你解决没;
