### ISSUE TITLE
How can we get all token ids for a specific trait?

### ISSUE THREAD

**Issue by aster2709** [ProjectOpenSea/opensea-js#670]
Is there an endpoint for getting all token ids for a specific trait.

for example, there's 46 bored apes with gold fur trait.
![image](https://user-images.githubusercontent.com/39130640/179170952-62b60b2d-73b7-4d99-9205-9e6e7100b47c.png)

How can I get this programmatically, and the token ids of these 46. Thanks

**Comment by rgutierrezatx** [comment]
i use the assets endpoint and cursor to fetch the entire collection and stored the tokens and their traits in my local database.   then when i need to query tokens by trait, i just do it locally.
