### ISSUE TITLE
Collection Offers using SDK/API

### ISSUE THREAD

**Issue by MetalGear-cmd** [ProjectOpenSea/opensea-js#672]
Hey @jtaaa 
This is not an issue, it's a feature request.
It would be really appreciated if the Dev team can enable collection offers using the new seaport protocol via the SDK/Api.
I am sure the team is already working on it, and if so it would be really amazing to have an eta on when this feature will be rolled out to the API.
And if not then I am requesting the team to add this feature to the SDK/API.
Thanks.

**Comment by jtaaa** [comment]
Support for collection offers is currently in the works. I don't have an ETA for you but it will be soon.

**Comment by MetalGear-cmd** [comment]
> Support for collection offers is currently in the works. I don't have an ETA for you but it will be soon.
Thanks for the update.

**Comment by moon0712** [comment]
any update for Collection Offers using SDK/API?

**Comment by MetalGear-cmd** [comment]
@jtaaa Any update? a rough ETA?

**Comment by moon0712** [comment]
Any update?

**Comment by 0xshawn** [comment]
+1

**Comment by mark-ht** [comment]
> Support for collection offers is currently in the works. I don't have an ETA for you but it will be soon.

Is it possible to give some rough timeline at this point? E.g weeks / months? We're wanting to place collection offers based on certain criteria and for everyone's sake would rather do so via collection based bid rather than through say 6k individual bids!

**Comment by amondi-media** [comment]
+1

**Comment by moon0712** [comment]
+N

**Comment by M4tsuri** [comment]
Hello, I'm trying to send collection offers with `OpenSeaSDK.api.postOrder` and parameters generated according to the docs. However, the backend returns `Error: API Error 400: Asset does not exist ` when I'm sending offer with criteria (I copied the criteria from signing message sent to MetaMask). I wonder if this feature is not yet implemented in backend or I'm misusing the `postOrder` API.
Thank you.

**Comment by tino-q** [comment]
+N+1

**Comment by M4tsuri** [comment]
> 

Thank you for demonstrating. But the API seems to be making single offer when I'm making offer with `identifierOrCriteria` set to 0 and `itemType` **set exactly to 4 (which is ERC721_WITH_CRITERIA)**.

**Comment by Ghijo1** [comment]
> Hello, I'm trying to send collection offers with `OpenSeaSDK.api.postOrder` and parameters generated according to the docs. However, the backend returns `Error: API Error 400: Asset does not exist ` when I'm sending offer with criteria (I copied the criteria from signing message sent to MetaMask). I wonder if this feature is not yet implemented in backend or I'm misusing the `postOrder` API. Thank you.

Hello, I have the same issue. Did you solve in some way?
Thank you

**Comment by sevkibaba** [comment]
Hey guys, it will be good to have a working function for getOrder that is working on orderHash, thanks in advance.
