### ISSUE TITLE
Error: API Error 400: You must approve assets #0 for trading before creating an order

### ISSUE THREAD

**Issue by Novenqingtang** [ProjectOpenSea/opensea-js#679]
Hello, I use a new address. I want to use SDK to make offer for an asset. This error occurred when calling **createBuyOrder**. I guess it should be that I didn't approve WETH to the Opensea contract.

`API Error 400: You must approve assets #0 for trading before creating an order`

I traced this problem and found that the **executeAllActions** method in the @opensea/seaport-js library uses the for () code, and the approve contract call of wet and the createOrder API call at the same time, but createOrder API validate the WETH is approved. So i think we should use **for...of** or **for await** to execute the approve first, and then execute the **createOrder** API call after success. Please confirm whether there is this problem? thx.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/20578889/181021550-785be46d-89ef-447c-a39f-08ed83c4a942.png">

**Comment by Novenqingtang** [comment]
It's not this problem.

**Comment by Praveen-47** [comment]
facing the same problem with create Offer function, This happens when I change the address(to a new address)

**Comment by Novenqingtang** [comment]
@Praveen-47 It's the problem of @opensea/seaport-js,  it just await tx sending to node, but it not await the tx be included. 

[https://github.com/ProjectOpenSea/seaport-js/blob/main/src/utils/usecase.ts](https://github.com/ProjectOpenSea/seaport-js/blob/main/src/utils/usecase.ts) 

<img width="833" alt="image" src="https://user-images.githubusercontent.com/20578889/181196978-68a24bf5-1350-4ee4-b8b0-54d07dca7559.png">

**Comment by Novenqingtang** [comment]
@Praveen-47 Maybe, you can validate the approve and send approve tx before invoke opensea-sdk.

**Comment by Praveen-47** [comment]
Yes after doing the sign we can ignore the error

**Comment by dogukanakkaya** [comment]
If anyone having this issue with an ERC721 contract for Polygon, you can use this `isApprovedForAll` function. If you are using Polygon Mumbai & Opensea Testnet use this below:
```solidity
 function isApprovedForAll(
        address _owner,
        address _operator
) public view override returns (bool isOperator) {
        // if OpenSea's ERC721 Proxy Address is detected, auto-return true
        if (_operator == address(0x1E0049783F008A0085193E00003D00cd54003c71)) {
            return true;
        }

        // otherwise, use the default ERC721.isApprovedForAll()
        return ERC721.isApprovedForAll(_owner, _operator);
}
```
There was a lot of wrong addresses in the internet, i found the correct one by manually trying to approve my NFT listing from Opensea Testnet website and then checked the transaction's input data. You can see the correct address there:

<img width="1034" alt="Screenshot 2023-03-03 at 16 09 15" src="https://user-images.githubusercontent.com/51231605/222728164-f783c18e-1ffb-420a-99e1-993841ddcab7.png">
