### ISSUE TITLE
Create Sell Order error 

### ISSUE THREAD

**Issue by rayanoncyber** [ProjectOpenSea/opensea-js#68]
Hey! 

Every time the createSellOrder method is called, I get :
- MetaMask - RPC Error: execution reverted
- a confirmation message that Order hashes match
- API Error 400: ['Failed to extract transfer calldata'] after calling https://api.opensea.io/wyvern/v1/orders/post/

Haven't found a fix anywhere in a week so posting this here, might be a bug? 

Thank you,
Rayan Boutaleb

**Comment by wh1rl** [comment]
Faced the same issue today, it seems that createSellOrder doesn't work with gasless collections, right?
Also there is a postOrder method inside OpenSeaAPI, but I can't figure out how to make it work. 
Please help us :)

Thx

**Comment by wh1rl** [comment]
Also tried to hack a little into OpenSeaPort.prototype._makeSellOrder execution, replaced calldata to '0xf242432a0000000000000000000000009affc00b6f6f3c2890ffeb8092271c29bc1a56a900000000000000000000000000000000000000000000000000000000000000009affc00b6f6f3c2890ffeb8092271c29bc1a56a9000000000000010000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000' and it worked!
So maybe it needs a proper calldata for those gassless collections.

**Comment by wh1rl** [comment]
Managed to make it work, @iamsupercharged you need to set assets's schemaName to WyvernSchemaName.ERC1155

**Comment by iamsupercharged** [comment]
Yesss works for me too. Thank you! Should be added to the docs it's quite confusing and hard to find an answer for!
