### ISSUE TITLE
OpenSea fees are required to post this order.

### ISSUE THREAD

**Issue by hoanghiep** [ProjectOpenSea/opensea-js#682]
Hi. I am trying to list a nft via post method to https://api.opensea.io/v2/orders/ethereum/seaport/listings. I have sent full "consideration" list. But Opensea API always response: ['OpenSea fees are required to post this order.']

Here is my post data:
```
 {
    "parameters": {
        "offerer": "0x0",
        "zone": "0x004C00500000aD104D7DBd00e3ae0A5C00560C00",
        "zoneHash": "0x3000000000000000000000000000000000000000000000000000000000000000",
        "startTime": 1659083122,
        "endTime": 1661675122,
        "orderType": 2,
        "offer": [{
            "itemType": 2,
            "token": "0x0",
            "identifierOrCriteria": "3429",
            "startAmount": "1",
            "endAmount": "1"
        }],
        "consideration": [{
            "itemType": 0,
            "token": "0x0000000000000000000000000000000000000000",
            "identifierOrCriteria": "0",
            "startAmount": "68250000000000000",
            "endAmount": "68250000000000000",
            "recipient": "0x0"
        }, {
            "itemType": 0,
            "token": "0x0000000000000000000000000000000000000000",
            "identifierOrCriteria": "0",
            "startAmount": "1750000000000000",
            "endAmount": "1750000000000000",
            "recipient": "0x8De9C5A032463C561423387a9648c5C7BCC5BC90"
        }, {
            "itemType": 0,
            "token": "0x0000000000000000000000000000000000000000",
            "identifierOrCriteria": "0",
            "startAmount": "7000000000000000",
            "endAmount": "7000000000000000",
            "recipient": "0x0"
        }],
        "totalOriginalConsiderationItems": 3,
        "salt": "0x8a4922a6fabcfc97b4e75807785e88ea",
        "conduitKey": "0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000",
        "counter": "0"
    },
    "signature": "0x0"
}
```
Please show me hơ to fix it? Thank you.

**Comment by ZionNFT** [comment]
Bump! This is affecting my community and a few other tools using this SDK too.

**Comment by tritium01** [comment]
Bump! this is also affecting my community

**Comment by aya015757881** [comment]
If you trim the consideration array to contain only two elements, the offerer being the first, then setting the ratio of the income of the offerer against that of the second address to 97.5% : 2.5% shall do good.

**Comment by Rotemy** [comment]
I'm pretty sure this is related to the fact this collection has multiple royalty recipients. I already approached Opensea dev support about it.

**Comment by ZionNFT** [comment]
> If you trim the consideration array to contain only two elements, the offerer being the first, then setting the ratio of the income of the offerer against that of the second address to 97.5% : 2.5% shall do good.


Hey @aya015757881 !

Thanks a lot for this suggestion. Do you have a fork with this implemented?

**Comment by whitelotus96** [comment]
Bump! This is the same issue for me.

**Comment by AGTGreg** [comment]
Bump! Same thing on my side as well.

**Comment by koin-marian** [comment]
Bump! 20 days and no response? This is ridiculous...

**Comment by Rotemy** [comment]
why `"token": "0x0", ?

**Comment by hoanghiep** [comment]
Some possible causes of the error are as follows:

1. You have not called the setApproveForAll for OpenSea: Conduit function before creating the order

2. You are using the wrong address for OpenSea: Fees. Currently this address is : OpenSea: Fees 3 - 0x0000a26b00c1f0df003000390027140000faa719

3. Please use createSellOrder function instead of creating and sending json data yourself, as your packet may not update with the correct information.

4. https://github.com/ProjectOpenSea/opensea-js/commit/bf81cfeef303858031a9a83243266b0d548bde4a

5. https://github.com/ProjectOpenSea/opensea-js/issues/697#issuecomment-1219418644

**Comment by pufferdev0807** [comment]
Awesome, I had the same problems before but it is working now.
Perfect.

**Comment by jawkhan** [comment]
> Awesome, I had the same problems before but it is working now. Perfect.

what changes did you make exactly to make it work?

**Comment by ahomberger** [comment]
I had the same error when my offers was at the wallet balance.
I fixed it by rounding the amount to 5 digits and reduce it of -0.00001 ETH

So in Python:  max_offer_price_eth = round(wallet_balance_eth, 5) - 0.00001
