### ISSUE TITLE
Searching OpenSea via the API

### ISSUE THREAD

**Issue by KirkMunro** [ProjectOpenSea/opensea-js#685]
I'm new to the OpenSea API, and looking for a way to search via the API just like I would via the search field on the OpenSea website. Is there a discovery API for OpenSea that supports this? I want to be able to mimic the behavior of the search bar on OpenSea.

If someone could point me in the right direction, I'd appreciate it.

**Comment by cterech** [comment]
Hey Kirk! Unfortunately, we don't support search on the API -- we don't have plans for that anytime soon.
