### ISSUE TITLE
Opensea SDK polygon network cannot create order

### ISSUE THREAD

**Issue by Daudxu** [ProjectOpenSea/opensea-js#687]
When I use opensea SDK polygon network
Create order cannot use interface createsellorder failed https://api.opensea.io/api/v1/asset/xxx
404 error

**Comment by onurozansahin** [comment]
Hey all, are there any plans for Polygon support? I'm wondering if Opensea SDK will ever support it, and would like to consider what I can do if the support is not going to be there.
