### ISSUE TITLE
getAssets() silently ignores seaport_sell_orders when using include_orders param

### ISSUE THREAD

**Issue by reaganchisholm** [ProjectOpenSea/opensea-js#689]
Using SDK version `4.0.6`

Based on the [docs](https://docs.opensea.io/reference/getting-assets), it seems like `include_orders` is supported and should return `seaport_sell_orders`

When calling `getAssets()` with `include_orders`
```js
const assets = await openseaSDK.api.getAssets({
  // ...
  include_orders: true
})
```

The API endpoints properly returns `seaport_sell_orders` with the asset: [Testnet API example call](https://testnets-api.opensea.io/api/v1/assets/?asset_contract_address=0x03e73ef97303e11703864a5404d71351ef61d8f8&include_orders=true&limit=1&order_direction=asc&token_ids=7100020009)

But it seems the issue happens when the assets are mapped from JSON, `seaport_sell_orders` are ignored, only the legacy `sell_orders` are accounted for

Current behaviour:
1. [call getAssets, process JSON assets returned from API](https://github.com/ProjectOpenSea/opensea-js/blob/master/src/api.ts#L260)
2. [each asset is mapped and only legacy sell_orders is accounted for, seaport_sell_orders gets ignored/not mapped to object](https://github.com/ProjectOpenSea/opensea-js/blob/5045231885ca86922b43b5a4b67e4c38bff3ed91/src/utils/utils.ts#L224)
3. Assets get returned silently excluding any `seaport_sell_orders`, even though they were included in API JSON response

Expected behaviour:
1. Call getAssets
2. Assets are mapped and account for `seaport_sell_orders`
3. Assets object is returned with `seaportSellOrders`

Please let me know if I can provide any other details.

**Comment by Rotemy** [comment]
You can't use include_orders with OpenSea SDK, they are not supporting it yet. Just call the API directly via http call

**Comment by reaganchisholm** [comment]
@Rotemy thanks for the reply. I'm a bit confused because you could use `include_orders` as I mentioned before the recent switch to `seaport_sell_orders`, it would return `sellOrders` on the assets just like it would when calling the API directly, so it seemed to be supported (maybe indirectly?)

Are you saying the SDK never intended to support it?

**Comment by Rotemy** [comment]
Probably it got removed from the SDK in the new (4.0) version because I don't see any reference to include_orders on that project. As you can just use the API using a http call I would close this issue.
