### ISSUE TITLE
fulfillOrder is listing the asset directly after the purchase

### ISSUE THREAD

**Issue by FloUz-ai** [ProjectOpenSea/opensea-js#690]
Hi guys, I use this sdk to buy assets from a collection with the fulfillOrder method. 

I encunter a very strange behaviour cause , immediatly after having bought the asset, it is listed without emiting any event.. 
This behavioutr seems to be pretty random. It doesn't happened for every call.

Anyone has an idea about this issue?

**Comment by Rotemy** [comment]
I really doubt it is doing it, maybe you have multiple listing for this asset?

**Comment by FloUz-ai** [comment]
I really don't know, it did not happened again.. i'll close the isssue
