### ISSUE TITLE
Private listing issue via SDK

### ISSUE THREAD

**Issue by lidaamber** [ProjectOpenSea/opensea-js#691]
The example of private listing in readme seems outdated:

```
// Address allowed to buy from you
const buyerAddress = "0x123..."

const listing = await openseaSDK.createSellOrder({
  tokenAddress: "0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d", // Decentraland
  tokenId: "115792089237316195423570985008687907832853042650384256231655107562007036952461", // Token ID
  accountAddress: OWNERS_WALLET_ADDRESS,
  startAmount: 10,
  buyerAddress
})
```

If changing it to the updated asset model like in regular listing example, the listing should likely look something like this:
```
const listing = await openseaSDK.createSellOrder({
  asset: {
    tokenAddress: privateTokenAddress,
    tokenId: privateTokenId,
  },    
  accountAddress: account,
  startAmount: 0.01,
  buyerAddress: buyer
})
```
But is also doesn't work and produces error `Error: API Error 400: OpenSea fees are required to post this order.`

Please let me know if there is any issue with the listing model above, or is it something on SDK side that should be fixed? Thanks

**Comment by Rotemy** [comment]
Does this collection has multiple royalty recipients?

**Comment by lidaamber** [comment]
Nope, it is an Opensea shared contract item, but not minted though. Is private listing allowed only for minted items?

**Comment by Rotemy** [comment]
> Nope, it is an Opensea shared contract item, but not minted though. Is private listing allowed only for minted items?

if it is not minted yet, what did you put here `privateTokenAddress` and here `privateTokenId`?

**Comment by lidaamber** [comment]
The shared contract address & the token id on the platform. This worked well for non-minted items for regular sale listing

**Comment by tullahnazari** [comment]
Any resolution to this issue? I randomly started getting it yesterday and before that everything was okay. I was able to createSellOrder previously.

**Comment by FloUz-ai** [comment]
Same issue here, on rinkeby . It worked few days ago, and nothing today ...

**Comment by FloUz-ai** [comment]
In my case nft's are minted already

**Comment by tullahnazari** [comment]
> Same issue here, on rinkeby . It worked few days ago, and nothing today ...

I figured mine out after posting earlier. You must've changed something. I was playing around with different parameters and forgot I added an extra parameter to test something. The error handling is just confusing, which is why i thought it was something related to my opensea account. You maybe added or deleted something to your call, triple check that, good luck!

**Comment by FloUz-ai** [comment]
Not even. I tried to sell an asset not private with this code : 

 ```
const listing = await openseaSDK.createSellOrder({
      asset: {
        tokenId,
        tokenAddress,
      },
      accountAddress: owner,
      startAmount: price,
    });
```

It went through. But as soon as I add a buyer address as follow : 
```
const listing = await openseaSDK.createSellOrder({
      asset: {
        tokenAddress,
        tokenId,
      },
      accountAddress: owner,
      startAmount: price,
      buyerAddress,
    });
```
    
    I have the error  ```API Error 400: OpenSea fees are required to post this order.```

**Comment by FloUz-ai** [comment]
> > Same issue here, on rinkeby . It worked few days ago, and nothing today ...
> 
> I figured mine out after posting earlier. You must've changed something. I was playing around with different parameters and forgot I added an extra parameter to test something. The error handling is just confusing, which is why i thought it was something related to my opensea account. You maybe added or deleted something to your call, triple check that, good luck!

Is everything working for you now?

**Comment by FloUz-ai** [comment]
No news since then.. Should be fine with the version 4.0.7
but nothing exepct on testnet ..What a weird behaviour

**Comment by 0xshawn** [comment]
Same error on testnets, why? @sunwrobert

**Comment by tullahnazari** [comment]
> Same error on testnets, why? @sunwrobert

Share your code.

**Comment by FloUz-ai** [comment]
@0xshawn , on my side It works now on testnet, the pb is only on mainnet

**Comment by 0xshawn** [comment]
```
const listing = await openseaSDK.createSellOrder({
  asset: {
    tokenAddress: privateTokenAddress,
    tokenId: privateTokenId,
  },    
  accountAddress: account,
  startAmount: 0.01,
  buyerAddress: buyer
})
```

@tullahnazari The code is the same as this one, both testnet and mainnet are failed to post with this error.
