### ISSUE TITLE
API Error 400 : OpenSea fees are required to post this order.

### ISSUE THREAD

**Issue by bechillin** [ProjectOpenSea/opensea-js#697]
I use the same script consistently without any problems. Today when the script ran to make offers, I am receiving Error 400 : OpenSea fees are required to post this order...

Funds have not changed in the wallet since the script last ran yesterday...

Enough WETH to cover bids, and also .1 eth sits in this wallet for transaction fees.

Does anybody have an idea where to start? I am not receiving any debugging errors, and have valid funds available.

Thank you for your time in advance. I appreciate any ideas, as I am stuck now after debugging something most of today.

**Comment by Edvv4rdd** [comment]
In Os discord Community team replied: "I put a bug report together on it team is aware."
so prolly smth broke on Os side, nothing to do, just wait.

**Comment by hoanghiep** [comment]
They changed OPENSEA_FEE_RECIPIENT. You can change OPENSEA_FEE_RECIPIENT to new address in contants.js file.

![opensea-fee](https://user-images.githubusercontent.com/1551503/185381516-2f8f8308-1f02-4b85-a7b6-e006dac97020.PNG)

https://github.com/ProjectOpenSea/opensea-js/pull/695/commits/bf81cfeef303858031a9a83243266b0d548bde4a

**Comment by ServantMaximus** [comment]
I encounter the same issue. Yesterday everything worked fine. Today it isn't.

**Comment by sunwrobert** [comment]
This is fixed now, please update to the latest `opensea-js`: 4.0.7

**Comment by sunwrobert** [comment]
> @sunwrobert can you please confirm if this also fixes the problem with multiple royalty recipient?

This does not fix the multiple royalty recipient unfortunately, we're looking at it but you won't need to update the SDK for this

**Comment by FloUz-ai** [comment]
Is it fixed for everyone ? I still have the same issue with the 4.0.7...

**Comment by LonnyX** [comment]
> This is fixed now, please update to the latest `opensea-js`: 4.0.7

Still the same error... Any update? 😕

**Comment by jawkhan** [comment]
I also have this same issue. Even with the correct opensea address for the opensea fee.
