### ISSUE TITLE
Cannot list nft

### ISSUE THREAD

**Issue by kaiqiangh** [ProjectOpenSea/opensea-js#699]
Cannot use opensea-js to list nft using the code below:
![image](https://user-images.githubusercontent.com/9014062/185420649-2f7823b7-ca0c-4a5b-a054-ff5bbae767f1.png)

Here is the output
![image](https://user-images.githubusercontent.com/9014062/185420396-62510986-8c07-4df5-892d-a83908b0d62d.png)

opensea-js version is 4.0.7

**Comment by stewart-prysm** [comment]
Refer to my comment https://github.com/ProjectOpenSea/opensea-js/issues/702#issuecomment-1220897398

**Comment by kaiqiangh** [comment]
> Refer to my comment [#702 (comment)](https://github.com/ProjectOpenSea/opensea-js/issues/702#issuecomment-1220897398)

Thanks! Resolved it after upgrading.
