### ISSUE TITLE
fulfillOrder function throwing No Schema Found For Asset error

### ISSUE THREAD

**Issue by dcarlcf** [ProjectOpenSea/opensea-js#7]
I cloned the OpenSea-JS repository so that I can integrate OpenSea auctions. I am attempting to call the fulfillOrder function, but getSchema is throwing an error.

I am running this code inside a React Component. Here is how I am initializing the seaport:

```
import {OpenSeaPort, Network} from '../opensea-js'
import { OrderSide } from '../opensea-js/lib/types.js'

const provider = new Web3.providers.HttpProvider('https://mainnet.infura.io/{api_key}')

const seaport = new OpenSeaPort(provider, {
  networkName: Network.Main
})
```

After successfully retrieving an order from the api, I am calling:

`  await seaport.fulfillOrder({ order, accountAddress })`

and getting back the error:

`Unhandled Rejection (Error): No schema found for this asset; please check back later!`

I am confident that a schema does actually exists for the NFT in question. I have tested with a CryptoKitty and a MLBCryptoBaseball figure.

The error is originating from opensea-js/lib/seaport.js line 1720, in the _getSchema function, which is called in from _makeMatchingOrder. _getSchema is reproduced below:

```
OpenSeaPort.prototype._getSchema = function (schemaName) {
        if (schemaName === void 0) { schemaName = types_1.WyvernSchemaName.ERC721; }
        console.log('schema name ' + schemaName)
        console.log('network name ' + this._networkName)
        console.log(WyvernSchemas.schemas)
        var schema = WyvernSchemas.schemas[this._networkName].filter(function (s) { return s.name == schemaName; })[0];
        console.log(schema)
        if (!schema) {
            throw new Error('No schema found for this asset; please check back later!');
        }
        return schema;
};

```
The function defaults to the schema name ERC721 when none is input (which is the case here), and then looks for that schema in the list of schemas WyvernSchemas has for the mainnet. 

I looked at the result of WyvernSchemas.schemas[main], and WyvernSchemas has 15 schemas for the mainnet, but none with the name ERC721. Is there something wrong with the way I am setting up my environment, or is there somewhere else I could load the schema from?

**Comment by alexanderatallah** [comment]
@dcarlcf You're not dependent on another version of wyvern-schemas somewhere, 
by any chance?

Are you on a PC? We've heard about problems with github dependencies from another Windows user. Even after deleting all dependencies and starting from scratch, I can't repro this on a mac, and I see the ERC721 schema showing up fine.

We're in the process of removing lots of submodule dependencies, and that might fix this bug along with https://github.com/ProjectOpenSea/opensea-js/issues/9 for sure

**Comment by dcarlcf** [comment]
No, not on a PC.

It does seem like a module error. When I clone opensea-js and run npm-install I get the same error message that appears on #9 .

This error also occurs when I clone the ships-log repository and run npm install, it gets stuck on the following step: 

`fetchMetadata: sill resolveWithNewModule bignumber.js@2.0.7 checking installable status`

and then throws the error in #9 

I tried on my brothers computer as npm got stuck at the same step and the same error occurred, I am running npm version 6.4.1.

Maybe I should try after the submodule dependencies are removed, when will that happen?

**Comment by alexanderatallah** [comment]
@dcarlcf what version of node are you using?

**Comment by dcarlcf** [comment]
I was running 9.7.1, upgraded to 11.1 and then 11.3 and error still occured

**Comment by alexanderatallah** [comment]
@dcarlcf You should downgrade to (or use nvm to install) 8.11.2. Odd-numbered versions of node are not recommended. See https://nodejs.org/en/. And version 10 has problems with some common crypto dependencies

**Comment by alexanderatallah** [comment]
I'll add a .nvmrc file to make it clear

**Comment by dcarlcf** [comment]
Ok got it, downgraded to 8.11.2 , now giving me this error:

```
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! warning: templates not found /var/folders/kq/25z2qgs123n9_6067kzqhtyw0000gn/T/pacote-git-template-tmp/git-clone-471b794c
npm ERR! warning: templates not found /var/folders/kq/25z2qgs123n9_6067kzqhtyw0000gn/T/pacote-git-template-tmp/git-clone-471b794c
npm ERR! git-lfs filter-process: git-lfs: command not found
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR! Unable to checkout '91ee5d23072fd5c1e62bb78eb6d8fa335098ee5f' in submodule path 'src/wyvern-ethereum/utxo-merkle-proof'
npm ERR! Failed to recurse into submodule path 'src/wyvern-ethereum'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/duncancockfoster/.npm/_logs/2018-12-06T22_04_01_081Z-debug.log
```

**Comment by alexanderatallah** [comment]
@dcarlcf can you try using the most recent version now, `0.4.0-rc8`? I removed the submodule dependencies, so this error should go away!

**Comment by dcarlcf** [comment]
Tried again, this time failed with:

```
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/ProjectOpenSea/wyvern-js.git /Users/duncancockfoster/.npm/_cacache/tmp/git-clone-b8d8ca5e
npm ERR! warning: templates not found /var/folders/kq/25z2qgs123n9_6067kzqhtyw0000gn/T/pacote-git-template-tmp/git-clone-16d0591e
npm ERR! git-lfs filter-process: git-lfs: command not found
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR! warning: Clone succeeded, but checkout failed.
npm ERR! You can inspect what was checked out with 'git status'
npm ERR! and retry the checkout with 'git checkout -f HEAD'
npm ERR! 
npm ERR! 
```

**Comment by alexanderatallah** [comment]
Try googling the git-lfs issue. Maybe this will help? https://github.com/SRombauts/UE4GitPlugin/issues/50

**Comment by dcarlcf** [comment]
Ok I will investigate
