### ISSUE TITLE
Fulfillorder Stuck .. more than an hour 

### ISSUE THREAD

**Issue by FloUz-ai** [ProjectOpenSea/opensea-js#700]
Hi, guys, I try to fullfill an order the openSea SDK fulfillorder method, it goes well on some token but get stuck on other.. now it's been one hour it's trying to Buy one ... any idea whats gooing on ? 

How can I improved the speed of tramsaction, I already put a gasLimit at 20000000000..?

**Comment by tungleanh92** [comment]
Hi @FloUz-ai, can you show me how to create provider with private key? Thanks
