### ISSUE TITLE
ISSUE : Opensea fees are required to post this order

### ISSUE THREAD

**Issue by neicras** [ProjectOpenSea/opensea-js#702]
I got the captioned 404 errors while placing bid. Had this since a few days ago, what is causing this?

**Comment by stewart-prysm** [comment]
Opensea has updated their fee recipient address. You need to use the latest version of `opensea-js` or change any usages of this const `OPENSEA_FEE_RECIPIENT` to this new address: `0x0000a26b00c1f0df003000390027140000faa719`.

Opensea team-- please provide notice ahead of time for API changes like this. This broke listings on my app and many others. Thank you.

**Comment by AmazingZ-sys** [comment]
Opensea team-- please provide notice ahead of time for API changes like this. This broke listings on my app and many others. Thank you.

**Comment by sunwrobert** [comment]
Yup, sorry guys. Will do next time!
