### ISSUE TITLE
Can we use opensea graphql for getting assets with query?

### ISSUE THREAD

**Issue by prodvdjin** [ProjectOpenSea/opensea-js#71]
If I check query on following playground, it works.
https://api.opensea.io/graphql

But if I integrate the graphql on my next.js project, it does not work.
Can we find a way to use the graphql on our customized projects?

**Comment by prodvdjin** [comment]
@alexanderatallah @taylorjdawson @DJViau 
Please help me on this issue.

**Comment by iamoperand** [comment]
I'm interested to know this as well.

**Comment by hiimkhaled** [comment]
I have tried to query top NFTs but their cloudflare firewall stops accessing the graphql endpoint. There is no way I found in REST to get top NFTs, the /collection endpoint does not support sorting.

**Comment by hashgarage** [comment]
I'm struggling with the same issue. The weird thing is it works from postman, but not from cURL or any other way I tried to make the request

**Comment by imbyoe** [comment]
same issue here, let me know if anyone finds a work around

**Comment by sfichera** [comment]
I'm having this same issue with python... can't bypass cloudflare :-(

**Comment by JustroX** [comment]
Same issue here. Any updates on this?

**Comment by warneracw21** [comment]
Any updates? I am able to use the graphql API flawlessly in Graphiql, but not from any application

**Comment by artyrcheek** [comment]
Same issue here,  the REST api isn't great...

**Comment by artyrcheek** [comment]
@eth0izzle s comment on #66 May be useful to some people

**Comment by joventuraz** [comment]
Is this not accesible anymore?

**Comment by arcticmatt** [comment]
https://api.opensea.io/graphql doesn't work for me, I get an "access denied" error

**Comment by joventuraz** [comment]
> > I'm struggling with the same issue. The weird thing is it works from postman, but not from cURL or any other way I tried to make the request
> 
> How did you manage to make this work on postman?

Opensea does not allow a different origin than theirs to access their graphql anymore

**Comment by sfichera** [comment]
Sup guys how are u? All I wanted to do was to take a snapshot of current holders at my OS (OPENSTORE) collection... So i've ended up using free account at "moralis.io" in order to get the info I was trying to get with the graphQL... I've used "/api/v2/nft" endpoint... Hopes this helps! 👍

**Comment by ctohster** [comment]
Seems that they don't want you to be able to access the data. Best option would be to web scrape it

**Comment by mwmwmw** [comment]
If you can access it via python, node, etc. The you just need a cloud function or something similar to grab the data.

I get a 403, so perhaps you need one of the coveted API keys to do so.

**Comment by Aun-Shahbaz-Awan** [comment]
https://rinkeby-api.opensea.io/graphql/ will work for rinkeby-testnet

**Comment by vasinl124** [comment]
+1

**Comment by CastilloLuis** [comment]
same request here, do we have any update about this? web-scraping could work but isn't the best solution imo. I'm wondering if this can be accessible by a subgraph. I would like to query opensea's collection in order to explorer by any [key] given

**Comment by matthewklinko** [comment]
I can access the graphql without issues

**Comment by MarkMoranNZ** [comment]
> I can access the graphql without issues

Hey Matthew. Would you mind contacting me re graphql? Se my profile for email. Cheers, Mark

**Comment by omareldamiry** [comment]
> I can access the graphql without issues

@matthewklinko How?

**Comment by matthewklinko** [comment]
> > I can access the graphql without issues
> 
> @matthewklinko How?

check out https://discord.gg/Yezs2VDhBV

**Comment by MuhammadMinhaj** [comment]
Has anyone managed to access the polygon API in open-sea?
