### ISSUE TITLE
Opensea use webscoketProvider to createorder error~

### ISSUE THREAD

**Issue by moon0712** [ProjectOpenSea/opensea-js#712]
openseaPort upgrade to openseaSDK…cant use Provider webscoket…

const wallet = new HDWalletProvider(PRIVATE_KEY, wss://mainnet.infura.io/ws/v3/XXXXX);

get error reason:

underlying network changed (event=“changed”, network={“chainId”:15407434,“name”:“unknown”}, detectedNetwork={“name”:“homestead”,“chainId”:1,“ensAddress”:“0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e”}, code=NETWORK_ERROR, version=providers/5.6.8)

how to fix it.thanks

**Comment by donnlee** [comment]
Many people having this problem.
https://github.com/ProjectOpenSea/opensea-js/issues/630

No idea how to fix.
