### ISSUE TITLE
stop when installing , cant get SDK resources

### ISSUE THREAD

**Issue by LucasDcarprio** [ProjectOpenSea/opensea-js#714]
idealTree:Administrator: **sill idealTree buildDeps**
i tried :
 change npm & node versions // not work
close Vpn //not work 
change to Linux  //not work
change to yarn way to install // not work
'An unknown git error occurred'
how you guys install it ?

**Comment by LucasDcarprio** [comment]
![Uploading img-git.png…]()

**Comment by LucasDcarprio** [comment]
![img-git](https://user-images.githubusercontent.com/97388772/186850023-4142e46a-e103-4b63-ace7-26274acd96f1.png)

**Comment by LucasDcarprio** [comment]
use CNPM type to install , still cant find binary in $PATH

**Comment by nickyoung92** [comment]
Same here, seems like a recurring issue too. Can devs do something?
