### ISSUE TITLE
Error while trying to post order to OpenSea Error: API Error 400: You have attempted to create a listing, but you provided an invalid number of currency consideration items: 4. A consideration array for a listing may only have 2 or 3 currency items

### ISSUE THREAD

**Issue by Rotemy** [ProjectOpenSea/opensea-js#716]
This happens when I try to post an order for a collection that has multiple royalties recipients.

Of course that using the website it is working perfectly. 

Can you please lift this restriction from the API? pretty urgent

**Comment by Rotemy** [comment]
Important to mention that I make sure to send the same information as when sending using the website

**Comment by Rotemy** [comment]
Also, if I remove the additional one consideration item I get this error: "Collection fees are required to post this order" 

this is extremely frustration.

**Comment by tino-q** [comment]
From the [docs](https://docs.opensea.io/v2.0/reference/create-an-offer):

> the consideration array must have exactly two or three items. The items are (in order): the asset (nft), the OpenSea fee, and an optional collection fee

**Comment by sunwrobert** [comment]
Are you still having issues? Should no longer be an issue

**Comment by Rotemy** [comment]
No this is fixed!
