### ISSUE TITLE
Error : Collection fees are required to post this order.

### ISSUE THREAD

**Issue by Racherin** [ProjectOpenSea/opensea-js#717]
Hi, I'm getting below error when trying to send an offer with opensea-js version 4.0.7.

```shell
Error: API Error 400: Collection fees are required to post this order.
```

This error occurs in collections with more than one royalty recipient. I can see consideration items are signed correctly on website, but it displays only first royalty recipient on opensea-js.

an example code is as below:
```javascript
const seaport = new OpenSeaSDK(nodeProvider, {
    networkName: Network.Main,
    apiKey: "",
  });

const offer = await seaport.createBuyOrder({
  asset: {
    tokenId: "3090",
    tokenAddress: "0x9df8aa7c681f33e442a0d57b838555da863504f3",
  },
  accountAddress: "",
  startAmount: 0.005,
});

```

@alexanderatallah @sunwrobert @jtaaa

**Comment by ahmetcanerkilavuz** [comment]
same error for 4.0.7 @sunwrobert

**Comment by sunwrobert** [comment]
Should be fixed now
