### ISSUE TITLE
ERR_BAD_REQUEST: duplicate key value violates unique constraint "api_fee_account_id_basis_points_276d8b7b_uniq"

### ISSUE THREAD

**Issue by thlix** [ProjectOpenSea/opensea-js#718]
This is a new one. I also tried removing OS fees but then it says Opensea fees are required to post this order.

**Comment by thlix** [comment]
Seems like it was global OS outage

**Comment by ahmetcanerkilavuz** [comment]
@sunwrobert same error for 4.0.7
