### ISSUE TITLE
what is the meaning of the error "invalid order signature" or 

### ISSUE THREAD

**Issue by hsjo12** [ProjectOpenSea/opensea-js#720]
Hello, 

I have minted simple ERC721 to the kalytn mainnet via REMIX IDE. 

Everything is fine except buying a NFT. 

When I tried to buy NFT, I have got an error "invalid order signature"  or  "Your purchase of X failed. This usually happens when gas prices increase or because someone purchased the item before you."

Please let me know why I got this error

Thank you in advance

**Comment by SajawalFareedi** [comment]
got any solutions?

**Comment by sunwrobert** [comment]
Closing, let me know if anything else pops up

**Comment by Tomsonx232** [comment]
I'm having the same issue, don't close this please

**Comment by wongzigii** [comment]
Same issue while listing.

**Comment by onessss** [comment]
Same issue while listing too
