### ISSUE TITLE
FetchError: request to "https://xxx" failed, reason: connect ETIMEDOUT

### ISSUE THREAD

**Issue by G-Z-Ming** [ProjectOpenSea/opensea-js#722]
I try to call the API according to the example you gave, but keep reporting this error

![5912](https://user-images.githubusercontent.com/40484256/188088052-be2abba6-d430-459f-8248-6b7acdb848a8.png)
![5928](https://user-images.githubusercontent.com/40484256/188088075-24553356-9379-40a7-93e3-6e2c554d84e6.png)

**"opensea-js": "^4.0.7",**
**"web3": "^1.7.5",**

**Comment by G-Z-Ming** [comment]
Added, I am testing the rinkeby network

**Comment by ryanio** [comment]
let us know if this is still happening for you. rinkeby is deprecated so you should use goerli
