### ISSUE TITLE
is there a way to check NFT is "reported for suspicious activity"?

### ISSUE THREAD

**Issue by rk-helper** [ProjectOpenSea/opensea-js#726]

**Comment by Racherin** [comment]
@rk-helper use `supports_wyvern` from below API

https://api.opensea.io/api/v1/asset/0xed5af388653567af2f388e6224dc7c4b3241c544/5/?format=json

**Comment by quantix-nft** [comment]
So, I don't understand: in which way I have to use that property (supports_wyvern) to understand whether a specific asset has been flagged as "suspicious" or not?

**Comment by dhapoer** [comment]
up, this issue.
