### ISSUE TITLE
createBuyOrder returning Unable to get current owner from smart contract

### ISSUE THREAD

**Issue by mncn** [ProjectOpenSea/opensea-js#73]
I'm trying to make an offer through createBuyOrder method to a ERC1155 created by createFactorySellOrders but I'm getting "Unable to get current owner from smart contract".  Any ideas?

```
  const offer = await seaport.createBuyOrder({
      asset: order.asset,
      accountAddress,
      startAmount: parseFloat(amount),
      sellOrder: order,
      schemaName,
  });
```

Response:
`Error: Unable to get current owner from smart contract at OpenSeaPort.eval (seaport.js?8b9d:1587)`

Everything seems  fine when I make an offer on testnets.opensea.io, but got this when trying with the API.

**Comment by swarlezbarkley** [comment]
Same here. I am having the same error but with using the function seaport.getAssetBalance(). Please let me know if you have found the solution to this. Thank you

**Comment by kzitouni** [comment]
Did you guys figure it out? Im getting this issue now @mncn @swarlezbarkley

**Comment by ruskid** [comment]
same when using rinkeby chain

**Comment by esteban-OpenSea** [comment]
Just wanted to check in, is this still an ongoing issue for you all?

**Comment by ahjohnwon** [comment]
the same to me,how to solve it?

**Comment by xCozmox** [comment]
@esteban-OpenSea  I still have this issue in the current opensea-js. What is the solution around it?
