### ISSUE TITLE
Use own Zone in order placement

### ISSUE THREAD

**Issue by davidseroussi** [ProjectOpenSea/opensea-js#732]
After reading the documentation and implementation of Seaport, it seems we should be able to provide a `zone` of our own (as long as it implements ZoneInterface) when placing an order.

However, when specifying a custom `zone` I deployed in the API, I am getting an error:
```
API Error 400: You provided an invalid zone: 0x557F6b960F4Fe4fA13bD189C610a33Eb344512ea, please use OpenSea's zone: 0x00000000e88fe2628ebc5da81d2b3cead633e89e for order placement
```
Is this intended behaviour ?  If so, what's the point of having so much customization in Seaport if everything gets blocked by the API ?(Advanced offers are also not supported by the API)

**Comment by sunwrobert** [comment]
You can have your own zone if you launch your own marketplace with Seaport 😉 . However right now we are enforcing it to be only our OpenSea verified zones.
