### ISSUE TITLE
Allow for `owner` param when querying for collections.

### ISSUE THREAD

**Issue by iworkinprogress** [ProjectOpenSea/opensea-js#738]
There was a recent API change that is preventing us from querying the `collections` endpoint by `owner`. This worked as of September 12th and is explicitly mentioned in the documentation:

https://docs.opensea.io/reference/retrieving-collections
```
To include all collections relevant to a user (including non-whitelisted ones), set the owner param.
```

To reproduce:
```
curl --request GET \
     --url 'https://api.opensea.io/api/v1/collections?offset=0&limit=10&owner=0x96dC73c8B5969608C77375F085949744b5177660' \
     --header 'Accept: application/json'
```

returns:
```
{"owner":["extra fields not permitted"]}
```

Expected to return a list of collections owned by the address specified in the `owner` param.

**Comment by cterech** [comment]
hey @iworkinprogress - ```owner``` is not a valid query param - please use ```asset_owner```, example here: https://api.opensea.io/api/v1/collections?offset=0&limit=10&asset_owner=0x96dC73c8B5969608C77375F085949744b5177660

Docs: https://docs.opensea.io/reference/retrieving-collections

note: this is not a regression, ```asset_owner``` was always the name

**Comment by iworkinprogress** [comment]
That's not correct.

`owner` - used to grab all collections CREATED by someone.
`asset_owner` - grabs collections where someone owns a piece in that collection.

See this part in the docs:
```
This endpoint provides a list of all the collections supported and vetted by OpenSea. **To include all collections relevant to a user (including non-whitelisted ones), set the owner param.**
```
