### ISSUE TITLE
Empty array on retrive assets

### ISSUE THREAD

**Issue by arieltoledo** [ProjectOpenSea/opensea-js#741]
Hello, Im trying to get assets from a owner wallet address [https://testnets.opensea.io/es/0x75B53377777a409ea84Bfc1e4fB95274eBc705fF](url), but I only get a empty array. 
Trying the api directly produces the same behaviour [https://testnets-api.opensea.io/api/v1/assets?owner=0x75b53377777a409ea84bfc1e4fb95274ebc705fF&order_direction=desc&offset=0&limit=20](url)
Etherscan shows that the tokens are minted ok [https://rinkeby.etherscan.io/token/0xd11b128a352eb733d17bdb3aa4a2580e33c836cd](url).
What I missing here ? It was working ok until yesterday. 
Thanks in advance.

**Comment by cterech** [comment]
hi, we cut over from Rinkeby to Goerli on 9/13 (yesterday), please see the announcement here: https://twitter.com/apiopensea/status/1569740605097402369?s=20&t=OAqIgT3OWJ6w50_-4Lf2eg

**Comment by arieltoledo** [comment]
@cterech Thanks a lot. Saved my day.
