### ISSUE TITLE
API Error 404: Not found. Full message was '{"success":false}'

### ISSUE THREAD

**Issue by Sam53534512** [ProjectOpenSea/opensea-js#742]
when i call sdk createSellOrder .return issue API Error 404: Not found. Full message was '{"success":false}' anybody resolve it?

**Comment by parkj90** [comment]
I'm also getting the same error when calling createSellOrder on Goerli testnet.

**Comment by hexzerodev** [comment]
Yeah encountered this issue too when on Rinkeby. Seems like Rinkeby is deprecated since 3 days ago in release 4.0.10

**Comment by kevgithub** [comment]
Same error on Goerli
const provider = new Web3.providers.HttpProvider('https://eth-goerli.g.alchemy.com/v2/...');
const openseaSDK = new OpenSeaSDK(provider, {
    networkName: Network.Goerli,
    apiKey: '' //if apiKey is set, (API Error 401: Unauthorized. Full message was '"Invalid API key"')
});

**Comment by 0xshawn** [comment]
+1

**Comment by Taha-daboussi** [comment]
bump , any thing happened to this issues ?

**Comment by nl0243** [comment]
+1
