### ISSUE TITLE
OpenSea Matic Support: `Contract` Calls

### ISSUE THREAD

**Issue by benleim** [ProjectOpenSea/opensea-js#747]
I've attempted to call the `https://api.opensea.io/api/v1/asset_contract/{asset_contract_address}` for each of the top 10 projects on OpenSea by volume. None of them have contracts associated with the address ("unknown"). However, when I look up the "slug" for the collection, it clearly exists and has a contract listed.

**Comment by cterech** [comment]
Hey @benleim we don't support matic yet, no timeline for support at the moment
