### ISSUE TITLE
querying assets by contract addresses started to return empty list on Rinkeby

### ISSUE THREAD

**Issue by asghaier76** [ProjectOpenSea/opensea-js#748]
Using retrieve assets endpoint and specify only certain contract addresses using the parameter contract_addresses has stopped working recently on rinkeby and always returns empty list removing the param of contract addressed still works fine though

**Comment by cterech** [comment]
hey @asghaier76 -- we cut over from Rinkeby to Goerli last week. See here: https://twitter.com/apiopensea/status/1569740605097402369?s=20&t=gEF8hXHtt6nAmf1S8v4ZhQ
