### ISSUE TITLE
Some Listing Errors and do not list any item 

### ISSUE THREAD

**Issue by okyanu** [ProjectOpenSea/opensea-js#751]
Some collections have this error when listing
example:0xcda7ffe2576dd4f3bf5ad77be7d4aa770375bf9c,0xCd4043aC76c1aC493B349bD3a3e9771e58dE3378 or 0x4a2cd543839b65ab1f26a16b8a77d06629ce897f

When I pressed listing button and then these error

![unknown2](https://user-images.githubusercontent.com/7879484/191530613-62dc488a-468f-4783-a4b2-8a389c71901f.png)
![unknown3](https://user-images.githubusercontent.com/7879484/191530833-f75449ea-5a63-47ea-88a4-f565f12dedb5.png)

And also got an error in terminal like this

RRNLRequestError: Relay request for `useHandleBlockchainActionsCreateOrderMutation` failed by the following reasons:

1. [400] You must approve assets #38 for trading before creating an order
       create(orderData: $orderData, clientSignature: $clientSi
       ^^^
    at t.createRequestError

**Comment by cterech** [comment]
@okyanu this does not concern our SDK repo as the listing was created on the UI - can you file a support ticket here https://support.opensea.io/hc/en-us
