### ISSUE TITLE
Expected waiting time for a API key?

### ISSUE THREAD

**Issue by quarantaquatro** [ProjectOpenSea/opensea-js#755]
Hi guys, how long does it take currently aproximetly to get an API key? Are we talking days, weeks, or months?

We would use the OpenSea API in our platform but if it takes months (some people told me) to get API access we need to plan accordingly and use alternatives instead. 

I realize that this isn't the best place to ask for, but on the other hand, I count on the fact that many here might have experience with that already.

thx in advance

**Comment by mostafa-codes** [comment]
@quarantaquatro 
same issue here. I'm still trying to get an api key but get no response.
did get your API key?

**Comment by quarantaquatro** [comment]
I never did! It's a joke, to be honest. I give you the tip to check out
Rapidapi and use their opensea-data-query. It's not free but for $15 you
get 250.000k requests a month. It depends on what you are looking for. In
my case it helped for a while with 2 accounts but in the meanwhile, I have
moved to another API provider completely.

**Comment by mostafa-rio** [comment]
@quarantaquatro thanks for the comment. it is so sad that we can not rely on a top team in the NFT market.

**Comment by ryanio** [comment]
https://docs.opensea.io/reference/api-keys#how-do-i-get-an-api-key
