### ISSUE TITLE
How to generate `criteriaProof` for `fulfillAdvancedOrder`?

### ISSUE THREAD

**Issue by 0hoenno** [ProjectOpenSea/opensea-js#759]
Hello, looked through all the documentation, nowhere is there any information on how `criteriaProof` is generated, could you tell me please?

sample transaction:
-  https://etherscan.io/tx/0xe51b26c2f0a69a2791b7e597f2483618f04534daab2487a40a175ff827753b98

criteriaProof:
```
0x532fe6ef6e75dc9024f829762ee0e1ce06332194391450fdad5e2b4d9eb8b846
0xa3614d31dafc9a306d5b5a532ceb1d7ddceec9bee040037ab9f4b81279547c2a
0x6572c485879d3d3f74da480b1a54d322336b4b13b01dac588c3f322217ffcbb3
0x8d1a2e7cafa9c591408a2916b90f4bea2e6c0cc50c5d1a5b30538e71945a5a4d
0x3ff523cc6fce068ea687c49b0a3da56ba36eb603fdfb22216f267039264e7854
0x0e77818ba21b225cdbaaab0b2caa82bf519cc54408b5068e3d9e44ed0ceb52ea
0x43ba81d66a58ec90e892a504ceff91209ee77164014a9abd4f4f7545853ec25c
0x35142243787aa63a3237a8a0dc927a1a7c5680f27d561ddfbdbbfcc9e2b3bfd4
0x18ee99221a38f3f1a71dca5dfdced50da33c045af0f70b7b77d5639ae7e1b79c
0x71ccd21ff5c16ef9a77529617142c69ca7bdafd51826f4939d5cd0379f417605
```

**Comment by cterech** [comment]
hey @0hoenno, we don't currently provide a mechanism to generate criteriaProofs programmatically - we do plan to support this in the future

**Comment by ohan8** [comment]
@cterech, how does the opensea website do this? is there no way for developers to mimic this?

**Comment by cryptothink629** [comment]
> hey @0hoenno, we don't currently provide a mechanism to generate criteriaProofs programmatically - we do plan to support this in the future

Hi, can you tell us how to calculate criteriaProofs manually?

**Comment by XingyuLi20** [comment]
Hey @cterech, any idea when the support will get added?
