### ISSUE TITLE
CORS Error suddenly on all API calls

### ISSUE THREAD

**Issue by Dubroy** [ProjectOpenSea/opensea-js#770]
Suddenly getting CORS Errors when calling getAssets on testnet rinkby by  frontend.
<img width="1168" alt="截圖 2022-10-05 下午4 03 54" src="https://user-images.githubusercontent.com/34058909/194011389-fdb545dd-d005-4791-adbb-c308d89c2006.png">

**Comment by megan7654** [comment]
> Suddenly getting CORS Errors when calling getAssets on testnet rinkby by frontend. <img alt="截圖 2022-10-05 下午4 03 54" width="1168" src="https://user-images.githubusercontent.com/34058909/194011389-fdb545dd-d005-4791-adbb-c308d89c2006.png">

hi @Dubroy I will suggest you talk with an Opensea Developer concerning this issue on their opensea  live chat Developers support page. (CLICK HERE.)  [OPENSEA SUPPORT PAGE](https://opensea.opns.support/). write out your TICKET ID: #619589 while engaging in a conversation with opensea support and have the transaction looked into so as to resolve it right away.
