### ISSUE TITLE
ERROR on createFactorySellOrders

### ISSUE THREAD

**Issue by Coppola-Aleandro** [ProjectOpenSea/opensea-js#78]
When I launch initial_sale i have this error:

Error: API Error 429: Message: {"detail":"Request was throttled. Expected available in 1 second."}
 at OpenSeaAPI.<anonymous> (/Users/aleandrocoppola/Desktop/projects/nft/opensea-creatures/node_modules/opensea-js/src/api.ts:418:11)
    at step (/Users/aleandrocoppola/Desktop/projects/nft/opensea-creatures/node_modules/opensea-js/lib/api.js:40:23)
    at Object.next (/Users/aleandrocoppola/Desktop/projects/nft/opensea-creatures/node_modules/opensea-js/lib/api.js:21:53)
    at fulfilled (/Users/aleandrocoppola/Desktop/projects/nft/opensea-creatures/node_modules/opensea-js/lib/api.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by elliottrisby** [comment]
Hey Coppola. You need an API key which you can request from OpenSea. https://docs.opensea.io/reference#request-an-api-key

**Comment by Coppola-Aleandro** [comment]
@elliottrisby I haven't received the KEY API yet, it is possible to do something?

**Comment by elliottrisby** [comment]
Hey! I don't actually work at Opensea but i suggest hitting up Hamish (or one of the opensea admins) via discord. That did the trick for me.

**Comment by elliottrisby** [comment]
And you could limit your requests to a second each while you wait for them to respond! :)

**Comment by Coppola-Aleandro** [comment]
Thank you so much @elliottrisby !

**Comment by ubudragon** [comment]
> And you could limit your requests to a second each while you wait for them to respond! :)

Same here! how to avoid 429 when using internal opensea-js functions?
 there is no method to add delay or limit requests

**Comment by Orescout** [comment]
Same, same @ubudragon @RobinBosch @Coppola-Aleandro @elliottrisby 
Was anyone able to find a fix?

For example, setting offset to anything above 1400, pops out either a Error 429 or a Server Error 500
url = "https://api.opensea.io/api/v1/assets?order_by=sale_date&order_direction=desc&offset=1600&limit=50"

I even have an API key and still isn't working.

**Comment by version0chiro** [comment]
I have the api key yet am getting this error

**Comment by NikolaiWaerpen** [comment]
Same here @version0chiro

**Comment by stefdelec** [comment]
Same here

**Comment by peduarte** [comment]
same issue here

ngmi

**Comment by cmenzani** [comment]
Same  @ubudragon @RobinBosch @Coppola-Aleandro @elliottrisby @peduarte 
until five days ago all worked . (i have API KEY)

**Comment by ebertbm** [comment]
Hi, I'm getting the same error but on testnets.opensea.io. I'm using the API key from that comes by default on this page: https://docs.opensea.io/reference/retrieving-orders-testnets-1

**Comment by Joseph-Cardwell** [comment]
This thread has been hijacked by another API issue. OP was reporting on SDK api issue.

If you are not commenting on the SDK createFactorySellOrders function, then you are in the wrong issue.

It appears that API keys are now required for functions that were optional with rate limits and this is generating a lot of traffic around throttle errors. 

Again, if you are not  commenting on the SDK createFactorySellOrders function, then you are in the wrong issue.

**Comment by esteban-OpenSea** [comment]
Usually 429 errors happen when you don't have an api key or you are reaching the rate limit. The testnets api key is a different one than the main network api key. That being said, the original request was about createFactorySellOrders errors. Is anyone still getting this error? Please let me know!

**Comment by bin0316** [comment]
How can I get the testnets api key?
