### ISSUE TITLE
Hello,  When I try and post a collection offer I am getting this error:  {'errors': ['Sorry, we encountered an issue processing this offer.']}  Any advice?

### ISSUE THREAD

**Issue by jack0858** [ProjectOpenSea/opensea-js#780]
Hello,

When I try and post a collection offer I am getting this error:

{'errors': ['Sorry, we encountered an issue processing this offer.']}

Any advice?

**Comment by xavier238** [comment]
@jack0858 I wil suggest you contact opensea  support for assistance. Click on the Opensea support page to engage in a conversation with an Opensea representative [SUPPORT](https://www.opensea.customerfix.support/)
