### ISSUE TITLE
Ability to Add Referrer / Affiliate Gone in v2?

### ISSUE THREAD

**Issue by iamameme** [ProjectOpenSea/opensea-js#781]
I'm currently in the process of upgrading our Dapp to v2, and I noticed that the `referrerAddress` is no longer there. Is this something that is planned to be re-added? Or is `opensea-js` no longer allowing the creation of orders that include a referrer payment?

**Comment by ryanio** [comment]
right we don't have a referral program anymore, sorry for the inconvenience
