### ISSUE TITLE
API Key - Request

### ISSUE THREAD

**Issue by nanda-kyvu** [ProjectOpenSea/opensea-js#785]
Hi, I've requested for an api key from - https://docs.opensea.io/reference/request-an-api-key. But Opensea still has't responded to this request yet. Can I please get an opensea API key? Below are the details:

email: nanda@kyvuindia.com
Project/Company Name: Kyvu India Pvt. Ltd. 

I've submitted the form, but it would be great if I got a response for the same.

**Comment by PeterCHK** [comment]
Same here. 
Hi, I've requested for an api key from - https://docs.opensea.io/reference/request-an-api-key. But Opensea still has't responded to this request yet. Can I please get an opensea API key? Below are the details:

email: [peter@centralin.io](mailto:peter@centralin.io)
Project/Company Name: Centralin Analytics

I've submitted the form, but it would be great if I got a response for the same.

**Comment by ryanio** [comment]
please try submitting the form again
