### ISSUE TITLE
OpenSea.io scam 

### ISSUE THREAD

**Issue by Lazarus1776** [ProjectOpenSea/opensea-js#796]
Open sea scam was such that made nft's appear under "my collectibles" as if it was a free airdrop. When I tried to sell it, I got a scam signature request to list for sale but was actually approving all my Usdc out of my wallet for nothing in exchange. https://metamask.app.link/send/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48@1/transfer?address=0x2d67936f1ED96220CFc5Cf5F6F1fFC16401Bdcd3&uint256=8.88e8

**Comment by ryanio** [comment]
please report the NFT on opensea so it can be removed, thank you

**Comment by Lazarus1776** [comment]
Incomplete.
Scammed out of $884 USDC by a scam signature request.
