### ISSUE TITLE
Calling getCurrentPrice results in toBigNumber(...).round is not a function

### ISSUE THREAD

**Issue by dcarlcf** [ProjectOpenSea/opensea-js#8]
I am initializing an OpenSea port after cloning the repository. [Issue #7](https://github.com/ProjectOpenSea/opensea-js/issues/7) shows exactly how I am initializing it.

When I attempt to call:

`seaport.getCurrentPrice(order)`

I am getting the error Unhandled Rejection (TypeError): toBigNumber(...).round is not a function, originating in src/opensea-js/lib/seaport.js:704.

I installed web3 and BigNumber using npm install web3 and npm install BigNumber. Is there a different version of BigNumber I should be using to be compatible?

**Comment by alexanderatallah** [comment]
@dcarlcf the currentPrice should be appended on each order - you can do `order.currentPrice`. But if you notice other bignumber issues, then you can use the same version in opensea-js: ^4.0.4
