### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by NielsDom** [ProjectOpenSea/opensea-js#80]
![bug](https://user-images.githubusercontent.com/44423012/113280607-b591f980-930e-11eb-9db9-77c00dfbe871.png)
similar issue as https://github.com/ProjectOpenSea/opensea-js/issues/79

It is working fine on localhost but not on a public server when I call "createBuyOrder". 

Is there any issue in my code or is it a bug on your side?

Thanks

**Comment by Meemaw** [comment]
Hey @NielsDom! Fix was just merged -- should be live in ~15 mins. Sorry for the inconvenience.

**Comment by NielsDom** [comment]
awesome working thanks
