### ISSUE TITLE
Firecamp example file not working

### ISSUE THREAD

**Issue by inkredabull** [ProjectOpenSea/opensea-js#807]
No chat or support on the [OpenSea site](https://docs.opensea.io/) so opening an issue here.

On [Using Stream API without SDK](https://docs.opensea.io/reference/using-stream-api-without-sdk) there is a file referenced at the very bottom: [Stream API Example_firecamp.json](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/d5b6c691-06c7-499e-87e5-adfc9ba31bbc/Stream_API_Example_firecamp.json)

Getting `AccessDenied`

**Comment by hedeqiang** [comment]
+1

**Comment by len-cl** [comment]
Hey there, the help is not useful without the file. A bit stuck. Thanks!

**Comment by aviexk** [comment]
same here +1 on this

**Comment by ryanio** [comment]
Sorry about that, fixed the link in the docs: https://ipfs.io/ipfs/QmeCtMKqiyBUuqwhj2FPFCG74nTkQxjsd4wJLzKHAx4iPM
