### ISSUE TITLE
Can`t install opensea-js using yarn

### ISSUE THREAD

**Issue by ashitosh03** [ProjectOpenSea/opensea-js#809]
I am getting the issue while installing **opensea-js** library using **yarn**. 
`error An unexpected error occurred: "https://github.com/ProjectOpensea/0x-tools/raw/provider-patch/utils/0x-utils-6.5.0.tgz: ETIMEDOUT"`

I am using 
git version - 2.25.1
node version - v16.10.0 / v16.11.0
opensea-js- ^4.0.12

**Comment by StevenJ59** [comment]
I have try windows 11 and 10
Ubuntu 22
Node 14 , several of 16.x ,  18.x 
Npm 6 ,  9.4 , 8 , 8.3 , 8.4 
Opensea-js  4.0.12 and previous
  "resolutions": {
   "@0x/utils": "https://github.com/ProjectOpensea/0x-tools/raw/provider-patch/utils/0x-utils-6.5.0.tgz"
 }

i always end with something like : "npm ERR! enoent An unknown git error occurred" 
or with yarn : "Error: Couldn't find the binary git" 


there is some library missing ????
what i am suppose to do ???

**Comment by StevenJ59** [comment]
i was getting the same issue with w10/w11 but its work with ubuntu

**Comment by ryanio** [comment]
i believe we have removed the need for this dependency now, please let us know in a new issue if this is still happening for you

**Comment by Luckyman123** [comment]
@ashitosh03 are you still workin on pumapay`
