### ISSUE TITLE
WalletConnect v1.0 will be officially deprecated on March 1, 2023.

### ISSUE THREAD

**Issue by 95decode** [ProjectOpenSea/opensea-js#810]
WalletConnect v1.0 will be officially deprecated on March 1, 2023.

I think the current opensea is using WalletConnect v1 and doesn't support v2.0.

Can you talk about the v2.0 support schedule?

References
[medium](https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)
[docs](https://docs.walletconnect.com/2.0)

**Comment by 95decode** [comment]
Is there anyone who can give me an answer?

**Comment by 95decode** [comment]
The shutdown was extended to June 28 (read about it [here](https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595))

**Comment by andyrobert3** [comment]
@95decode i think we should re-open this issue since 28 June is around the corner
