### ISSUE TITLE
Error: API Error 404: Not found. Full message was '{"success":false}'

### ISSUE THREAD

**Issue by vmnfts** [ProjectOpenSea/opensea-js#816]
getting this "Error: API Error 404: Not found. Full message was '{"success":false}'"
when calling openseaSDK.api.getOrder
could you guys help me to fix this?

node v - 16.18.0
opensea-js 4.0.12

**Comment by sunwrobert** [comment]
Are you confident that you are supply the correct token address and token id?

**Comment by vmnfts** [comment]
> Are you confident that you are supplying the correct token address and token id? If so, can you list it?

yes mate, they are correct.

**Comment by slava239** [comment]
Have anyone found a solution?

**Comment by ryanio** [comment]
are you using the latest version of opensea-js?

**Comment by slava239** [comment]
Yes, it's 5.0.2 version

Here is my code
``` javascript
import dotenv from 'dotenv';
dotenv.config();

import HDWalletProvider from "@truffle/hdwallet-provider";

import pkg from 'opensea-js';
const { Network, OpenSeaSDK } = pkg;

const contractAddress = "0xe24e4d4535f504d6d7957356534e23b4e787289f";
const tokenId = 1844;
const offerExpiration = 15;

const provider = new HDWalletProvider(process.env.PRIVATE_KEY, process.env.ALCHEMY_URL);
const myWallet = provider.getAddress();

console.log(myWallet);

const openseaSDK = new OpenSeaSDK(provider, {
  networkName: Network.Main,
  apiKey: process.env.OPENSEA_API_KEY
});

getWETHbalance(myWallet);

// example from OpenSea API docs
const offer = await openseaSDK.createBuyOrder({
  asset: {
    tokenId,
    contractAddress,
  },
  myWallet,
  startAmount: 0.012,
}).then(function (offer) {
  console.log('[DEBUG]', new Date(), `Offer placed, expires in ${offerExpiration}min`, myOffer.orderHash, nft);
})
  .catch(function (error) {
    console.log('[ERROR]', new Date(), 'Offer failed', error);
  });


async function getWETHbalance(wallet) {
  const balanceOfWETH = await openseaSDK.getTokenBalance({
    accountAddress: wallet,
    tokenAddress: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
  })

  console.log(balanceOfWETH);

}
```
It returns 
`DEPRECATED: Please use providerUtils.standardizeOrThrow() instead
DEPRECATED: Please use providerUtils.standardizeOrThrow() instead
[ERROR] 2023-05-24T05:54:17.579Z Offer failed Error: API Error 404: Not found. Full message was '{"success":false}'
    at OpenSeaAPI.<anonymous> (/Users/slava/JavaProjects/js-parser/node_modules/opensea-js/lib/api.js:563:31)
    at step (/Users/slava/JavaProjects/js-parser/node_modules/opensea-js/lib/api.js:67:23)
    at Object.next (/Users/slava/JavaProjects/js-parser/node_modules/opensea-js/lib/api.js:48:53)
    at fulfilled (/Users/slava/JavaProjects/js-parser/node_modules/opensea-js/lib/api.js:39:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
659550000000000000`

The last number is the wallet balance. So the function openseaSDK.getTokenBalance() works correctly, but function openseaSDK.createBuyOrder() throws an API Error 404

**Comment by ryanio** [comment]
can you try with the latest v6, we have refactored/fixed a lot of code, if you can give a small snippet reproducable example of the error we can try to investigate exactly what's going wrong

**Comment by ryanio** [comment]
Please reply here or open a new issue with more details on how to reproduce with the latest version of opensea-js so we can more concretely help you. Thank you!
