### ISSUE TITLE
Improve collection stats JSON response documentation

### ISSUE THREAD

**Issue by rickstaa** [ProjectOpenSea/opensea-js#820]
It would be nice if we could update the OpenSea REST API documentation so that it explains the JSON keys that are returned by the `/collection/{collection_slug}/stats` endpoint (see https://docs.opensea.io/reference/retrieving-collection-stats). Especially the difference between the `<TIME_PERIOD>_change,` `<TIME_PERIOD>_difference,` `total_supply,` and `count` is not directly apparent (see https://stackoverflow.com/a/75088805/8135687).

**Comment by rickstaa** [comment]
Not eyet fixed.

**Comment by ryanio** [comment]
thanks for the suggestion, i'll fwd to our team

**Comment by rickstaa** [comment]
@github-actions I think this is not stale, given that @ryanio forwarded it to the team 🤔.

**Comment by ryanio** [comment]
not sure when we can get to this, but if you have some suggestions to share with the team of valuable stats to surface (and how you'd prefer to calculate them) i'd be happy to pass them on

**Comment by rickstaa** [comment]
> not sure when we can get to this, but if you have some suggestions to share with the team of valuable stats to surface (and how you'd prefer to calculate them) i'd be happy to pass them on

@ryan thanks for your answer. The calculations are okay. This issue is about improving the documentation so that it displays how the calculations for the different stats are done.

**Comment by ryanio** [comment]
@rickstaa ah understood, thanks, will make sure we have this on our tracker for our new docs hub we are working on

**Comment by ryanio** [comment]
@rickstaa it seems like we are actually actively working on a stats v2 endpoint that will be much more clearly documented

**Comment by rickstaa** [comment]
> @rickstaa it seems like we are actually actively working on a stats v2 endpoint that will be much more clearly documented

Amazing! Feel free to close this issue whenever you seem fit 👍.

**Comment by ryanio** [comment]
thanks! ok i'll close for now, when you see the stats v2 docs and if you have any suggestions for them please feel free to open a new issue.
