### ISSUE TITLE
Retrieve collection offers (Beta) API endpoint bug

### ISSUE THREAD

**Issue by rafaeluzzi** [ProjectOpenSea/opensea-js#823]
Retrieve collection offers (Beta) endpoint is sometimes reporting double the amount of the actual offer.
<img width="567" alt="osbug" src="https://user-images.githubusercontent.com/43967/212560583-976bdf26-3f0e-4e7d-9274-a57eb989e14c.png">
<img width="1017" alt="osbug2" src="https://user-images.githubusercontent.com/43967/212560598-25d42b45-533c-452c-9526-19ffb3f132d9.png">

**Comment by quary1993** [comment]
<img width="372" alt="Screen Shot 2023-05-02 at 1 32 48 PM" src="https://user-images.githubusercontent.com/17161829/235643816-49916381-5e1a-433d-adaa-06b080173386.png">
The offer is for 2 nft's (in consideration items, you got amount: 2)
