### ISSUE TITLE
API key request has not been answered for a month. 

### ISSUE THREAD

**Issue by justx-it-help** [ProjectOpenSea/opensea-js#824]
We have contacted within various ways to request opensea API key. 
However, we have not got any answer from Opensea. 

Anyone can help?

**Comment by nnbp7** [comment]
If you would like to buy an Opensea API Key, feel free to contact me via telegram or discord

telegram: @Tenneb55
discord: Tenneb#8617

**Comment by mostafa-codes** [comment]
@nnbp7 
Same problem here. we are trying to use Opeansea API in our project.
No response so far. if there is any quick way to get an API key please email us at support@nftocean.market.

**Comment by nnbp7** [comment]
Are you still in need of an Opensea api key?

čet, 13. tra 2023. u 09:15 mostafa rahmani ***@***.***>
napisao je:

**Comment by mostafa-rio** [comment]
Yes, @nnbp7. we are still struggling to get an API key no response from the Opensea team.
is there any way to contact the team?

**Comment by nnbp7** [comment]
As far as i know no, the only way is to purchase them. we have not been
able to get an api key from opensea for months.

pon, 17. tra 2023. u 08:19 mostafa rahmani ***@***.***>
napisao je:

**Comment by mostafa-rio** [comment]
But they dont have any pricing section for their API. Anyi can checkout the prices?

**Comment by nnbp7** [comment]
The only person i know that i can forward you to is on Telegram.

This is their user ID: @Tenneb55

We bought our Opensea API key through them.

pon, 17. tra 2023. u 08:30 mostafa rahmani ***@***.***>
napisao je:

**Comment by ryanio** [comment]
Sorry for the trouble, serve API keys are now slowly rolling out: https://twitter.com/apiopensea/status/1651650717546074112

**Comment by ryanio** [comment]
You should now have access to API keys in your account: https://docs.opensea.io/reference/api-keys#how-do-i-get-an-api-key
