### ISSUE TITLE
How to set the "Creator earnings" rate using opensea-js?

### ISSUE THREAD

**Issue by CoolDevMan** [ProjectOpenSea/opensea-js#825]
We use opensea-js to set the "Creator earnings" rate when setting a NFT for sale.

https://projectopensea.github.io/opensea-js/#making-listings--selling-items
We checked the above link and source code, but couldn't find the setting method.

createSellOrder({ asset, accountAddress, startAmount, endAmount, quantity, domain, salt, listingTime, expirationTime, paymentTokenAddress, buyerAddress})

If there is a way, please let me know what information should be added when calling the createSellOrder function.

**Comment by Ghijo1** [comment]
> We use opensea-js to set the "Creator earnings" rate when setting a NFT for sale.
> 
> https://projectopensea.github.io/opensea-js/#making-listings--selling-items We checked the above link and source code, but couldn't find the setting method.
> 
> createSellOrder({ asset, accountAddress, startAmount, endAmount, quantity, domain, salt, listingTime, expirationTime, paymentTokenAddress, buyerAddress})
> 
> If there is a way, please let me know what information should be added when calling the createSellOrder function.

Hello, did you solve? I have the same issue

**Comment by CoolDevMan** [comment]
Unfortunately, I haven't been able to find a way yet.
