### ISSUE TITLE
seaport.getAssetBalance() throws: Unable to get current owner from smart contract

### ISSUE THREAD

**Issue by swarlezbarkley** [ProjectOpenSea/opensea-js#83]
I am trying to use seaport.getAssetBalance(). It is throwing an error of: Unable to get current owner from smart contract.

This is an example of my code following the documentation.

```
const balances = await seaport.getAssetBalance({
  accountAddress: '0x06e98b5030E4A4b43cF284af02EEb4dEBD5a52Aa',
  asset: {
    tokenAddress: addresses.ARTWORK_COLLECTION,
    tokenId: assets[0].tokenId,
    schemaName: 'ERC1155',
   },
})
```

Please let me know if this issue is common with you.

**Comment by shantiscript** [comment]
I am facing the same issue

**Comment by Wutklumpen** [comment]
Same over here. Don't understand a thing.

**Comment by Wutklumpen** [comment]
Ok, I switched to a different asset which is now ERC721, and getAssetBalance does work now. 
Before I also tried with an ERC1155. Question is now, how can we get balance for ERC1155 tokens?

**Comment by kingsframe** [comment]
any updates on this? it looks opensea bydefault mint to ERC1155 so this is currently an issue

**Comment by ruskid** [comment]
same when using rinkeby chain

**Comment by esteban-OpenSea** [comment]
Hello, is everyone still getting this error? Is it still only with ERC1155 or just with rinkeby chain?

**Comment by esteban-OpenSea** [comment]
Checking in again, is this still an issue?

**Comment by nishilshah17** [comment]
This is occurring for me, for an 1155 asset. Same error on both Rinkeby and Main.

**Comment by ahjohnwon** [comment]
the same to me. how to solve it？

**Comment by ahjohnwon** [comment]
This is my code:
try {
  const offer = await seaport.createBuyOrder({
    asset: {
      tokenAddress:tokenAddress,
      tokenId:tokenId,
      schemaName:'ERC721'
    },
    accountAddress:walletAddress,
    // Value of the offer, in units of the payment token (or wrapped ETH if none is specified):
    startAmount: 0.1,
  })
  console.log(offer);
} catch(err) { 
  console.log(err);
}

**Comment by nehaannvinu** [comment]
Has anyone figured the solution?
