### ISSUE TITLE
getOrder for existing offer doesn't work

### ISSUE THREAD

**Issue by NoamN** [ProjectOpenSea/opensea-js#834]
For some reason, getOrder()  (with 'bid' as side) stopped returning offers, even when the item does have existing offer/s. It just returns 'no matching order found'. Anyone else encountered?

**Comment by NoamN** [comment]
It seems that also on opensea, some of the offers don't appear in the item activity table. Only very few appear. Only those that appear, are returning as response when using api.getOrders() (with 'bid' as side).

**Comment by deiay** [comment]
Running into a similar issue. Noticing that collection offers are showing on opensea but don’t show when I query them use the seaport API. For example [0xb88749711ddac8ace7fe858e1f6ae6648394926a](https://opensea.io/0xb88749711ddac8ace7fe858e1f6ae6648394926a/bids-made) has several collection offers showing on opensea:

![Screen-Shot-2023-02-16-at-12 16 58-PM](https://user-images.githubusercontent.com/7328115/219478063-db7aaed3-ac8e-44cd-9cea-701f7849a1c3.jpeg)

But when I query the opensea api for bid orders, no orders are returned:
![Screen-Shot-2023-02-16-at-12 18 57-PM](https://user-images.githubusercontent.com/7328115/219477936-a4a13240-4d44-41a5-af40-87ac3f6b607f.jpeg)

**Comment by Jared-James** [comment]
Having the exact same issue.
