### ISSUE TITLE
ACCEPT A COLLECTION OFFER USING MATCH ORDERS ADVANCEDA

### ISSUE THREAD

**Issue by mustafa222lk** [ProjectOpenSea/opensea-js#835]
hey there,
Im trying to make a script that can accept collection offers for nfts. I see opensea usese match advanced orders to do so. Sadly i can not call it on seasport.js for some reason. When I use fulfill orders it also doesnt work and it gets reverted. Im fetching the orders from their official api and then try to fulfill it with me as the owner of the nft. How can I call match advanced orders ?

**Comment by ryanio** [comment]
closing this for now since you have not provided any details to help debug. what is the revert error message? you can try just using fulfillBasicOrder
