### ISSUE TITLE
No option for "collection" param in OpenSeaAssetQuery type

### ISSUE THREAD

**Issue by nawangwe** [ProjectOpenSea/opensea-js#84]
We are able to provide this parameter to the api as shown [here](https://docs.opensea.io/reference#getting-assets), but it's not available in the library, can we add this parameter into OpenSeaAssetQuery type?

**Comment by furysheep** [comment]
Same issue. Can we add?

**Comment by esteban-OpenSea** [comment]
@nawangwe , just wanted to follow up on this. You mean fetching assets right? if so take a look at [this](https://projectopensea.github.io/opensea-js/classes/OpenSeaAPI.html#:~:text=Returns%20Promise%3CT%3E-,getAsset,-getAsset(__namedParameters%3A%20%7B%20tokenAddress).

**Comment by esteban-OpenSea** [comment]
Did the link I sent help?

**Comment by nawangwe** [comment]
Hi @esteban-OpenSea, I haven't checked the link in detail, but this is a minor issue, as I was still able to access and reference the attribute even if it wasn't included in the type.
