### ISSUE TITLE
Listings API only returns orders with quantity 1 for ERC1155 tokens

### ISSUE THREAD

**Issue by luoyeETH** [ProjectOpenSea/opensea-js#841]
I'm using opensea api to fetch listings for ERC1155 tokens, but I found that the API only returns orders with quantity 1, even if there are orders with larger quantities on OpenSea.  
  
node.js version 16.15.0.    
  
The URL I'm using is https://api.opensea.io/v2/orders/ethereum/seaport/listings?asset_contract_address=0xe70659b717112ac4e14284d0db2f5d5703df8e43&limit=5&token_ids=2&order_by=eth_price&order_direction=asc  
![image](https://user-images.githubusercontent.com/99408135/221179794-599baaf2-5545-4e96-987e-85ca3bafb2c0.png)  
Thank you for your help

**Comment by JoshuaSchmidt-OpenSea** [comment]
@luoyeETH There was a bug in the `eth_price` sort order for multi-quantity listings which has since been fixed. Please try again and reopen if you see any issues.
