### ISSUE TITLE
Error: API Error 400: You have attempted to create a listing, but you provided an invalid number of currency consideration items: 7. A consideration array for a listing may only have between 1 and 7 currency items at OpenSeaAPI

### ISSUE THREAD

**Issue by kevgithub** [ProjectOpenSea/opensea-js#842]
When I try to make listing with `createSellOrder`, it happens:
`Error: API Error 400: You have attempted to create a listing, but you provided an invalid number of currency consideration items: 7. A consideration array for a listing may only have between 1 and 7 currency items at OpenSeaAPI...`
First of all, I think this error message itself is a mistake!  (7 is between 1 and 7)
And I checked the contract(0x0be697ce3f41508510ccf502c55c37990274f05e) metadata, the reason why consideration items has 7 values ​​is because fees provided 5 wallet addresses.
```
"fees": {
      "seller_fees": {
        "0x6761c6a415658f680b386474cf04de493b33f6bb": 295,
        "0x10ce402c60ec0a17420f391a0e3bdd5930272ce4": 90,
        "0x0814a7dbc4fcb83d79c54bd3d7bf885b2485059e": 50,
        "0x83cc0283de19ccaedb8127289d4d552bde5abf9d": 40,
        "0xa5343d151fc822ff8e7ff5db0930e994356b0372": 25
      },
```
Please confirm if this is a bug of SDK or am I doing something wrong? Thanks

**Comment by whalefrat** [comment]
hey there,when i try to list with createSellOrder.it says "API Error 400: 2 validation errors for OrderInput
parameters -> counter
  value is not a valid integer (type=type_error.integer)
parameters -> counter
  str type expected (type=type_error.str)"
a week ago,createSellOrder would work,what happened?does it have something to do with royality?createSellOrder not working anymore?or did i miss something here?

**Comment by Ghijo1** [comment]
> seller_fees

Hello, how you can set the fees with the SDK?

**Comment by dreygur** [comment]
> hey there,when i try to list with createSellOrder.it says "API Error 400: 2 validation errors for OrderInput

Bro, you're not alone!
My app also facing this issue.

**Comment by dreygur** [comment]
Here is what I have done to solve the issue:

1. Updated the opensea-js package (didn't work)
2. Copied the sourcecode and placed inside my project. Imported from there. (Didn't work)
3. Made a link to the package using yarn. (It worked)

**Comment by whalefrat** [comment]
> 

bro,great to hear that you solved it,could you paste the code which you "Made a link to the package using yarn",I haven't fully understood what happened with opensea-js

**Comment by whalefrat** [comment]
> Here is what I have done to solve the issue:
> 
> 1. Updated the opensea-js package (didn't work)
> 2. Copied the sourcecode and placed inside my project. Imported from there. (Didn't work)
> 3. Made a link to the package using yarn. (It worked)

bro,great to hear that you solved it,could you paste the code which you "Made a link to the package using yarn",I haven't fully understood what happened with opensea-js

**Comment by dreygur** [comment]
Run
```sh
yarn link
```
In the opensea-js project and
```sh
yarn link opensea-js
```
In your project folder

**Comment by kevgithub** [comment]
> > seller_fees
> 
> Hello, how you can set the fees with the SDK?
The SDK does not support setting fees. The fees mentioned above is the contract(0x0be697ce3f41508510ccf502c55c37990274f05e) metadata I obtained through the API (
https://api.opensea.io/api/v1/asset_contract/{asset_contract_address}). The SDK code will use these wallet addresses to generate the value of the consideration array

**Comment by montasaurus** [comment]
I see the issue here--working on getting a fix in now. Sorry for the interruption!

**Comment by montasaurus** [comment]
Should be fixed now!
