### ISSUE TITLE
Throttled requets even with API key

### ISSUE THREAD

**Issue by macelai** [ProjectOpenSea/opensea-js#86]
Hey, first of all, thanks for this SDK and API that we are using to build a custom NFT store! I'm having some problems using the API key, I'm getting the throttle message with API key on rinkeby and mainnet, we can make like 7 requests before throttled, and then pretty long throttle interval. We are using the `/asset/` to get information about every NFT that we are listing so we can display custom info.

Is this the expected behavior? Is there any way to this differently?

**Comment by Mortaro** [comment]
I am also having this problem, but Throttle happens randomly even on second requests.

I assume this is a bug because the SDK makes 2 requests to place a bid, and often one throttles the other

**Comment by nuanyang233** [comment]
OpenSea Api has a request frequency limit, you need to apply for sdk api key [here](https://docs.opensea.io/reference#request-an-api-key)

You can add it to the apiConfig When you create the new OpenSeaPort

```js
new OpenSeaPort(provider, {
        apiKey: 'Your api key'
})
```

**Comment by Macelai** [comment]
Hey @nuanyang233, thanks for your response. 

The thing is that I have an API key already and it still throttles, even for placing a bid like @Mortaro said.

**Comment by Mortaro** [comment]
I can confirm that i have the API key set on SDK, i also tried using directly as an API call and had the problem

**Comment by snuderl** [comment]
@Mortaro  @Macelai 

Do you know the rate limit you have on your api key? We have some keys with a very low limit.

If you guys could send me more info about your key (your contact email when key was added or api key itself) to blaz.snuderl (at) opensea.io I can look into it for you.

**Comment by Macelai** [comment]
Hey @snuderl, I don't have that information, I'll send an email, thanks!

**Comment by draghetto86** [comment]
Same here

**Comment by jlgasparrini** [comment]
This is happening to me also on Rinkeby network, but can anyone confirm if this is happening in production environments?

**Comment by Macelai** [comment]
> This is happening to me also on Rinkeby network, but can anyone confirm if this is happening in production environments?

yes, happen on production as well

**Comment by benmcmaster** [comment]
I am also having these issues. I haven't tested on production yet.

Has anyone found any workarounds?

**Comment by Mortaro** [comment]
After contacting OpenSea, they confirmed this is the normal behavior and we made a proxy around it. 

For the back-end part we use our key to cache requests and redistribute them to clients, and for front-end only stuff we use no api key so each user has its own throttle limits

**Comment by chahakshah111** [comment]
Hey, i'm getting the same error. Can you please explain me what i have to do in order to overcome this error? @Mortaro

**Comment by cryptobrokering** [comment]
> After contacting OpenSea, they confirmed this is the normal behavior and we made a proxy around it.
> 
> For the back-end part we use our key to cache requests and redistribute them to clients, and for front-end only stuff we use no api key so each user has its own throttle limits

Yeah would be nice to know how you used a proxy for sending OS requests

**Comment by zigapk** [comment]
I there any way to find out about API limits for a certain API key?

**Comment by judescripts** [comment]
Same issue here also not getting a response back from Opensea on request for API key... need to use sdk to make bids but the throttle issue is so annoying :( Anyone have any idea how to overcome this just for nodejs server app?

**Comment by ali-farooq0** [comment]
Anybody know what the limits are for the opensea apis? Running into the exact same issue. You'd think they'd have a higher allowance for API requests for people who have API Keys. But you'd be wrong :D.

**Comment by mmlmike010** [comment]
also running into this issue. even am getting denied now to the opensea website from my IP address from using my production api

**Comment by SaulMoonves** [comment]
I adjusted my rate to about a request every two seconds and everything was fine but now I am getting a 429 "too many requests" error sometimes. It would be great to know how to avoid this.

**Comment by angelhtml** [comment]
hi,I requested the Opensea API key a few days ago but have not received anything yet, anyone can help me?

**Comment by baba43** [comment]
The entire policy around the current API is overall a disaster. 

The existing limits for querying (take **AND**, much worse, offset) lead to having to do a lot of queries unnecessarily. The fact that you can't retrieve older entries leads to bombarding the API with polling. Both together result in an unnecessary flood of queries ON BOTH SIDES.

I have tried to implement our interface as gently as possible, but since there is no meaningful paging mechanism and the offset is far too small, I have to poll the API frequently.  

As if that wasn't messy enough, I get the error message "Too many requests" and have **no idea** how to fix this problem. How many requests are allowed with/without an API key? Can this be documented anywhere, please?

The solution is now that every user of the API has to set up a proxy network, instead of simply adapting the API to basic standards? That should not be the solution!

This problem together with the fact that various requests generally end in a 500 error (certain collections, the query of all NFTs sorted by sales price and some others) leads me to the judgment that this API has been implemented bunglingly. For a small company this would not be a problem, but OpenSea is not small and should have more than enough budget.

I would be really happy if the API would be given some time in development in the future and furthermore I would also be happy if my bugreports from 6 months ago would at least get a response.

**Comment by Trontor** [comment]
I've found this extremely frustrating too. The API is too limited

**Comment by priyeshshah11** [comment]
Facing the same issue here, Is this ever going to be addressed or improved by OpenSea? The api/sdk is barely usable if it is going to be limited so much. At least let people know what the limit is, so that they can manage their implementations accordingly.

**Comment by arjun921** [comment]
@priyeshshah11 Did you try using different User Agent in the request header didn't help?
Cause that worked for me.

**Comment by priyeshshah11** [comment]
> @priyeshshah11 Did you try using different User Agent in the request header didn't help? Cause that worked for me.
> 
> Wrote about it here https://arjun921.medium.com/how-to-fix-the-damn-opensea-403-error-in-python-c753ebbc8f5f

@arjun921 No, I haven't tried it yet as we are using the sdk functions but I did read your article earlier (nice workaround btw), we will have to switch to use the api endpoints to adopt your suggested method.

**Comment by macelai** [comment]
The solution that worked for us, it's just like @Mortaro explained

**Comment by aakash-joyaether** [comment]
> After contacting OpenSea, they confirmed this is the normal behavior and we made a proxy around it.
> 
> For the back-end part we use our key to cache requests and redistribute them to clients, and for front-end only stuff we use no api key so each user has its own throttle limits

can anyone please explain in more detail, i m also facing same throttle issue after 2 requests

**Comment by esteban-OpenSea** [comment]
Hello Everyone, just to add to this. Usually throttled requests occur when there are some issues or outages with the site. I recommend joining our [dev discord](https://discord.com/invite/opensea) and checking the [status](https://status.opensea.io/) of the site for most recent information.

**Comment by esteban-OpenSea** [comment]
Feel free to let me know if you normally receive that error though!

**Comment by MikeMoldawsky** [comment]
> Feel free to let me know if you normally receive that error though!

I can say that I'm constantly getting 429 Too many Request Errors. 

It happens even when sleeping for 2 seconds between API requests. 

You should, at the minimum, declare what's the rate you are supporting (after all it's an API).

Thanks

**Comment by emorling** [comment]
> Feel free to let me know if you normally receive that error though!

Yes, it's really easy to get this error.

**Comment by DishantPal** [comment]
Hi any recent update on this? need to display listings but getting throttled heavily

**Comment by emorling** [comment]
What throttles are you seeing? I can fetch 4 calls to /assets endpoint per second, roughly.

**Comment by mizanxali** [comment]
Facing the same issue with the NFT API. Trying to fetch collections but 2 out of 7 requests get throttled, even with a production API key.

**Comment by bujoralexandru** [comment]
Yep... this is sad. I've wasted 3 days of development time to try and figure out why isn't my code working, even tough I'm doing everything as the docs are suggesting... Rate limiting is not predictable, as it should be, so we can respect it. 

@esteban-OpenSea, #468 is linked to this also.

**Comment by emorling** [comment]
@mizanxali @bujoralexandru 

Check the response headers, and retry on the proposed time:


```
const sleep = ms => new Promise(res => setTimeout(res, ms));
const rateLimitDelay = parseInt(err.response.headers['retry-after']);
await sleep(rateLimitDelay);
```

**Comment by bujoralexandru** [comment]
> @mizanxali @bujoralexandru
> 
> Check the response headers, and retry on the proposed time:
> 
> ```
> const sleep = ms => new Promise(res => setTimeout(res, ms));
> const rateLimitDelay = parseInt(err.response.headers['retry-after']);
> await sleep(rateLimitDelay);
> // try again
> ```

Already doing that, please check the screenshots in issue #468.

**Comment by LookRain** [comment]
> You should, at the minimum, declare what's the rate you are supporting (after all it's an API).

+1. I've been looking for what the rate limit is everywhere but could not find an anwser

**Comment by emorling** [comment]
Yup, I am able to do 4-5 API calls per second

**Comment by LookRain** [comment]
> Yup, I am able to do 4-5 API calls per second

Is that with an API key or without?

**Comment by emorling** [comment]
With an API key

**Comment by LookRain** [comment]
> With an API key

That's weird.. I guess they have different rate limits for different endpoints, I'm able to make 50+ `api.opensea.io/api/v1/collection/${slug}`requests within a second, and that's without an API key...

**Comment by emorling** [comment]
> > With an API key
> 
> That's weird.. I guess they have different rate limits for different endpoints, I'm able to make 50+ `api.opensea.io/api/v1/collection/${slug}`requests within a second, and that's without an API key...

OK! I wam reffering to  https://api.opensea.io/api/v1/assets

**Comment by LookRain** [comment]
Uh ok I'm trying out the event api, also getting a limit of 4 calls per second. However, there seem to be additional limits as well? I staggered my 50 calls half a second apart, but still got limited, and the error response header asks me to retry in 180 seconds... that's not very nice...

**Comment by aster2709** [comment]
`createBundleBuyOrder` throttles for me, Its not even the rate limit. I can't even do one. whereas `createBuyOrder` seems to work smoothly

**Comment by pancakes9798** [comment]
hi guys, since OS disabled api based order submissions i m getting this error "API error 429 : Request was throrrled" any tips to how to fix that? @esteban-OpenSea @Mortaro. I m getting this error for multiple bids on NFTs collections

**Comment by fahmidme** [comment]
> 

Same, just wasted a lot of time refactoring thinking I'm coding Promises wrong 😅
