### ISSUE TITLE
Price Drop: shows selection of non selectable tokens

### ISSUE THREAD

**Issue by lucadgtrip** [ProjectOpenSea/opensea-js#87]
- On English auction
- On Price Drop

**an unexpected dropdown of tokens is available.**

Since only WETH are accepted, they are not selectable.
When choosing a token, the choice is ignored and WETH remains the selected one.

User issue: 
since it would be actually great to have other coins (especially stable coins) the user spends time selecting the token and nothing happens.

![Screenshot 2021-04-09 at 11 24 10](https://user-images.githubusercontent.com/34341206/114163493-ec7d9600-9932-11eb-8a38-fae5689b941f.png)

Ref:
listing: https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/93380629908989276154329187712159695682604484101294988604591734364126547279873
Mac Os Big Sur 
Firefox 87.0 (64-bit)
Brave Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64)

**Comment by esteban-OpenSea** [comment]
Issue is fixed on drop downs on english auctions
