### ISSUE TITLE
fulfillOrder failing with TypeError: Cannot read properties of null (reading 'toHexString')

### ISSUE THREAD

**Issue by nickfujita** [ProjectOpenSea/opensea-js#875]
When calling `fulfillOrder`, the operation is failing with the following error:
`TypeError: Cannot read properties of null (reading 'toHexString')`

![image](https://user-images.githubusercontent.com/6342442/224225571-6ac0d692-6626-4b4a-b26b-d8f5803dc81c.png)

v4.0.23
Ethereum & Polygon mainnets

**Comment by lukaskai** [comment]
Hey Nick! I assume you interact directly with Seaport js to sign order, so now you need to get fulfillment data from API in a separate call. See how it is done in Seaport js. There you will get signature and function call ABI (which you are missing).

https://github.com/ProjectOpenSea/opensea-js/blob/4ff77166f72a9b08ec76a134c9965f6dfef63c9e/src/sdk.ts#L1115

**Comment by nickfujita** [comment]
Thanks @lukaskai looks like we were discarding the orderHash since it wasn't being used previously. Seems to work when using `seaport-js` directly instead. However, ran into another issue where only the networks from the legacy [wyvern Network](https://github.com/ProjectWyvern/wyvern-js/blob/8c449566dc556c64c407e30ffe56df26799aaf3d/src/types.ts#L18) are available. This causes failures not only when using `OpenSeaSDK.fulfillOrder`, but even trying to use `OpenSeaAPI. generateFulfillmentData` fails since it's [unable to properly map the networkName](https://github.com/ProjectOpenSea/opensea-js/blob/4ff77166f72a9b08ec76a134c9965f6dfef63c9e/src/orders/utils.ts#L98) for anything other than Ethereum and Goerli

In any case was able to get it working eventually by calling things manually, so closing out this issue 🙏🏼
