### ISSUE TITLE
signature: null for listings and offers on API

### ISSUE THREAD

**Issue by turcottep** [ProjectOpenSea/opensea-js#886]
Using the Stream API as well as the rest API, the signature field in the listings and the offers is null, which make it impossible to fulfill them.

example call: 
`'https://api.opensea.io/v2/listings/collection/boredapeyachtclub/all?limit=1'`

returns:
`{
  "listings": [
    {
      "order_hash": "0xcb613eea16f1dd6f7dc0353b16b7b63b089a1fc9cc38d078ac09085c59fd0ba5",
      "chain": "ethereum",
      "type": "basic",
      "price": {
        "current": {
          "currency": "ETH",
          "value": "9999000000000000000000"
        }
      },
      "protocol_data": {
        "parameters": {
          "offerer": "0x60dbb8cdae2e4fd30c626f916631aa57d68513f4",
          "offer": [
            {
              "itemType": 2,
              "token": "0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D",
              "identifierOrCriteria": "3716",
              "startAmount": "1",
              "endAmount": "1"
            }
          ],
          "consideration": [
            {
              "itemType": 0,
              "token": "0x0000000000000000000000000000000000000000",
              "identifierOrCriteria": "0",
              "startAmount": "9499050000000000000000",
              "endAmount": "9499050000000000000000",
              "recipient": "0x60DBB8cdae2E4Fd30C626F916631Aa57d68513F4"
            },
            {
              "itemType": 0,
              "token": "0x0000000000000000000000000000000000000000",
              "identifierOrCriteria": "0",
              "startAmount": "249975000000000000000",
              "endAmount": "249975000000000000000",
              "recipient": "0x0000a26b00c1F0DF003000390027140000fAa719"
            },
            {
              "itemType": 0,
              "token": "0x0000000000000000000000000000000000000000",
              "identifierOrCriteria": "0",
              "startAmount": "249975000000000000000",
              "endAmount": "249975000000000000000",
              "recipient": "0xA858DDc0445d8131daC4d1DE01f834ffcbA52Ef1"
            }
          ],
          "startTime": "1664000895",
          "endTime": "1679552895",
          "orderType": 2,
          "zone": "0x004C00500000aD104D7DBd00e3ae0A5C00560C00",
          "zoneHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "salt": "0x360c6ebe000000000000000000000000000000000000000041f2dd378ab1e9ec",
          "conduitKey": "0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000",
          "totalOriginalConsiderationItems": 3,
          "counter": 0
        },
        "signature": null
      },
      "protocol_address": "0x00000000006c3852cbef3e08e8df289169ede581"
    }
  ],
  "next": "cGs9NjUwOTI0OTMwNiZjcmVhdGVkX2RhdGU9MjAyMi0wOS0yNCswNiUzQTMwJTNBNDAuNzY2Mzgw"
}`

Note the  "signature": null

**Comment by cterech** [comment]
Please see https://twitter.com/apiopensea/status/1628786984058781696
