### ISSUE TITLE
Provider problem

### ISSUE THREAD

**Issue by krzysztofmn** [ProjectOpenSea/opensea-js#887]
Dear Opensea Team,

I've been using an old opensea-js version for a long time. As after recent update my app stopped working, I have upgraded to 4.0.24. Unfortunately, I can't seem to make it work. For wallet provider I was using truffle HD Wallet. After upgrade I got the following error:

`TypeError: provider.getNetwork is not a function
    at new MulticallProvider (D:\os_app\node_modules\@0xsequence\multicall\dist\0xsequence-multicall.cjs.dev.js:348:20)
    at new Seaport (D:\os_app\node_modules\@opensea\seaport-js\lib\seaport.js:214:34)
    at new OpenSeaSDK (D:\os_app\node_modules\opensea-js\lib\sdk.js:138:24)
    at init_seaport (D:\os_app\main.js:699:15)
    at main (D:\os_app\main.js:1372:8)
    at Object.<anonymous> (D:\os_app\main.js:1380:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47`

Afterwards, I have upgraded truffle HD Wallet to most recent version (2.1.8), but it didn't solve the issue.

In this case I decided to try other solutions - ethers + Infura / Alchemy. At first I didn't add ethers to project dependencies, because my understanding is that it is a part of opensea-js already. Unfortunately, I was still getting errors:

`D:\os_app\node_modules\ethers\utils\web.js:84
                var error = new Error('invalid response - ' + request.status);
                            ^
Error: invalid response - 400
    at request.onreadystatechange (D:\os_app\node_modules\ethers\utils\web.js:84:29)
    at exports.XMLHttpRequest.dispatchEvent (D:\os_app\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:591:25)
    at setState (D:\os_app\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (D:\os_app\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (node:events:524:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  statusCode: 400,
  responseText: '{"jsonrpc":"2.0","error":{"code":-32600,"message":"invalid json request"}}'`

After that I tried adding ethers 5.7.2 to project dependencies, but after rebuilding the project I'm still getting an error, although a different one:

`D:\os_app\node_modules\ethers\node_modules\@ethersproject\logger\lib\index.js:238
        var error = new Error(message);
                    ^
Error: bad response (status=400, headers={"date":"Fri, 17 Mar 2023 01:45:29 GMT","content-type":"application/json","content-length":"84","connection":"keep-alive","x-alchemy-trace-id":"TRACE-ID","cf-cache-status":"DYNAMIC","server":"cloudflare","cf-ray":"CF_RAY"}, body="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":-32600,\"message\":\"invalid request method.\"}}", requestBody="{\"method\":{\"method\":\"eth_chainId\",\"params\":[],\"id\":1,\"jsonrpc\":\"2.0\"},\"id\":43,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://eth-mainnet.g.alchemy.com/v2/MY_KEY", code=SERVER_ERROR, version=web/5.7.1)
at Logger.makeError (D:\os_app\node_modules\ethers\node_modules\@ethersproject\logger\lib\index.js:238:21)
at D:\os_app\node_modules\ethers\node_modules\@ethersproject\web\lib\index.js:275:36
at step (D:\os_app\node_modules\ethers\node_modules\@ethersproject\web\lib\index.js:33:23)
at Object.next (D:\os_app\node_modules\ethers\node_modules\@ethersproject\web\lib\index.js:14:53)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'bad response',
  code: 'SERVER_ERROR',
  status: 400,
  headers: {
    date: 'Fri, 17 Mar 2023 01:45:29 GMT',
    'content-type': 'application/json',
    'content-length': '84',
    connection: 'keep-alive',
    'x-alchemy-trace-id': 'TRACE-ID',
    'cf-cache-status': 'DYNAMIC',
    server: 'cloudflare',
    'cf-ray': 'CF_RAY'
  },
  body: '{"jsonrpc":"2.0","id":0,"error":{"code":-32600,"message":"invalid request method."}}',
  requestBody: '{"method":{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"},"id":43,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://eth-mainnet.g.alchemy.com/v2/MY_KEY'
}`

my last idea was upgrading ethers to 6.1.0, but I get an even different error:

`TypeError: unknown ProviderEvent (argument="event", value="data", code=INVALID_ARGUMENT, version=6.1.0)
    at makeError (D:\os_app\node_modules\ethers\lib.commonjs\utils\errors.js:114:21)
    at assert (D:\os_app\node_modules\ethers\lib.commonjs\utils\errors.js:138:15)
    at assertArgument (D:\os_app\node_modules\ethers\lib.commonjs\utils\errors.js:150:5)
    at getSubscription (D:\os_app\node_modules\ethers\lib.commonjs\providers\abstract-provider.js:139:35)
    at #getSub (D:\os_app\node_modules\ethers\lib.commonjs\providers\abstract-provider.js:882:36)
    at JsonRpcProvider.on (D:\os_app\node_modules\ethers\lib.commonjs\providers\abstract-provider.js:896:39)
    at RequestManager.setProvider (D:\os_app\node_modules\web3\node_modules\web3-core-requestmanager\lib\index.js:95:27)
    at new RequestManager (D:\os_app\node_modules\web3\node_modules\web3-core-requestmanager\lib\index.js:39:10)
    at Object.packageInit (D:\os_app\node_modules\web3\node_modules\web3-core\lib\index.js:45:31)
    at new Web3 (D:\os_app\node_modules\web3\lib\index.js:39:10)
    at new OpenSeaSDK (D:\os_app\node_modules\opensea-js\lib\sdk.js:131:21)
    at init_seaport (D:\os_app\main.js:705:11)
    at main (D:\os_app\main.js:1412:8)
    at Object.<anonymous> (D:\os_app\main.js:1420:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10) {
  code: 'INVALID_ARGUMENT',
  argument: 'event',
  value: 'data'
}`

My code initializing Opensea looks like this:

const opensea_sdk = require('opensea-js');
const Seaport = require("@opensea/seaport-js").Seaport;
const ethers = require("ethers").ethers;

provider = new ethers.providers.JsonRpcProvider('https://' + INFURA or ALCHEMY link + MY_KEY); // ethers 5.7.2
//provider = new ethers.JsonRpcProvider('https://' + INFURA or ALCHEMY link + MY_KEY); // ethers 6.1.0
signer = new ethers.Wallet('MY_PRIVATE_KEY', provider); 
seaport = new Seaport(signer, {seaportVersion:"1.4"});
os_sdk = new opensea_sdk.OpenSeaSDK(provider,{
		networkName: opensea_sdk.Network.Main,
		apiKey: MY_OS_KEY
		});

Please kindly help me solve this problem, I've been banging my head against the wall for a few days already, trying to make it work :(

**Comment by krzysztofmn** [comment]
Could anyone please assist me with this issue? :(

**Comment by mohsinkc** [comment]
Hey did you solve this error?

**Comment by krzysztofmn** [comment]
Unfortunately not. Do you have any solutions?

**Comment by mohsinkc** [comment]
@JoshuaSchmidt-OpenSea can you please help?
This is my code:

const providerOrUrl = "https://" + NETWORK + ".infura.io/v3/" + NODE_API_KEY;
const provider = new HDWalletProvider(privateKey, providerOrUrl);
const openseaSDK = new OpenSeaSDK(provider, {
networkName: Network.Main,
apiKey: API_KEY,
});

This same code used to work till version 4.0.12. Is it related to HD wallet Provider or anything else?
I will be grateful if you can help us both.
Thanks
Cheers!

**Comment by mohsinkc** [comment]
> Unfortunately not. Do you have any solutions?

Whats your whole code? Can you please share maybe I can make it work and that will solve both ours problem

**Comment by krzysztofmn** [comment]
Prior to opensea-js upgrade my code was as below. My current code initializing Opensea you can find at the end of my first post in this thread.

    const opensea_sdk       = require('opensea-js');
    const hdwallet_provider = require('@truffle/hdwallet-provider');

    let provider_config = {
      providerOrUrl: cfg.is_infura
        ? 'https://' + cfg.network + '.infura.io/v3/' + cfg.node_key
        : 'https://eth-' + cfg.network + '.alchemyapi.io/v2/' + cfg.node_key
    };

    if ('mnemonic' in cfg) {
      provider_config['mnemonic'] = {
        phrase: cfg.mnemonic
      };
    } else if (('private_keys' in cfg) && cfg.private_keys.length >= 1) {
      provider_config['privateKeys'] = cfg.private_keys;
    } else {
      print_log('Error: No mnemonic phrase or private keys.');
      return null;
    }

    wallet_provider = new hdwallet_provider(provider_config);

    if (isNullOrUndefined(wallet_provider)) {
      return false;
    }

    wallet_provider.engine.on('error', error => print_error(error));

    let api_config = {
      networkName: opensea_sdk.Network.Main,
      apiKey: cfg.opensea_key
    };

    seaport = new opensea_sdk.OpenSeaPort(
      wallet_provider,
      api_config,
      (arg) => print_sea_log(arg)
    );

**Comment by mohsinkc** [comment]
I used opensea-js version 2.0.2 it solved the issue

**Comment by krzysztofmn** [comment]
How come anything is working for you in 2.0.2 if opensea-js is already at 5.0.0? There are a lot of deprecated things in v2. Are you able to place any offers?

**Comment by mohsinkc** [comment]
I have not tried that. However the getOrdets() returns success false 404 so
I'm using the v.2 endpoint of the listings and and I'm also placing offers
using v.2 endpoint. So not sure if that is working or not.

**Comment by krzysztofmn** [comment]
@JoshuaSchmidt-OpenSea could you please kindly help with this issue? I believe going down from v5.0.0 to v2.0.2 is not the way to go in general.

**Comment by luoyeETH** [comment]
Same issue here, I'm also using HDWalletProvider, but after upgrading to version 6.0.2, it doesn't work. I encountered an error message saying 'ERROR 6377: Either signer or a JsonRpcProvider must be provided'.

**Comment by luoyeETH** [comment]
> Same issue here, I'm also using HDWalletProvider, but after upgrading to version 6.0.2, it doesn't work. I encountered an error message saying 'ERROR 6377: Either signer or a JsonRpcProvider must be provided'.

Referring to this portion of code at https://github.com/ProjectOpenSea/opensea-js/blob/main/test/integration/setup.ts#LL24C1-L24C1, I made modifications to my code, and now it is running correctly.

```
        const wallet = new Wallet(privateKey);
        const publicKey = await wallet.getAddress();
        const provider = new HDWalletProvider({
            privateKeys: [privateKey],
            providerOrUrl: `https://eth-mainnet.alchemyapi.io/v2/${alchemyKey}`,
            addressIndex: 0
        });

        const openseaSDK = new OpenSeaSDK(provider, {
            networkName: osNetwork.Main,
            apiKey: openseaApiKey
        })
```
=>
```
        const RPC_PROVIDER = new ethers.providers.JsonRpcProvider(
            `https://eth-mainnet.g.alchemy.com/v2/${alchemyKey}`
        );
        const wallet = new ethers.Wallet(privateKey as string, RPC_PROVIDER);
        const publicKey = await wallet.getAddress();
        const openseaSDK = new OpenSeaSDK(RPC_PROVIDER,
            {
              chain: osNetwork.Mainnet,
              apiKey: openseaApiKey,
            },
            (line) => console.info(`MAINNET: ${line}`),
            wallet
          );
```

**Comment by ryanio** [comment]
truffle's HDWalletProvider [is not supported in ethers](https://github.com/trufflesuite/truffle/issues/5138), but you can use ethers built in [HDWallet utils](https://docs.ethers.org/v5/api/utils/hdnode/) - here is a small tutorial on how to use it: https://medium.com/coinmonks/hd-wallets-in-ethers-js-e173190e4858

please open a new issue with details on how to reproduce if you are still having issues. thank you!

**Comment by creed-dev** [comment]
@ryanio

**Comment by ryanio** [comment]
@creed-dev Provide the wallet as the 4th constructor param to the sdk

**Comment by creed-dev** [comment]
@ryanio

**Comment by ryanio** [comment]
@creed-dev it doesn't seem like the Wallet has a provider connected, could you try e.g. `new ethers.Wallet.fromMnemonic(mnemonic).connect(provider)`

**Comment by MuhammadMinhaj** [comment]
I am facing the same issue with opensea-js `^6.1.12` version. And my ethers version is: "^6.7.1"
If anyone has solved the problem please let me know. Here is the implemented code: Thank you.


` const privateKey =   '';
      const providerUrl = '';

      const provider = new ethers.JsonRpcProvider(providerUrl);
      const wallet = new ethers.Wallet(privateKey, provider);

      const openseaSDK = new OpenSeaSDK(wallet, {
        chain: Chain.Goerli,
        // apiKey: opensea.api_key,
      });

      // create listing
      const contractAddress = '0x';
      const address = '0x';
      const expirationTime = Math.round(Date.now() / 1000 + 60 * 60 * 24);
      const listing = await openseaSDK.createListing({
        asset: {
          tokenId: 16,
          tokenAddress: contractAddress,
        },
        accountAddress: address,
        startAmount: 1,
        listingTime: expirationTime,
      });
      console.log('Create listing data', listing);`

**Comment by ryanio** [comment]
@MuhammadMinhaj for now we only support ethers v5, ethers v6 support will come in a future major version upgrade switch will have to switch to bigint

**Comment by MuhammadMinhaj** [comment]
Thanks for your response. I'm not willing to downgrade the ethers version. Is there any alternative of ethers.js to use in opensea current sdk?
