### ISSUE TITLE
Error when generating fulfillment data

### ISSUE THREAD

**Issue by ntop001** [ProjectOpenSea/opensea-js#889]
Original error:
```
Request failed with status code 400 { errors: [ 'Error when generating fulfillment data' ] }
```
When I try to fulfill an order, if the fulfiller own the NFT then it'll get an success response. But if the fulfiller don't own the NFT, it'll
return 400.  It's that true? (I did not find any explaining in the docs)

**Comment by montasaurus** [comment]
Yes, that's true. I just called it out more explicitly in the docs here: https://docs.opensea.io/reference/fulfill-an-offer
