### ISSUE TITLE
Failed atomic match with args. when trying to fulfillOrder.

### ISSUE THREAD

**Issue by djpysu** [ProjectOpenSea/opensea-js#90]
I have minted some items with the factory contract from OpenSea.

I have created a sell order, all good.
This is the asset:

https://testnets.opensea.io/assets/0xdc3f3102dad0d2b5b5b9e675a65f94c74f809e3d/2

When trying to buy, it gives you an error

_Oops, the Ethereum network rejected this transaction :( The OpenSea devs have been alerted, but this problem is typically due an item being locked or untransferrable. The exact error was "execution reverted..."_

Doing it by a script, when trying to fulfill that order it crashes with something like this:

`seaport.js?8b9d:3058 Failed atomic match with args:  (11) [Array(14), Array(18), Array(8), "0x23b872dd0000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000003", "0x23b872dd00000000000000000000000051f45bb541b8fe99…0000000000000000000000000000000000000000000000003", "0x00000000ffffffffffffffffffffffffffffffffffffffff…0000000000000000000000000000000000000000000000000", "0x000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000", "0x", "0x", Array(2), Array(5)]`

This is how I am doing it:

```
const order = await this.seaport.api.getOrder({ 
        asset_contract_address: '0xdc3f3102dad0d2b5b5b9e675a65f94c74f809e3d',
        token_id: 3,
        side: OrderSide.Sell 
      })
      const transactionHash = await this.seaport.fulfillOrder({
        order,
        accountAddress: '0x791963C71409Ef6DAC661Bd6eA0eb6422F692d82',
})
```

Help please?

**Comment by TheMaxKim** [comment]
Hey @djpysu , want to let me know if this is fixed by either downgrading your OZ version or overriding the methods described here? https://github.com/ProjectOpenSea/opensea-creatures/issues/68#issuecomment-821286197

**Comment by IAmKio** [comment]
@djpysu did you solve this issue? having the same problem...

**Comment by bdvorianov-sapient** [comment]
Have a similar issue when testing on Rinkeby. Strange, but it's Rinkeby-only for me, all good in main net

**Comment by bdvorianov-sapient** [comment]
@IAmKio maybe you found something?

**Comment by simonare** [comment]
I am also having same issue, any solution?

**Comment by esteban-OpenSea** [comment]
Just wanted to follow up on this. Is everyone still experiencing this issue?

**Comment by esteban-OpenSea** [comment]
Checking in again, are you still having issues with this? Please use the latest version of the SDK and Node

**Comment by bdvorianov** [comment]
Back then I've switched to self-written solution, but later we switched back to SDK, maybe a newer version, now everything is fine. Now we have a ton of warning in terminal, but that's for another issue, I think.

**Comment by maxschnaider** [comment]
make sure you did transfer ownership of your NFT contract to your Factory contract
`await creature.transferOwnership(CreatureFactory.address);`
