### ISSUE TITLE
Error: Failed to extract transfer calldata

### ISSUE THREAD

**Issue by james2doyle** [ProjectOpenSea/opensea-js#92]
![Screen Shot 2021-04-17 at 3 27 56 PM](https://user-images.githubusercontent.com/1425304/115128325-deaebd00-9f91-11eb-89dc-4fa5686a8b7f.png)

Getting this error when trying to execute `createBuyOrder`. I am using `window.ethereum` as my provider and the main network for execution.

I'm running on `localhost` and using MetaMask. Not sure if anyone else is having issues here.

Attached my log from the console when the `POST` request returned a `400` error

Console log: [localhost-1618698488304.log](https://github.com/ProjectOpenSea/opensea-js/files/6330144/localhost-1618698488304.log)

**Comment by lukaprelic** [comment]
issue solved here:
https://github.com/ProjectOpenSea/opensea-js/issues/85
add schemaName: WyvernSchemaName.ERC1155 property to asset in createsellorder.
opensea needs to fix their docs

**Comment by esteban-OpenSea** [comment]
Issue appears to be solved.

Solution:
Install node 8.11.2 (you can use nvm).
Using "schemaName: WyvernSchemaName.ERC1155"
