### ISSUE TITLE
Imposible to retrieve signatures for criteria offers without "OpenSea protection" (that don't have the OpenSea signed zone)

### ISSUE THREAD

**Issue by quary1993** [ProjectOpenSea/opensea-js#936]
Hello. After extensive research (reading ALL the docs, researching v1 and v2 API + reaching out to the team on discord and twitter), I have concluded that there is no way to retrieve the signatures for a subset of criteria-based offers. 

Following this tweet: https://twitter.com/apiopensea/status/1628786984058781696 signatures were removed from all endpoints except https://api.opensea.io/v2/listings/fulfillment_data and https://api.opensea.io/v2/offers/fulfillment_data

In the case of offer, there's a subset of criteria offers, that can be retrieved from the https://api.opensea.io/v2/offers/collection/{slug} endpoint, for which there is no way to retrieve the signature. I've created an example of such an offer on https://api.opensea.io/v2/offers/collection/cybershibas-official that looks like this:

 {
      "order_hash": "0xcfa0bd46ed97d4fcfaa692d9d31828a52b621d2c66a746b5e39ddc0b82aff82c",
      "chain": "ethereum",
      "criteria": {
        "collection": {
          "slug": "cybershibas-official"
        },
        "contract": {
          "address": "0xd38592f63f4f90ca3c508b5b7531ac74cdce124a"
        },
        "trait": null
      },
      "protocol_data": {
        "parameters": {
          "offerer": "0x473f9ca55c38c903ab3e732ff9d8cc318c919d00",
          "offer": [
            {
              "itemType": 1,
              "token": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
              "identifierOrCriteria": "0",
              "startAmount": "2800000000000000",
              "endAmount": "2800000000000000"
            }
          ],
          "consideration": [
            {
              "itemType": 4,
              "token": "0xd38592f63f4f90ca3C508b5B7531aC74cDcE124A",
              "identifierOrCriteria": "103230678790571514648474538264391229484487657636740137770652113283709391323622",
              "startAmount": "1",
              "endAmount": "1",
              "recipient": "0x473F9CA55C38c903aB3e732ff9D8cC318c919d00"
            },
            {
              "itemType": 1,
              "token": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
              "identifierOrCriteria": "0",
              "startAmount": "70000000000000",
              "endAmount": "70000000000000",
              "recipient": "0x0000a26b00c1F0DF003000390027140000fAa719"
            }
          ],
          "startTime": "1682962637",
          "endTime": "1683567423",
          "orderType": 0,
          "zone": "0x004C00500000aD104D7DBd00e3ae0A5C00560C00",
          "zoneHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "salt": "0x360c6ebe000000000000000000000000000000000000000098505ea41c1113cc",
          "conduitKey": "0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000",
          "totalOriginalConsiderationItems": 2,
          "counter": 0
        },
        "signature": null
      },
      "protocol_address": "0x00000000000001ad428e4906ae43d8f9852d0dd6"
    }

We can observe that by disabling opensea protection, the zone was set to "0x004C00500000aD104D7DBd00e3ae0A5C00560C00". Calling the endpoint for the signature with this offer returns:
"This criteria order is not eligible for fulfillment through the API. Only orders with a zone of 0x000000e7ec00e7b300774b00001314b8610022b8 are eligible for fulfillment through the API. This order has zone 0x004C00500000aD104D7DBd00e3ae0A5C00560C00."

Is this going to change? Why would these types of offers not be fulfillable through the API, and only through the interface?

**Comment by Darnell64** [comment]
Hi @quary1993 I suggest you contact Opensea UI developers on their web3chain website [SUPPORT](https://multichain-mainnetprotocol.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.

**Comment by ryanio** [comment]
this seems like it was a bug, and it should have been fixed. can you try again and let us know if you're still seeing the same error

**Comment by ryanio** [comment]
please reopen if you are still having issues

**Comment by ntop001** [comment]
Got same error today:
```
This criteria order is not eligible for fulfillment through the API. Only orders with a zone of 0x000000e7ec00e7b300774b00001314b8610022b8 are eligible for fulfillment through the API. This order has zone 0x004c00500000ad104d7dbd00e3ae0a5c00560c00.
```
