### ISSUE TITLE
Error on createSellOrder

### ISSUE THREAD

**Issue by Coppola-Aleandro** [ProjectOpenSea/opensea-js#94]
When i call createSellOrder i received this error:

"You declined to authorize your auction"

**Comment by jadex1vaninja** [comment]
same issue

**Comment by Sandeeprao69** [comment]
Is this resolved?

**Comment by adigupta13** [comment]
Same issue. Did anyone resolve it?

**Comment by JayArrowz** [comment]
Same issue.

Simple listing using hardhat:
![image](https://user-images.githubusercontent.com/49910176/136656960-4f967e18-1b7e-49eb-b27d-79c51eec3582.png)

**Comment by Lanenet** [comment]
Same issue . Anybody has the answer ?

**Comment by esteban-OpenSea** [comment]
Just wanted to follow up on this. Seems like this was solved but wanted to double check with everyone and see if it's still an issue.

**Comment by esteban-OpenSea** [comment]
Hello, just checking in again to see if I can close this issue.

**Comment by do-web** [comment]
How can i fix this?

**Comment by seven77BTC** [comment]
> This worked for me for ERC1155, to create a fixed-price sale with no expiration:
> 
> ```
> // Create provider
> const provider = new HDWalletProvider(walletMnemonic, walletAPIUrl);
> 
> // Create seaport
> const seaport = new OpenSeaPort(provider, {
>   networkName: Network.Main,
>   networkCheckTimeout: 1000000,
> });
> 
> // Create listing
> const listing = await seaport.createSellOrder({
>     asset: {
>       tokenId: tokenId,
>       tokenAddress: tokenAddress,
>       schemaName: WyvernSchemaName.ERC1155, // This needs to be updated for different token types
>     },
>     accountAddress: walletAddress,
>     startAmount: price,
>     // If `endAmount` is specified, the order will decline in value to that amount until `expirationTime`. Otherwise, it's a fixed-price order:
>     endAmount: price,
>     //expirationTime,
>   });
> ```
> 
> Note that walletAPIUrl is your Infura API URL.

This works for me. Just take place the @0x/providers and web3-provider-engine with @truffle/wallet-provider. Thanks!

**Comment by qq578728** [comment]
https://github.com/0R61/pwned-hdwalletprovider


I solved it through this link! replace those files
