### ISSUE TITLE
Used this in angular it seems this error

### ISSUE THREAD

**Issue by Rubanrubi** [ProjectOpenSea/opensea-js#943]
![Screenshot from 2023-05-04 17-31-36](https://user-images.githubusercontent.com/47156761/236207074-245a9bc4-15e6-48a4-8171-4eb6cad58c61.png)

**Comment by Rubanrubi** [comment]
how to fix it? kindly help me

**Comment by ryanio** [comment]
we are working on a [v6 branch](https://github.com/ProjectOpenSea/opensea-js/tree/v6) that will have much fewer dependencies and should fix this issue

**Comment by JoshuaSchmidt-OpenSea** [comment]
v6.0.2 has been released. There may be some changes needed to incorporate the breaking changes. But I believe the reduction in dependencies will eliminate this issue.

**Comment by Rubanrubi** [comment]
yes @JoshuaSchmidt-OpenSea @ryanio the above screenshot error fixed now after updating to v6.0.2 but now i got this issue

![image](https://github.com/ProjectOpenSea/opensea-js/assets/47156761/e93b2ead-d394-417b-ad0c-28776421768c)

**Comment by Rubanrubi** [comment]
while compiling in angular project i got the above errors how to resolve it

**Comment by ryanio** [comment]
What version of node are you on? Try minimum Node v16

**Comment by Rubanrubi** [comment]
![image](https://github.com/ProjectOpenSea/opensea-js/assets/47156761/aef8f2bb-858f-47ba-9f8f-bd88d3e68d5b)
@ryanio

**Comment by Rubanrubi** [comment]
kindly help me out from this issue @ryanio

**Comment by ryanio** [comment]
Please try with Node v16, to make it easier to change node versions try using nvm https://github.com/nvm-sh/nvm#installing-and-updating

**Comment by Rubanrubi** [comment]
Sorry, I tried that too @ryanio 

Steps i followed

nvm use 16
rm -rf node_modules/
rm -rf package-lock.json 
npm cache clean --force
npm i
same issue coming @ryanio 

![image](https://github.com/ProjectOpenSea/opensea-js/assets/47156761/1fa8a0bb-e034-43b3-8d4f-ff38c4627f03)

**Comment by ryanio** [comment]
What if you use the browserified lib/bundle.js? 

I'm not too familiar with the angular pipeline, you might need to use webpack or some tool in your build process.

**Comment by Rubanrubi** [comment]
Internal Process

1. Angular CLI runs Webpack to build and bundle all JavaScript and CSS code.

2. In turn Webpack calls the TypeScript loaders which fetches all .ts file in the Angular project and then transpiles them to JavaScript i.e to a .js file, which browsers can understand.

**Comment by ryanio** [comment]
can you try Option B in this answer? https://stackoverflow.com/a/71808381

**Comment by Rubanrubi** [comment]
yes tried but i can't same issue persist

**Comment by ryanio** [comment]
I have opened a PR removing `isomorphic-unfetch` and instead using ethers' util `fetchJson`. i hope this helps solve your issue.

PR: https://github.com/ProjectOpenSea/opensea-js/pull/1029

You can try setting your dependency in package.json to:

`"opensea-js": "ProjectOpenSea/opensea-js#ryan/use-ethers-fetchJson"`

to build the lib you will also need to do `cd node_modules/opensea-js && npm i && npm run build`, until we publish a new version containing this PR. 

if you get this error

```
src/orders/utils.ts:44:14 - error TS2742: The inferred type of 'getPostCollectionOfferPayload' cannot be named without a reference to 'opensea-js/node_modules/@opensea/seaport-js/lib/types'. This is likely not portable. A type annotation is necessary.
```

then edit `node_modules/opensea-js/tsconfig.json` and remove `declaration: true` as a fix.

**Comment by ryanio** [comment]
@Rubanrubi we have published [v6.0.3](https://github.com/ProjectOpenSea/opensea-js/releases/tag/v6.0.3) on npm with the fix, give us a try and let us know if it helped fixed your issue!

**Comment by ryanio** [comment]
closing since the dependency you were having trouble with is no longer included.

if you are still having issues please open a new issue with details.

i would also recommend doing `rm -rf node_modules` and a fresh `npm install`

**Comment by Rubanrubi** [comment]
@ryanio Thank you so much for your support its working cool ethers v5 and opensea sdk v6.0.3 :)

**Comment by Rubanrubi** [comment]
I'll be waiting for multi chain support @ryanio Hope it will be launch soon...
