### ISSUE TITLE
Unable to fulfill Orders when network is testnet mumbai

### ISSUE THREAD

**Issue by ds-hamza** [ProjectOpenSea/opensea-js#945]
Hello Opensea team, 

I have discovered something strange on testnets.opensea.
My minted NFTs are getting listed on Opensea but I'm unable to purchase these using the v1.5 of seaport protocol when network is polygon's testnet mumbai.
I have used same smart contract code to mint NFTs on both Goerli and  Mumbai. The listing and purchase flow went straight ahead using Goerli but on Mumbai the execution always reverts. 

Could someone please look into this issue?

You're still able to purchase NFTs that were listed using the older version of seaport contract on polygon's testnet mumbai

**Comment by Scottyfis** [comment]
@ds-hamza Talk to Polygon Support on the [Polygon Live Support](https://matic-network.org/) so that your issue can be looked into.

**Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by ryanio** [comment]
We are looking into resolving it now, thanks for reporting

**Comment by ryanio** [comment]
This should be resolved now, can you try again?

**Comment by ds-hamza** [comment]
That's surely resolved now. 
Thank you @ryanio.
