### ISSUE TITLE
execution reverted: AssetContractShared#creatorOnly: ONLY_CREATOR_ALLOWED'

### ISSUE THREAD

**Issue by nickandless0** [ProjectOpenSea/opensea-js#951]
`

      import React, { useEffect, useState } from 'react';
      import { Container, Col, Row } from 'react-bootstrap';
      import ListingCard from '../../components/ListingCard';
      import { OpenSeaPort, Network } from 'opensea-js';
      import { useWeb3React } from '@web3-react/core';
      import { WyvernSchemaName } from 'opensea-js/lib/types';
      
      const nftOwnerAddress = '0x7C8F6808778bA76841d3700Cada31206c438f49D'; // owner address
      
      const seaport = new OpenSeaPort(window.ethereum, {
          networkName: Network.Goerli, // Replace with your desired network
          // apiKey: '', // Replace with your OpenSea API key
      });
      
      
      const TraitListing = React.memo(() => {
          const { account } = useWeb3React();
          const [nfts, setNfts] = useState([]);

    useEffect(() => {
        fetchNFTCollection()
    }, []);

    // Function to fetch and display your NFT collection
    const fetchNFTCollection = async () => {
        try {
            // Fetch the NFT assets owned by the specified address
            const assets = await seaport.api.getAssets({
                owner: nftOwnerAddress,
            });
            setNfts(assets.assets);
            console.log('assets', assets);
        } catch (error) {
            console.error(error);
        }
    };

    const createSellOffer = async (tokenAddress, tokenId, price) => {
        console.log({ tokenAddress, tokenId, price })
        try {
            const order = await seaport.createSellOrder({
                asset: {
                    tokenAddress: tokenAddress,
                    tokenId,
                    schemaName: WyvernSchemaName.ERC1155
                },
                quantity: 1,
                accountAddress: nftOwnerAddress,
                startAmount: price,
            });

            console.log('order created', order);

        } catch (error) {
            console.error('Error creating buy offer:', error);
            // Handle any errors that may occur
            // Provide appropriate feedback to the user
        }
    };

    const sleep = (ms) => {
        return new Promise(resolve => setTimeout(resolve, ms));
      }

    const fulfillBuyOffer = async (tokenAddress, tokenId) => {
        try {
            const { orders } = await seaport.api.getOrders({
                assetContractAddress: tokenAddress,
                tokenId: tokenId,
                side: "ask"
            })
            const order = orders[0];

            console.log('order', order);

            await sleep(3000);

            const { hash } = await seaport.fulfillOrder({ order, accountAddress: account });

            console.log('Buy offer fulfilled:', hash);

        } catch (error) {
            console.error('Error fulfilling buy offer:', error);
            // Handle any errors that may occur
            // Provide appropriate feedback to the user
        }
    };

    return (
        <Container fluid>
            <Row>
                {nfts.map((item, index) => (
                    <Col key={index} xs={12} sm={6} md={4} lg={3}>
                        <ListingCard
                            item={item}
                            createSellOffer={() => createSellOffer(item.tokenAddress, item.tokenId, 0.002)}
                            fulfillBuyOffer={() => fulfillBuyOffer(item.tokenAddress, item.tokenId)}
                        />
                    </Col>
                ))}
            </Row>
        </Container>
    )
    });
    
    export default TraitListing;

`

I am getting errors when trying to fulfill a sell offer 

first, I am creating a sell offer using the function createSellOffer using the owner wallet from the metamask order is created successfully 
but when I call fulfillBuyOffer from another user's wallet I am getting an error 
execution reverted: AssetContractShared#creatorOnly: ONLY_CREATOR_ALLOWED'

my goal is to allow users to purchase the nft from opensea and also from my own website.

**Comment by ryanio** [comment]
if you are trying to create a sell offer for the shared storefront (0x495f947276749Ce646f68AC8c248420045cb7b5e), it has a lazy mint adapter. if the item is not minted on chain, you should set the token contract address to `0xA604060890923Ff400e8c6f5290461A83AEDACec` which will mint the item while processing the sale.

**Comment by nickandless0** [comment]
@ryanio can you give me example ?

**Comment by nickandless0** [comment]
seaport.api.getAssets give me list of tokens with there address so i am passing that address

**Comment by ryanio** [comment]
what address?

**Comment by ryanio** [comment]
if you can send the token address and token id that is not working for you with createSellOffer, we can try to recreate to help fix

**Comment by ryanio** [comment]
Please reply here or open a new issue with the details I requested if you are still having problems. Thank you!
