### ISSUE TITLE
Null Owner

### ISSUE THREAD

**Issue by HighPotato** [ProjectOpenSea/opensea-js#96]
When calling this API , I get null owner for the requested asset, how can I retrieve a token's owner Off-chain and On-chain? 

`https://api.opensea.io/api/v1/asset/0xd07dc4262bcdbf85190c01c996b4c06a461d2430/473964`

**Comment by esteban-OpenSea** [comment]
Owners for 1155s are returned in the `top_ownerships` list returned by the /`asset/:asset_contract_address/:token_id endpoint:` https://docs.opensea.io/reference/retrieving-a-single-asset

**Comment by ellingtonsu** [comment]
Is top_ownerships includes **ALL** owners of an ERC-1155 token?

**Comment by mattmarcello** [comment]
In my experience, it does not.
