### ISSUE TITLE
createBuyOrder fails on fetch asset

### ISSUE THREAD

**Issue by NoamN** [ProjectOpenSea/opensea-js#993]
Trying to create buy order while passing these params:
```
seaport.createBuyOrder({
                asset: { tokenId: tokenId, tokenAddress: collectionAddress },
                accountAddress: '0xB6ac8f7gBC4A6aC2858CBBD6AB23DDB637ACB10C',
                startAmount: 0.01,
            });
```
this come back with the following error:
FetchError: Invalid response body while trying to fetch https://api.opensea.io/api/v1/asset/0xC73DDAB94EG0B85AD34Ce816e3cfd6eg76bc00ea/3800/?: read ECONNRESET

**Comment by JoshuaSchmidt-OpenSea** [comment]
This looks like a transient error with the OS backend. Is it consistently happening or did this happen for a short period of time?

**Comment by NoamN** [comment]
it happens consistently…

**Comment by JoshuaSchmidt-OpenSea** [comment]
Does that collection exist? I don't see that contract address on etherscan.

https://etherscan.io/address/0xC73DDAB94EG0B85AD34Ce816e3cfd6eg76bc00ea

**Comment by NoamN** [comment]
yea sure- tried with existing collection address and token id. Changed it when I copied the code here (not sure why)…
But I just tried from different computer and it worked (maybe related to proxy or something)…. Now I have different issue- it keeps failing for order already exist, but I’ll research it a bit and will open new issue if needed. Thanks for the help!
